import type { ServiceContent } from '@/components/leaf-service-page';

export const institutionalSetupServices: Record<string, ServiceContent> = {
  'political-party': {
    title: 'Political Party Formation & License',
    description:
      'Political party formation and Section 29A registration with Election Commission of India — constitution, executive, application, ECI hearing and recognition.',
    keywords: ['political party registration', 'Section 29A RP Act', 'ECI registration', 'political party formation India', 'recognized political party', 'state political party'],
    overview:
      'Forming a political party in India requires registration with the Election Commission of India (ECI) under Section 29A of the Representation of the People Act, 1951. Registration grants the party the right to contest elections, allotment of common symbols (after recognition criteria), and Section 13A income-tax exemption (subject to compliance).\n\nThe process involves drafting the party constitution, identifying office bearers, gathering minimum 100 members from at least three States with affidavits, paying fee (₹10,000), filing application with ECI, public notice in two newspapers, and ECI hearing. After registration, recognition as State Party / National Party requires additional electoral performance criteria.\n\nWe handle end-to-end party formation — strategic naming, constitution drafting, member affidavit preparation, ECI application, hearing representation and post-registration compliance (Section 29C reports, Section 13A claim, ECI annual filings).',
    whyChooseUs: [
      { title: 'ECI-Specialist Counsel', desc: 'Experienced in Section 29A applications, oppositions and hearings.' },
      { title: 'Constitution Drafting', desc: 'Customized party constitution per ECI guidelines, with internal democracy compliance.' },
      { title: 'Member Affidavit Coordination', desc: '100+ member affidavits across States compiled and filed.' },
      { title: 'Post-Registration Compliance', desc: 'Section 13A, 29C reports, annual filings, election compliances.' },
    ],
    keyPoints: [
      'Section 29A RP Act registration with ECI',
      'Party constitution drafting (internal democracy mandated)',
      'Office bearers and central committee setup',
      '100+ founding member affidavits across 3+ States',
      'Public notice in 2 newspapers (English + regional)',
      'ECI fee — ₹10,000',
      'ECI hearing representation',
      'Symbol allotment (recognition pending)',
      'Section 13A income tax exemption',
      'Section 29C contribution reporting',
      'Annual ECI compliance filings',
      'State / National Party recognition strategy',
    ],
    process: [
      { title: 'Strategic Setup', desc: 'Party name, ideology positioning, founding members across States.' },
      { title: 'Constitution & Application', desc: 'Constitution drafted; ECI application Form-3 prepared.' },
      { title: 'Public Notice', desc: '2 newspapers — invite objections within 30 days.' },
      { title: 'ECI Filing', desc: 'Submit application with affidavits, fee, NOC documents.' },
      { title: 'Hearing & Registration', desc: 'ECI hearing; address objections; receive registration.' },
      { title: 'Compliance Setup', desc: 'Section 13A bookkeeping, Section 29C reporting calendar.' },
    ],
    documents: [
      'Party constitution',
      'List of office bearers with photo IDs',
      'Affidavits of 100+ founding members',
      'Members\' address proofs across 3+ States',
      'Bank account opening letter',
      'Newspaper notices (2 publications)',
      'PAN of party (post-registration)',
      'Office address proof',
    ],
    statutoryRefs: [
      { name: 'Representation of the People Act, 1951 — Section 29A', desc: 'Party registration framework.' },
      { name: 'Section 29C', desc: 'Annual contribution reporting to ECI.' },
      { name: 'Income-tax Act, 1961 — Section 13A', desc: 'Tax exemption for registered political parties.' },
      { name: 'ECI Symbols (Reservation and Allotment) Order, 1968', desc: 'Symbol allotment and party recognition.' },
    ],
    pitfalls: [
      { title: 'Inadequate Member Coverage', desc: 'Less than 100 members or not from 3+ States invites application rejection.' },
      { title: 'Missing Internal Democracy', desc: 'Constitution must provide for periodic internal elections; absence is rejection ground.' },
      { title: 'Section 13A Lapses', desc: 'Above ₹20,000 cash contribution without donor record disqualifies entire 13A exemption.' },
      { title: 'Symbol Allotment Confusion', desc: 'Symbol is allotted only on satisfying recognition criteria — newly registered parties face this.' },
    ],
    faqs: [
      { q: 'How long does ECI registration take?', a: 'Typically 6-12 months from application — comprising public notice (30 days), ECI processing, hearing and registration.' },
      { q: 'What is the difference between registered and recognized?', a: 'Registered party is approved by ECI but doesn\'t have a reserved symbol. Recognition (State / National) requires electoral performance — vote share / seat percentage thresholds.' },
      { q: 'Can a party be deregistered?', a: 'Yes — by ECI for non-compliance. Recently several inactive parties have been delisted.' },
      { q: 'Are donations to political parties tax-deductible?', a: 'Donors can claim Section 80GGB / 80GGC for donations to registered political parties — but cash donations restricted to ₹2,000.' },
      { q: 'What about electoral bonds?', a: 'The 2024 Supreme Court ruling struck down the Electoral Bond scheme. Going forward, party finance follows direct disclosure norms.' },
    ],
    relatedServices: [
      { name: 'ITR for Political Party', href: '/services/business-registration/taxation/itr-political-party' },
      { name: 'Society Registration (NGO)', href: '/services/business-registration/other-registration/society-registration' },
      { name: 'Trust Registration (NGO)', href: '/services/business-registration/other-registration/trust-registration' },
    ],
  },

  'university-setup': {
    title: 'University Setup & License',
    description:
      'End-to-end legal support for setting up universities — State Private University Act / Deemed-to-be-University, UGC approval, NOCs, infrastructure compliance.',
    keywords: ['university setup India', 'private university registration', 'deemed university', 'UGC approval', 'state private university act', 'higher education setup'],
    overview:
      'Establishing a university in India is a multi-year, multi-regulator project. Three primary routes: (a) Central University by Act of Parliament, (b) State Private University by State Act, (c) Deemed-to-be-University recognition by Ministry of Education on UGC recommendation. Each has distinct eligibility, capital requirement, infrastructure norms and approval timelines.\n\nA private university typically requires 25-50 acres land, ₹50-100 crore corpus, sponsor body (society / trust / Section 8), academic infrastructure, qualified faculty plan and detailed business case. State Act-based private universities are the most common new-entry route.\n\nWe provide end-to-end advisory — entity structuring, State NOC, sponsor body documentation, State Private University Bill drafting / lobbying, UGC inspection coordination, statutory committee setup and post-establishment compliance under UGC, AICTE, NMC, BCI etc.',
    whyChooseUs: [
      { title: 'End-to-End Project Lead', desc: 'From land acquisition to first batch — single project lead across regulators.' },
      { title: 'State Bill Drafting', desc: 'Private university bill drafted to State template with negotiable provisions.' },
      { title: 'UGC Inspection Readiness', desc: 'Infrastructure, faculty, governance prepared for UGC visits.' },
      { title: 'Multi-Regulator Coordination', desc: 'AICTE, NMC, BCI, NCTE, COA approvals as program-specific.' },
    ],
    keyPoints: [
      'State Private University Act establishment',
      'Deemed-to-be-University recognition (MoE / UGC)',
      'Sponsor body — Society / Trust / Section 8 setup',
      'Land use, zoning and infrastructure approvals',
      'State NOC / Essentiality Certificate',
      'Bill drafting for private university',
      'UGC, AICTE, NMC, BCI program approvals',
      'Affiliation framework (where applicable)',
      'Statutory committees — Governing Council, Academic Council, Finance Committee',
      'NAAC / NBA accreditation readiness',
    ],
    process: [
      { title: 'Project Diagnostic', desc: 'Vision, scale, location, programs, regulatory route selection.' },
      { title: 'Sponsor Body & Land', desc: 'Set up sponsor entity; acquire land; obtain land-use approvals.' },
      { title: 'State Approval', desc: 'State NOC; Bill drafting and passage in State Legislature.' },
      { title: 'UGC Recognition', desc: 'UGC recognition under Section 2(f) of UGC Act; first batch commencement.' },
      { title: 'Operations', desc: 'Faculty, programs, statutory committees, governance, ongoing compliance.' },
    ],
    statutoryRefs: [
      { name: 'UGC Act, 1956', desc: 'Statutory framework for universities and higher education.' },
      { name: 'State Private University Acts', desc: 'State-specific framework — Maharashtra, Karnataka, Haryana, Rajasthan, etc.' },
      { name: 'UGC (Deemed Universities) Regulations, 2010', desc: 'Deemed university recognition framework.' },
      { name: 'AICTE, NMC, BCI, NCTE, COA Acts', desc: 'Program-specific regulator approvals.' },
    ],
    pitfalls: [
      { title: 'Underestimating Timeline', desc: 'University setup typically takes 3-7 years end-to-end. Realistic project planning is essential.' },
      { title: 'Insufficient Corpus', desc: 'Below regulatory corpus (typically ₹50 crore+) invites State / UGC rejection.' },
      { title: 'Land Use Issues', desc: 'Agricultural-to-educational conversion, zoning, FSI must be cleared before commencement.' },
      { title: 'Faculty Plan Gaps', desc: 'UGC inspection focuses heavily on faculty qualifications and ratios; weak plan invites adverse report.' },
    ],
    faqs: [
      { q: 'How long does university setup take?', a: 'Typically 3-7 years from concept to first batch — sponsor body setup (1 year), land + State approvals (1-2 years), Bill / Act passage (1-2 years), UGC recognition + faculty / infra (1-2 years).' },
      { q: 'What is the minimum corpus?', a: 'Varies by State. Typical ranges — Maharashtra ₹50 crore, Karnataka ₹50 crore, Gujarat ₹100 crore, Haryana ₹100 crore. Check specific State Act.' },
      { q: 'Private University Act or Deemed?', a: 'Private University Act — geographic limitation (in State). Deemed — pan-India operation but stricter eligibility (existing institution with track record).' },
      { q: 'Can foreign universities operate in India?', a: 'Yes — under UGC (Setting up and Operation of Campuses of Foreign Higher Educational Institutions in India) Regulations, 2023. Several foreign universities have begun India operations.' },
    ],
    relatedServices: [
      { name: 'School Setup & License', href: '/services/business-registration/institutional-setup/school-setup' },
      { name: 'Society Registration', href: '/services/business-registration/other-registration/society-registration' },
      { name: 'Educational Law', href: '/services/global-business/educational-law' },
    ],
  },

  'school-setup': {
    title: 'School Setup & License',
    description:
      'School setup advisory — State NOC, CBSE / ICSE / State Board affiliation, RTE compliance, infrastructure and recurring affiliation renewals.',
    keywords: ['school setup India', 'CBSE affiliation', 'ICSE school setup', 'private school license', 'RTE compliance school', 'school registration'],
    overview:
      'Setting up a school requires layered approvals — entity registration (society / trust / Section 8), State Government NOC / Essentiality Certificate, recognition by State Education Department, board affiliation (CBSE / ICSE / State Board / IB), RTE Section 12(1)(c) compliance and various municipal / safety clearances.\n\nThe sequence typically takes 2-4 years from concept to first session. Critical milestones include land acquisition with appropriate use, infrastructure construction per board norms, faculty hiring, fire & safety certificates, and pre-affiliation inspection. Provisional affiliation precedes regular affiliation by 2-3 years.\n\nWe handle end-to-end school setup — sponsor body formation, State approvals, board affiliation, RTE compliance, fee regulation (where applicable), recurring renewals and dispute defence (parent / regulator / labour matters).',
    whyChooseUs: [
      { title: 'CBSE / ICSE / IB Specialists', desc: 'Affiliation experience across all major boards with current SOP knowledge.' },
      { title: 'State NOC Coordination', desc: 'State Education Department NOC handled — often the bottleneck.' },
      { title: 'RTE Compliance', desc: '25% RTE Section 12(1)(c) admission process and reimbursement.' },
      { title: 'Recurring Renewals', desc: 'Renewal calendar managed; never miss a deadline.' },
    ],
    keyPoints: [
      'Society / Trust / Section 8 sponsor body',
      'State NOC / Essentiality Certificate',
      'CBSE affiliation (provisional / regular)',
      'ICSE affiliation (CISCE)',
      'State Board recognition',
      'IB / IGCSE accreditation',
      'RTE Act 2009 — 25% admission compliance',
      'Land use and infrastructure norms (per board)',
      'Fire, building, sanitation NOCs',
      'Faculty qualifications (B.Ed for primary, subject-specialists for secondary)',
      'POSH Act compliance and ICC',
      'Anti-ragging committee (where applicable)',
    ],
    process: [
      { title: 'Project Setup', desc: 'Sponsor body, land, building plan, business case.' },
      { title: 'State NOC', desc: 'State Education Department application; site verification.' },
      { title: 'Construction & Setup', desc: 'School building per board norms; recruitment.' },
      { title: 'Board Affiliation', desc: 'CBSE / ICSE / State Board provisional affiliation.' },
      { title: 'First Batch & RTE', desc: 'First academic session; RTE 25% admission process.' },
      { title: 'Regular Affiliation', desc: '2-3 years later, regular affiliation after compliance review.' },
    ],
    statutoryRefs: [
      { name: 'Right to Education Act, 2009', desc: '25% admission for disadvantaged children; reimbursement framework.' },
      { name: 'CBSE Affiliation Bye-laws, 2018', desc: 'Affiliation norms — infrastructure, faculty, governance.' },
      { name: 'CISCE Regulations', desc: 'ICSE affiliation framework.' },
      { name: 'State Education Acts', desc: 'State-specific school regulation — fee, admission, recognition.' },
    ],
    pitfalls: [
      { title: 'Wrong Land Use', desc: 'Agricultural / commercial use without educational conversion blocks affiliation.' },
      { title: 'RTE Non-Compliance', desc: '25% RTE admission lapses invite parent litigation, regulatory action and reimbursement issues.' },
      { title: 'Faculty Shortcuts', desc: 'Underqualified or ad-hoc faculty during inspection can derail affiliation.' },
      { title: 'Fee Regulation Defiance', desc: 'States with Fee Regulation Acts (Tamil Nadu, Maharashtra, Karnataka) have legal fee caps.' },
    ],
    faqs: [
      { q: 'How long does CBSE affiliation take?', a: 'Provisional affiliation 12-18 months from full application. Regular affiliation comes 2-3 years after provisional.' },
      { q: 'What is RTE 25% obligation?', a: 'Section 12(1)(c) of RTE Act mandates 25% admission of disadvantaged / weaker section children at entry-level. State governments reimburse fee per State norms.' },
      { q: 'Can private schools be for-profit?', a: 'School education in India is largely required to be not-for-profit. Coaching, training, ed-tech businesses can be for-profit.' },
      { q: 'What happens if affiliation is denied?', a: 'Provisional affiliation can be re-applied after curing defects. Final denial can be challenged before CBSE Appellate Authority and writ courts.' },
    ],
    relatedServices: [
      { name: 'University Setup & License', href: '/services/business-registration/institutional-setup/university-setup' },
      { name: 'Society Registration (NGO)', href: '/services/business-registration/other-registration/society-registration' },
      { name: 'Educational Law — Institutional', href: '/services/global-business/educational-law/institutional' },
    ],
  },

  'hospital-setup': {
    title: 'Hospital Setup & License',
    description:
      'Multi-specialty hospital setup — Clinical Establishment Act registration, NABH accreditation, biomedical waste, fire / pollution NOCs and ongoing compliance.',
    keywords: ['hospital setup India', 'clinical establishment act', 'NABH accreditation', 'hospital license', 'biomedical waste authorization', 'multi-specialty hospital'],
    overview:
      'Hospital establishment is heavily regulated and varies by State — Clinical Establishments (Registration and Regulation) Act, 2010 in adopting States, plus State-specific Acts. Approvals span building / land use, fire safety, biomedical waste authorization (under BMW Rules, 2016), pollution control, drug license, blood bank license (if applicable), AERB for radiology, MTP authorization, and various sub-specialty registrations.\n\nMulti-specialty hospitals additionally require empanelment with insurance, government schemes (Ayushman Bharat / State health schemes), employees insurance and CGHS empanelment. NABH (National Accreditation Board for Hospitals) accreditation, while voluntary, is increasingly required by insurers and corporate clients.\n\nWe handle end-to-end hospital licensing — entity formation, multi-NOC procurement, accreditation readiness, ongoing compliance and dispute defence (medical negligence, regulator disputes, employment matters).',
    whyChooseUs: [
      { title: 'Multi-NOC Coordination', desc: 'Fire, pollution, BMW, drug, AERB, blood bank — all NOCs in single workflow.' },
      { title: 'NABH Pre-Accreditation', desc: 'Quality manual, SOPs and protocol design for NABH readiness.' },
      { title: 'Insurance Empanelment', desc: 'CGHS, ESIC, Ayushman Bharat empanelment alongside operational launch.' },
      { title: 'Compliance Calendar', desc: 'Renewal-tracking calendar across 10-15 distinct licenses.' },
    ],
    keyPoints: [
      'Clinical Establishments Act registration',
      'State hospital / nursing home registration',
      'Building & fire safety NOCs',
      'Biomedical Waste authorization (BMW Rules, 2016)',
      'Pollution Control Board consent',
      'Drug License (Form 20B / 21B)',
      'Blood Bank License (if applicable)',
      'AERB radiation safety license',
      'MTP authorization (if applicable)',
      'CGHS / ESIC / Ayushman Bharat empanelment',
      'NABH / NABL accreditation',
      'POSH / Anti-Ragging compliance',
    ],
    process: [
      { title: 'Project Diagnostic', desc: 'Specialty mix, bed strength, location, regulator mapping.' },
      { title: 'Entity & Land', desc: 'Sponsor body; land with healthcare use; building plan.' },
      { title: 'Multi-NOC Stack', desc: 'Fire, pollution, BMW, drug, AERB, blood bank in parallel.' },
      { title: 'Operational Launch', desc: 'Faculty / staff onboarding; SOPs; first patient.' },
      { title: 'Empanelment', desc: 'CGHS, ESIC, Ayushman Bharat, private insurers.' },
      { title: 'NABH', desc: 'Pre-accreditation gap; SSR; assessment; accreditation.' },
    ],
    statutoryRefs: [
      { name: 'Clinical Establishments Act, 2010', desc: 'Registration for clinics / hospitals / nursing homes in adopting States.' },
      { name: 'BMW Rules, 2016', desc: 'Biomedical waste handling and authorization.' },
      { name: 'Drugs and Cosmetics Act, 1940', desc: 'Pharmacy / drug stocking license.' },
      { name: 'Atomic Energy (Radiation Protection) Rules, 2004', desc: 'AERB license for radiology / radiation procedures.' },
      { name: 'MTP Act, 1971 (as amended)', desc: 'Authorization for termination procedures.' },
    ],
    pitfalls: [
      { title: 'BMW Authorization Lapse', desc: 'Biomedical waste authorization is critical — unauthorized waste handling attracts criminal action.' },
      { title: 'Fire NOC Renewal', desc: 'State fire NOC requires periodic renewal; lapses invite hospital closure.' },
      { title: 'CEA Non-Adoption States', desc: 'In States that haven\'t adopted CEA, State-specific Acts apply — verify before assuming framework.' },
      { title: 'NABH Without Foundation', desc: 'Pursuing NABH without consistent SOPs invites assessment failure.' },
    ],
    faqs: [
      { q: 'How long does hospital setup take?', a: '12-24 months from sponsor body to operational hospital, depending on bed size and specialty. Multi-specialty 200+ bed hospitals often take 24-36 months.' },
      { q: 'Is NABH mandatory?', a: 'Not mandatory by law. But practically required for empanelment with major insurers, corporates, government schemes (Ayushman Bharat especially).' },
      { q: 'What about Ayushman Bharat empanelment?', a: 'Empanelment via State Health Authority — requires CEA / equivalent registration, NABH (or NABH-Entry Level), specialty match and infrastructure verification.' },
      { q: 'Can NRIs / foreign capital invest in hospitals?', a: 'Yes — FDI is permitted up to 100% under automatic route in greenfield hospitals. Brownfield acquisitions over 49% require government approval.' },
    ],
    relatedServices: [
      { name: 'University Setup & License', href: '/services/business-registration/institutional-setup/university-setup' },
      { name: 'AYUSH License', href: '/services/business-registration/license/ayush-license' },
      { name: 'Drug License', href: '/services/business-registration/license/drug-license' },
    ],
  },

  'petrol-pump': {
    title: 'Petrol Pump License',
    description:
      'Petrol pump (retail outlet) license — Oil Marketing Company (IOCL / BPCL / HPCL / Reliance / Nayara) dealership, NOC, infrastructure and operational compliance.',
    keywords: ['petrol pump license', 'OMC dealership', 'IOCL dealership', 'petrol pump dealership India', 'CC&DA agreement', 'fuel station license'],
    overview:
      'Setting up a petrol pump (retail outlet) involves obtaining dealership from an Oil Marketing Company (OMC) — IOCL, BPCL, HPCL, Reliance, Nayara, Shell — plus a stack of regulatory approvals. OMCs periodically advertise dealership opportunities with eligibility criteria (age, education, financial capacity, land ownership / lease, demographic restrictions for SC/ST/OBC quotas).\n\nKey approvals include: OMC dealership letter, NOC from district administration, Petroleum and Explosives Safety Organisation (PESO) license under Petroleum Rules, 2002, Local Body NOC, Fire NOC, Pollution Consent (CTE / CTO), Police NOC, Highway Authority NOC (if on highway), Building plan approvals and Drug Inspector NOC (where lubricant retail).\n\nWe handle end-to-end petrol pump licensing — eligibility advisory for OMC bid, application drafting, NOC procurement chain, infrastructure compliance and dealership commencement.',
    whyChooseUs: [
      { title: 'OMC Bid Advisory', desc: 'Application strength assessment for IOCL, BPCL, HPCL, Reliance dealership rounds.' },
      { title: 'Multi-NOC Chain', desc: 'PESO, Fire, Pollution, Local Body, Highway, Police — all coordinated.' },
      { title: 'Land Compliance', desc: 'Land use (commercial / highway), set-back, easement issues navigated.' },
      { title: 'Operational Compliance', desc: 'Periodic PESO renewals, BIS / weights & measures, fire drills.' },
    ],
    keyPoints: [
      'OMC dealership application (IOCL / BPCL / HPCL / Reliance)',
      'PESO license under Petroleum Rules, 2002',
      'Land — minimum 1200-1500 sqm typical',
      'Land use approvals (commercial / highway)',
      'Set-back from highway / habitation',
      'Fire NOC with mock drill',
      'Pollution Consent (CTE / CTO)',
      'Local Body / Municipal NOC',
      'Highway Authority NOC (NH/SH locations)',
      'Police NOC',
      'Drug Inspector NOC (lubricant retail)',
      'CC&DA (Capital, Construction & Dealership Agreement) with OMC',
    ],
    process: [
      { title: 'OMC Eligibility', desc: 'Verify category (open / SC / ST / OBC), education, age, finances, land ownership.' },
      { title: 'Bid Application', desc: 'Apply during OMC dealership advertisement; selection by draw / interview.' },
      { title: 'Selection & Land', desc: 'Selected; land verification by OMC team.' },
      { title: 'NOC Stack', desc: 'PESO, Fire, Pollution, Local Body, Highway, Police NOCs.' },
      { title: 'Construction', desc: 'OMC-approved layout; tank installation; pumps; safety features.' },
      { title: 'Commissioning', desc: 'PESO inspection; OMC commissioning; trial run; commercial operation.' },
    ],
    statutoryRefs: [
      { name: 'Petroleum Act, 1934', desc: 'Foundation petroleum law.' },
      { name: 'Petroleum Rules, 2002', desc: 'PESO license, storage, dispensing.' },
      { name: 'Petroleum and Minerals Pipelines Act', desc: 'Pipeline-related regulation.' },
      { name: 'Static and Mobile Pressure Vessels Rules', desc: 'For LPG / CNG outlets.' },
    ],
    pitfalls: [
      { title: 'Land Title Defects', desc: 'OMCs verify land title rigorously; defects discovered post-bid lead to dealership cancellation.' },
      { title: 'Set-back / Easement Issues', desc: 'Highway set-back norms (NHAI 30m+) often missed in private land selection.' },
      { title: 'PESO Inspection Failures', desc: 'Layout deviations from approved plan cause PESO refusal or delay.' },
      { title: 'Operational Compliance', desc: 'Periodic PESO renewals (every 1-3 years), fire drills, audit are mandatory.' },
    ],
    faqs: [
      { q: 'How do I apply for petrol pump dealership?', a: 'Through OMC advertisements (IOCL, BPCL, HPCL, Reliance) — periodically released with eligibility criteria. Apply online during the open window.' },
      { q: 'What land area is required?', a: 'Typically 1200-1500 sqm for highway outlets, smaller for urban (800-1200 sqm). Specific requirements per OMC and location.' },
      { q: 'Can I sell my dealership?', a: 'Generally yes, with OMC consent and dealership transfer process. Some dealerships are tied to specific bidder (SC/ST quota etc.) and have transfer restrictions.' },
      { q: 'How profitable is a petrol pump?', a: 'Margins on fuels are regulated and modest. Profitability depends on volume, location and ancillary services (lubes, food, ATM, c-store).' },
    ],
    relatedServices: [
      { name: 'Factory License', href: '/services/business-registration/license/factory-license' },
      { name: 'Liquor License', href: '/services/business-registration/license/liquor-license' },
      { name: 'Trade License', href: '/services/business-registration/license/trade-license' },
    ],
  },

  'csr-advisory': {
    title: 'CSR Advisory',
    description:
      'Corporate Social Responsibility advisory under Section 135 Companies Act — CSR policy, project structuring, implementation, reporting and Form CSR-2 filing.',
    keywords: ['CSR advisory', 'Section 135 Companies Act', 'CSR policy', 'CSR-2 filing', 'CSR implementation', 'corporate social responsibility India'],
    overview:
      'Corporate Social Responsibility (CSR) under Section 135 of the Companies Act, 2013 is mandatory for companies meeting any of: net worth ≥ ₹500 crore, turnover ≥ ₹1000 crore, or net profit ≥ ₹5 crore. Eligible companies must spend ≥ 2% of average net profits of preceding 3 years on CSR activities under Schedule VII.\n\nKey compliance includes: CSR Committee constitution, CSR Policy adoption, identification of implementing entities (NGO with 12A / 12AB + 80G or Section 8 / Trust / Society), CSR-1 registration of implementing agencies, project execution per approved policy, impact assessment for projects > ₹1 crore (where companies have spent > ₹10 crore in 3 preceding years), and annual reporting via Form CSR-2.\n\nWe provide end-to-end CSR advisory — policy design, partner selection, project structuring, audit-ready accounting, impact assessment coordination and Form CSR-2 / Schedule VII reporting.',
    whyChooseUs: [
      { title: 'Strategic CSR Design', desc: 'Beyond compliance — CSR aligned with business and stakeholder strategy.' },
      { title: 'Partner Vetting', desc: 'Implementing agency due diligence (12A, 80G, FCRA, governance, track record).' },
      { title: 'Impact Assessment', desc: 'Coordinated impact studies for projects > ₹1 crore.' },
      { title: 'Form CSR-2 Filing', desc: 'Annual reporting handled with full Schedule VII compliance.' },
    ],
    keyPoints: [
      'Section 135 applicability assessment',
      'CSR Committee constitution',
      'CSR Policy drafting per Schedule VII',
      'Implementing agency vetting (12A / 12AB / 80G / FCRA)',
      'CSR-1 registration of agency',
      'CSR project structuring',
      '2% of average net profit computation',
      'Unspent amount handling — 30 March transfer to Unspent CSR Account',
      'Impact assessment for projects > ₹1 crore',
      'Form CSR-2 annual reporting',
      'Schedule VII activity compliance',
      'Penalty avoidance — Section 135(7)',
    ],
    process: [
      { title: 'Applicability Diagnosis', desc: 'Verify thresholds; compute 2% mandate.' },
      { title: 'Committee & Policy', desc: 'Constitute CSR Committee; adopt CSR Policy.' },
      { title: 'Partner Selection', desc: 'Vet implementing agencies; CSR-1 registration confirmation.' },
      { title: 'Project Approval', desc: 'Board approval for annual CSR action plan.' },
      { title: 'Implementation & Audit', desc: 'Execute projects; maintain audit-ready records.' },
      { title: 'Reporting', desc: 'Annual report under Schedule III; Form CSR-2 filing within 31 March of next FY.' },
    ],
    statutoryRefs: [
      { name: 'Companies Act, 2013 — Section 135', desc: 'CSR mandate framework.' },
      { name: 'Companies (CSR Policy) Rules, 2014 (as amended 2021)', desc: 'Procedural framework.' },
      { name: 'Schedule VII', desc: 'Permissible CSR activity categories.' },
      { name: 'Section 135(7)', desc: 'Penalty for non-compliance — 2x unspent amount or ₹1 crore (whichever less).' },
    ],
    pitfalls: [
      { title: 'Schedule VII Non-Alignment', desc: 'Activities not aligned with Schedule VII don\'t qualify as CSR — leading to spend disallowance and penalty.' },
      { title: 'Unspent Without Transfer', desc: 'Unspent CSR (excluding ongoing projects) must transfer to specified fund within 6 months. Default invites penalty.' },
      { title: 'Implementing Agency Without CSR-1', desc: 'CSR contributions to non-CSR-1 registered agencies don\'t qualify.' },
      { title: 'Missing Impact Assessment', desc: 'Projects > ₹1 crore (for companies with > ₹10 crore CSR spend in 3 years) require impact assessment.' },
    ],
    faqs: [
      { q: 'Is CSR optional or mandatory?', a: 'Mandatory for companies meeting any threshold under Section 135 (net worth, turnover, or net profit). Spending less than 2% requires explanation in Board\'s report.' },
      { q: 'Can CSR be done in-house?', a: 'Yes — through company itself, holding subsidiary or related entity (with CSR-1 registration), or through external Section 8 / Trust / Society / political research / academic institution (with proper registration).' },
      { q: 'What if we don\'t spend the full 2%?', a: 'Unspent amount (excluding ongoing projects) must be transferred to a Schedule VII fund within 6 months. Ongoing projects can be carried forward in Unspent CSR Account.' },
      { q: 'Is Form CSR-2 mandatory?', a: 'Yes — annual filing within 31 March of next FY. Detailed reporting on policy, projects, spend, impact.' },
      { q: 'What is the penalty?', a: 'Twice the unspent amount required to be transferred OR ₹1 crore (whichever less) on company; ₹2 lakh on each defaulting officer.' },
    ],
    relatedServices: [
      { name: 'Annual Compliances — Pvt. Ltd.', href: '/services/compliances/company-compliances/annual-pvt-ltd' },
      { name: 'Section 8 Company Registration', href: '/services/business-registration/company-registration/section-8-company' },
      { name: 'ITR for NGO', href: '/services/business-registration/taxation/itr-ngo' },
    ],
  },
};
