import type { ServiceContent } from '@/components/leaf-service-page';

export const institutionalSetupServices: Record<string, ServiceContent> = {
  'political-party': {
    title: 'Political Party Formation & License',
    description:
      'Political party formation and Section 29A registration with Election Commission of India — constitution, executive, application, ECI hearing and recognition.',
    keywords: ['political party registration', 'Section 29A RP Act', 'ECI registration', 'political party formation India', 'recognized political party', 'state political party'],
    overview:
      'Forming a political party in India requires registration with the Election Commission of India (ECI) under Section 29A of the Representation of the People Act, 1951. Registration grants the party the right to contest elections, allotment of common symbols (after recognition criteria), and Section 13A income-tax exemption (subject to compliance).\n\nThe process involves drafting the party constitution, identifying office bearers, gathering minimum 100 members from at least three States with affidavits, paying fee (₹10,000), filing application with ECI, public notice in two newspapers, and ECI hearing. After registration, recognition as State Party / National Party requires additional electoral performance criteria.\n\nWe handle end-to-end party formation — strategic naming, constitution drafting, member affidavit preparation, ECI application, hearing representation and post-registration compliance (Section 29C reports, Section 13A claim, ECI annual filings).',
    whyChooseUs: [
      { title: 'ECI-Specialist Counsel', desc: 'Experienced in Section 29A applications, oppositions and hearings.' },
      { title: 'Constitution Drafting', desc: 'Customized party constitution per ECI guidelines, with internal democracy compliance.' },
      { title: 'Member Affidavit Coordination', desc: '100+ member affidavits across States compiled and filed.' },
      { title: 'Post-Registration Compliance', desc: 'Section 13A, 29C reports, annual filings, election compliances.' },
    ],
    keyPoints: [
      'Section 29A RP Act registration with ECI',
      'Party constitution drafting (internal democracy mandated)',
      'Office bearers and central committee setup',
      '100+ founding member affidavits across 3+ States',
      'Public notice in 2 newspapers (English + regional)',
      'ECI fee — ₹10,000',
      'ECI hearing representation',
      'Symbol allotment (recognition pending)',
      'Section 13A income tax exemption',
      'Section 29C contribution reporting',
      'Annual ECI compliance filings',
      'State / National Party recognition strategy',
    ],
    process: [
      { title: 'Strategic Setup', desc: 'Party name, ideology positioning, founding members across States.' },
      { title: 'Constitution & Application', desc: 'Constitution drafted; ECI application Form-3 prepared.' },
      { title: 'Public Notice', desc: '2 newspapers — invite objections within 30 days.' },
      { title: 'ECI Filing', desc: 'Submit application with affidavits, fee, NOC documents.' },
      { title: 'Hearing & Registration', desc: 'ECI hearing; address objections; receive registration.' },
      { title: 'Compliance Setup', desc: 'Section 13A bookkeeping, Section 29C reporting calendar.' },
    ],
    documents: [
      'Party constitution',
      'List of office bearers with photo IDs',
      'Affidavits of 100+ founding members',
      'Members\' address proofs across 3+ States',
      'Bank account opening letter',
      'Newspaper notices (2 publications)',
      'PAN of party (post-registration)',
      'Office address proof',
    ],
    statutoryRefs: [
      { name: 'Representation of the People Act, 1951 — Section 29A', desc: 'Party registration framework.' },
      { name: 'Section 29C', desc: 'Annual contribution reporting to ECI.' },
      { name: 'Income-tax Act, 1961 — Section 13A', desc: 'Tax exemption for registered political parties.' },
      { name: 'ECI Symbols (Reservation and Allotment) Order, 1968', desc: 'Symbol allotment and party recognition.' },
    ],
    pitfalls: [
      { title: 'Inadequate Member Coverage', desc: 'Less than 100 members or not from 3+ States invites application rejection.' },
      { title: 'Missing Internal Democracy', desc: 'Constitution must provide for periodic internal elections; absence is rejection ground.' },
      { title: 'Section 13A Lapses', desc: 'Above ₹20,000 cash contribution without donor record disqualifies entire 13A exemption.' },
      { title: 'Symbol Allotment Confusion', desc: 'Symbol is allotted only on satisfying recognition criteria — newly registered parties face this.' },
    ],
    faqs: [
      { q: 'How long does ECI registration take?', a: 'Typically 6-12 months from application — comprising public notice (30 days), ECI processing, hearing and registration.' },
      { q: 'What is the difference between registered and recognized?', a: 'Registered party is approved by ECI but doesn\'t have a reserved symbol. Recognition (State / National) requires electoral performance — vote share / seat percentage thresholds.' },
      { q: 'Can a party be deregistered?', a: 'Yes — by ECI for non-compliance. Recently several inactive parties have been delisted.' },
      { q: 'Are donations to political parties tax-deductible?', a: 'Donors can claim Section 80GGB / 80GGC for donations to registered political parties — but cash donations restricted to ₹2,000.' },
      { q: 'What about electoral bonds?', a: 'The 2024 Supreme Court ruling struck down the Electoral Bond scheme. Going forward, party finance follows direct disclosure norms.' },
    ],
    relatedServices: [
      { name: 'ITR for Political Party', href: '/services/business-registration/taxation/itr-political-party' },
      { name: 'Society Registration (NGO)', href: '/services/business-registration/other-registration/society-registration' },
      { name: 'Trust Registration (NGO)', href: '/services/business-registration/other-registration/trust-registration' },
    ],
  },

  'university-setup': {
    title: 'University Setup & License',
    description:
      'End-to-end legal support for setting up universities — State Private University Act / Deemed-to-be-University, UGC approval, NOCs, infrastructure compliance.',
    keywords: ['university setup India', 'private university registration', 'deemed university', 'UGC approval', 'state private university act', 'higher education setup'],
    overview:
      'Establishing a university in India is a multi-year, multi-regulator project. Three primary routes: (a) Central University by Act of Parliament, (b) State Private University by State Act, (c) Deemed-to-be-University recognition by Ministry of Education on UGC recommendation. Each has distinct eligibility, capital requirement, infrastructure norms and approval timelines.\n\nA private university typically requires 25-50 acres land, ₹50-100 crore corpus, sponsor body (society / trust / Section 8), academic infrastructure, qualified faculty plan and detailed business case. State Act-based private universities are the most common new-entry route.\n\nWe provide end-to-end advisory — entity structuring, State NOC, sponsor body documentation, State Private University Bill drafting / lobbying, UGC inspection coordination, statutory committee setup and post-establishment compliance under UGC, AICTE, NMC, BCI etc.',
    whyChooseUs: [
      { title: 'End-to-End Project Lead', desc: 'From land acquisition to first batch — single project lead across regulators.' },
      { title: 'State Bill Drafting', desc: 'Private university bill drafted to State template with negotiable provisions.' },
      { title: 'UGC Inspection Readiness', desc: 'Infrastructure, faculty, governance prepared for UGC visits.' },
      { title: 'Multi-Regulator Coordination', desc: 'AICTE, NMC, BCI, NCTE, COA approvals as program-specific.' },
    ],
    keyPoints: [
      'State Private University Act establishment',
      'Deemed-to-be-University recognition (MoE / UGC)',
      'Sponsor body — Society / Trust / Section 8 setup',
      'Land use, zoning and infrastructure approvals',
      'State NOC / Essentiality Certificate',
      'Bill drafting for private university',
      'UGC, AICTE, NMC, BCI program approvals',
      'Affiliation framework (where applicable)',
      'Statutory committees — Governing Council, Academic Council, Finance Committee',
      'NAAC / NBA accreditation readiness',
    ],
    process: [
      { title: 'Project Diagnostic', desc: 'Vision, scale, location, programs, regulatory route selection.' },
      { title: 'Sponsor Body & Land', desc: 'Set up sponsor entity; acquire land; obtain land-use approvals.' },
      { title: 'State Approval', desc: 'State NOC; Bill drafting and passage in State Legislature.' },
      { title: 'UGC Recognition', desc: 'UGC recognition under Section 2(f) of UGC Act; first batch commencement.' },
      { title: 'Operations', desc: 'Faculty, programs, statutory committees, governance, ongoing compliance.' },
    ],
    statutoryRefs: [
      { name: 'UGC Act, 1956', desc: 'Statutory framework for universities and higher education.' },
      { name: 'State Private University Acts', desc: 'State-specific framework — Maharashtra, Karnataka, Haryana, Rajasthan, etc.' },
      { name: 'UGC (Deemed Universities) Regulations, 2010', desc: 'Deemed university recognition framework.' },
      { name: 'AICTE, NMC, BCI, NCTE, COA Acts', desc: 'Program-specific regulator approvals.' },
    ],
    pitfalls: [
      { title: 'Underestimating Timeline', desc: 'University setup typically takes 3-7 years end-to-end. Realistic project planning is essential.' },
      { title: 'Insufficient Corpus', desc: 'Below regulatory corpus (typically ₹50 crore+) invites State / UGC rejection.' },
      { title: 'Land Use Issues', desc: 'Agricultural-to-educational conversion, zoning, FSI must be cleared before commencement.' },
      { title: 'Faculty Plan Gaps', desc: 'UGC inspection focuses heavily on faculty qualifications and ratios; weak plan invites adverse report.' },
    ],
    faqs: [
      { q: 'How long does university setup take?', a: 'Typically 3-7 years from concept to first batch — sponsor body setup (1 year), land + State approvals (1-2 years), Bill / Act passage (1-2 years), UGC recognition + faculty / infra (1-2 years).' },
      { q: 'What is the minimum corpus?', a: 'Varies by State. Typical ranges — Maharashtra ₹50 crore, Karnataka ₹50 crore, Gujarat ₹100 crore, Haryana ₹100 crore. Check specific State Act.' },
      { q: 'Private University Act or Deemed?', a: 'Private University Act — geographic limitation (in State). Deemed — pan-India operation but stricter eligibility (existing institution with track record).' },
      { q: 'Can foreign universities operate in India?', a: 'Yes — under UGC (Setting up and Operation of Campuses of Foreign Higher Educational Institutions in India) Regulations, 2023. Several foreign universities have begun India operations.' },
    ],
    relatedServices: [
      { name: 'School Setup & License', href: '/services/business-registration/institutional-setup/school-setup' },
      { name: 'Society Registration', href: '/services/business-registration/other-registration/society-registration' },
      { name: 'Educational Law', href: '/services/global-business/educational-law' },
    ],
  },

  'school-setup': {
    title: 'School Setup & License',
    description:
      'School setup advisory — State NOC, CBSE / ICSE / State Board affiliation, RTE compliance, infrastructure and recurring affiliation renewals.',
    keywords: ['school setup India', 'CBSE affiliation', 'ICSE school setup', 'private school license', 'RTE compliance school', 'school registration'],
    overview:
      'Setting up a school requires layered approvals — entity registration (society / trust / Section 8), State Government NOC / Essentiality Certificate, recognition by State Education Department, board affiliation (CBSE / ICSE / State Board / IB), RTE Section 12(1)(c) compliance and various municipal / safety clearances.\n\nThe sequence typically takes 2-4 years from concept to first session. Critical milestones include land acquisition with appropriate use, infrastructure construction per board norms, faculty hiring, fire & safety certificates, and pre-affiliation inspection. Provisional affiliation precedes regular affiliation by 2-3 years.\n\nWe handle end-to-end school setup — sponsor body formation, State approvals, board affiliation, RTE compliance, fee regulation (where applicable), recurring renewals and dispute defence (parent / regulator / labour matters).',
    whyChooseUs: [
      { title: 'CBSE / ICSE / IB Specialists', desc: 'Affiliation experience across all major boards with current SOP knowledge.' },
      { title: 'State NOC Coordination', desc: 'State Education Department NOC handled — often the bottleneck.' },
      { title: 'RTE Compliance', desc: '25% RTE Section 12(1)(c) admission process and reimbursement.' },
      { title: 'Recurring Renewals', desc: 'Renewal calendar managed; never miss a deadline.' },
    ],
    keyPoints: [
      'Society / Trust / Section 8 sponsor body',
      'State NOC / Essentiality Certificate',
      'CBSE affiliation (provisional / regular)',
      'ICSE affiliation (CISCE)',
      'State Board recognition',
      'IB / IGCSE accreditation',
      'RTE Act 2009 — 25% admission compliance',
      'Land use and infrastructure norms (per board)',
      'Fire, building, sanitation NOCs',
      'Faculty qualifications (B.Ed for primary, subject-specialists for secondary)',
      'POSH Act compliance and ICC',
      'Anti-ragging committee (where applicable)',
    ],
    process: [
      { title: 'Project Setup', desc: 'Sponsor body, land, building plan, business case.' },
      { title: 'State NOC', desc: 'State Education Department application; site verification.' },
      { title: 'Construction & Setup', desc: 'School building per board norms; recruitment.' },
      { title: 'Board Affiliation', desc: 'CBSE / ICSE / State Board provisional affiliation.' },
      { title: 'First Batch & RTE', desc: 'First academic session; RTE 25% admission process.' },
      { title: 'Regular Affiliation', desc: '2-3 years later, regular affiliation after compliance review.' },
    ],
    statutoryRefs: [
      { name: 'Right to Education Act, 2009', desc: '25% admission for disadvantaged children; reimbursement framework.' },
      { name: 'CBSE Affiliation Bye-laws, 2018', desc: 'Affiliation norms — infrastructure, faculty, governance.' },
      { name: 'CISCE Regulations', desc: 'ICSE affiliation framework.' },
      { name: 'State Education Acts', desc: 'State-specific school regulation — fee, admission, recognition.' },
    ],
    pitfalls: [
      { title: 'Wrong Land Use', desc: 'Agricultural / commercial use without educational conversion blocks affiliation.' },
      { title: 'RTE Non-Compliance', desc: '25% RTE admission lapses invite parent litigation, regulatory action and reimbursement issues.' },
      { title: 'Faculty Shortcuts', desc: 'Underqualified or ad-hoc faculty during inspection can derail affiliation.' },
      { title: 'Fee Regulation Defiance', desc: 'States with Fee Regulation Acts (Tamil Nadu, Maharashtra, Karnataka) have legal fee caps.' },
    ],
    faqs: [
      { q: 'How long does CBSE affiliation take?', a: 'Provisional affiliation 12-18 months from full application. Regular affiliation comes 2-3 years after provisional.' },
      { q: 'What is RTE 25% obligation?', a: 'Section 12(1)(c) of RTE Act mandates 25% admission of disadvantaged / weaker section children at entry-level. State governments reimburse fee per State norms.' },
      { q: 'Can private schools be for-profit?', a: 'School education in India is largely required to be not-for-profit. Coaching, training, ed-tech businesses can be for-profit.' },
      { q: 'What happens if affiliation is denied?', a: 'Provisional affiliation can be re-applied after curing defects. Final denial can be challenged before CBSE Appellate Authority and writ courts.' },
    ],
    relatedServices: [
      { name: 'University Setup & License', href: '/services/business-registration/institutional-setup/university-setup' },
      { name: 'Society Registration (NGO)', href: '/services/business-registration/other-registration/society-registration' },
      { name: 'Educational Law — Institutional', href: '/services/global-business/educational-law/institutional' },
    ],
  },

  'hospital-setup': {
    title: 'Hospital Setup & License',
    description:
      'Multi-specialty hospital setup — Clinical Establishment Act registration, NABH accreditation, biomedical waste, fire / pollution NOCs and ongoing compliance.',
    keywords: ['hospital setup India', 'clinical establishment act', 'NABH accreditation', 'hospital license', 'biomedical waste authorization', 'multi-specialty hospital'],
    overview:
      'Hospital establishment is heavily regulated and varies by State — Clinical Establishments (Registration and Regulation) Act, 2010 in adopting States, plus State-specific Acts. Approvals span building / land use, fire safety, biomedical waste authorization (under BMW Rules, 2016), pollution control, drug license, blood bank license (if applicable), AERB for radiology, MTP authorization, and various sub-specialty registrations.\n\nMulti-specialty hospitals additionally require empanelment with insurance, government schemes (Ayushman Bharat / State health schemes), employees insurance and CGHS empanelment. NABH (National Accreditation Board for Hospitals) accreditation, while voluntary, is increasingly required by insurers and corporate clients.\n\nWe handle end-to-end hospital licensing — entity formation, multi-NOC procurement, accreditation readiness, ongoing compliance and dispute defence (medical negligence, regulator disputes, employment matters).',
    whyChooseUs: [
      { title: 'Multi-NOC Coordination', desc: 'Fire, pollution, BMW, drug, AERB, blood bank — all NOCs in single workflow.' },
      { title: 'NABH Pre-Accreditation', desc: 'Quality manual, SOPs and protocol design for NABH readiness.' },
      { title: 'Insurance Empanelment', desc: 'CGHS, ESIC, Ayushman Bharat empanelment alongside operational launch.' },
      { title: 'Compliance Calendar', desc: 'Renewal-tracking calendar across 10-15 distinct licenses.' },
    ],
    keyPoints: [
      'Clinical Establishments Act registration',
      'State hospital / nursing home registration',
      'Building & fire safety NOCs',
      'Biomedical Waste authorization (BMW Rules, 2016)',
      'Pollution Control Board consent',
      'Drug License (Form 20B / 21B)',
      'Blood Bank License (if applicable)',
      'AERB radiation safety license',
      'MTP authorization (if applicable)',
      'CGHS / ESIC / Ayushman Bharat empanelment',
      'NABH / NABL accreditation',
      'POSH / Anti-Ragging compliance',
    ],
    process: [
      { title: 'Project Diagnostic', desc: 'Specialty mix, bed strength, location, regulator mapping.' },
      { title: 'Entity & Land', desc: 'Sponsor body; land with healthcare use; building plan.' },
      { title: 'Multi-NOC Stack', desc: 'Fire, pollution, BMW, drug, AERB, blood bank in parallel.' },
      { title: 'Operational Launch', desc: 'Faculty / staff onboarding; SOPs; first patient.' },
      { title: 'Empanelment', desc: 'CGHS, ESIC, Ayushman Bharat, private insurers.' },
      { title: 'NABH', desc: 'Pre-accreditation gap; SSR; assessment; accreditation.' },
    ],
    statutoryRefs: [
      { name: 'Clinical Establishments Act, 2010', desc: 'Registration for clinics / hospitals / nursing homes in adopting States.' },
      { name: 'BMW Rules, 2016', desc: 'Biomedical waste handling and authorization.' },
      { name: 'Drugs and Cosmetics Act, 1940', desc: 'Pharmacy / drug stocking license.' },
      { name: 'Atomic Energy (Radiation Protection) Rules, 2004', desc: 'AERB license for radiology / radiation procedures.' },
      { name: 'MTP Act, 1971 (as amended)', desc: 'Authorization for termination procedures.' },
    ],
    pitfalls: [
      { title: 'BMW Authorization Lapse', desc: 'Biomedical waste authorization is critical — unauthorized waste handling attracts criminal action.' },
      { title: 'Fire NOC Renewal', desc: 'State fire NOC requires periodic renewal; lapses invite hospital closure.' },
      { title: 'CEA Non-Adoption States', desc: 'In States that haven\'t adopted CEA, State-specific Acts apply — verify before assuming framework.' },
      { title: 'NABH Without Foundation', desc: 'Pursuing NABH without consistent SOPs invites assessment failure.' },
    ],
    faqs: [
      { q: 'How long does hospital setup take?', a: '12-24 months from sponsor body to operational hospital, depending on bed size and specialty. Multi-specialty 200+ bed hospitals often take 24-36 months.' },
      { q: 'Is NABH mandatory?', a: 'Not mandatory by law. But practically required for empanelment with major insurers, corporates, government schemes (Ayushman Bharat especially).' },
      { q: 'What about Ayushman Bharat empanelment?', a: 'Empanelment via State Health Authority — requires CEA / equivalent registration, NABH (or NABH-Entry Level), specialty match and infrastructure verification.' },
      { q: 'Can NRIs / foreign capital invest in hospitals?', a: 'Yes — FDI is permitted up to 100% under automatic route in greenfield hospitals. Brownfield acquisitions over 49% require government approval.' },
    ],
    relatedServices: [
      { name: 'University Setup & License', href: '/services/business-registration/institutional-setup/university-setup' },
      { name: 'AYUSH License', href: '/services/business-registration/license/ayush-license' },
      { name: 'Drug License', href: '/services/business-registration/license/drug-license' },
    ],
  },

  'petrol-pump': {
    title: 'Petrol Pump License',
    description:
      'Petrol pump (retail outlet) license — Oil Marketing Company (IOCL / BPCL / HPCL / Reliance / Nayara) dealership, NOC, infrastructure and operational compliance.',
    keywords: ['petrol pump license', 'OMC dealership', 'IOCL dealership', 'petrol pump dealership India', 'CC&DA agreement', 'fuel station license'],
    overview:
      'Setting up a petrol pump (retail outlet) involves obtaining dealership from an Oil Marketing Company (OMC) — IOCL, BPCL, HPCL, Reliance, Nayara, Shell — plus a stack of regulatory approvals. OMCs periodically advertise dealership opportunities with eligibility criteria (age, education, financial capacity, land ownership / lease, demographic restrictions for SC/ST/OBC quotas).\n\nKey approvals include: OMC dealership letter, NOC from district administration, Petroleum and Explosives Safety Organisation (PESO) license under Petroleum Rules, 2002, Local Body NOC, Fire NOC, Pollution Consent (CTE / CTO), Police NOC, Highway Authority NOC (if on highway), Building plan approvals and Drug Inspector NOC (where lubricant retail).\n\nWe handle end-to-end petrol pump licensing — eligibility advisory for OMC bid, application drafting, NOC procurement chain, infrastructure compliance and dealership commencement.',
    whyChooseUs: [
      { title: 'OMC Bid Advisory', desc: 'Application strength assessment for IOCL, BPCL, HPCL, Reliance dealership rounds.' },
      { title: 'Multi-NOC Chain', desc: 'PESO, Fire, Pollution, Local Body, Highway, Police — all coordinated.' },
      { title: 'Land Compliance', desc: 'Land use (commercial / highway), set-back, easement issues navigated.' },
      { title: 'Operational Compliance', desc: 'Periodic PESO renewals, BIS / weights & measures, fire drills.' },
    ],
    keyPoints: [
      'OMC dealership application (IOCL / BPCL / HPCL / Reliance)',
      'PESO license under Petroleum Rules, 2002',
      'Land — minimum 1200-1500 sqm typical',
      'Land use approvals (commercial / highway)',
      'Set-back from highway / habitation',
      'Fire NOC with mock drill',
      'Pollution Consent (CTE / CTO)',
      'Local Body / Municipal NOC',
      'Highway Authority NOC (NH/SH locations)',
      'Police NOC',
      'Drug Inspector NOC (lubricant retail)',
      'CC&DA (Capital, Construction & Dealership Agreement) with OMC',
    ],
    process: [
      { title: 'OMC Eligibility', desc: 'Verify category (open / SC / ST / OBC), education, age, finances, land ownership.' },
      { title: 'Bid Application', desc: 'Apply during OMC dealership advertisement; selection by draw / interview.' },
      { title: 'Selection & Land', desc: 'Selected; land verification by OMC team.' },
      { title: 'NOC Stack', desc: 'PESO, Fire, Pollution, Local Body, Highway, Police NOCs.' },
      { title: 'Construction', desc: 'OMC-approved layout; tank installation; pumps; safety features.' },
      { title: 'Commissioning', desc: 'PESO inspection; OMC commissioning; trial run; commercial operation.' },
    ],
    statutoryRefs: [
      { name: 'Petroleum Act, 1934', desc: 'Foundation petroleum law.' },
      { name: 'Petroleum Rules, 2002', desc: 'PESO license, storage, dispensing.' },
      { name: 'Petroleum and Minerals Pipelines Act', desc: 'Pipeline-related regulation.' },
      { name: 'Static and Mobile Pressure Vessels Rules', desc: 'For LPG / CNG outlets.' },
    ],
    pitfalls: [
      { title: 'Land Title Defects', desc: 'OMCs verify land title rigorously; defects discovered post-bid lead to dealership cancellation.' },
      { title: 'Set-back / Easement Issues', desc: 'Highway set-back norms (NHAI 30m+) often missed in private land selection.' },
      { title: 'PESO Inspection Failures', desc: 'Layout deviations from approved plan cause PESO refusal or delay.' },
      { title: 'Operational Compliance', desc: 'Periodic PESO renewals (every 1-3 years), fire drills, audit are mandatory.' },
    ],
    faqs: [
      { q: 'How do I apply for petrol pump dealership?', a: 'Through OMC advertisements (IOCL, BPCL, HPCL, Reliance) — periodically released with eligibility criteria. Apply online during the open window.' },
      { q: 'What land area is required?', a: 'Typically 1200-1500 sqm for highway outlets, smaller for urban (800-1200 sqm). Specific requirements per OMC and location.' },
      { q: 'Can I sell my dealership?', a: 'Generally yes, with OMC consent and dealership transfer process. Some dealerships are tied to specific bidder (SC/ST quota etc.) and have transfer restrictions.' },
      { q: 'How profitable is a petrol pump?', a: 'Margins on fuels are regulated and modest. Profitability depends on volume, location and ancillary services (lubes, food, ATM, c-store).' },
    ],
    relatedServices: [
      { name: 'Factory License', href: '/services/business-registration/license/factory-license' },
      { name: 'Liquor License', href: '/services/business-registration/license/liquor-license' },
      { name: 'Trade License', href: '/services/business-registration/license/trade-license' },
    ],
  },

  'csr-advisory': {
    title: 'CSR Advisory',
    description:
      'Corporate Social Responsibility advisory under Section 135 Companies Act — CSR policy, project structuring, implementation, reporting and Form CSR-2 filing.',
    keywords: ['CSR advisory', 'Section 135 Companies Act', 'CSR policy', 'CSR-2 filing', 'CSR implementation', 'corporate social responsibility India'],
    overview:
      'Corporate Social Responsibility (CSR) under Section 135 of the Companies Act, 2013 is mandatory for companies meeting any of: net worth ≥ ₹500 crore, turnover ≥ ₹1000 crore, or net profit ≥ ₹5 crore. Eligible companies must spend ≥ 2% of average net profits of preceding 3 years on CSR activities under Schedule VII.\n\nKey compliance includes: CSR Committee constitution, CSR Policy adoption, identification of implementing entities (NGO with 12A / 12AB + 80G or Section 8 / Trust / Society), CSR-1 registration of implementing agencies, project execution per approved policy, impact assessment for projects > ₹1 crore (where companies have spent > ₹10 crore in 3 preceding years), and annual reporting via Form CSR-2.\n\nWe provide end-to-end CSR advisory — policy design, partner selection, project structuring, audit-ready accounting, impact assessment coordination and Form CSR-2 / Schedule VII reporting.',
    whyChooseUs: [
      { title: 'Strategic CSR Design', desc: 'Beyond compliance — CSR aligned with business and stakeholder strategy.' },
      { title: 'Partner Vetting', desc: 'Implementing agency due diligence (12A, 80G, FCRA, governance, track record).' },
      { title: 'Impact Assessment', desc: 'Coordinated impact studies for projects > ₹1 crore.' },
      { title: 'Form CSR-2 Filing', desc: 'Annual reporting handled with full Schedule VII compliance.' },
    ],
    keyPoints: [
      'Section 135 applicability assessment',
      'CSR Committee constitution',
      'CSR Policy drafting per Schedule VII',
      'Implementing agency vetting (12A / 12AB / 80G / FCRA)',
      'CSR-1 registration of agency',
      'CSR project structuring',
      '2% of average net profit computation',
      'Unspent amount handling — 30 March transfer to Unspent CSR Account',
      'Impact assessment for projects > ₹1 crore',
      'Form CSR-2 annual reporting',
      'Schedule VII activity compliance',
      'Penalty avoidance — Section 135(7)',
    ],
    process: [
      { title: 'Applicability Diagnosis', desc: 'Verify thresholds; compute 2% mandate.' },
      { title: 'Committee & Policy', desc: 'Constitute CSR Committee; adopt CSR Policy.' },
      { title: 'Partner Selection', desc: 'Vet implementing agencies; CSR-1 registration confirmation.' },
      { title: 'Project Approval', desc: 'Board approval for annual CSR action plan.' },
      { title: 'Implementation & Audit', desc: 'Execute projects; maintain audit-ready records.' },
      { title: 'Reporting', desc: 'Annual report under Schedule III; Form CSR-2 filing within 31 March of next FY.' },
    ],
    statutoryRefs: [
      { name: 'Companies Act, 2013 — Section 135', desc: 'CSR mandate framework.' },
      { name: 'Companies (CSR Policy) Rules, 2014 (as amended 2021)', desc: 'Procedural framework.' },
      { name: 'Schedule VII', desc: 'Permissible CSR activity categories.' },
      { name: 'Section 135(7)', desc: 'Penalty for non-compliance — 2x unspent amount or ₹1 crore (whichever less).' },
    ],
    pitfalls: [
      { title: 'Schedule VII Non-Alignment', desc: 'Activities not aligned with Schedule VII don\'t qualify as CSR — leading to spend disallowance and penalty.' },
      { title: 'Unspent Without Transfer', desc: 'Unspent CSR (excluding ongoing projects) must transfer to specified fund within 6 months. Default invites penalty.' },
      { title: 'Implementing Agency Without CSR-1', desc: 'CSR contributions to non-CSR-1 registered agencies don\'t qualify.' },
      { title: 'Missing Impact Assessment', desc: 'Projects > ₹1 crore (for companies with > ₹10 crore CSR spend in 3 years) require impact assessment.' },
    ],
    faqs: [
      { q: 'Is CSR optional or mandatory?', a: 'Mandatory for companies meeting any threshold under Section 135 (net worth, turnover, or net profit). Spending less than 2% requires explanation in Board\'s report.' },
      { q: 'Can CSR be done in-house?', a: 'Yes — through company itself, holding subsidiary or related entity (with CSR-1 registration), or through external Section 8 / Trust / Society / political research / academic institution (with proper registration).' },
      { q: 'What if we don\'t spend the full 2%?', a: 'Unspent amount (excluding ongoing projects) must be transferred to a Schedule VII fund within 6 months. Ongoing projects can be carried forward in Unspent CSR Account.' },
      { q: 'Is Form CSR-2 mandatory?', a: 'Yes — annual filing within 31 March of next FY. Detailed reporting on policy, projects, spend, impact.' },
      { q: 'What is the penalty?', a: 'Twice the unspent amount required to be transferred OR ₹1 crore (whichever less) on company; ₹2 lakh on each defaulting officer.' },
    ],
    relatedServices: [
      { name: 'Annual Compliances — Pvt. Ltd.', href: '/services/compliances/company-compliances/annual-pvt-ltd' },
      { name: 'Section 8 Company Registration', href: '/services/business-registration/company-registration/section-8-company' },
      { name: 'ITR for NGO', href: '/services/business-registration/taxation/itr-ngo' },
    ],
  },

  'hotel-resort': {
    title: 'Hotel & Resort Setup & License',
    description:
      'End-to-end hotel and resort licensing — land use, building & fire NOCs, FSSAI, excise/bar license, Police/Sarai Act, pollution consent, lift & DG NOCs and Tourism star classification.',
    keywords: ['hotel license India', 'resort setup license', 'bar license hotel', 'hotel star classification', 'Sarai Act registration', 'FSSAI hotel', 'eating house license', 'hospitality licensing'],
    overview:
      'A hotel or resort is one of the most license-intensive businesses in India — a single property can require 15-25 distinct approvals across municipal, fire, police, excise, food safety, pollution, labour and tourism authorities. The exact stack depends on size, location (urban / hill / coastal / forest), facilities (bar, swimming pool, banquet, spa, casino) and whether alcohol is served.\n\nCore approvals include land-use conversion / commercial zoning, sanctioned building plan and occupancy / completion certificate, Fire NOC, FSSAI food license, Police "eating house" and lodging registration under the Sarai Act, 1867 (or State equivalent), Pollution Control Board Consent to Establish and Operate, lift / escalator license, DG-set NOC, signage license, music / performance license (PPL & IPRS) and — where alcohol is served — an Excise bar / liquor license. Coastal resorts additionally need CRZ clearance and large greenfield projects may trigger Environmental Clearance under EIA Notification, 2006. Voluntary Ministry of Tourism HRACC star classification (1-5 Star / Heritage) unlocks tax benefits and travel-trade visibility.\n\nWe manage the entire license stack as a single sequenced project — pre-construction approvals, parallel NOC procurement, excise licensing, tourism classification and the recurring renewal calendar so no certificate ever lapses.',
    whyChooseUs: [
      { title: 'Full License-Stack Mapping', desc: 'A property-specific matrix of all 15-25 approvals with sequence and dependencies — no surprises mid-build.' },
      { title: 'Excise & Bar Licensing', desc: 'State excise bar / FL-3 / restaurant liquor licensing — often the slowest and most contested approval.' },
      { title: 'Tourism Star Classification', desc: 'HRACC documentation and inspection readiness for 3-5 Star / Heritage classification.' },
      { title: 'Renewal Calendar', desc: 'Single dashboard tracking 20+ license renewals — fire, FSSAI, excise, pollution, lift, Sarai.' },
    ],
    keyPoints: [
      'Land-use conversion / commercial-hospitality zoning',
      'Sanctioned building plan + occupancy / completion certificate',
      'Fire NOC (provisional + final, with mock drill)',
      'FSSAI license (State / Central per turnover)',
      'Police eating-house & lodging (Sarai Act, 1867) registration',
      'Excise bar / liquor license (FL-3 / restaurant bar)',
      'Pollution Control Board CTE / CTO consent',
      'Lift & escalator license; DG-set NOC',
      'Swimming pool & spa NOCs',
      'Music / performance license — PPL & IPRS',
      'Signage / advertisement license; trade license',
      'CRZ clearance (coastal) / Environmental Clearance (large projects)',
      'Ministry of Tourism HRACC star classification',
      'Shops & Establishment / labour, POSH, GST registration',
    ],
    process: [
      { title: 'License Mapping', desc: 'Property-specific audit of all required approvals based on size, location and facilities.' },
      { title: 'Pre-Construction Approvals', desc: 'Land-use conversion, building plan sanction, fire scheme, CRZ / EC where applicable.' },
      { title: 'Build & Parallel NOCs', desc: 'Pollution CTE, lift, DG, water — procured alongside construction.' },
      { title: 'Operational Licenses', desc: 'Occupancy certificate, FSSAI, Police / Sarai, fire final NOC, signage.' },
      { title: 'Excise & Entertainment', desc: 'Bar / liquor license, music (PPL / IPRS), banquet / event permissions.' },
      { title: 'Classification & Renewals', desc: 'HRACC star classification; renewal calendar set up across all licenses.' },
    ],
    documents: [
      'Entity incorporation / partnership documents',
      'Land title / lease deed + land-use conversion order',
      'Sanctioned building plan & occupancy certificate',
      'Fire safety scheme & NOC',
      'Layout of kitchen, bar, rooms, pool',
      'FSSAI application with food category list',
      'Owner / manager KYC for Police & Sarai registration',
      'Pollution consent application with effluent / STP details',
      'DG-set, lift and electrical safety certificates',
      'GST & PAN of the establishment',
    ],
    statutoryRefs: [
      { name: 'Sarai Act, 1867 / State lodging rules', desc: 'Registration of hotels, inns and lodging houses with Police / District authority.' },
      { name: 'State Excise Acts & Rules', desc: 'Bar / liquor license for serving alcohol (FL-3 / restaurant bar categories).' },
      { name: 'FSS Act, 2006 & Regulations', desc: 'Food safety license and hygiene compliance for all food service.' },
      { name: 'Water Act, 1974 & Air Act, 1981', desc: 'Pollution Control Board Consent to Establish and Operate.' },
      { name: 'EIA Notification, 2006 / CRZ Notification, 2019', desc: 'Environmental and coastal clearance for large or coastal projects.' },
      { name: 'Copyright Act, 1957', desc: 'Public performance / music licenses (PPL, IPRS).' },
    ],
    pitfalls: [
      { title: 'Building First, Approvals Later', desc: 'Starting construction before sanctioned plan / land-use conversion invites demolition risk and stalled licensing.' },
      { title: 'Underestimating Excise Timeline', desc: 'Bar / liquor licenses are quota-limited, location-restricted (distance from schools / temples) and slow — start early.' },
      { title: 'Fire NOC Lapses', desc: 'Provisional fire NOC must convert to final and renew periodically; lapses trigger sealing.' },
      { title: 'CRZ Ignorance', desc: 'Beach / backwater resorts built within CRZ without clearance face stop-work and demolition orders.' },
      { title: 'Music License Notices', desc: 'Playing music without PPL / IPRS licenses attracts copyright infringement notices and damages.' },
    ],
    faqs: [
      { q: 'How many licenses does a hotel need?', a: 'Typically 15-25 depending on size and facilities — including building / occupancy, fire, FSSAI, Police / Sarai, pollution, lift, DG, signage, and bar / liquor if alcohol is served. We provide a property-specific matrix.' },
      { q: 'Is a bar license mandatory?', a: 'Only if you serve alcohol. It is among the hardest approvals — state-quota limited, with distance restrictions from schools, places of worship and highways. Many hotels phase it after launch.' },
      { q: 'What is Sarai Act registration?', a: 'A colonial-era requirement to register lodging houses with the District / Police authority. Many States have modernised it, but lodging / guest registration remains mandatory.' },
      { q: 'Do I need a star classification?', a: 'It is voluntary, granted by the Ministry of Tourism (HRACC). It is not required to operate, but unlocks GST / tax benefits, travel-trade credibility and government empanelment.' },
      { q: 'How long does full licensing take?', a: 'For a mid-size hotel, 12-24 months from land to operational launch, running pre-construction and operational approvals in parallel. Bar licensing and classification often extend beyond opening.' },
    ],
    relatedServices: [
      { name: 'Liquor License', href: '/services/business-registration/license/liquor-license' },
      { name: 'FSSAI License', href: '/services/business-registration/license/fssai-license' },
      { name: 'Trade License', href: '/services/business-registration/license/trade-license' },
    ],
  },

  'ngo-advisory': {
    title: 'NGO Compliances & Advisory',
    description:
      'End-to-end NGO compliance for Trusts, Societies and Section 8 companies — 12A/12AB & 80G renewals, Form 10B/10BD audits, ITR-7, FCRA returns, CSR-1 and NITI Aayog Darpan.',
    keywords: ['NGO compliance', '12A 12AB renewal', '80G renewal', 'Form 10BD 10BE', 'ITR-7 NGO', 'FCRA annual return', 'CSR-1 registration', 'NITI Aayog Darpan', 'Section 8 compliance'],
    overview:
      'NGOs in India — whether structured as a Trust, Society or Section 8 company — operate under one of the heaviest recurring compliance burdens of any entity type, spanning Income-tax, the FCRA, the Companies Act / State Registrar and the funding ecosystem. Non-compliance routinely leads to cancellation of 12A / 80G registration, blocking of foreign funding, and disqualification from CSR and government grants.\n\nThe core annual cycle includes: maintaining 12AB (formerly 12A) registration with periodic 5-year renewal, 80G renewal, statutory audit and filing of Form 10B / 10BB, income-tax return in ITR-7, donation reporting via Form 10BD with issue of Form 10BE certificates to donors, and application / accumulation forms (10 / 9A) where income is set aside. Foreign-funded NGOs must hold valid FCRA registration (renewed every 5 years), operate the designated SBI New Delhi FCRA account, and file the annual FC-4 return. To receive corporate CSR funds, the NGO must hold CSR-1 registration; NITI Aayog NGO-Darpan registration is a gateway for most government grants. Section 8 companies additionally carry full ROC compliance (AOC-4, MGT-7, DIR-3 KYC, board / general meetings), while Societies and Trusts file with the State Registrar / Charity Commissioner.\n\nWe run the entire compliance calendar for you — registrations and renewals, audits, returns, donor reporting and grant-readiness — with proactive alerts so a missed filing never costs you your exemptions or your funding.',
    whyChooseUs: [
      { title: 'Single Compliance Calendar', desc: 'Every income-tax, FCRA, ROC and Registrar deadline tracked in one place with advance alerts.' },
      { title: 'Exemption Protection', desc: '12AB / 80G renewals filed correctly and on time — the lifeline of any NGO, guarded.' },
      { title: 'Funding Readiness', desc: 'CSR-1, NITI Aayog Darpan and FCRA kept current so corporate and government funds keep flowing.' },
      { title: 'Audit & Donor Reporting', desc: 'Form 10B / 10BB audits and Form 10BD / 10BE donor certificates handled end-to-end.' },
    ],
    keyPoints: [
      '12AB registration & 5-year renewal (income-tax exemption)',
      '80G registration & renewal (donor deduction)',
      'Statutory audit + Form 10B / 10BB filing',
      'Income-tax return in ITR-7',
      'Form 10BD donation statement + Form 10BE donor certificates',
      'Form 9A / 10 — income application & accumulation',
      'FCRA registration / renewal & annual FC-4 return',
      'FCRA designated SBI account & quarterly disclosure',
      'CSR-1 registration to receive corporate CSR funds',
      'NITI Aayog NGO-Darpan registration & updates',
      'Section 8 ROC filings — AOC-4, MGT-7, DIR-3 KYC',
      'Society / Trust annual filing with Registrar / Charity Commissioner',
      'Governing body / general body meetings & minutes',
      'TDS, GST and payroll (PF / ESI) where applicable',
    ],
    process: [
      { title: 'Compliance Diagnostic', desc: 'Review entity type, existing registrations, lapses and funding sources; build the calendar.' },
      { title: 'Registration Cleanup', desc: 'Regularise 12AB, 80G, CSR-1, Darpan and FCRA — file pending renewals / fresh applications.' },
      { title: 'Books & Audit', desc: 'Maintain books, reconcile donations / grants, conduct statutory audit (10B / 10BB).' },
      { title: 'Returns & Reporting', desc: 'File ITR-7, Form 10BD, issue 10BE certificates, FC-4 for foreign funds.' },
      { title: 'Governance', desc: 'Conduct and minute statutory meetings; file ROC / Registrar returns.' },
      { title: 'Ongoing Monitoring', desc: 'Calendar-driven alerts; renewals tracked years ahead so nothing lapses.' },
    ],
    documents: [
      'Trust deed / Society MoA & rules / Section 8 incorporation docs',
      'PAN & registration certificate of the NGO',
      'Existing 12AB / 80G / CSR-1 / FCRA / Darpan certificates',
      'Books of account, receipts & payments, donor ledger',
      'Bank statements (incl. FCRA designated account)',
      'Donation details for Form 10BD (donor PAN, amount, mode)',
      'List of governing body / trustees with KYC',
      'Prior-year audit reports & ITR acknowledgements',
    ],
    statutoryRefs: [
      { name: 'Income-tax Act, 1961 — Sections 11, 12, 12A/12AB', desc: 'Registration and exemption framework for charitable / religious entities.' },
      { name: 'Section 80G & Form 10BD / 10BE', desc: 'Donor deduction, mandatory donation reporting and donor certificates.' },
      { name: 'FCRA, 2010 & FCRR, 2011', desc: 'Foreign contribution registration, designated account and annual FC-4 return.' },
      { name: 'Companies Act, 2013 — Section 8 & CSR Rules', desc: 'ROC compliance for Section 8 companies and CSR-1 for receiving CSR funds.' },
      { name: 'State Societies Acts / Trust Acts', desc: 'Annual filing with Registrar of Societies / Charity Commissioner.' },
    ],
    pitfalls: [
      { title: 'Missing 12AB / 80G Renewal', desc: 'These now require periodic renewal — a missed deadline cancels exemption and makes the entire income taxable.' },
      { title: 'Form 10BD Omissions', desc: 'Failure to file the donation statement / issue 10BE blocks donors\' 80G deduction and attracts a per-day fee.' },
      { title: 'FCRA Account Misuse', desc: 'Foreign funds must route only through the designated SBI New Delhi account; mixing funds risks FCRA cancellation.' },
      { title: 'No CSR-1 = No CSR Funds', desc: 'Companies cannot route CSR to an NGO without valid CSR-1 (Form CSR-1) registration.' },
      { title: 'Section 8 ROC Defaults', desc: 'Skipping AOC-4 / MGT-7 / DIR KYC attracts penalties and director disqualification.' },
    ],
    faqs: [
      { q: 'How often must 12A and 80G be renewed?', a: 'Under the current regime, 12AB and 80G registrations are granted for a fixed term (generally 5 years) and must be renewed before expiry. Provisional registrations have shorter validity. Missing renewal cancels the exemption.' },
      { q: 'What is Form 10BD?', a: 'An annual statement of donations received that 80G-registered NGOs must file (by 31 May). Based on it, the NGO issues Form 10BE certificates to donors, which donors need to claim their 80G deduction.' },
      { q: 'Do all NGOs need FCRA?', a: 'Only NGOs that receive or intend to receive foreign contributions. FCRA registration (or prior permission) is mandatory before accepting any foreign funds, and the FC-4 annual return must be filed even for nil receipts.' },
      { q: 'What is NITI Aayog Darpan registration?', a: 'A unique ID for NGOs on the NGO-Darpan portal. It is a prerequisite for applying to most central / state government grants and schemes, and for FCRA and CSR processes.' },
      { q: 'What happens if an NGO does not comply?', a: 'Consequences range from late fees and penalties to cancellation of 12AB / 80G (income becomes taxable), suspension of FCRA, ineligibility for CSR and government funds, and director / trustee liability.' },
    ],
    relatedServices: [
      { name: '12A & 80G Registration', href: '/services/business-registration/other-registration/12a-80g-registration' },
      { name: 'FCRA / FEMA Registration', href: '/services/business-registration/other-registration/fcra-fema-registration' },
      { name: 'ITR for NGO', href: '/services/business-registration/taxation/itr-ngo' },
    ],
  },

  'industries-setup': {
    title: 'Industries Setup & License',
    description:
      'End-to-end industrial unit setup — Udyam / MSME, industrial land allotment, IEM / industrial licence, environmental clearance, pollution CTE/CTO, factory licence and single-window approvals.',
    keywords: ['industry setup India', 'industrial license', 'Udyam registration', 'IEM industrial entrepreneur memorandum', 'consent to establish', 'environmental clearance industry', 'industrial land allotment', 'manufacturing unit setup'],
    overview:
      'Setting up an industrial / manufacturing unit in India is a multi-regulator project that begins long before the first machine is installed. The approval stack scales with the nature of the product (white / green / orange / red category), scale of investment, location (industrial estate vs. private land) and whether the activity falls in a restricted or reserved list. Many States now offer single-window clearance portals that consolidate these approvals — but the underlying statutory consents remain distinct.\n\nThe typical journey includes entity formation, Udyam (MSME) registration, securing industrial land — allotment from a State industrial development corporation (e.g., MIDC, GIDC, SIPCOT, UPSIDA) or land-use conversion of private land — and an Industrial Entrepreneur Memorandum (IEM) with DPIIT, or an industrial licence under the IDR Act, 1951 for items still requiring one. Environmental approvals are central: Environmental Clearance under the EIA Notification, 2006 for scheduled industries, and Consent to Establish (CTE) followed by Consent to Operate (CTO) from the State Pollution Control Board under the Water and Air Acts. Construction and operation then require building plan sanction, Fire NOC, Factory licence under the Factories Act, 1948, power and water connections, hazardous-waste authorisation where relevant, and labour registrations (PF, ESI, contract labour). Exporters add IEC and product certification (BIS) as applicable.\n\nWe act as your single industrial-setup project lead — sequencing land, environmental, factory and utility approvals, navigating State single-window portals and incentive schemes, and delivering an operational, fully-licensed unit.',
    whyChooseUs: [
      { title: 'Project-Lead Model', desc: 'One team coordinating land, environment, factory, fire, utilities and labour approvals end-to-end.' },
      { title: 'Pollution & EC Expertise', desc: 'Category mapping, CTE / CTO and Environmental Clearance handled by environmental-law specialists.' },
      { title: 'Land & Incentives', desc: 'Industrial-estate allotment (MIDC / GIDC / SIPCOT) and State incentive / subsidy claims navigated.' },
      { title: 'Single-Window Navigation', desc: 'State single-window portals filed correctly to compress timelines.' },
    ],
    keyPoints: [
      'Entity formation & Udyam (MSME) registration',
      'Industrial land allotment (MIDC / GIDC / SIPCOT / UPSIDA) or land-use conversion',
      'Industrial Entrepreneur Memorandum (IEM) with DPIIT',
      'Industrial licence under IDR Act, 1951 (restricted / reserved items)',
      'Environmental Clearance (EIA Notification, 2006) for scheduled industries',
      'Pollution Control Board — Consent to Establish (CTE) & Operate (CTO)',
      'Building plan sanction & Fire NOC',
      'Factory licence under Factories Act, 1948',
      'Power & water connection, DG-set NOC',
      'Hazardous & other waste authorisation',
      'BIS / product certification (where mandatory)',
      'IEC for exporters; GST registration',
      'Labour — PF, ESI, Contract Labour, Shops & Establishment',
      'State industrial incentive / subsidy claims',
    ],
    process: [
      { title: 'Feasibility & Mapping', desc: 'Product / category classification, location strategy, full approval matrix and incentive scan.' },
      { title: 'Entity & Land', desc: 'Incorporation, Udyam, industrial-estate allotment or land-use conversion.' },
      { title: 'Environmental Approvals', desc: 'Environmental Clearance (if scheduled) and Consent to Establish from the SPCB.' },
      { title: 'Build & Factory Licence', desc: 'Building plan sanction, Fire NOC, factory plan approval and licence under the Factories Act.' },
      { title: 'Utilities & Waste', desc: 'Power / water connection, DG-set, hazardous-waste authorisation, Consent to Operate.' },
      { title: 'Commission & Comply', desc: 'Trial run, labour registrations, BIS / IEC and the recurring renewal calendar.' },
    ],
    documents: [
      'Entity incorporation documents & PAN',
      'Detailed project report (DPR) / business plan',
      'Land allotment letter / sale deed + land-use conversion order',
      'Machinery list, process flow & raw-material details',
      'Effluent / emission & waste-generation details (for pollution consent)',
      'Building / factory layout plan',
      'Investment, capacity & employment figures (for IEM / incentives)',
      'Directors / promoters KYC',
    ],
    statutoryRefs: [
      { name: 'Industries (Development & Regulation) Act, 1951', desc: 'IEM filing and industrial licensing for restricted / reserved items.' },
      { name: 'EIA Notification, 2006', desc: 'Environmental Clearance for scheduled industrial projects.' },
      { name: 'Water Act, 1974 & Air Act, 1981', desc: 'Consent to Establish and Operate from the State Pollution Control Board.' },
      { name: 'Factories Act, 1948', desc: 'Factory plan approval and licence for manufacturing premises.' },
      { name: 'MSMED Act, 2006', desc: 'Udyam registration and MSME benefits.' },
      { name: 'Hazardous & Other Wastes Rules, 2016', desc: 'Authorisation for generation, storage and disposal of hazardous waste.' },
    ],
    pitfalls: [
      { title: 'Skipping Consent to Establish', desc: 'Beginning construction / installation before CTE invites closure orders and heavy penalties from the SPCB.' },
      { title: 'Wrong Category Assumption', desc: 'Mis-classifying a red-category unit as orange / green leads to rejected consents and retrospective action.' },
      { title: 'Land-Use Mismatch', desc: 'Operating industry on agricultural / non-industrial land without conversion stalls every downstream approval.' },
      { title: 'Ignoring Environmental Clearance', desc: 'Scheduled industries that skip EC face stop-work, demolition and NGT proceedings.' },
      { title: 'Incentive Deadlines Missed', desc: 'State subsidies (capital, power, interest) have strict claim windows often tied to commencement date.' },
    ],
    faqs: [
      { q: 'Do I need an industrial licence to start a factory?', a: 'Most industries are de-licensed and only need to file an Industrial Entrepreneur Memorandum (IEM). A formal industrial licence under the IDR Act is required only for a small list of reserved / restricted items (e.g., defence, certain hazardous chemicals) and items reserved for the public / small-scale sector.' },
      { q: 'What is the difference between CTE and CTO?', a: 'Consent to Establish (CTE) is obtained before construction / installation; Consent to Operate (CTO) is obtained after the unit is built and before commercial production. Both come from the State Pollution Control Board.' },
      { q: 'When is Environmental Clearance required?', a: 'When the project / activity is listed in the Schedule to the EIA Notification, 2006 (by type and threshold). Category A projects are appraised by the Centre and Category B by the State (SEIAA).' },
      { q: 'What is Udyam registration?', a: 'The MSME registration on the Udyam portal, based on investment and turnover. It unlocks priority-sector lending, subsidies, tender benefits and protection under the MSMED Act for delayed payments.' },
      { q: 'How long does it take to set up an industrial unit?', a: 'Highly variable — a simple green-category MSME can be operational in a few months, while a red-category or EC-requiring project can take 12-24+ months. Land, environmental and factory approvals are the main timeline drivers.' },
    ],
    relatedServices: [
      { name: 'Factory Setup & License', href: '/services/business-registration/institutional-setup/factory-setup' },
      { name: 'Factory License', href: '/services/business-registration/license/factory-license' },
      { name: 'Import Export Code (IEC)', href: '/services/business-registration/other-registration/import-export-code' },
    ],
  },

  'factory-setup': {
    title: 'Factory Setup & License',
    description:
      'Complete factory setup and licensing under the Factories Act, 1948 — pre-construction plan approval, factory licence, fire & pollution NOCs, boiler registration and labour compliance.',
    keywords: ['factory license', 'Factories Act 1948', 'factory plan approval', 'Chief Inspector of Factories', 'boiler registration', 'factory setup India', 'factory registration', 'manufacturing premises license'],
    overview:
      'A factory — any premises where 10 or more workers work with power, or 20 or more without power, in a manufacturing process — must be registered and licensed under the Factories Act, 1948, administered by the State Chief Inspector of Factories (Directorate of Industrial Safety & Health). Unlike a generic trade licence, a factory licence is granted only after the premises, layout and safety arrangements are approved, and it governs everything from worker safety and working hours to hazardous-process controls.\n\nThe sequence is front-loaded: the building / factory plan must be approved by the Chief Inspector before construction (Form 1 type approval), followed by application for registration and grant of licence under Sections 6 and 7. Around it sits a stack of supporting approvals — Fire NOC, Pollution Control Board CTE / CTO, building / occupancy certificate, and — where steam pressure plant is used — boiler registration under the Boilers Act, 1923. Factories engaged in a "hazardous process" (Schedule to the Act) carry heightened obligations: site appraisal, on-site emergency plans, mandatory safety and welfare officers, and disclosure to workers and the public. Operating a factory also triggers labour registrations and welfare compliance — PF, ESI, Contract Labour licensing, and statutory registers and returns.\n\nWe handle factory licensing end-to-end — plan approval, licence application and grant, the supporting NOC stack, boiler and hazardous-process compliance, and annual licence renewals and returns — so production starts on a fully compliant footing.',
    whyChooseUs: [
      { title: 'Plan Approval First-Time-Right', desc: 'Factory layout and plan prepared to the Inspectorate\'s norms so pre-construction approval is not delayed.' },
      { title: 'Hazardous-Process Expertise', desc: 'Schedule-listed hazardous factories: safety officers, emergency plans and disclosures handled.' },
      { title: 'Supporting NOC Stack', desc: 'Fire, pollution, boiler and occupancy approvals coordinated alongside the licence.' },
      { title: 'Renewals & Returns', desc: 'Annual licence renewal, Form returns and register upkeep tracked so the licence never lapses.' },
    ],
    keyPoints: [
      'Applicability assessment (10+ with power / 20+ without)',
      'Pre-construction factory building / plan approval (Chief Inspector)',
      'Factory registration & licence under Sections 6 / 7, Factories Act, 1948',
      'Stability certificate for factory building',
      'Fire NOC with safety scheme',
      'Pollution Control Board CTE / CTO consent',
      'Boiler registration under Boilers Act, 1923 (if applicable)',
      'Hazardous-process compliance (Schedule) — site appraisal & emergency plan',
      'Safety Officer / Welfare Officer appointment (per worker threshold)',
      'Occupier & Manager declaration (Form 2)',
      'Contract Labour registration; PF & ESI',
      'Statutory registers, abstracts & annual / half-yearly returns',
      'Licence renewal & amendment (capacity / worker change)',
    ],
    process: [
      { title: 'Applicability & Scoping', desc: 'Confirm Factories Act applicability, worker count, power use and hazardous-process status.' },
      { title: 'Plan Approval', desc: 'Prepare and submit factory building / layout plan to the Chief Inspector for pre-construction approval.' },
      { title: 'Supporting NOCs', desc: 'Fire NOC, pollution CTE, boiler registration and occupancy / stability certificates.' },
      { title: 'Licence Application', desc: 'File registration & licence application (with occupier / manager details) under Sections 6 / 7.' },
      { title: 'Inspection & Grant', desc: 'Factory inspection; address observations; grant of factory licence.' },
      { title: 'Compliance Setup', desc: 'Registers, safety / welfare appointments, returns calendar and annual licence renewal.' },
    ],
    documents: [
      'Land / premises documents & occupancy certificate',
      'Factory building & layout plan (for plan approval)',
      'Stability certificate from a competent engineer',
      'Machinery list, installed power (HP) & worker count',
      'Manufacturing process flow & material details',
      'Occupier & Manager KYC and consent (Form 2)',
      'Fire NOC and pollution consent',
      'Boiler details / registration (if steam plant used)',
    ],
    statutoryRefs: [
      { name: 'Factories Act, 1948', desc: 'Registration, licensing, safety, health and welfare of workers in factories.' },
      { name: 'State Factories Rules', desc: 'State-specific procedures, forms, fee and renewal for factory licensing.' },
      { name: 'Boilers Act, 1923', desc: 'Registration and periodic inspection of boilers / steam pressure plant.' },
      { name: 'Water Act, 1974 & Air Act, 1981', desc: 'Pollution Control Board consent for the factory premises.' },
      { name: 'Contract Labour (R&A) Act, 1970', desc: 'Registration where contract labour is engaged.' },
    ],
    pitfalls: [
      { title: 'Building Before Plan Approval', desc: 'Constructing the factory before the Chief Inspector approves the plan can force costly modifications or block the licence.' },
      { title: 'Misjudging Applicability', desc: 'Assuming the Act does not apply (worker / power thresholds) when it does exposes the occupier to prosecution.' },
      { title: 'Hazardous-Process Gaps', desc: 'Schedule-listed factories without safety officers, emergency plans and disclosures face severe liability.' },
      { title: 'Boiler Non-Registration', desc: 'Operating an unregistered / uninspected boiler is a criminal offence with serious safety consequences.' },
      { title: 'Lapsed Renewal', desc: 'Factory licences are periodic; missing renewal means operating without a valid licence and penalties on the occupier.' },
    ],
    faqs: [
      { q: 'When does the Factories Act apply?', a: 'When 10 or more workers are working (or worked in the preceding 12 months) with the aid of power, or 20 or more workers without power, in any manufacturing process. Some States prescribe lower thresholds.' },
      { q: 'Who is the "occupier" of a factory?', a: 'The person who has ultimate control over the affairs of the factory. For a company, a director is deemed the occupier. The occupier carries primary statutory responsibility for compliance and worker safety.' },
      { q: 'Is factory licence the same as an industrial licence?', a: 'No. The factory licence (Factories Act, 1948) governs the safety and operation of the manufacturing premises and is granted by the State Inspectorate. An industrial licence (IDR Act) relates to permission to manufacture certain restricted products and is separate.' },
      { q: 'Do I need plan approval before construction?', a: 'Yes. The building / factory layout plan must be approved by the Chief Inspector of Factories before construction begins. Building first risks rejection and rework.' },
      { q: 'How often is the licence renewed?', a: 'Factory licences are issued for a period (typically 1-5 years depending on the State) and must be renewed before expiry, along with filing of prescribed annual / half-yearly returns.' },
    ],
    relatedServices: [
      { name: 'Industries Setup & License', href: '/services/business-registration/institutional-setup/industries-setup' },
      { name: 'Factory License', href: '/services/business-registration/license/factory-license' },
      { name: 'Petrol Pump License', href: '/services/business-registration/institutional-setup/petrol-pump' },
    ],
  },
};
