import type { ServiceContent } from '@/components/leaf-service-page';

export const taxationServices: Record<string, ServiceContent> = {
  'itr-individual': {
    title: 'ITR for Individual',
    description:
      'Income Tax Return filing for salaried, self-employed, freelancer, NRI and HNI individuals — accurate ITR-1 to ITR-7 filing with maximum legal deductions.',
    keywords: ['ITR for individual', 'income tax return filing', 'ITR-1', 'ITR-2', 'NRI ITR filing', 'salaried ITR', 'freelancer tax return', 'tax filing India'],
    overview:
      'Filing Income Tax Return (ITR) under the Income-tax Act, 1961 is mandatory for individuals whose total income exceeds the basic exemption limit and beneficial in many other cases (refund, loan applications, visa, business credibility). The right ITR form (ITR-1 Sahaj for salaried with simple income, ITR-2 for capital gains / multiple house properties, ITR-3 for business / profession, ITR-4 Sugam for presumptive taxation) determines processing speed and refund timeline.\n\nWe handle ITR filing for salaried individuals, freelancers / consultants, business owners, capital-gains earners, NRIs, foreign-income earners and HNIs. We optimize legal deductions (80C, 80D, 80E, 80G, HRA, LTA, capital-gains exemptions under 54 / 54F / 54EC) and represent in scrutiny / appeal proceedings if returns are picked up by CPC or AO.',
    whyChooseUs: [
      { title: 'Maximum Deductions', desc: 'We surface every legitimate deduction — 80C, 80D, NPS, HRA, home-loan, capital-gains exemptions.' },
      { title: 'NRI Specialists', desc: 'NRI filings with DTAA treaty benefits, Form 67 and tax credit optimization.' },
      { title: 'Form Selection', desc: 'Wrong ITR form invites defective return notices — we map facts to correct form.' },
      { title: 'Scrutiny Defence', desc: 'If your return is picked up for scrutiny, we represent through assessment and appeals.' },
    ],
    keyPoints: [
      'ITR-1 Sahaj for salaried individuals (income up to ₹50 lakh)',
      'ITR-2 for capital gains, multiple house properties, foreign income',
      'ITR-3 for business / profession income',
      'ITR-4 Sugam for presumptive taxation (44AD / 44ADA / 44AE)',
      'Old vs New tax regime evaluation',
      'Section 80C / 80D / 80G / 80E / 80EEA deductions',
      'HRA, LTA and Section 10 exemptions',
      'Capital gains computation and Section 54 / 54F / 54EC reinvestment',
      'NRI ITR with DTAA benefits and Form 67',
      'Defective return / refund issue resolution',
    ],
    process: [
      { title: 'Document Gathering', desc: 'Collect Form 16, AIS, TIS, Form 26AS, bank statements, capital-gains records, investment proofs.' },
      { title: 'Computation', desc: 'Income classification, deduction analysis, regime comparison and tax computation.' },
      { title: 'Form Selection & Filing', desc: 'Choose appropriate ITR form; file on incometax.gov.in within due date.' },
      { title: 'Verification', desc: 'E-verify via Aadhaar OTP, net-banking, DSC or send signed ITR-V to CPC Bengaluru.' },
      { title: 'Refund Tracking', desc: 'Monitor processing; address CPC notices; track refund deposit.' },
    ],
    documents: [
      'PAN, Aadhaar, bank account details',
      'Form 16 / 16A from employer',
      'Form 26AS, AIS, TIS from income-tax portal',
      'Investment proofs (LIC, ELSS, NPS, PPF)',
      'Home-loan interest certificate',
      'Capital-gains statements (broker, MF, property)',
      'Rent receipts (HRA)',
      'Medical insurance receipts (80D)',
      'NRI: DTAA documents, foreign income statements',
    ],
    statutoryRefs: [
      { name: 'Income-tax Act, 1961 — Section 139', desc: 'ITR filing obligation; due date 31 July (non-audit) / 31 October (audit).' },
      { name: 'Section 80C-80U', desc: 'Deductions from gross total income.' },
      { name: 'Section 54 / 54F / 54EC', desc: 'Capital gains exemption on reinvestment.' },
      { name: 'CBDT Circulars / Notifications', desc: 'Annual ITR forms, due-date extensions and procedural rules.' },
    ],
    pitfalls: [
      { title: 'Wrong ITR Form', desc: 'Filing ITR-1 with capital gains / multiple house property invites defective return notice u/s 139(9).' },
      { title: 'Missing AIS / Form 26AS Reconciliation', desc: 'Discrepancies between AIS / 26AS and ITR trigger notices and refund delays.' },
      { title: 'Old Regime by Default', desc: 'New regime is default since FY 2023-24 — explicit opt-out via Form 10-IEA needed for old regime business income.' },
      { title: 'Belated Return Penalty', desc: 'Late filing under Section 234F attracts ₹1,000 / ₹5,000 fee; loss of carry-forward of losses.' },
    ],
    faqs: [
      { q: 'Who must file ITR?', a: 'Individuals with gross total income above the basic exemption limit (₹2.5 lakh / ₹3 lakh / ₹5 lakh based on age & regime), and others required by Section 139 (foreign asset holders, high-value spenders, business owners). Filing is also useful for refunds, loans and visa.' },
      { q: 'What is the ITR filing due date?', a: 'For non-audit individuals — 31 July of the assessment year. For audit cases — 31 October. Belated returns can be filed till 31 December with late fee.' },
      { q: 'Old regime or new regime?', a: 'New regime has lower slabs but fewer deductions. Old regime is better when deductions (80C, 80D, HRA, home loan interest) exceed the differential. We compute both and recommend.' },
      { q: 'Can I revise my ITR?', a: 'Yes — under Section 139(5), revised ITR can be filed by 31 December of the assessment year.' },
      { q: 'What if I miss the due date?', a: 'File belated return under Section 139(4) with late fee (₹1,000 / ₹5,000). Loss-carry-forward is generally lost. After 31 December, only ITR-U updated return route is available.' },
      { q: 'Are NRIs taxed in India?', a: 'NRIs are taxed only on India-source income and income received in India. DTAA may further reduce / eliminate tax. Form 67 needed for foreign tax credit.' },
    ],
    relatedServices: [
      { name: 'Tax Planning — Individual', href: '/services/business-registration/taxation/tax-planning-individual' },
      { name: 'Tax Audit', href: '/services/business-registration/taxation/tax-audit' },
      { name: 'ITR for Companies', href: '/services/business-registration/taxation/itr-companies' },
    ],
  },

  'itr-companies': {
    title: 'ITR for Companies',
    description:
      'Income Tax Return filing for companies — ITR-6, MAT computation, transfer pricing certification, audit reports and assessment / appeal representation.',
    keywords: ['ITR for companies', 'ITR-6 filing', 'corporate tax return', 'MAT computation', 'company tax filing India', 'transfer pricing'],
    overview:
      'Companies (other than those claiming Section 11 exemption) must file ITR-6 under Section 139 of the Income-tax Act, 1961 — typically by 31 October of the assessment year (with audit). Corporate ITR involves substantial complexity — MAT (Section 115JB) computation, dividend distribution treatment, transfer pricing for related-party transactions, capital expenditure depreciation, and various special-deduction regimes (Section 80-IAC, 35 R&D, etc.).\n\nOur Chartered Accountants and tax counsel handle ITR filing for Pvt Ltd, Public Ltd, OPC, Section 8 and other corporate forms. We integrate Tax Audit (Section 44AB), Transfer Pricing report (Form 3CEB), audit reports under Sections 92E / 80JJAA, and timely uploads to the income-tax portal.',
    whyChooseUs: [
      { title: 'CA + Tax Counsel Team', desc: 'Both compliance filing and complex litigation handled in-house.' },
      { title: 'MAT & AMT Computation', desc: 'Minimum Alternate Tax / AMT computation with carry-forward MAT credit tracking.' },
      { title: 'Transfer Pricing Integrated', desc: 'Form 3CEB, TP study and ITR aligned for related-party-rich entities.' },
      { title: 'Scrutiny / Appeal Defence', desc: 'CPC notices, Section 143(2) scrutiny, CIT(A), ITAT appeals.' },
    ],
    keyPoints: [
      'ITR-6 filing for non-exempt companies',
      'MAT computation under Section 115JB',
      'Transfer Pricing Report (Form 3CEB) for related parties',
      'Tax Audit Report (Form 3CD) integration',
      'Section 80-IAC startup deduction (eligible startups)',
      'Section 35 R&D deductions',
      'Depreciation, additional depreciation and disallowances',
      'Equalization Levy and Significant Economic Presence (SEP)',
      'Foreign tax credit via Form 67 and DTAA',
      'CPC / Section 143(1) intimations and Section 143(2) scrutiny',
    ],
    process: [
      { title: 'Audit Coordination', desc: 'Coordinate with statutory auditor for Form 3CD, Form 3CA / 3CB sign-off.' },
      { title: 'Computation', desc: 'Profit computation, MAT computation, deduction analysis.' },
      { title: 'Filing', desc: 'Upload ITR-6 with audit reports on income-tax portal by 31 October.' },
      { title: 'Verification', desc: 'DSC-based e-verification; track acknowledgment.' },
      { title: 'Post-Filing', desc: 'Address CPC intimations; handle scrutiny / assessment if selected.' },
    ],
    statutoryRefs: [
      { name: 'Income-tax Act, 1961 — Section 139', desc: 'Corporate ITR filing obligation.' },
      { name: 'Section 115JB', desc: 'Minimum Alternate Tax — 15% of book profit.' },
      { name: 'Section 92-92F', desc: 'Transfer pricing for international and specified domestic transactions.' },
      { name: 'Section 44AB', desc: 'Tax Audit threshold — turnover > ₹1 crore (₹10 crore for digital).' },
    ],
    pitfalls: [
      { title: 'Late Filing', desc: 'Late corporate ITR attracts ₹5,000 fee + loss-carry-forward denial; severe for loss-making startups.' },
      { title: 'Missing TP Study', desc: 'Section 92D requires TP documentation maintained even before ITR filing.' },
      { title: 'MAT Credit Lapse', desc: 'MAT credit (Section 115JAA) is carry-forward for 15 years; un-utilized credits lapse beyond.' },
      { title: 'GAAR Triggers', desc: 'Aggressive tax structures may invite GAAR (Section 95-102) scrutiny.' },
    ],
    faqs: [
      { q: 'When is corporate ITR due?', a: '31 October of the assessment year (for tax-audit cases). Companies without audit obligation: 31 July (rare for active companies).' },
      { q: 'What is MAT?', a: 'Minimum Alternate Tax under Section 115JB — 15% of book profit. Applies when normal tax is less than MAT. Excess paid as MAT becomes MAT credit usable in future years.' },
      { q: 'Do startups have ITR concessions?', a: 'Recognized startups under DPIIT can claim Section 80-IAC — 100% profit deduction for any 3 consecutive years out of first 10. Eligibility and CBDT certification needed.' },
      { q: 'What is the corporate tax rate?', a: 'Domestic companies: 22% (Section 115BAA — without specific deductions) or 30% with deductions. Manufacturing companies (Section 115BAB): 15%. Plus surcharge and cess.' },
      { q: 'Is e-verification mandatory?', a: 'Yes — corporate ITRs must be verified within 30 days of filing, typically via DSC. Without verification, return is treated as not filed.' },
    ],
    relatedServices: [
      { name: 'Tax Audit', href: '/services/business-registration/taxation/tax-audit' },
      { name: 'Tax Planning — Corporate', href: '/services/business-registration/taxation/tax-planning-corporate' },
      { name: 'GST Audit', href: '/services/business-registration/taxation/gst-audit' },
      { name: 'Annual Compliances — Pvt. Ltd.', href: '/services/compliances/company-compliances/annual-pvt-ltd' },
    ],
  },

  'itr-ngo': {
    title: 'ITR for NGO',
    description:
      'Income Tax Return filing for charitable / religious trusts and Section 8 companies — ITR-7, Form 10B / 10BB audit and Section 11 / 12 exemption claims.',
    keywords: ['ITR for NGO', 'ITR-7 filing', 'trust tax return', 'Section 11 exemption', 'Form 10B audit', 'NGO income tax', 'charitable trust ITR'],
    overview:
      'NGOs registered as Trusts, Societies and Section 8 companies file ITR-7 and claim exemption under Sections 11-13 of the Income-tax Act, 1961, subject to 12A / 12AB registration, 80G certification (for donor benefit) and compliance with charitable purpose requirements. Annual filings include Form 10B / 10BB (audit report), Form 9A / 10 (accumulation for 5 years) and Form 10BD (donor reporting).\n\nWe handle end-to-end NGO tax compliance — ITR-7 filing, Form 10B / 10BB audit by CA, Section 11 exemption claims, donor reporting via Form 10BD, FCRA-compliant foreign-contribution accounting, and representation in re-registration / scrutiny proceedings.',
    whyChooseUs: [
      { title: 'NGO-Specialist Counsel', desc: 'Section 11-13 jurisprudence, anonymous donations, accumulation strategy.' },
      { title: 'Form 10BD Donor Reporting', desc: 'Annual donor reporting for 80G donations — accurate and timely.' },
      { title: 'FCRA Coordination', desc: 'For NGOs receiving foreign contribution — FCRA + IT Act alignment.' },
      { title: '12AB Re-registration', desc: 'Periodic re-registration filings handled with full documentation.' },
    ],
    keyPoints: [
      'ITR-7 filing for NGOs claiming Section 11 / 12 exemption',
      'Form 10B / 10BB audit report (depending on income threshold)',
      'Section 12AB registration / re-registration',
      '80G certification for donor income tax benefit',
      'Form 10BD donor reporting (annual)',
      'Form 9A / 10 accumulation for future application',
      'Anonymous donations under Section 115BBC',
      'Foreign contribution under FCRA + IT Act alignment',
      'CSR-grant accounting',
      'Scrutiny / re-assessment representation',
    ],
    process: [
      { title: 'Books of Account', desc: 'Maintain books per Section 12A(b) — receipts, payments, bank, donor records.' },
      { title: 'Audit', desc: 'Form 10B (income > ₹5 crore or foreign contribution) or 10BB by CA.' },
      { title: 'Form 10BD', desc: 'Donor reporting before 31 May for 80G donations of previous year.' },
      { title: 'ITR-7 Filing', desc: 'File on income-tax portal within due date (31 October for audit / 31 July otherwise).' },
      { title: 'E-Verification', desc: 'DSC-based verification within 30 days.' },
    ],
    statutoryRefs: [
      { name: 'Income-tax Act, 1961 — Sections 11-13', desc: 'Charitable / religious trust exemptions.' },
      { name: 'Section 12A / 12AB', desc: 'Registration of charitable trusts; 5-year periodic re-registration.' },
      { name: 'Section 80G', desc: 'Donor income-tax benefit certification.' },
      { name: 'FCRA, 2010', desc: 'Foreign contribution receipt and accounting.' },
    ],
    pitfalls: [
      { title: 'Late Form 10BD', desc: 'Missing 31 May deadline disqualifies donors from 80G benefit — reputational and legal damage.' },
      { title: 'Excessive Accumulation', desc: 'Accumulation beyond 15% (Section 11(1)(a)) without Form 10 is fully taxable.' },
      { title: 'Anonymous Donations', desc: 'Anonymous donations exceeding 5% of total / ₹1 lakh attract 30% tax under Section 115BBC.' },
      { title: 'Re-registration Lapse', desc: 'Failing to re-register under Section 12AB before expiry of provisional / regular registration disqualifies exemption.' },
    ],
    faqs: [
      { q: 'Are NGOs exempt from income tax?', a: 'NGOs registered under Section 12A / 12AB and applying income for charitable / religious purposes are exempt under Section 11. Compliance with conditions (audit, accumulation, anonymous donation rules) is mandatory.' },
      { q: 'What is Form 10BD?', a: 'Donor statement filed annually by 80G-approved entities listing donors and amounts received. Donors need this to claim 80G deduction in their ITR.' },
      { q: 'What is the due date for ITR-7?', a: '31 October for audit cases (most NGOs), 31 July otherwise. Audit Form 10B / 10BB must be filed before ITR.' },
      { q: 'Can NGO income be carried forward?', a: 'Up to 15% can be accumulated without specific application. For more, Form 10 must specify purpose and period (max 5 years).' },
      { q: 'What if NGO loses 12A registration?', a: 'Income becomes taxable as AOP. Re-registration is possible but during the lapse period taxes may apply. Strict compliance with renewal timelines is essential.' },
    ],
    relatedServices: [
      { name: 'Society Registration (NGO)', href: '/services/business-registration/other-registration/society-registration' },
      { name: 'Trust Registration (NGO)', href: '/services/business-registration/other-registration/trust-registration' },
      { name: '12A & 80G Registration', href: '/services/business-registration/other-registration/12a-80g-registration' },
      { name: 'FCRA / FEMA Registration', href: '/services/business-registration/other-registration/fcra-fema-registration' },
    ],
  },

  'itr-political-party': {
    title: 'ITR for Political Party',
    description:
      'Income Tax Return filing for registered political parties under Section 13A — ITR-7, donor reporting under Section 29C of RP Act and electoral bond receipts.',
    keywords: ['ITR political party', 'Section 13A', 'political party tax exemption', 'ITR-7 political', 'RP Act 29C', 'electoral bonds tax'],
    overview:
      'Political parties registered under Section 29A of the Representation of the People Act, 1951 enjoy income tax exemption under Section 13A of the Income-tax Act, 1961, subject to maintenance of books, audit, donor reporting and ITR filing. Parties file ITR-7 by 31 October.\n\nKey conditions for Section 13A exemption: (a) maintenance of books with names and addresses of donors above ₹20,000, (b) audited accounts, (c) submission of contribution report to ECI under Section 29C of RP Act before due date, (d) cash donations restricted to ₹2,000 per donor. Failure on any condition can result in loss of entire exemption.\n\nWe handle ITR filing, audit coordination, ECI Section 29C reports, electoral bond accounting and dispute resolution for registered political parties of all sizes.',
    whyChooseUs: [
      { title: 'Compliance Specialists', desc: 'Section 13A, 29A, 29C compliances handled in single workflow.' },
      { title: 'Electoral Bond Treatment', desc: 'Donor anonymity preservation while satisfying audit and disclosure requirements.' },
      { title: 'ECI Coordination', desc: 'Annual contribution reports filed with Election Commission of India before due date.' },
      { title: 'Litigation Support', desc: 'Tax tribunals, ECI proceedings and constitutional challenges navigated.' },
    ],
    keyPoints: [
      'ITR-7 filing for registered political parties',
      'Section 13A exemption claim',
      'Donor reporting (above ₹20,000 cash limit)',
      'Section 29C RP Act contribution report to ECI',
      'Electoral bond accounting',
      'Cash donation restriction (₹2,000 cap)',
      'Audited accounts under Companies / Society law',
      'Annual report to ECI before due date',
      'Section 29A registration compliance',
      'Election expenditure reporting',
    ],
    process: [
      { title: 'Books & Audit', desc: 'Maintain donor registers, bank records, expense vouchers; coordinate audit.' },
      { title: 'Contribution Report (29C)', desc: 'Compile contributions above ₹20,000 with donor PAN / ID for ECI report.' },
      { title: 'ECI Filing', desc: 'File contribution report with ECI before due date (typically 30 September).' },
      { title: 'ITR-7 Filing', desc: 'File ITR-7 claiming Section 13A exemption by 31 October.' },
      { title: 'Verification', desc: 'DSC-based e-verification.' },
    ],
    statutoryRefs: [
      { name: 'Income-tax Act, 1961 — Section 13A', desc: 'Income tax exemption for registered political parties.' },
      { name: 'Representation of the People Act, 1951 — Sections 29A, 29C', desc: 'Party registration and contribution reporting.' },
      { name: 'Election Commission Rules', desc: 'Annual reporting, election expenditure and disclosure requirements.' },
      { name: 'Finance Act, 2017', desc: 'Cash donation limit reduced to ₹2,000 per donor.' },
    ],
    pitfalls: [
      { title: 'Above ₹20,000 Without Donor Records', desc: 'Even single instance disqualifies entire Section 13A exemption.' },
      { title: 'Late ECI Filing', desc: 'Missing Section 29C deadline can lead to loss of exemption.' },
      { title: 'Cash Donations Above ₹2,000', desc: 'Strictly prohibited for parties claiming 13A exemption.' },
      { title: 'Inadequate Audit', desc: 'Audit must independently verify donor list and contribution sources.' },
    ],
    faqs: [
      { q: 'Are political parties tax-exempt?', a: 'Registered political parties under Section 29A RP Act enjoy Section 13A exemption — but only on full compliance with disclosure, donor record, audit and ECI filing requirements.' },
      { q: 'What about donations above ₹20,000?', a: 'Allowed but donor name, address and amount must be recorded in books. PAN required from donor; absence triggers consequences.' },
      { q: 'Are electoral bonds anonymous?', a: 'The 2024 Supreme Court decision struck down the Electoral Bond scheme. Going forward, party financing has stricter disclosure norms.' },
      { q: 'What is Section 29C report?', a: 'Annual report by political parties to ECI listing all contributions above ₹20,000 with donor details. Filing deadline is typically 30 September.' },
      { q: 'Can a new party claim Section 13A in first year?', a: 'Yes — provided Section 29A registration is complete and other conditions are met from first year of operation.' },
    ],
    relatedServices: [
      { name: 'Political Party Formation & License', href: '/services/business-registration/institutional-setup/political-party' },
      { name: 'Tax Audit', href: '/services/business-registration/taxation/tax-audit' },
      { name: 'ITR for NGO', href: '/services/business-registration/taxation/itr-ngo' },
    ],
  },

  'tax-planning-individual': {
    title: 'Tax Planning — Individual',
    description:
      'Strategic tax planning for individuals — investments, retirement, capital gains, succession and HUF — to legally minimize tax under the Income-tax Act, 1961.',
    keywords: ['tax planning individual', 'income tax saving', 'tax planning India', 'capital gains planning', 'HUF tax planning', 'retirement tax planning'],
    overview:
      'Tax Planning is the legal arrangement of one\'s financial affairs to minimize tax liability through judicious use of deductions, exemptions, rebates and structuring options available under the Income-tax Act, 1961. Effective tax planning balances tax efficiency, liquidity, risk and life-stage needs.\n\nFor individuals, planning spans Section 80C investment basket (PPF, ELSS, NPS, life insurance), Section 80D health insurance, home-loan interest, HRA, capital gains reinvestment under Section 54 / 54F / 54EC, retirement planning, HUF formation, gifting strategy and estate planning.\n\nWe provide year-round tax planning advisory — ideally engaged early in the financial year — with quarterly check-ins, ITR filing alignment and continuous adjustment as tax laws change.',
    whyChooseUs: [
      { title: 'Holistic Financial View', desc: 'Tax + investment + insurance + estate integrated, not just deduction stacking.' },
      { title: 'Old vs New Regime', desc: 'Continuous evaluation as income / deductions evolve.' },
      { title: 'HUF & Family Strategy', desc: 'HUF formation, family-arrangement and gifting for inter-generational tax efficiency.' },
      { title: 'Capital Gains Planning', desc: 'Section 54 / 54EC / 54F sequencing for property and securities gains.' },
    ],
    keyPoints: [
      'Section 80C — ₹1.5 lakh investment basket (PPF, ELSS, NPS, LIC)',
      'Section 80D — health insurance up to ₹75,000',
      'Section 80E — education loan interest',
      'NPS Section 80CCD(1B) — additional ₹50,000',
      'HRA, LTA, food coupon optimization',
      'Home loan interest (Section 24) and principal (Section 80C)',
      'Capital gains exemption — Section 54 / 54F / 54EC',
      'HUF formation for income splitting',
      'Gift to spouse / minor — Section 64 clubbing rules',
      'Retirement planning — NPS, EPF, gratuity tax treatment',
      'Old vs New regime annual evaluation',
    ],
    process: [
      { title: 'Profile Mapping', desc: 'Income sources, family structure, life-stage, financial goals.' },
      { title: 'Strategy', desc: 'Tax-saving plan with investment, insurance and structural recommendations.' },
      { title: 'Implementation', desc: 'Execute investments, register HUF (if applicable), file relevant forms.' },
      { title: 'Quarterly Review', desc: 'Track investments, regime suitability, life events, law changes.' },
      { title: 'ITR Alignment', desc: 'Year-end planning aligned with ITR filing.' },
    ],
    statutoryRefs: [
      { name: 'Income-tax Act, 1961', desc: 'Foundational law with deductions and exemptions.' },
      { name: 'Section 80C-80U', desc: 'Various deductions from gross total income.' },
      { name: 'Section 54-54EC', desc: 'Capital gains exemption on reinvestment.' },
      { name: 'Section 64', desc: 'Clubbing of income — spouse, minor child.' },
    ],
    pitfalls: [
      { title: 'Last-Minute 80C Investments', desc: 'Hurried March investments often default to suboptimal products. Plan early in year.' },
      { title: 'Ignoring New Regime Math', desc: 'New regime is default since FY 2023-24. Old regime needs explicit choice.' },
      { title: 'Spouse / Minor Investments', desc: 'Income from such investments may be clubbed under Section 64 — defeating tax saving.' },
      { title: 'No Estate Planning', desc: 'Tax planning without succession (Will, nomination, HUF) creates inheritance tax (when reintroduced) and probate complexities.' },
    ],
    faqs: [
      { q: 'When should I start tax planning?', a: 'In April-May for the current financial year. Early planning enables optimal investment timing, HRA structuring and capital-gains sequencing.' },
      { q: 'What is HUF tax benefit?', a: 'A HUF (Hindu Undivided Family) is a separate tax entity with its own ₹2.5 lakh exemption + 80C deduction. Income from HUF property is taxed in HUF\'s hands — useful for inter-generational tax planning.' },
      { q: 'Can I switch between old and new regime?', a: 'Salaried — yes, year-on-year. Business income — switch is one-time per Section 115BAC. New regime is default.' },
      { q: 'Are my parents\' investments deductible?', a: 'Health insurance for parents is deductible under Section 80D up to ₹50,000 (₹25,000 if non-senior). Other expenses for parents — generally not deductible.' },
      { q: 'How much tax can I save?', a: 'For ₹15 lakh income, well-planned old regime can save ₹1-1.5 lakh vs no planning. Specifics depend on income, age and goals.' },
    ],
    relatedServices: [
      { name: 'ITR for Individual', href: '/services/business-registration/taxation/itr-individual' },
      { name: 'Tax Planning — Corporate', href: '/services/business-registration/taxation/tax-planning-corporate' },
      { name: 'Will Registration', href: '/services/property/registration/will-registration' },
    ],
  },

  'tax-planning-corporate': {
    title: 'Tax Planning — Corporate',
    description:
      'Corporate tax planning — entity selection, transaction structuring, transfer pricing, cross-border tax, R&D and startup deductions for legal tax minimization.',
    keywords: ['corporate tax planning', 'company tax planning India', 'transfer pricing planning', 'cross-border tax', 'startup tax 80-IAC', 'R&D tax planning'],
    overview:
      'Corporate Tax Planning is a strategic exercise that integrates tax considerations into business decisions — entity selection (Pvt Ltd vs LLP vs OPC), business structuring (single entity vs holding-subsidiary), transaction-level planning (slump sale vs share sale, mergers, demergers), transfer pricing for related parties, cross-border structuring under DTAAs and use of regime-specific incentives.\n\nCorporates can avail Section 115BAA (22% concessional rate), Section 115BAB (15% for new manufacturing), Section 80-IAC (startup deduction), Section 35 R&D deductions, Section 80JJAA additional employment deduction and various other regime-specific benefits subject to conditions.\n\nWe provide ongoing CFO-level tax advisory for corporates, integrate tax into M&A and financing decisions, structure international operations and represent in tax disputes / appeals.',
    whyChooseUs: [
      { title: 'CFO-Level Advisory', desc: 'Tax integrated into business strategy, not just compliance.' },
      { title: 'M&A Tax Structuring', desc: 'Slump sale, share purchase, merger, demerger optimized for tax.' },
      { title: 'Cross-Border DTAA', desc: 'PE risk analysis, withholding optimization, MLI applicability.' },
      { title: 'Disputes & Appeals', desc: 'CIT(A), ITAT, High Court representation in tax matters.' },
    ],
    keyPoints: [
      'Entity selection — Pvt Ltd, LLP, OPC, Section 8 tax comparison',
      'Section 115BAA — 22% concessional regime',
      'Section 115BAB — 15% for new manufacturing',
      'Section 80-IAC — Startup 100% deduction',
      'Section 35 R&D weighted deduction',
      'Section 80JJAA — additional employment',
      'Transfer pricing — Section 92-92F compliance',
      'Cross-border tax — DTAA, GAAR, MLI',
      'M&A tax — slump sale vs share sale vs amalgamation',
      'Group restructuring and demerger',
      'Holding-subsidiary tax efficiency',
    ],
    process: [
      { title: 'Tax Diagnostic', desc: 'Current entity structure, tax position, opportunities.' },
      { title: 'Structuring', desc: 'Recommend entity / transaction / group structure changes.' },
      { title: 'Implementation', desc: 'File necessary forms, restructure entities, document transfer pricing.' },
      { title: 'Ongoing Compliance', desc: 'Quarterly reviews, board updates, annual assessments.' },
      { title: 'Disputes', desc: 'Where assessments / appeals arise, litigate strategically.' },
    ],
    statutoryRefs: [
      { name: 'Income-tax Act — Section 115BAA / 115BAB', desc: 'Concessional corporate tax regimes.' },
      { name: 'Section 80-IAC', desc: 'Startup deduction (3 of 10 years).' },
      { name: 'Sections 92-92F', desc: 'Transfer pricing rules.' },
      { name: 'Section 95-102 (GAAR)', desc: 'General Anti-Avoidance Rules.' },
    ],
    pitfalls: [
      { title: 'Inappropriate 115BAA Election', desc: 'Section 115BAA election forfeits various deductions. Election should be after detailed analysis.' },
      { title: 'TP Documentation Gaps', desc: 'Missing TP study during related-party transactions invites adjustments and penalty.' },
      { title: 'GAAR-Triggering Structures', desc: 'Pure tax-driven structures without commercial substance attract GAAR.' },
      { title: 'PE Risk in Cross-Border', desc: 'Indian agents / dependent operations may create PE — exposing foreign principal to Indian tax.' },
    ],
    faqs: [
      { q: 'Should we elect Section 115BAA?', a: 'Compute tax under both regimes — old (with deductions) and new 115BAA (22% flat). For most stable companies, 115BAA is beneficial. Election is irrevocable.' },
      { q: 'Are startups eligible for 80-IAC?', a: 'Yes — DPIIT-recognized startups can claim 100% deduction for any 3 consecutive years out of first 10. Inter-Ministerial Board certification required.' },
      { q: 'When is transfer pricing applicable?', a: 'Section 92 — international related-party transactions. Section 92BA — specified domestic transactions exceeding thresholds. Both require maintenance and Form 3CEB filing.' },
      { q: 'How does GAAR apply?', a: 'GAAR (Sections 95-102) applies to "impermissible avoidance arrangements" — those lacking commercial substance and primarily for tax benefit. Threshold: tax benefit > ₹3 crore.' },
      { q: 'Can we restructure tax-neutrally?', a: 'Yes — through Section 47 (transactions not regarded as transfer), Section 72A (carry-forward of losses on amalgamation) and similar provisions, subject to conditions.' },
    ],
    relatedServices: [
      { name: 'ITR for Companies', href: '/services/business-registration/taxation/itr-companies' },
      { name: 'Tax Audit', href: '/services/business-registration/taxation/tax-audit' },
      { name: 'Merger & Acquisitions', href: '/services/lawyer-services/corporate-services/merger-acquisitions' },
    ],
  },

  'tax-audit': {
    title: 'Tax Audit',
    description:
      'Tax Audit under Section 44AB of Income-tax Act — Form 3CD reporting, audit report (Form 3CA / 3CB) by Chartered Accountant for businesses crossing turnover thresholds.',
    keywords: ['tax audit', 'Section 44AB', 'Form 3CD', 'tax audit India', 'CA audit', 'turnover audit threshold', '44AB threshold'],
    overview:
      'Tax Audit under Section 44AB of the Income-tax Act, 1961 is mandatory for businesses / professions crossing prescribed turnover / receipts thresholds — typically ₹1 crore for business, ₹50 lakh for profession (₹10 crore where 95%+ digital transactions). The audit is conducted by a Chartered Accountant who issues audit report in Form 3CA (along with statutory audit) or 3CB (independent), accompanied by detailed Form 3CD (44 clauses on income, expenses, compliance).\n\nTax Audit due date is 30 September of the assessment year (subject to extensions). Late filing attracts penalty under Section 271B — 0.5% of turnover or ₹1.5 lakh whichever is lower.\n\nWe coordinate Tax Audit by empaneled Chartered Accountants, prepare Form 3CD documentation, address Form 3CD compliance gaps, and integrate Tax Audit with ITR-6 / ITR-3 filing.',
    whyChooseUs: [
      { title: 'Empaneled CAs', desc: 'Network of qualified CAs available for Tax Audit assignments.' },
      { title: 'Form 3CD Quality', desc: 'Detailed, accurate Form 3CD reduces scrutiny risk.' },
      { title: 'TDS / Section 40A Coverage', desc: 'Comprehensive coverage of TDS lapses, related-party transactions, presumptive computations.' },
      { title: 'ITR Integration', desc: 'Tax Audit findings reflected accurately in ITR-6 / ITR-3.' },
    ],
    keyPoints: [
      'Section 44AB applicability assessment',
      'Form 3CD preparation (44 clauses)',
      'Audit report — Form 3CA (with statutory) / 3CB (standalone)',
      'TDS compliance review (Section 40(a)(ia) disallowance)',
      'Cash payment > ₹10,000 disallowance (Section 40A(3))',
      'Related-party disclosures (Section 40A(2))',
      'Inventory and method-of-accounting verification',
      'Presumptive taxation (44AD / 44ADA / 44AE) opt-out',
      'GST / TDS reconciliation',
      'Filing on income-tax portal before 30 September',
    ],
    process: [
      { title: 'Threshold Verification', desc: 'Confirm tax-audit applicability based on turnover, digital transaction ratio.' },
      { title: 'Document Compilation', desc: 'Books, ledgers, TDS, GST returns, bank statements, contracts.' },
      { title: 'CA Audit', desc: 'CA conducts test checks, Form 3CD preparation.' },
      { title: 'Filing', desc: 'Form 3CA / 3CB + 3CD uploaded on income-tax portal by 30 September.' },
      { title: 'Acceptance & ITR', desc: 'Auditee accepts on portal; ITR follows by 31 October.' },
    ],
    statutoryRefs: [
      { name: 'Income-tax Act — Section 44AB', desc: 'Tax Audit threshold and conditions.' },
      { name: 'Section 44AD / 44ADA / 44AE', desc: 'Presumptive taxation alternatives.' },
      { name: 'Form 3CA / 3CB / 3CD', desc: 'Prescribed audit report formats.' },
      { name: 'Section 271B', desc: 'Penalty for failure to audit / late filing.' },
    ],
    pitfalls: [
      { title: 'Late Tax Audit', desc: 'Penalty under Section 271B — 0.5% of turnover up to ₹1.5 lakh. Frequent.' },
      { title: 'Wrong Form (3CA vs 3CB)', desc: 'Form 3CA used when statutory audit applies; 3CB standalone. Wrong form invites query.' },
      { title: 'TDS Lapses Disallowed', desc: 'Sec 40(a)(ia) disallowance for non-deduction / non-deposit of TDS — caught in Tax Audit.' },
      { title: 'Cash > ₹10,000', desc: 'Sec 40A(3) disallows cash expense above ₹10,000. Tax Audit reports trigger automatic ITR adjustment.' },
    ],
    faqs: [
      { q: 'When is Tax Audit applicable?', a: 'Business turnover > ₹1 crore (₹10 crore if 95%+ digital), Profession receipts > ₹50 lakh, or Presumptive opt-out cases. Complete list under Section 44AB(a)-(e).' },
      { q: 'What is the due date?', a: '30 September of the assessment year (subject to CBDT extensions). ITR follows by 31 October.' },
      { q: 'Who can conduct Tax Audit?', a: 'A Chartered Accountant in practice, registered with ICAI, who is not the assessee or a related person.' },
      { q: 'What if turnover is just below ₹1 crore?', a: 'Tax Audit not mandatory. But maintain books per Section 44AA. Watch threshold annually.' },
      { q: 'Can I revise audit report?', a: 'Yes — under specific circumstances (clerical errors, supplementary information). Substantive revisions invite scrutiny.' },
    ],
    relatedServices: [
      { name: 'ITR for Companies', href: '/services/business-registration/taxation/itr-companies' },
      { name: 'GST Audit', href: '/services/business-registration/taxation/gst-audit' },
      { name: 'CA Audit & Report', href: '/services/compliances/closure-convert-others/ca-audit-report' },
      { name: 'Tax Planning — Corporate', href: '/services/business-registration/taxation/tax-planning-corporate' },
    ],
  },

  'gst-audit': {
    title: 'GST Audit',
    description:
      'GST Audit and GSTR-9 / 9C compliance — annual return, reconciliation statement, ITC reconciliation and audit by CA / CMA for GST-registered businesses.',
    keywords: ['GST audit', 'GSTR-9', 'GSTR-9C', 'GST annual return', 'GST reconciliation', 'CA GST audit', 'CMA audit GST'],
    overview:
      'GST compliance involves annual return filing in Form GSTR-9 (mandatory above ₹2 crore turnover) and reconciliation statement in GSTR-9C (mandatory above ₹5 crore turnover) — the latter being the GST audit equivalent. While the statutory audit by CA / CMA was removed in 2021 (replaced with self-certification of GSTR-9C), reconciliation rigor and accuracy remain critical to avoid future demands and penalties.\n\nKey areas of GST audit: outward supply reconciliation (GSTR-1 vs books), inward supply matching (GSTR-2A / 2B vs ITC), output tax payment, RCM compliance, e-way bill matching, refund claim accuracy, TDS/TCS credits and exempt-supply treatment.\n\nWe handle end-to-end GST annual return filing, GSTR-9C reconciliation, audit support and dispute resolution before GST officers, AAR, GST Tribunal and High Court.',
    whyChooseUs: [
      { title: 'CA + CMA Team', desc: 'Both qualifications available for GST audit assignments.' },
      { title: 'Books-to-Returns Reconciliation', desc: 'Detailed reconciliation between books, GSTR-1 / 3B / 9.' },
      { title: 'ITC Maximization', desc: 'Identify missed ITC and reverse irregular ITC before audit.' },
      { title: 'Audit / Litigation', desc: 'Departmental audit (Section 65), special audit (Section 66) and tribunal representation.' },
    ],
    keyPoints: [
      'GSTR-9 annual return (mandatory > ₹2 crore turnover)',
      'GSTR-9C reconciliation statement (> ₹5 crore turnover)',
      'GSTR-1 / 3B vs books reconciliation',
      'GSTR-2A / 2B vs ITC reconciliation',
      'RCM (Reverse Charge Mechanism) compliance',
      'E-invoicing compliance (> ₹5 crore turnover)',
      'E-way bill matching with returns',
      'Refund claim accuracy and reasonableness',
      'TDS / TCS credit reconciliation',
      'HSN / SAC code accuracy',
    ],
    process: [
      { title: 'Books Closure', desc: 'Finalize books for the financial year; ensure all supplies / ITC are recorded.' },
      { title: 'Reconciliation', desc: 'Books vs GSTR-1 vs GSTR-3B; ITC books vs 2A / 2B; e-way bills.' },
      { title: 'Pre-filing Adjustments', desc: 'Pay short-paid tax with interest; reverse irregular ITC.' },
      { title: 'GSTR-9 / 9C Filing', desc: 'File annual return + reconciliation by 31 December (or extended date).' },
      { title: 'Departmental Audit Defence', desc: 'Where audit is conducted, support with reconciliation and explanations.' },
    ],
    statutoryRefs: [
      { name: 'CGST Act, 2017 — Section 35(5) (until 2021)', desc: 'Mandatory GST audit (now self-certification).' },
      { name: 'Section 44 + Rule 80', desc: 'Annual return and reconciliation statement.' },
      { name: 'Section 65', desc: 'Departmental audit by GST officers.' },
      { name: 'Section 66', desc: 'Special audit by CA / CMA on Commissioner\'s direction.' },
      { name: 'Section 73 / 74', desc: 'Demand and recovery of short-paid tax.' },
    ],
    pitfalls: [
      { title: 'Late GSTR-9 / 9C', desc: 'Late fees + risk of audit / scrutiny.' },
      { title: 'Books vs Returns Mismatch', desc: 'Mismatch between books and GSTR-3B leads to demand notices under Section 73 / 74.' },
      { title: 'ITC Without 2A / 2B', desc: 'ITC claimed without supplier upload faces reversal.' },
      { title: 'RCM Non-Payment', desc: 'Reverse charge tax not paid and not declared in GSTR-3B is a common audit finding.' },
    ],
    faqs: [
      { q: 'Is GST audit mandatory?', a: 'GSTR-9 is mandatory above ₹2 crore turnover. GSTR-9C reconciliation is mandatory above ₹5 crore — now self-certified by taxpayer (CA / CMA audit not statutorily mandatory since FY 2020-21).' },
      { q: 'What is the due date?', a: '31 December of the year following the financial year (subject to CBIC extensions).' },
      { q: 'What is GSTR-9C?', a: 'Reconciliation statement between GSTR-9 (annual return) and audited financial statements. Self-certified by taxpayer for entities above ₹5 crore turnover.' },
      { q: 'What if mismatches are found?', a: 'Pay differential tax with interest before filing or face Section 73 / 74 demand notice with penalty.' },
      { q: 'Can ITC be claimed if missed in GSTR-3B?', a: 'Generally, ITC must be claimed within the due date for filing return for September of next FY or annual return — whichever is earlier. After this, ITC may lapse.' },
    ],
    relatedServices: [
      { name: 'GST Filing', href: '/services/compliances/company-compliances/gst-filing' },
      { name: 'GST Registration', href: '/services/business-registration/company-registration/gst-registration' },
      { name: 'Tax Audit', href: '/services/business-registration/taxation/tax-audit' },
      { name: 'ITR for Companies', href: '/services/business-registration/taxation/itr-companies' },
    ],
  },
};
