import type { ServiceContent } from '@/components/leaf-service-page';

export const documentationBusinessCorporateServices: Record<string, ServiceContent> = {
  noc: {
    title: 'No Objection Certificate (NOC)',
    description:
      'NOC drafting and procurement — society / RWA, employer, lender, government authority, parent company NOCs for property, business, education and travel purposes.',
    keywords: [
      'no objection certificate',
      'NOC drafting',
      'society NOC',
      'employer NOC',
      'lender NOC',
      'parent company NOC',
      'NOC format India',
    ],
    overview:
      'A No Objection Certificate (NOC) is a written declaration by a stakeholder confirming they have no objection to a specified action — sale of property, employment with another organization, marriage of a minor, foreign travel, business expansion, transfer or franchise grant. NOCs are required under various laws and contractual arrangements and serve as evidence of consent.\n\nCommon NOCs include: society / RWA NOC for property sale or alteration, employer NOC for moonlighting / external employment, lender NOC for property sale of mortgaged asset, parent company NOC for subsidiary actions, government authority NOC for industry / construction, and bank NOC for loan transfer.\n\nWe draft NOCs with precise scope, conditions and validity periods. We also assist in procuring NOCs from third parties — particularly society / RWA NOCs, lender NOCs, and authority NOCs which often face procedural delays.',
    whyChooseUs: [
      { title: 'Scope-Specific Drafting', desc: 'NOCs drafted to be exactly as broad as needed and not broader.' },
      { title: 'Procurement Support', desc: 'Beyond drafting — we follow up with society / RWA / lender for actual issuance.' },
      { title: 'Legal Notice Where Refused', desc: 'When NOCs are unreasonably refused, we issue legal notice.' },
      { title: 'Renewal Tracking', desc: 'Time-bound NOCs tracked for renewal.' },
    ],
    keyPoints: [
      'Society / RWA NOC for property sale, lease, alteration',
      'Employer NOC for outside employment',
      'Lender NOC for sale of mortgaged property',
      'Parent / Holding company NOC',
      'Government / Authority NOC',
      'Spouse NOC for property / passport',
      'Marriage NOC',
      'Bank NOC for fund transfer / loan closure',
      'Indemnity backing NOC',
      'Time-bound NOC validity tracking',
    ],
    process: [
      { title: 'Scope Definition', desc: 'Identify exact action requiring NOC and stakeholder authority.' },
      { title: 'Drafting', desc: 'Tailored NOC with scope, conditions, validity.' },
      { title: 'Issuer Coordination', desc: 'For third-party NOCs, follow up with issuer.' },
      { title: 'Authentication', desc: 'Notarization or registration where required.' },
    ],
    statutoryRefs: [
      { name: 'Indian Contract Act, 1872', desc: 'NOCs as form of consent under contract law.' },
      { name: 'Cooperative Societies Acts (State-specific)', desc: 'Society NOC procedures.' },
      { name: 'Companies Act, 2013', desc: 'Inter-company NOCs and consent letters.' },
    ],
    pitfalls: [
      { title: 'Vague NOC Language', desc: 'Open-ended NOCs may inadvertently consent to broader actions than intended.' },
      { title: 'No Time Limit', desc: 'NOCs without validity period may be relied upon years later in changed circumstances.' },
      { title: 'Unauthorized Signatory', desc: 'NOC signed by person without authority is invalid; verify signing authority.' },
      { title: 'Ignoring Conditions', desc: 'NOCs often have conditions (e.g., subject to dues clearance); ignoring conditions invalidates the NOC.' },
    ],
    faqs: [
      { q: 'Is NOC legally binding?', a: 'A signed NOC is binding as a contractual representation; the issuer cannot resile from the consent for the specified scope and period without breach.' },
      { q: 'Can a society refuse NOC for property sale?', a: 'Society NOC for sale cannot be unreasonably withheld — most cooperative laws permit transfer subject to bye-laws (membership transfer, dues clearance). Refusal can be challenged before Registrar of Cooperatives.' },
      { q: 'How long is a NOC valid?', a: 'As specified in the NOC. Best practice: 3-6 months for transactional NOCs, longer for general consents. Beyond expiry, fresh NOC needed.' },
      { q: 'What if employer refuses NOC for outside employment?', a: 'Depends on employment terms. If contract restricts moonlighting / outside employment, refusal is enforceable. If contract is silent, refusal can often be challenged.' },
      { q: 'Does NOC need to be notarized?', a: 'Not always — for routine NOCs, signed letter suffices. For high-value transactions or court submissions, notarization adds evidentiary weight.' },
    ],
    relatedServices: [
      { name: 'Affidavit', href: '/services/documentation/legal/affidavit' },
      { name: 'Legal Notice', href: '/services/documentation/legal/legal-notice' },
      { name: 'Memorandum of Understanding (MoU)', href: '/services/documentation/business-corporate/mou' },
    ],
  },

  'offer-appointment-letter': {
    title: 'Offer / Appointment Letter',
    description:
      'Drafting and review of Offer Letters and Appointment Letters — compensation, role, probation, notice period, NDA and statutory protections.',
    keywords: [
      'offer letter format',
      'appointment letter',
      'employment letter India',
      'offer letter drafting',
      'employment contract',
      'CTC appointment letter',
    ],
    overview:
      'Offer Letters and Appointment Letters are the foundational employment contracts that define every employer-employee relationship. While Offer Letters are typically pre-joining intent letters and Appointment Letters are formal post-joining contracts, the substantive terms — compensation, role, location, hours, probation, notice period, confidentiality, IP assignment and termination — flow through both.\n\nIndian employment law overlays the contract with statutory protections — Industrial Disputes Act for workmen, Shops & Establishments Acts (State-specific), Code on Wages, EPF, ESIC, Gratuity, Maternity Benefit and POSH Act. Letters that contradict statute are unenforceable to that extent; well-drafted letters integrate statutory minimums and customize the rest.\n\nWe draft for employers (HR-friendly templates), employees (negotiating offers) and senior executives (CXO / CEO contracts with stock options, severance, non-compete and arbitration). We also review letters before signing to flag unusual or onerous clauses.',
    whyChooseUs: [
      { title: 'Employer / Employee Both Sides', desc: 'Drafting style adapted to whom we represent.' },
      { title: 'Senior Executive Contracts', desc: 'CXO / CEO offers with stock options, severance, non-compete.' },
      { title: 'Statute-Mapped Compliance', desc: 'EPF, ESIC, Gratuity, POSH, Maternity Benefit integrated.' },
      { title: 'Template Library for HR', desc: 'For high-volume employers — versioned template library with annual refresh.' },
    ],
    keyPoints: [
      'Offer letter (intent) vs Appointment letter (contract)',
      'Compensation structure (CTC, fixed, variable, benefits)',
      'Role, location, working hours, leave',
      'Probation period and confirmation criteria',
      'Notice period (employee and employer side)',
      'Confidentiality and IP assignment',
      'Non-compete and non-solicit (enforceability bounds)',
      'Statutory benefits (EPF, ESIC, Gratuity)',
      'Termination — with cause, without cause',
      'Arbitration / dispute resolution',
      'POSH Act incorporation',
    ],
    process: [
      { title: 'Briefing', desc: 'Capture role, level, compensation, location, special clauses.' },
      { title: 'Drafting', desc: 'Tailored letter with all material terms.' },
      { title: 'Review & Sign-off', desc: 'Internal HR / legal review; finalize.' },
      { title: 'Issuance & Acceptance', desc: 'Letter issued; signed and returned by candidate.' },
    ],
    statutoryRefs: [
      { name: 'Indian Contract Act, 1872', desc: 'Foundational contract law.' },
      { name: 'Industrial Employment (Standing Orders) Act, 1946', desc: 'Standing orders for industrial establishments.' },
      { name: 'Code on Wages, 2019; Industrial Relations Code, 2020', desc: 'New labour code framework.' },
      { name: 'Shops & Establishments Acts (State-specific)', desc: 'Working hours, leaves, holidays.' },
      { name: 'Niranjan Shankar Golikari (1967) SC', desc: 'Non-compete during employment is valid; post-termination is restricted under Section 27 Contract Act.' },
    ],
    pitfalls: [
      { title: 'Overbroad Non-Compete', desc: 'Post-termination non-compete is generally void under Section 27. Only narrow restraints (limited time, geography, scope) are upheld.' },
      { title: 'Hidden Statutory Liabilities', desc: 'Even if not written, Gratuity, EPF, ESIC are statutory entitlements; ignoring creates liability.' },
      { title: 'Vague Termination Clause', desc: '"Termination at company discretion" without procedural fairness invites wrongful termination claims.' },
      { title: 'No POSH Reference', desc: 'POSH Act applies to all establishments with 10+ employees; absence in offer letter doesn\'t excuse compliance.' },
    ],
    faqs: [
      { q: 'Is offer letter legally binding?', a: 'Generally yes — once signed and accepted, offer letter is a contract. Pure offer letters can be revoked before acceptance; post-acceptance breach exposes employer to damages.' },
      { q: 'Can employer reduce offered CTC?', a: 'Pre-joining — yes (with consent or by withdrawing offer with damages exposure). Post-joining — only with employee consent or per terms of appointment letter.' },
      { q: 'Is non-compete enforceable in India?', a: 'Section 27 Contract Act voids restraints of trade. During employment — enforceable. Post-termination — generally void, except narrow exceptions for trade secrets / goodwill / specific industries.' },
      { q: 'What is the difference between probation and full employment?', a: 'During probation, termination is easier (typically without notice for unsatisfactory performance). Post-confirmation, full notice period and termination protections apply.' },
      { q: 'Can I negotiate offer letter terms?', a: 'Yes — offer letters are negotiable, especially CTC, joining bonus, notice period, stock options and non-compete. Negotiate before signing.' },
    ],
    relatedServices: [
      { name: 'Resignation Letter', href: '/services/documentation/business-corporate/resignation-letter' },
      { name: 'Termination Letter', href: '/services/documentation/business-corporate/termination-letter' },
      { name: 'Non-Disclosure Agreement (NDA)', href: '/services/documentation/business-corporate/nda' },
      { name: 'Industrial Dispute', href: '/services/lawyer-services/corporate-services/industrial-dispute' },
    ],
  },

  'resignation-letter': {
    title: 'Resignation Letter',
    description:
      'Strategic Resignation Letter drafting — preserving rights, dues, references and avoiding wrongful termination / breach allegations.',
    keywords: [
      'resignation letter format',
      'resignation letter drafting',
      'resignation notice',
      'employee resignation',
      'resignation acceptance',
      'F&F settlement',
    ],
    overview:
      'A Resignation Letter is the employee\'s formal notice of intent to terminate employment. While seemingly simple, the letter\'s exact wording, timing, accepted notice period and tone can significantly affect dues clearance, references, non-compete enforceability and any subsequent disputes.\n\nMatters can quickly become contentious — employer disputing resignation date, reducing F&F amounts, delaying relieving letter, claiming breach of bond / non-compete, threatening litigation. Strategic drafting protects against these — establishing notice period compliance, dues claim, request for proper relieving and asserting rights without provocation.\n\nWe draft routine resignations, escalation-ready resignations (where issues are likely), constructive dismissal resignations (where employee is forced to resign due to hostile conditions), and senior executive resignations with severance / non-compete trade-offs.',
    whyChooseUs: [
      { title: 'Strategy Over Template', desc: 'Each resignation drafted to specific facts and intended outcome.' },
      { title: 'Constructive Dismissal Cases', desc: 'When employee is forced to resign — language preserves wrongful-termination claim.' },
      { title: 'F&F Recovery', desc: 'When dues are withheld — escalation legal notice to recover F&F.' },
      { title: 'Senior Executive Exits', desc: 'CXO exits with severance, ESOP, non-compete trade-offs negotiated.' },
    ],
    keyPoints: [
      'Routine resignation with proper notice',
      'Constructive dismissal resignation (preserving claim)',
      'Senior executive exit (severance, ESOP, non-compete)',
      'Bond / training-cost dispute strategy',
      'F&F dues claim — salary, gratuity, encashment, PF, ESOPs',
      'Relieving letter / experience certificate',
      'Reference letter request',
      'NDA / non-compete acknowledgment',
      'Request for transition handover',
      'Dispute escalation legal notice',
    ],
    process: [
      { title: 'Briefing', desc: 'Capture employment terms, exit reasons, intended next steps.' },
      { title: 'Drafting', desc: 'Tailored letter — routine, escalation-ready or strategic.' },
      { title: 'Issuance', desc: 'Send via email + hard copy with delivery acknowledgment.' },
      { title: 'Follow-through', desc: 'Track acceptance, F&F, relieving; escalate if delays / disputes arise.' },
    ],
    statutoryRefs: [
      { name: 'Indian Contract Act, 1872', desc: 'Resignation as termination of employment contract.' },
      { name: 'Industrial Disputes Act, 1947', desc: 'For workmen — protections continue post-resignation in specific cases.' },
      { name: 'Payment of Gratuity Act, 1972', desc: 'Gratuity payable for 5+ years of continuous service (also on resignation).' },
      { name: 'Section 17 EPF Act', desc: 'PF withdrawal after employment termination.' },
    ],
    pitfalls: [
      { title: 'Ambiguous Notice Date', desc: 'Resignation letter without clear last working date creates F&F disputes.' },
      { title: 'Acknowledging Liability', desc: '"I apologize for any inconvenience" can be used against you in bond / breach claims.' },
      { title: 'Verbal Agreements Forgotten', desc: 'Verbal promises (reduced notice, severance) should be documented in resignation acceptance.' },
      { title: 'Skipping Bond Defense', desc: 'If employer cites training bond, default response should challenge enforceability if disproportionate.' },
    ],
    faqs: [
      { q: 'How much notice period is required?', a: 'As per appointment letter — typically 30-90 days. Longer for senior roles. Some States/Acts cap notice at 3 months.' },
      { q: 'Can I leave before notice period ends?', a: 'Without employer\'s consent — risks bond claim, salary deduction, denial of relieving. Negotiate buyback or shorter notice with employer.' },
      { q: 'What is F&F (Full & Final) settlement?', a: 'Final dues — pending salary, leave encashment, gratuity (if eligible), ESOP exercise (if applicable), reimbursements, minus deductions. Typically processed within 30-45 days of last working day.' },
      { q: 'Can employer withhold relieving letter?', a: 'Generally no — relieving letter cannot be unreasonably withheld. If withheld, escalate to HR head, then legal notice. Right to relieving is supported by judicial precedent.' },
      { q: 'What about training bond / education sponsorship recovery?', a: 'Bond is enforceable if reasonable and proportionate to employer\'s actual cost. Excessive bonds (cost ₹50,000 but bond ₹10 lakh) are routinely struck down. Disputes go to civil court.' },
    ],
    relatedServices: [
      { name: 'Offer / Appointment Letter', href: '/services/documentation/business-corporate/offer-appointment-letter' },
      { name: 'Termination Letter', href: '/services/documentation/business-corporate/termination-letter' },
      { name: 'Industrial Dispute', href: '/services/lawyer-services/corporate-services/industrial-dispute' },
      { name: 'Legal Notice', href: '/services/documentation/legal/legal-notice' },
    ],
  },

  'termination-letter': {
    title: 'Termination Letter',
    description:
      'Termination Letter drafting and process — performance-based, disciplinary, redundancy and retrenchment terminations with statutory and procedural compliance.',
    keywords: [
      'termination letter',
      'employee termination',
      'wrongful termination defense',
      'retrenchment letter',
      'performance termination',
      'disciplinary termination',
    ],
    overview:
      'Employee termination is one of the highest-risk HR actions — exposing employers to wrongful termination, industrial dispute, and discrimination claims. The Termination Letter is the apex document that crystallizes the action and either protects the employer or establishes the employee\'s case.\n\nIndian termination law differs substantially based on employee category — managerial / executive employees are governed primarily by contract; "workmen" under Industrial Disputes Act, 1947 have substantial procedural protections (Section 25F retrenchment notice + compensation). The IR Code, 2020 (where notified) reorganizes this framework.\n\nWe draft terminations across categories — for cause (misconduct after inquiry), poor performance (after PIP), redundancy / retrenchment, restructuring / RIF, project-end and contract non-renewal. We integrate procedural fairness, statutory compliance, F&F structuring and post-exit obligations.',
    whyChooseUs: [
      { title: 'Litigation-Resistant', desc: 'Terminations drafted to withstand industrial / civil court scrutiny.' },
      { title: 'Procedural Fairness', desc: 'Inquiry, show-cause, opportunity to be heard — embedded in process.' },
      { title: 'Workmen vs Manager Distinction', desc: 'Different procedures for IDA workmen vs contract executives.' },
      { title: 'Severance Structuring', desc: 'Tax-optimized severance packages with full statutory compliance.' },
    ],
    keyPoints: [
      'Termination for cause / misconduct (after inquiry)',
      'Performance termination (after PIP)',
      'Redundancy / retrenchment (Section 25F IDA — workmen)',
      'Restructuring / RIF (reduction-in-force)',
      'Project-end / contract non-renewal',
      'Show-cause and inquiry procedure',
      'Severance and ex-gratia structuring',
      'F&F components (notice pay, gratuity, leave, ESOPs)',
      'Non-compete / NDA reaffirmation',
      'Reference letter / experience certificate',
    ],
    process: [
      { title: 'Pre-termination Diagnostic', desc: 'Map employee category, employment terms, ground for termination, statutory framework.' },
      { title: 'Show-Cause / PIP', desc: 'Where required — show-cause notice, opportunity to be heard, PIP documentation.' },
      { title: 'Inquiry (for misconduct)', desc: 'Domestic inquiry per principles of natural justice.' },
      { title: 'Termination Letter', desc: 'Comprehensive letter with grounds, date, F&F, post-exit obligations.' },
      { title: 'F&F Settlement', desc: 'Process F&F within 30-45 days; coordinate clearance.' },
    ],
    statutoryRefs: [
      { name: 'Industrial Disputes Act, 1947 — Section 25F', desc: 'Retrenchment compensation for workmen — 1 month notice + 15 days wages per year.' },
      { name: 'IDA Section 25N', desc: 'Government permission required for retrenchment in establishments with 100+ workmen.' },
      { name: 'Industrial Relations Code, 2020', desc: 'Replaces IDA where notified; raises threshold to 300+.' },
      { name: 'Shops & Establishments Acts', desc: 'State-specific notice and termination provisions for non-IDA employees.' },
      { name: 'Anglo-American Direct Tea Trading (1955) SC', desc: 'Principles of natural justice in domestic inquiry.' },
    ],
    pitfalls: [
      { title: 'No Inquiry for Misconduct', desc: 'Termination for misconduct without proper inquiry is wrongful — invites reinstatement and back-wages order.' },
      { title: 'Skipping 25F Compliance', desc: 'For workmen, Section 25F notice and compensation are mandatory. Skipping is fatal to retrenchment.' },
      { title: 'Vague Termination Reasons', desc: 'Vague termination ("not suitable", "performance issues" without documentation) is challengeable.' },
      { title: 'No Severance Where Customary', desc: 'Where industry / company practice is to pay severance, refusal in specific case can support discrimination claim.' },
    ],
    faqs: [
      { q: 'What is the difference between termination for cause and without cause?', a: 'Termination for cause (misconduct, breach) requires inquiry. Without cause / for performance / redundancy uses different procedures and compensation structures. IDA Section 25F applies to retrenchment of workmen regardless.' },
      { q: 'How much notice / pay is required?', a: 'Per appointment letter (typically 30-90 days). For workmen — Section 25F mandates 1 month notice + 15 days pay per year of service. For non-workmen — contract terms govern.' },
      { q: 'Can I terminate during probation?', a: 'Yes — typically with reduced notice and without inquiry. But documented performance / behavior concerns are recommended to defend against challenge.' },
      { q: 'What about gratuity for terminated employees?', a: 'Gratuity Act provides for gratuity for 5+ years of continuous service — payable on termination unless employee terminated for proven gross misconduct (Section 4(6)).' },
      { q: 'Can a terminated employee challenge?', a: 'Yes — through (a) Industrial Dispute (workmen), (b) civil suit for breach (executives), (c) writ petition (PSU / quasi-government). Outcomes range from reinstatement, back-wages to compensation.' },
    ],
    relatedServices: [
      { name: 'Offer / Appointment Letter', href: '/services/documentation/business-corporate/offer-appointment-letter' },
      { name: 'Resignation Letter', href: '/services/documentation/business-corporate/resignation-letter' },
      { name: 'Industrial Dispute', href: '/services/lawyer-services/corporate-services/industrial-dispute' },
      { name: 'Legal Notice', href: '/services/documentation/legal/legal-notice' },
    ],
  },

  mou: {
    title: 'Memorandum of Understanding (MoU)',
    description:
      'MoU drafting and review — for joint ventures, strategic partnerships, M&A intent, business collaboration, government / institutional arrangements.',
    keywords: [
      'memorandum of understanding',
      'MoU drafting',
      'business MoU',
      'partnership MoU',
      'binding non-binding MoU',
      'collaboration agreement',
    ],
    overview:
      'A Memorandum of Understanding (MoU) is a preliminary document recording the understanding between parties on a proposed transaction or relationship. MoUs range from non-binding letters of intent to fully binding interim agreements. The legal effect depends on language, intention and conduct of parties.\n\nMoUs are commonly used at start of joint ventures, M&A discussions, strategic partnerships, government / institutional collaborations, R&D partnerships and inter-company arrangements. While "MoU" connotes non-binding intent, certain clauses (confidentiality, exclusivity, jurisdiction, IP) are typically expressed as binding even within an otherwise non-binding MoU.\n\nWe draft MoUs across contexts — capturing commercial intent, allocating risk during pre-deal phase, preserving negotiation leverage, and clearly delineating binding vs non-binding portions. We also review MoUs before execution to flag legal exposure.',
    whyChooseUs: [
      { title: 'Binding-Status Clarity', desc: 'Each clause explicitly marked binding / non-binding to prevent unintended liability.' },
      { title: 'Strategic Drafting', desc: 'MoUs structured to advance commercial goals while preserving flexibility.' },
      { title: 'Conversion-Ready', desc: 'MoUs structured for smooth conversion into definitive agreements.' },
      { title: 'Multi-Party MoUs', desc: 'For consortia, multi-stakeholder collaborations and government MoUs.' },
    ],
    keyPoints: [
      'JV / partnership MoU',
      'M&A letter of intent (LoI)',
      'Strategic collaboration MoU',
      'Government / institutional MoU',
      'R&D / IP collaboration MoU',
      'Binding vs non-binding clauses',
      'Confidentiality (binding)',
      'Exclusivity / standstill (binding)',
      'Definitive agreement timeline',
      'Termination and post-termination obligations',
    ],
    process: [
      { title: 'Briefing', desc: 'Capture parties, transaction concept, timeline and binding-status preferences.' },
      { title: 'Drafting', desc: 'MoU with clear binding/non-binding marking, key commercial terms, dispute resolution.' },
      { title: 'Negotiation', desc: 'Mark-up rounds with counterparty.' },
      { title: 'Execution', desc: 'Signing with witnesses; effective date.' },
      { title: 'Definitive Agreement', desc: 'Subsequent definitive agreements consistent with MoU.' },
    ],
    statutoryRefs: [
      { name: 'Indian Contract Act, 1872', desc: 'Foundational law — even non-binding MoUs can create estoppel or partial binding.' },
      { name: 'Specific Relief Act, 1963', desc: 'Specific performance of binding MoU clauses.' },
      { name: 'Companies Act, 2013', desc: 'Material disclosure for MoUs that constitute price-sensitive information.' },
    ],
    pitfalls: [
      { title: 'Unclear Binding Status', desc: 'Without explicit marking, courts may infer binding intention from conduct and language — surprising parties.' },
      { title: 'Exclusivity Without End Date', desc: 'Indefinite exclusivity is unenforceable; specify reasonable period (3-12 months typical).' },
      { title: 'Confidentiality Holes', desc: 'MoU often shares sensitive information; confidentiality clause must be robust and binding.' },
      { title: 'Ignoring Long-Stop Date', desc: 'Without deadline for definitive agreement, MoU drags indefinitely; add a long-stop date with consequences.' },
    ],
    faqs: [
      { q: 'Is MoU legally binding?', a: 'Depends on drafting and intent. MoUs can be: (a) entirely non-binding (intent only), (b) entirely binding (effectively contracts), or (c) partially binding (specific clauses binding). Explicit marking is recommended.' },
      { q: 'What is the difference between MoU, LoI, and Term Sheet?', a: 'These terms overlap significantly. "Term Sheet" connotes financial deal terms; "LoI" connotes intent to enter transaction; "MoU" is broader. Substance over label — actual binding effect determined by content.' },
      { q: 'Should MoU be on stamp paper?', a: 'For clearly non-binding MoUs — nominal stamp duty (₹100-500). For binding MoUs that effectively are agreements — full stamp duty applicable to underlying transaction.' },
      { q: 'Can I sue for breach of non-binding MoU?', a: 'Generally not for breach — but binding clauses (confidentiality, exclusivity) can be enforced. Separately, doctrine of estoppel may apply if one party reasonably relied to its detriment.' },
      { q: 'How long should an MoU be?', a: 'Depends on transaction. Simple MoUs — 2-5 pages. Complex JVs / M&A — 10-30 pages. Match length to transaction complexity.' },
    ],
    relatedServices: [
      { name: 'Joint Venture Agreement', href: '/services/documentation/business-corporate/joint-venture-agreement' },
      { name: 'Non-Disclosure Agreement (NDA)', href: '/services/documentation/business-corporate/nda' },
      { name: 'Business Agreement', href: '/services/documentation/legal/business-agreement' },
      { name: 'Merger & Acquisitions', href: '/services/lawyer-services/corporate-services/merger-acquisitions' },
    ],
  },

  'franchise-agreement': {
    title: 'Franchise Agreement',
    description:
      'Franchise Agreement drafting and review for franchisors and franchisees — territory, fees, IP, training, exclusivity, termination and dispute resolution.',
    keywords: [
      'franchise agreement India',
      'franchise lawyer',
      'master franchise agreement',
      'franchise fee',
      'unit franchise agreement',
      'restaurant franchise',
      'retail franchise',
    ],
    overview:
      'Franchise Agreements govern the relationship between a Franchisor (brand / IP owner) and Franchisee (operator using the brand) — covering brand licensing, territorial rights, training, operations support, fees (initial + royalty), procurement, advertising and termination. India does not have dedicated franchise legislation, so franchise relationships are governed by Indian Contract Act, IP laws, FEMA (for cross-border), Competition Act and tax laws.\n\nWell-drafted franchise agreements balance franchisor control (essential for brand consistency) with franchisee independence (essential for business viability). Common categories include retail, F&B, education, healthcare, fitness and services franchises, and master franchise / area development arrangements.\n\nWe draft and negotiate franchise agreements for both sides. We also handle multi-unit operator agreements, master franchise rights for international brands, area development agreements, and franchise disputes / arbitration.',
    whyChooseUs: [
      { title: 'Franchisor & Franchisee', desc: 'Acted on both sides — gives realistic negotiation perspective.' },
      { title: 'Master Franchise Capability', desc: 'International brand entry into India; cross-border franchise law and FEMA.' },
      { title: 'Sector Knowledge', desc: 'F&B, retail, fitness, education, healthcare — sector-specific clauses.' },
      { title: 'Dispute & Termination Strategy', desc: 'Termination clauses survive scrutiny; arbitration provisions enforceable.' },
    ],
    keyPoints: [
      'Unit Franchise Agreement (single outlet)',
      'Multi-Unit Operator Agreement',
      'Master Franchise Agreement (region-wide rights)',
      'Area Development Agreement',
      'Initial fee, royalty, marketing fund',
      'Territorial exclusivity',
      'IP licensing — trademark, copyright, trade dress',
      'Operations manual and brand standards',
      'Training and support obligations',
      'Procurement / approved supplier requirements',
      'Termination, cure rights and post-termination',
      'Renewal terms and ROFR',
      'Dispute resolution and governing law',
    ],
    process: [
      { title: 'Term Sheet', desc: 'Capture territory, fees, term, exclusivity, key obligations.' },
      { title: 'Drafting', desc: 'Comprehensive agreement with sector-specific clauses.' },
      { title: 'Negotiation', desc: 'Mark-up rounds; in-person sessions for material terms.' },
      { title: 'Execution', desc: 'Signing with proper authority; stamp duty per State.' },
      { title: 'Operations', desc: 'Compliance tracking, periodic reviews, renewal flags.' },
    ],
    statutoryRefs: [
      { name: 'Indian Contract Act, 1872', desc: 'Foundational contract law.' },
      { name: 'Trade Marks Act, 1999', desc: 'Trademark licensing; registration of franchisees as licensees.' },
      { name: 'Competition Act, 2002', desc: 'Restrictive territorial / pricing arrangements may attract scrutiny under Section 3.' },
      { name: 'FEMA, 1999', desc: 'Cross-border franchise — royalty payment compliance.' },
      { name: 'Income Tax Act / Withholding', desc: 'TDS on royalty / franchise fees; equalization levy considerations.' },
    ],
    pitfalls: [
      { title: 'Vague Territorial Exclusivity', desc: '"Exclusive territory" without geographic specificity invites disputes when franchisor opens nearby outlets.' },
      { title: 'One-Sided Termination', desc: 'Franchisor termination at will, without cure rights, may be unenforceable in India.' },
      { title: 'Unregistered Trademark License', desc: 'Trademark license without recordal as Registered User has weaker enforceability.' },
      { title: 'Missing Performance Standards', desc: 'Without measurable performance standards, termination for under-performance is contestable.' },
    ],
    faqs: [
      { q: 'Is franchise registration mandatory in India?', a: 'No — India has no dedicated franchise registration. Trademark licensing should be recorded with Trademark Registry; FEMA filings for cross-border. Other regulatory filings depend on sector.' },
      { q: 'What fees are typically charged?', a: 'Initial Franchise Fee (one-time, ₹2-50 lakh typical), Royalty (3-10% of revenue), Marketing Fund (1-3%), Training Fee. Specific structures vary by sector and brand strength.' },
      { q: 'Can franchisee terminate before term ends?', a: 'Only as per agreement — typically requires breach by franchisor or specific termination clauses. Random termination invites damages claim.' },
      { q: 'What if franchisor doesn\'t support franchisee?', a: 'Franchisee can issue legal notice for breach, claim damages, or seek arbitration. Detailed support obligations in agreement strengthen the case.' },
      { q: 'How long is a typical franchise term?', a: '5-10 years initial term with renewal options. Longer for capital-intensive franchises (manufacturing, hotels). Shorter for service franchises.' },
    ],
    relatedServices: [
      { name: 'Joint Venture Agreement', href: '/services/documentation/business-corporate/joint-venture-agreement' },
      { name: 'Trademark Registration', href: '/services/lawyer-services/ipr-services/trademark/registration' },
      { name: 'Business Agreement', href: '/services/documentation/legal/business-agreement' },
      { name: 'Memorandum of Understanding (MoU)', href: '/services/documentation/business-corporate/mou' },
    ],
  },

  'joint-venture-agreement': {
    title: 'Joint Venture Agreement',
    description:
      'Joint Venture Agreement drafting — equity JV, contractual JV, multi-party JV with governance, exit, deadlock resolution and FEMA compliance.',
    keywords: [
      'joint venture agreement',
      'JV agreement India',
      'equity joint venture',
      'contractual joint venture',
      'JV governance',
      'JV exit clauses',
    ],
    overview:
      'A Joint Venture (JV) is a strategic alliance where two or more parties combine resources, capabilities or markets to pursue a specific project or business. JVs are structured as Equity JVs (joint Indian company / LLP), Contractual JVs (purely contractual without separate vehicle), or Limited Partnerships. Each has distinct tax, governance, exit and liability implications.\n\nIndian JVs are commonly between Indian and foreign partners — under FEMA, Press Note 3, sectoral FDI limits and various regulatory frameworks. Pure-Indian JVs face fewer regulatory complexities but still require careful structuring on governance, deadlock, exit, IP and dispute resolution.\n\nWe structure and document JVs across sectors — manufacturing, technology, real estate, healthcare, infrastructure and services. We integrate corporate, tax, FEMA, IP, employment and dispute resolution into a single coherent JV architecture. We also handle JV exit, restructuring and disputes.',
    whyChooseUs: [
      { title: 'Cross-Border JV Specialists', desc: 'India-foreign JVs with FEMA, Press Note 3 and tax compliance.' },
      { title: 'Multi-Disciplinary', desc: 'Corporate + tax + FEMA + IP + employment integrated.' },
      { title: 'Governance Drafting', desc: 'Reserved matters, board, deadlock — drafted to actually work in disputes.' },
      { title: 'Exit Strategy', desc: 'Tag-along, drag-along, ROFR, ROFO, put-call — drafted with realistic exits.' },
    ],
    keyPoints: [
      'Equity JV (Indian SPV / LLP)',
      'Contractual JV (no separate entity)',
      'Cross-border JV with FEMA compliance',
      'JV with technology / IP contribution',
      'Governance — Board composition, reserved matters',
      'Voting — super-majority on critical decisions',
      'Equity contributions and additional capital calls',
      'Tag-along, drag-along, ROFR, ROFO',
      'Deadlock — Russian roulette, Texas shoot-out, mediation',
      'Exit — IPO, buyout, third-party sale',
      'IP licensing within JV',
      'Non-compete and exclusivity',
    ],
    process: [
      { title: 'Strategic Framing', desc: 'JV objectives, contributions, scope, geography, exit timeline.' },
      { title: 'Structure Selection', desc: 'Equity JV, Contractual JV, LLP — based on tax, regulatory and governance fit.' },
      { title: 'JV Documents', desc: 'JVA, SHA, AoA, ancillary licenses, IP transfer.' },
      { title: 'Regulatory', desc: 'FEMA filings (FC-GPR), CCI notification (where applicable), sectoral approvals.' },
      { title: 'Operations', desc: 'JV company incorporation, board constitution, capital infusion.' },
      { title: 'Exit', desc: 'JV unwind, buyout, IPO — exit per terms.' },
    ],
    statutoryRefs: [
      { name: 'Companies Act, 2013', desc: 'Indian SPV incorporation and governance.' },
      { name: 'LLP Act, 2008', desc: 'LLP-form JVs.' },
      { name: 'FEMA, 1999 — NDI Rules, 2019', desc: 'Foreign investment in JVs.' },
      { name: 'Competition Act, 2002', desc: 'CCI notification for JVs crossing thresholds.' },
      { name: 'Income Tax Act', desc: 'JV taxation; deemed profit / loss attribution.' },
    ],
    pitfalls: [
      { title: 'Vague Reserved Matters', desc: 'Broad reserved matters create deadlock; precise enumeration with super-majority works better.' },
      { title: 'No Deadlock Mechanism', desc: 'JVs without deadlock-resolution become hostage situations — embed put-call, mediation or ultimate dissolution.' },
      { title: 'IP Licensing Missing', desc: 'When one partner contributes IP, license terms must be explicit — exclusivity, term, royalty, post-termination rights.' },
      { title: 'Regulatory Non-Compliance', desc: 'Cross-border JVs without FEMA filings face compounding and potential void.' },
    ],
    faqs: [
      { q: 'Equity JV or Contractual JV?', a: 'Equity JV: separate entity, limited liability, easier external capital, more governance. Contractual JV: simpler, no entity, direct liability, faster setup. Choice depends on scale, longevity and partner trust.' },
      { q: 'Is CCI approval needed for JV?', a: 'If parties\' assets or turnover crosses thresholds under Competition Act, prior CCI notification is mandatory. Many JVs qualify for de minimis exemption.' },
      { q: 'How long does JV setup take?', a: 'Term sheet to definitive: 2-4 months. Regulatory approvals + entity setup: additional 2-4 months. Cross-border with multiple regulators: 6-12 months.' },
      { q: 'Can I exit a JV before term ends?', a: 'Per agreement. Typical exits: tag-along (with majority sale), drag-along (forced sale), put option (sell to partner), buyout (sell to third party with ROFR). Without exit clauses, exit is contentious.' },
      { q: 'What if JV becomes deadlocked?', a: 'Per agreement. Common mechanisms: mediation → arbitration → put-call → Russian roulette → dissolution. Pre-defined mechanism prevents hostile escalation.' },
    ],
    relatedServices: [
      { name: 'Memorandum of Understanding (MoU)', href: '/services/documentation/business-corporate/mou' },
      { name: 'Merger & Acquisitions', href: '/services/lawyer-services/corporate-services/merger-acquisitions' },
      { name: 'Business Agreement', href: '/services/documentation/legal/business-agreement' },
      { name: 'FDI in Real Estate', href: '/services/property/real-estate/fdi' },
      { name: 'Cross-Border Transactions', href: '/services/lawyer-services/aviation-maritime/international/cross-border-transactions' },
    ],
  },

  nda: {
    title: 'Non-Disclosure Agreement (NDA)',
    description:
      'NDA drafting — unilateral, mutual, employee, vendor, M&A NDAs with confidentiality, non-use, non-circumvention and IP protection.',
    keywords: [
      'NDA agreement',
      'non-disclosure agreement India',
      'mutual NDA',
      'employee NDA',
      'M&A NDA',
      'confidentiality agreement',
    ],
    overview:
      'A Non-Disclosure Agreement (NDA) — also called Confidentiality Agreement — protects sensitive information shared between parties from unauthorized disclosure or use. NDAs are foundational in employment, vendor relationships, business discussions, M&A, technology licensing, JV negotiations, due diligence and any context where confidential information is exchanged.\n\nNDAs come in three primary flavors: (a) Unilateral — one party discloses, other receives, (b) Mutual — both disclose and receive, (c) Multilateral — three or more parties. Modern NDAs combine confidentiality with non-use, non-circumvention, IP non-license, residual knowledge, return / destruction obligations and enforcement mechanisms.\n\nWe draft NDAs across contexts — employee NDAs as part of appointment letters, vendor / contractor NDAs, M&A diligence NDAs, technology licensing NDAs and government contractor NDAs. We also enforce NDAs through legal notice, injunction and damages claims.',
    whyChooseUs: [
      { title: 'Context-Specific Drafting', desc: 'Employment NDA, M&A NDA, vendor NDA — different requirements, different drafting.' },
      { title: 'Enforcement-Ready', desc: 'Drafted with damages quantification, jurisdiction, injunction-friendly language.' },
      { title: 'IP-Aware', desc: 'NDAs preserve IP without inadvertent license; residual knowledge handled.' },
      { title: 'Cross-Border', desc: 'Multi-jurisdiction NDAs with proper governing law and forum selection.' },
    ],
    keyPoints: [
      'Unilateral / Mutual / Multilateral NDA',
      'Employee / contractor confidentiality',
      'M&A / due diligence NDA',
      'Vendor / supplier NDA',
      'Technology / IP licensing NDA',
      'Definition of Confidential Information',
      'Permitted use and disclosure',
      'Term of confidentiality (often outlasting agreement)',
      'Return / destruction obligations',
      'Non-use, non-circumvention, non-solicit',
      'IP ownership and no-license',
      'Residual knowledge',
      'Injunctive relief and damages',
    ],
    process: [
      { title: 'Briefing', desc: 'Capture parties, information categories, purpose, term needs.' },
      { title: 'Drafting', desc: 'Tailored NDA — unilateral / mutual / multilateral as appropriate.' },
      { title: 'Review', desc: 'Internal review; counterparty mark-ups handled.' },
      { title: 'Execution', desc: 'Signed copies exchanged; counter-signed effective date.' },
    ],
    statutoryRefs: [
      { name: 'Indian Contract Act, 1872', desc: 'NDAs are contracts under Section 10.' },
      { name: 'Indian Evidence Act — Section 124-126', desc: 'Privileged communications.' },
      { name: 'Information Technology Act, 2000', desc: 'Electronic NDA validity (Section 10A).' },
      { name: 'Digital Personal Data Protection Act, 2023', desc: 'NDAs covering personal data.' },
      { name: 'Niranjan Shankar Golikari (1967) SC', desc: 'Employee confidentiality during employment is enforceable.' },
    ],
    pitfalls: [
      { title: 'Overbroad Confidentiality', desc: 'Defining everything as confidential dilutes protection. Specific definition with carve-outs (public domain, prior knowledge, third-party rightful) is stronger.' },
      { title: 'Indefinite Term', desc: 'Indefinite confidentiality of routine information is unenforceable. Match term to information sensitivity (3-5 years for routine; longer for trade secrets).' },
      { title: 'Missing Injunction Clause', desc: 'Without explicit injunction language, courts may take longer to grant interim relief.' },
      { title: 'No Damages Quantification', desc: 'Without liquidated damages or measurement methodology, damages calculation is difficult.' },
    ],
    faqs: [
      { q: 'How long is NDA enforceable?', a: 'For the term specified in the NDA — typically 2-5 years for routine commercial NDAs, 5-10+ for trade secrets. Some clauses (like non-use of trade secrets) can be perpetual.' },
      { q: 'Can NDA prevent ex-employee from joining competitor?', a: 'NDA protects confidential information — does not prevent employment. Non-compete clauses (separate provisions) face Section 27 Contract Act limits in India.' },
      { q: 'Are e-signed NDAs valid?', a: 'Yes — under IT Act Section 10A, e-signed NDAs are valid except for excluded categories. Standard practice in modern business.' },
      { q: 'What damages can I claim for NDA breach?', a: 'Actual damages (proven losses), liquidated damages (if specified), injunction (specific performance), account of profits (where breach generated profit). Exemplary damages rare in India.' },
      { q: 'Should NDA be on stamp paper?', a: 'Stamp duty per State — typically nominal (₹100-500). Some States require stamp on agreements above certain value.' },
    ],
    relatedServices: [
      { name: 'Memorandum of Understanding (MoU)', href: '/services/documentation/business-corporate/mou' },
      { name: 'Joint Venture Agreement', href: '/services/documentation/business-corporate/joint-venture-agreement' },
      { name: 'Legal Contract', href: '/services/documentation/legal/legal-contract' },
      { name: 'Offer / Appointment Letter', href: '/services/documentation/business-corporate/offer-appointment-letter' },
    ],
  },

  'auditor-appointment-letter': {
    title: 'Auditor Appointment Letter',
    description:
      'Auditor Appointment Letter drafting — statutory auditor under Section 139 Companies Act, internal auditor, tax auditor with engagement terms and scope.',
    keywords: [
      'auditor appointment letter',
      'statutory auditor appointment',
      'Section 139 Companies Act',
      'internal auditor letter',
      'tax auditor appointment',
      'CA appointment letter',
    ],
    overview:
      'Under Section 139 of the Companies Act, 2013, every company must appoint a statutory auditor at its first AGM for a 5-year term, with appointment ratified at each AGM. Auditor Appointment Letter (issued post Board / shareholder resolution) formally documents the engagement, scope, fees, term, independence, indemnity and reporting obligations.\n\nBeyond statutory auditors, companies engage internal auditors (mandatory under Section 138 for certain companies), tax auditors (under Section 44AB Income Tax Act for businesses crossing turnover thresholds), GST auditors, internal control auditors and sector-specific auditors. Each requires distinct engagement terms.\n\nWe draft auditor appointment letters for all categories — statutory, internal, tax, GST, cost auditors, secretarial auditors. We also handle related compliances — Form ADT-1 for ROC filing, written consent under Section 139(1), and removal / change of auditor.',
    whyChooseUs: [
      { title: 'All Auditor Categories', desc: 'Statutory, internal, tax, GST, cost, secretarial — single template suite.' },
      { title: 'ROC Compliance Bundle', desc: 'Form ADT-1 / ADT-3 filings handled with appointment letter.' },
      { title: 'Independence Compliance', desc: 'Section 144 services list integrated to ensure independence.' },
      { title: 'Engagement Letters', desc: 'CA-side engagement letter with scope, fees, indemnity drafted.' },
    ],
    keyPoints: [
      'Statutory auditor (Section 139 — 5-year term)',
      'Internal auditor (Section 138)',
      'Tax auditor (Section 44AB)',
      'GST auditor (state-specific)',
      'Cost auditor (Section 148)',
      'Secretarial auditor (Section 204)',
      'Board resolution + shareholder ratification',
      'Form ADT-1 ROC filing within 15 days',
      'Independence and prohibited services (Section 144)',
      'Fees and out-of-pocket terms',
      'Indemnity and liability cap',
    ],
    process: [
      { title: 'Auditor Selection', desc: 'Verify ICAI registration, peer review, capacity, sector experience.' },
      { title: 'Written Consent', desc: 'Auditor confirms eligibility and willingness in writing.' },
      { title: 'Board / Shareholder Resolution', desc: 'Pass resolution per Section 139 — first AGM appointment for 5 years.' },
      { title: 'Appointment Letter', desc: 'Issue formal appointment letter with engagement terms.' },
      { title: 'ROC Filing', desc: 'Form ADT-1 within 15 days of AGM.' },
    ],
    statutoryRefs: [
      { name: 'Companies Act, 2013 — Section 139', desc: 'Statutory auditor appointment for 5-year term.' },
      { name: 'Section 138', desc: 'Internal auditor for prescribed companies.' },
      { name: 'Section 144', desc: 'Prohibited non-audit services for statutory auditor.' },
      { name: 'Section 148', desc: 'Cost auditor.' },
      { name: 'Income Tax Act — Section 44AB', desc: 'Tax audit thresholds.' },
    ],
    pitfalls: [
      { title: 'Late ADT-1 Filing', desc: 'ROC filing after 15 days attracts late filing fees and may invalidate appointment in extreme cases.' },
      { title: 'Section 144 Conflict', desc: 'Statutory auditor providing prohibited services (book-keeping, internal audit) breaches independence.' },
      { title: 'Term Mismatch', desc: '5-year term must run from first AGM; mid-term appointments are co-terminus.' },
      { title: 'Vague Scope', desc: 'Loose engagement letter scope creates fee disputes; specific itemization recommended.' },
    ],
    faqs: [
      { q: 'How long is statutory auditor term?', a: 'Five consecutive years from first AGM. Reappointment for another 5 years. After two terms (10 years total for individual auditor / 10 years for firm), mandatory rotation under Section 139(2).' },
      { q: 'Can a company change auditor mid-term?', a: 'Yes — but requires special resolution and Central Government approval (Section 140) for removal before term. Or auditor resigning of own volition.' },
      { q: 'Is internal auditor mandatory?', a: 'Yes under Section 138 for: (a) listed companies, (b) public companies above thresholds, (c) private companies above turnover / borrowing thresholds.' },
      { q: 'What is ADT-1?', a: 'ROC form for filing notice of auditor appointment — to be filed within 15 days of AGM that appointed / re-appointed the auditor.' },
      { q: 'Can same firm be statutory + tax auditor?', a: 'Generally yes, but specific independence considerations apply. Section 144 prohibits certain non-audit services for statutory auditor.' },
    ],
    relatedServices: [
      { name: 'Appointment of Company Secretary', href: '/services/documentation/business-corporate/company-secretary-appointment' },
      { name: 'IPO Listing & Compliances', href: '/services/lawyer-services/corporate-services/ipo-listing' },
      { name: 'Insolvency & Bankruptcy', href: '/services/lawyer-services/corporate-services/insolvency-bankruptcy' },
    ],
  },

  'company-secretary-appointment': {
    title: 'Appointment of Company Secretary',
    description:
      'Company Secretary appointment under Section 203 Companies Act, 2013 — KMP designation, ROC filings, role and statutory compliance for prescribed companies.',
    keywords: [
      'company secretary appointment',
      'CS appointment Section 203',
      'KMP appointment',
      'company secretary letter',
      'ROC CS filing',
      'CS Whole Time',
    ],
    overview:
      'Under Section 203 of the Companies Act, 2013, certain companies must appoint a whole-time Company Secretary (CS) as Key Managerial Personnel (KMP). Mandatory for: (a) all listed companies, (b) public companies with paid-up share capital ₹10 crore or more, (c) private companies with paid-up capital ₹10 crore or more (since 2020 amendment).\n\nThe Company Secretary plays a central role — corporate governance, board / shareholder meetings, statutory filings, secretarial audits, regulatory liaison, compliance officer for SEBI / RBI matters and minute-keeping. The CS is a member of the Institute of Company Secretaries of India (ICSI) holding Certificate of Practice or in employment as designated CS.\n\nWe draft CS appointment letters, board / shareholder resolutions, ROC Form DIR-12 / MR-1 filings, and ongoing CS engagement documentation. We also support compliance officers in SEBI-listed companies and CS firms providing retainer services.',
    whyChooseUs: [
      { title: 'Section 203 Compliance', desc: 'CS appointment mapped to Section 203 thresholds and KMP framework.' },
      { title: 'ROC Filings Bundle', desc: 'DIR-12 / MR-1 filed within 30 days of appointment.' },
      { title: 'Compliance Officer Mapping', desc: 'For listed companies, CS as compliance officer under LODR.' },
      { title: 'Retainer CS Documentation', desc: 'For non-mandatory companies — flexible CS retainer arrangements.' },
    ],
    keyPoints: [
      'Section 203 mandatory CS appointment',
      'KMP designation under Section 203',
      'CS as Compliance Officer (Listed companies — LODR)',
      'CS roles — secretarial audit, ROC compliance, governance',
      'Board / shareholder resolutions',
      'Form DIR-12 (ROC) within 30 days',
      'Form MR-1 (ROC) for KMP appointment',
      'CS-employee vs CS-retainer arrangement',
      'Compensation and benefits',
      'Removal and ROC filings on cessation',
    ],
    process: [
      { title: 'Eligibility Check', desc: 'Verify Section 203 applicability based on company size / category.' },
      { title: 'CS Identification', desc: 'ICSI member with appropriate experience; reference checks.' },
      { title: 'Board Resolution', desc: 'Pass resolution appointing CS as KMP.' },
      { title: 'Appointment Letter', desc: 'Comprehensive letter — role, KRAs, compensation, term.' },
      { title: 'ROC Filings', desc: 'DIR-12 + MR-1 within 30 days of appointment.' },
    ],
    statutoryRefs: [
      { name: 'Companies Act, 2013 — Section 203', desc: 'Mandatory KMP including CS for prescribed companies.' },
      { name: 'Section 205', desc: 'Functions and duties of Company Secretary.' },
      { name: 'Companies (Appointment & Remuneration) Rules, 2014', desc: 'Procedural rules.' },
      { name: 'SEBI LODR Regulations, 2015', desc: 'CS as Compliance Officer for listed companies.' },
      { name: 'Company Secretaries Act, 1980', desc: 'ICSI framework and qualification.' },
    ],
    pitfalls: [
      { title: 'Late ROC Filing', desc: 'DIR-12 / MR-1 beyond 30 days attracts late fees; repeated lapses invite ROC scrutiny.' },
      { title: 'CS Without ICSI Membership', desc: 'CS appointed without ICSI membership doesn\'t satisfy Section 205 — appointment is invalid.' },
      { title: 'Threshold Miss', desc: 'Companies crossing ₹10 crore paid-up capital but not appointing CS face Section 203 penalty.' },
      { title: 'Vague KRAs', desc: 'Without measurable KRAs, performance disputes during exit are common.' },
    ],
    faqs: [
      { q: 'Which companies must appoint CS?', a: 'All listed companies, public companies with paid-up capital ₹10 crore+, and private companies with paid-up capital ₹10 crore+ (since 2020 amendment).' },
      { q: 'Is the CS an employee or independent?', a: 'KMP CS under Section 203 is a whole-time employee. For non-mandatory companies, CS can be retained as employee, retainer or external consultant.' },
      { q: 'Can one person be CFO + CS?', a: 'No — under Section 203, CS and CFO are separate KMP positions; no person can hold both simultaneously in a Section 203 company.' },
      { q: 'What ROC filings are required?', a: 'Form DIR-12 (notice of appointment of director / KMP) + Form MR-1 (return of appointment of KMP) within 30 days of appointment.' },
      { q: 'What is the CS\'s annual compensation?', a: 'Highly variable by company size and listed status. Listed company CS — ₹15-50 lakh+ annual. Mid-size unlisted — ₹8-25 lakh. Retainer CS — ₹50,000-2 lakh per month.' },
    ],
    relatedServices: [
      { name: 'Auditor Appointment Letter', href: '/services/documentation/business-corporate/auditor-appointment-letter' },
      { name: 'IPO Listing & Compliances', href: '/services/lawyer-services/corporate-services/ipo-listing' },
      { name: 'Securities Law & Compliances', href: '/services/lawyer-services/corporate-services/securities-law' },
    ],
  },
};
