import type { ServiceContent } from '@/components/leaf-service-page';

export const documentationLegalServices: Record<string, ServiceContent> = {
  'legal-notice': {
    title: 'Legal Notice',
    description:
      'Lawyer-drafted Legal Notices for civil, criminal, matrimonial, contractual, employment and consumer disputes — court-defensible, statute-mapped and dispatched with proof.',
    keywords: [
      'legal notice India',
      'legal notice format',
      'demand notice',
      'legal notice lawyer',
      'cease and desist notice',
      'legal notice cheque bounce',
      'legal notice reply',
    ],
    overview:
      'A Legal Notice is a formal written demand sent through an advocate setting out the sender\'s grievance, the legal basis, and the remedy sought before initiating litigation. While a Legal Notice is not always statutorily mandatory, it is procedurally required in many contexts — Section 138 of the Negotiable Instruments Act (cheque bounce), Section 80 CPC (suits against government), Section 12 of Consumer Protection Act, and many sector-specific laws.\n\nA well-drafted Legal Notice often resolves disputes without litigation. It also creates a contemporaneous record of the dispute and the demand — invaluable in subsequent court / arbitration proceedings. A poorly drafted notice (vague allegations, wrong recipient, missing prayer, weak service proof) routinely backfires and weakens the underlying case.\n\nWe draft and dispatch Legal Notices across categories — cheque bounce, contractual breach, debt recovery, matrimonial cruelty, employment dues, consumer complaints, defamation, IP infringement, real estate possession and Section 80 CPC. We also reply to Legal Notices on the receiving side.',
    whyChooseUs: [
      { title: 'Statute-Mapped Drafting', desc: 'Every notice cites applicable provisions — strengthens enforcement and pre-empts technical defences.' },
      { title: 'Service with Proof', desc: 'Registered post AD + courier + email; dispatch and delivery proof preserved for court.' },
      { title: 'Court-Defensible', desc: 'Drafted to survive cross-examination and form the foundation of subsequent litigation.' },
      { title: 'Receiver-Side Replies', desc: 'On the receiving end? We draft replies that protect rights and rebut allegations.' },
    ],
    keyPoints: [
      'Cheque Bounce notice (Section 138 NI Act) within 30 days',
      'Contractual breach and recovery demand',
      'Matrimonial cruelty / desertion notice',
      'Employment dues, gratuity, salary arrears',
      'Consumer Protection Act notice (Section 12)',
      'Defamation notice (civil / criminal)',
      'IP infringement (trademark, copyright, patent)',
      'Cease and desist notices',
      'Section 80 CPC notice (suits against government)',
      'Real estate possession / specific performance demand',
    ],
    process: [
      { title: 'Briefing', desc: 'Detailed briefing on facts, documents, intended outcome and recipient details.' },
      { title: 'Drafting', desc: 'Statute-mapped notice with chronology, allegations, demand, prayer and time-frame for compliance.' },
      { title: 'Review & Sign-off', desc: 'Client review and adjustments; advocate sign-off.' },
      { title: 'Dispatch', desc: 'Send via Registered Post AD + courier + email; preserve dispatch proof and delivery receipts.' },
      { title: 'Follow-up', desc: 'Track response; advise on next steps — settlement, mediation or litigation.' },
    ],
    statutoryRefs: [
      { name: 'Negotiable Instruments Act, 1881 — Section 138', desc: '30-day notice mandatory for cheque-bounce prosecution; complaint within 30 days of failure to pay.' },
      { name: 'CPC, 1908 — Section 80', desc: 'Two-month notice mandatory before suing Government / public officer for acts in official capacity.' },
      { name: 'Consumer Protection Act, 2019 — Section 12', desc: 'Notice strongly recommended before consumer complaint.' },
      { name: 'Contract Act, 1872; Specific Relief Act, 1963', desc: 'Underlying basis for contractual demands.' },
    ],
    pitfalls: [
      { title: 'Vague Allegations', desc: 'Notices with vague language ("you have caused harm") are routinely cured by recipients without consequence.' },
      { title: 'Missing Statutory Reference', desc: 'A Section 138 NI Act notice that doesn\'t cite Section 138 weakens the prosecution case.' },
      { title: 'Wrong Recipient', desc: 'Notice to wrong person (former director, sister-concern, agent) misses the target and may be inadmissible.' },
      { title: 'No Service Proof', desc: 'Bare hand delivery without postal AD / courier proof creates evidence problems at trial.' },
    ],
    faqs: [
      { q: 'Is a Legal Notice mandatory before filing a case?', a: 'Mandatory in some categories — Section 138 NI Act (cheque bounce), Section 80 CPC (suits vs Government), specific consumer protection contexts. In other matters it is optional but strongly recommended for evidence and settlement potential.' },
      { q: 'What is the typical response time given?', a: 'Typically 7-30 days depending on the matter — 15 days for cheque bounce (statutory), 7-15 days for contractual, 30 days for complex disputes.' },
      { q: 'How much does a Legal Notice cost?', a: 'Typically ₹1,500–₹15,000 depending on complexity, urgency and lawyer experience. Specialized notices (IP infringement, securities, regulatory) cost more.' },
      { q: 'What if no response is received?', a: 'Proceed with the threatened action — civil suit, criminal complaint, arbitration, regulatory complaint as appropriate. The notice serves as proof of demand and limitation start.' },
      { q: 'Can I send a Legal Notice myself without a lawyer?', a: 'Yes — but lawyer-drafted notices are markedly more effective. Recipients take advocate-issued notices seriously; self-drafted notices are often ignored.' },
      { q: 'Can I reply to a Legal Notice received?', a: 'Yes — we strongly recommend a lawyer-drafted reply. A reply rebuts allegations, sets out your position and prevents adverse inferences.' },
    ],
    relatedServices: [
      { name: 'Affidavit', href: '/services/documentation/legal/affidavit' },
      { name: 'Cheque Bounce — NI Act 138/142', href: '/services/lawyer-services/criminal-law/cheque-bounce-ni-act' },
      { name: 'Legal Contract', href: '/services/documentation/legal/legal-contract' },
      { name: 'Notary, Stamp & Attestation', href: '/services/documentation/legal/notary-stamp-attestation' },
    ],
  },

  'affidavit': {
    title: 'Affidavit',
    description:
      'Affidavit drafting and notarization for court proceedings, identity, address, name change, lost documents and statutory declarations — properly worded, stamped and admissible.',
    keywords: [
      'affidavit drafting',
      'affidavit format',
      'sworn affidavit',
      'identity affidavit',
      'name change affidavit',
      'lost document affidavit',
      'court affidavit India',
    ],
    overview:
      'An Affidavit is a sworn written statement made on oath before an authorized person — Notary Public, Magistrate, Oath Commissioner — used as evidence in court proceedings, government applications, statutory declarations and administrative matters. Governed by Order XIX of CPC and Sections 191–195 IPC, false statements in affidavits attract perjury liability.\n\nAffidavits are required for nearly every facet of legal and administrative life — court pleadings, identity proof, address change, name change, lost document indemnity, gap year explanations, joint property declarations, surety bonds, gift / acceptance affidavits, and statutory declarations under various Acts.\n\nWe draft, stamp, notarize and serve affidavits across India. We also handle apostilled / Embassy-attested affidavits for overseas use, and group / corporate affidavits for institutional needs.',
    whyChooseUs: [
      { title: 'Court-Ready Drafting', desc: 'Affidavits drafted per Order XIX CPC for direct use in pleadings.' },
      { title: 'Notary & Stamp Coordination', desc: 'Stamp paper procurement and Notary Public attestation handled.' },
      { title: 'Multi-Language', desc: 'Affidavits drafted in English plus regional languages with certified translations.' },
      { title: 'Apostille Support', desc: 'For overseas use — apostille / Embassy attestation coordinated.' },
    ],
    keyPoints: [
      'Court pleadings affidavits',
      'Identity / address proof',
      'Name change affidavit + Gazette publication',
      'Lost document indemnity affidavit',
      'Joint property affidavit',
      'Income / non-income affidavit',
      'Education gap-year affidavit',
      'Surety / guarantee affidavits',
      'Statutory declarations',
      'Apostilled / Embassy-attested affidavits',
    ],
    process: [
      { title: 'Briefing', desc: 'Capture facts, purpose, deponent details and authority requirements.' },
      { title: 'Drafting', desc: 'Tailored affidavit with proper format, paragraphing and verification.' },
      { title: 'Stamp Paper', desc: 'Procure non-judicial stamp paper of appropriate value (typically ₹10-100).' },
      { title: 'Execution & Notarization', desc: 'Deponent signs before Notary Public who attests with seal and signature.' },
      { title: 'Delivery', desc: 'Original affidavit delivered; soft copy retained.' },
    ],
    statutoryRefs: [
      { name: 'Code of Civil Procedure, 1908 — Order XIX', desc: 'Affidavits in court proceedings.' },
      { name: 'Indian Penal Code — Sections 191-195', desc: 'False statement in affidavit attracts perjury liability up to 7 years imprisonment.' },
      { name: 'Notaries Act, 1952', desc: 'Authority of Notaries Public to administer oath and attest affidavits.' },
      { name: 'Indian Stamp Act / State Schedules', desc: 'Stamp duty on affidavits.' },
    ],
    pitfalls: [
      { title: 'Wrong Stamp Value', desc: 'Insufficient stamp value renders affidavit inadmissible until corrected with penalty.' },
      { title: 'Missing Verification Clause', desc: 'Affidavit without proper verification clause (which paragraphs are within knowledge / belief) is procedurally defective.' },
      { title: 'False Statements', desc: 'Untrue affidavits attract perjury — clients should swear only what they personally know to be true.' },
      { title: 'Unauthorized Notary', desc: 'Notarization by unauthorized person (gazetted officer who is not Notary) is invalid.' },
    ],
    faqs: [
      { q: 'How much stamp duty on affidavit?', a: 'Varies by State — typically ₹10-100 for routine affidavits. Court affidavits often have specific schedules. For high-value affirmations (gift, settlement), higher duty may apply.' },
      { q: 'Who can attest an affidavit?', a: 'Notary Public, Magistrate, Oath Commissioner appointed by court, and certain consular officers (for overseas use).' },
      { q: 'How long is an affidavit valid?', a: 'Affidavit is a snapshot of facts as of date of swearing — validity depends on whether facts continue to be true. Some authorities require recent affidavits (3-6 months).' },
      { q: 'Can I sign affidavit electronically?', a: 'Generally no for traditional affidavits — physical signature before Notary is required. Some courts now accept e-affidavits in specific contexts (Supreme Court e-filing).' },
      { q: 'What if facts in affidavit turn out to be false?', a: 'Perjury proceedings can be initiated under Sections 193-196 IPC. Filing false affidavit in court can also lead to contempt.' },
    ],
    relatedServices: [
      { name: 'Notary, Stamp & Attestation', href: '/services/documentation/legal/notary-stamp-attestation' },
      { name: 'Apostille (MEA / HRD)', href: '/services/documentation/legal/apostille' },
      { name: 'Legal Notice', href: '/services/documentation/legal/legal-notice' },
    ],
  },

  'notary-stamp-attestation': {
    title: 'Notary, Stamp & Attestation',
    description:
      'Notarization, stamp paper procurement, attestation and certification of documents — for legal, regulatory, banking and overseas use.',
    keywords: [
      'notary public',
      'document attestation',
      'stamp paper',
      'notarize agreement',
      'attestation services India',
      'notarial certificate',
    ],
    overview:
      'Notarization, stamping and attestation are foundational legal services that underpin almost every transaction. Notary Publics under the Notaries Act, 1952 attest documents, administer oaths, take affidavits, certify true copies and protest negotiable instruments. Stamping under State Stamp Acts is mandatory for many documents to be legally enforceable. Attestation by gazetted officers, magistrates, banks or other authorities is required for various administrative purposes.\n\nMis-stamped or improperly attested documents are routinely rejected by courts, government offices, banks and overseas embassies. We handle the full range — Notary Public attestation, e-stamp paper procurement, stamp deficiency cure, gazetted officer attestation coordination, and consular attestation for overseas use.\n\nOur services span individuals (affidavits, declarations, agreements), corporates (board resolutions, agreements, certificates) and institutions (large-volume attestations).',
    whyChooseUs: [
      { title: 'End-to-End Solution', desc: 'Drafting + stamping + notarization + delivery — single workflow.' },
      { title: 'E-Stamp Capability', desc: 'SHCIL e-stamp procurement online without queue waste.' },
      { title: 'Pan-India Coverage', desc: 'Notary attestation across major Indian cities.' },
      { title: 'Urgent Track', desc: 'Same-day notarization for time-critical documents.' },
    ],
    keyPoints: [
      'Notary Public attestation',
      'Affidavit notarization',
      'Agreement notarization',
      'True copy attestation',
      'E-stamp paper procurement (SHCIL)',
      'Stamp deficiency cure under Section 35',
      'Gazetted officer attestation',
      'Magistrate attestation',
      'Bank manager attestation (specific contexts)',
      'Consular / Embassy attestation referrals',
    ],
    process: [
      { title: 'Document Review', desc: 'Confirm document, applicable stamp duty and attestation requirements.' },
      { title: 'Stamping', desc: 'Procure e-stamp paper of correct value online.' },
      { title: 'Execution', desc: 'Parties sign before Notary Public.' },
      { title: 'Notarization', desc: 'Notary attests with seal, signature, register number and date.' },
      { title: 'Delivery', desc: 'Original delivered with copies as needed.' },
    ],
    statutoryRefs: [
      { name: 'Notaries Act, 1952', desc: 'Authority and powers of Notary Public.' },
      { name: 'Indian Stamp Act, 1899 / State Acts', desc: 'Stamp duty on instruments.' },
      { name: 'Stamp Act Section 35', desc: 'Bar on admissibility of insufficiently stamped documents.' },
      { name: 'Various Statutes Requiring Attestation', desc: 'CPC, Evidence Act, Companies Act and others.' },
    ],
    pitfalls: [
      { title: 'Wrong Stamp Value', desc: 'Document stamped below required value is inadmissible until cured with penalty.' },
      { title: 'Missing Notary Seal', desc: 'Attestation without proper Notary seal and register entry is invalid.' },
      { title: 'Non-Notary Attestation', desc: 'Attestation by gazetted officer where Notary attestation is required does not cure.' },
      { title: 'Outdated Stamp Paper', desc: 'In some States, unused stamp paper has limited validity (typically 6 months).' },
    ],
    faqs: [
      { q: 'What is the difference between Notary and Magistrate attestation?', a: 'Both are valid attestations but for different purposes. Notary Public attests under Notaries Act; Magistrate attests in judicial / administrative capacity. Some specific documents (like marriage certificate attestation) require Magistrate; others accept Notary.' },
      { q: 'Is e-stamping recognized?', a: 'Yes — e-stamp papers via SHCIL (Stock Holding Corporation of India Ltd) are statutorily recognized in most States as equivalent to physical stamp paper.' },
      { q: 'How much does notarization cost?', a: 'Notary fee is statutorily prescribed (typically ₹35-100 per document). Service / facilitation fees additional. Total cost typically ₹500-2,000 including stamp paper for routine documents.' },
      { q: 'Can a Notary refuse to attest?', a: 'Yes — if Notary believes the document is false, illegal, or doesn\'t meet legal standards. Notary doesn\'t verify factual truth of contents but verifies parties\' identity and willingness.' },
      { q: 'Is online notarization available?', a: 'Limited online notarization is being introduced in some States. For most purposes, physical signing before Notary is still standard.' },
    ],
    relatedServices: [
      { name: 'Affidavit', href: '/services/documentation/legal/affidavit' },
      { name: 'Apostille (MEA / HRD)', href: '/services/documentation/legal/apostille' },
      { name: 'Legal Contract', href: '/services/documentation/legal/legal-contract' },
    ],
  },

  'apostille': {
    title: 'Apostille (MEA / HRD)',
    description:
      'Apostille and HRD attestation through Ministry of External Affairs (MEA) for overseas use of Indian documents — birth, marriage, education, commercial.',
    keywords: [
      'apostille India',
      'MEA apostille',
      'HRD attestation',
      'Hague Convention apostille',
      'document apostille for visa',
      'apostille birth certificate',
    ],
    overview:
      'Apostille is the international authentication procedure under the Hague Convention of 1961 by which a document issued in one member country is recognized as legally valid in another member country without further consular attestation. India has been a member since 2005. The Ministry of External Affairs (MEA) issues apostille seals on Indian documents for use in over 100 Hague-Convention member countries.\n\nFor non-Hague countries (UAE, China, Malaysia, etc.), Embassy / Consulate attestation is required after MEA attestation. Educational documents typically also require HRD (State Education Department) attestation before MEA apostille / attestation.\n\nWe handle the complete apostille / attestation chain — Notary attestation, State Home Department / HRD attestation, MEA apostille / attestation, Embassy attestation — for personal, educational and commercial documents. Common use cases: visa applications, foreign education, foreign employment, immigration, family unification, business expansion abroad.',
    whyChooseUs: [
      { title: 'End-to-End Chain', desc: 'Notary → State HRD / Home → MEA → Embassy — coordinated as single workflow.' },
      { title: 'Hague & Non-Hague Countries', desc: 'Apostille for Hague members; full attestation chain for others.' },
      { title: 'All Document Types', desc: 'Personal, educational, commercial — including degrees, marriage certificates, birth certificates, PCC, MoA / AoA.' },
      { title: 'Urgent Track', desc: 'Time-sensitive apostille for visa / job-joining deadlines.' },
    ],
    keyPoints: [
      'MEA apostille for Hague Convention countries',
      'MEA attestation for non-Hague countries',
      'State HRD attestation for educational documents',
      'State Home Department attestation for personal documents',
      'Chamber of Commerce attestation for commercial documents',
      'Notary attestation as foundation',
      'Embassy / Consulate attestation post-MEA',
      'Document translation where required',
      'Apostille for digitally signed documents',
      'Bulk apostille for institutional needs',
    ],
    process: [
      { title: 'Document Verification', desc: 'Verify document type, destination country (Hague / non-Hague) and required chain.' },
      { title: 'Foundation Attestation', desc: 'Notary, then State HRD (educational) or Home Department (personal) attestation.' },
      { title: 'MEA Apostille / Attestation', desc: 'Submit to MEA via authorized agent; receive apostille seal or attestation.' },
      { title: 'Embassy Attestation (non-Hague)', desc: 'For non-Hague countries, additional Embassy attestation in destination country language.' },
      { title: 'Delivery', desc: 'Original + scanned copy with full attestation chain.' },
    ],
    statutoryRefs: [
      { name: 'Hague Convention, 1961', desc: 'International framework for apostille recognition.' },
      { name: 'MEA Notification 2012', desc: 'Outsourcing of apostille / attestation to authorized agents.' },
      { name: 'State Education / HRD Departments', desc: 'Pre-MEA attestation for educational documents.' },
    ],
    pitfalls: [
      { title: 'Skipping HRD Attestation', desc: 'Educational documents going directly to MEA without HRD are rejected.' },
      { title: 'Wrong Country Mapping', desc: 'Non-Hague country requires Embassy attestation; many applicants miss this and face visa rejection.' },
      { title: 'Outdated Original', desc: 'Apostille of expired / superseded original is invalid; ensure original is current.' },
      { title: 'Translation Issues', desc: 'Some destination countries require translation of original into local language before / after apostille.' },
    ],
    faqs: [
      { q: 'What is the difference between Apostille and Attestation?', a: 'Apostille is for Hague Convention member countries (~100+ countries) — single MEA seal suffices. Attestation is for non-Hague countries — requires MEA + Embassy attestation chain.' },
      { q: 'How long does apostille take?', a: 'Typically 4-7 working days for foundation attestation + MEA apostille. Urgent track in 2-3 days. Embassy attestation adds 5-15 working days based on Embassy.' },
      { q: 'Which countries require Embassy attestation?', a: 'Non-Hague countries — UAE, Saudi Arabia, Qatar, Kuwait, Oman, Egypt, Jordan, Vietnam, China (Hong Kong / Macau yes; mainland selectively), and a few others.' },
      { q: 'How much does apostille cost?', a: 'MEA apostille fee is ₹50-100 per document. Total cost (Notary + HRD + MEA + service) typically ₹1,500-5,000 per document depending on type and urgency.' },
      { q: 'Can apostille be reversed?', a: 'No — apostille is permanent. If the underlying document is amended / cancelled, fresh apostille on new document is required.' },
    ],
    relatedServices: [
      { name: 'Notary, Stamp & Attestation', href: '/services/documentation/legal/notary-stamp-attestation' },
      { name: 'Affidavit', href: '/services/documentation/legal/affidavit' },
      { name: 'Marriage Registration', href: '/services/documentation/legal/marriage-registration' },
    ],
  },

  'marriage-registration': {
    title: 'Marriage Registration',
    description:
      'Marriage Registration under Hindu Marriage Act, Special Marriage Act and personal laws — Marriage Certificate procurement for visa, name change, banking and inheritance.',
    keywords: [
      'marriage registration India',
      'marriage certificate',
      'Hindu Marriage Act registration',
      'Special Marriage Act',
      'Tatkal marriage certificate',
      'court marriage registration',
    ],
    overview:
      'Marriage Registration is the formal recording of marriage by a competent authority — Sub-Registrar of Marriages, Marriage Officer, or Registrar under State rules — and issuance of a Marriage Certificate. While registration was traditionally optional, several Supreme Court rulings (notably Seema v. Ashwani Kumar, 2006) have made registration effectively mandatory for legal recognition.\n\nIndia has multiple marriage frameworks: (a) Hindu Marriage Act, 1955 for Hindus, Buddhists, Jains, Sikhs; (b) Special Marriage Act, 1954 for inter-faith / civil marriages; (c) Christian Marriage Act, 1872; (d) Parsi Marriage and Divorce Act, 1936; (e) Muslim Personal Law (registered through state-specific procedures).\n\nWe handle marriage registration end-to-end — couple counselling on applicable Act, application drafting, Notice procedure (under SMA), witness coordination, sub-registrar appearance and certificate procurement. Tatkal (urgent) registration available in many States.',
    whyChooseUs: [
      { title: 'All Acts Coverage', desc: 'HMA, SMA, Christian, Parsi and Muslim marriage registration.' },
      { title: 'Inter-faith / NRI Marriages', desc: 'Special Marriage Act registration for inter-faith and NRI couples.' },
      { title: 'Tatkal Registration', desc: 'Same-day to 7-day registration in States offering Tatkal.' },
      { title: 'Visa-Ready Certificates', desc: 'Apostille / attestation coordinated for overseas use.' },
    ],
    keyPoints: [
      'Hindu Marriage Act, 1955 registration',
      'Special Marriage Act, 1954 — inter-faith and civil marriages',
      'Christian Marriage Act, 1872',
      'Tatkal / urgent marriage certificate',
      '30-day notice under SMA Section 5',
      'Witness coordination (3 witnesses)',
      'Sub-Registrar / Marriage Officer appearance',
      'Marriage certificate procurement',
      'Apostille / Embassy attestation for visa',
      'Inter-State / overseas marriage recognition',
    ],
    process: [
      { title: 'Act Selection', desc: 'Determine applicable Act based on religion / inter-faith status.' },
      { title: 'Application & Notice', desc: 'File application; under SMA, 30-day public notice with objection window.' },
      { title: 'Witness & Documentation', desc: 'Compile 3 witnesses, IDs, photographs, age proof, address proof.' },
      { title: 'Marriage Officer Appearance', desc: 'Couple + witnesses appear before Marriage Officer / Sub-Registrar; oaths administered.' },
      { title: 'Certificate Issuance', desc: 'Marriage Certificate issued; copies delivered.' },
    ],
    documents: [
      'Age proof (10th certificate / passport / birth certificate)',
      'Address proof (Aadhaar / passport)',
      'Photographs (passport size)',
      'Marriage invitation card / wedding photographs (HMA)',
      'Affidavits of single status / divorce decree (if applicable)',
      'Three witnesses with IDs',
      'Inter-faith conversion certificate (if applicable)',
    ],
    statutoryRefs: [
      { name: 'Hindu Marriage Act, 1955 — Section 8', desc: 'Marriage registration provisions.' },
      { name: 'Special Marriage Act, 1954', desc: 'Inter-faith and civil marriages with 30-day notice.' },
      { name: 'Seema v. Ashwani Kumar (2006) Supreme Court', desc: 'Effectively mandates marriage registration.' },
      { name: 'State Marriage Rules', desc: 'Each State has procedural rules — Tatkal, fees, online filing.' },
    ],
    pitfalls: [
      { title: 'Choosing Wrong Act', desc: 'Inter-faith couples mistakenly registering under HMA face annulment risks; SMA is correct path.' },
      { title: 'Witness Impostors', desc: 'Witnesses must be genuine known persons of the couple; fake witnesses invite challenge.' },
      { title: 'Overseas Marriage Confusion', desc: 'Marriages abroad need separate registration / recognition in India for legal effect — under FMRA, Section 17 of HMA or Special Marriage Act.' },
      { title: 'Skipping Apostille for Visa', desc: 'For visa purposes, marriage certificate must be apostilled — many couples discover this at visa rejection.' },
    ],
    faqs: [
      { q: 'Is marriage registration mandatory?', a: 'Per Supreme Court directions, registration is effectively mandatory in all States. Without registration, marriage may face evidentiary challenges in inheritance, visa, name change and banking matters.' },
      { q: 'What is Tatkal marriage registration?', a: 'Same-day to 7-day urgent registration available in many States (Delhi Tatkal, Karnataka Tatkal). Higher fee than regular registration but useful for visa / job deadlines.' },
      { q: 'How long does normal registration take?', a: 'HMA registration: 1-15 days post-application. SMA: 30 days notice + actual registration after objection window.' },
      { q: 'Can NRI couples register under SMA?', a: 'Yes — at least one party should be in India for the duration of the notice + registration. Procedure same as resident SMA.' },
      { q: 'What if my marriage is overseas?', a: 'Foreign marriages can be registered in India under Foreign Marriage Act, 1969 (if both parties Indian) or recognized under Section 17 HMA / SMA.' },
    ],
    relatedServices: [
      { name: 'Apostille (MEA / HRD)', href: '/services/documentation/legal/apostille' },
      { name: 'Mutual Divorce', href: '/services/lawyer-services/family-law/mutual-divorce' },
      { name: 'Affidavit', href: '/services/documentation/legal/affidavit' },
    ],
  },

  'rent-lease-agreement': {
    title: 'Rent / Lease Agreement',
    description:
      'Drafting and registration of Rent and Lease Agreements — 11-month, long-term, residential, commercial — with security-deposit, lock-in, GST and TDS clauses.',
    keywords: [
      'rent agreement drafting',
      'lease agreement India',
      '11 month rent agreement',
      'commercial lease agreement',
      'rental contract',
      'tenancy agreement',
      'rent agreement format',
    ],
    overview:
      'Rent and Lease Agreements govern the most common form of property arrangement — short-term residential rentals, long-term residential leases, commercial / retail leases, industrial leases and warehouse arrangements. Each has distinct stamp duty, registration, GST, TDS and substantive law implications.\n\n11-month rental agreements are the most common in residential context — they avoid mandatory registration under Section 17(1)(d) of Registration Act and have lower stamp duty. Long-term leases (over 12 months) require compulsory registration. Commercial leases attract GST (18%) on the landlord; rents above ₹2.4 lakh/year attract TDS at 10% (Section 194-I).\n\nWe draft tenant-protective and landlord-protective agreements depending on which side we represent. Clauses include rent, security deposit, lock-in, escalation, maintenance, repairs, alterations, sub-letting, termination, dispute resolution and exit protocols.',
    whyChooseUs: [
      { title: 'Tenant or Landlord Side', desc: 'Drafting tilts where it should — based on whom we represent.' },
      { title: 'GST / TDS Mapping', desc: 'Tax implications mapped and allocated cleanly.' },
      { title: 'E-Stamp & Registration', desc: 'For long-term leases, full registration coordinated.' },
      { title: 'Termination Strategy', desc: 'Exit clauses, deposit return and dispute resolution drafted to prevent disputes.' },
    ],
    keyPoints: [
      '11-month rental agreement (no mandatory registration)',
      'Long-term lease (>12 months) — compulsory registration',
      'Residential / commercial / industrial / warehouse',
      'Security deposit and forfeiture terms',
      'Lock-in and exit notice',
      'Rent escalation (CPI / fixed %)',
      'Permitted use, alterations, sub-letting',
      'Maintenance allocation (paint, plumbing, AC)',
      'GST applicability and reverse charge',
      'TDS Section 194-I compliance',
      'Society / RWA NOC coordination',
    ],
    process: [
      { title: 'Term Sheet', desc: 'Capture rent, deposit, term, escalation, maintenance, lock-in, exit.' },
      { title: 'Drafting', desc: 'Tailored agreement with schedule, inventory, dispute resolution.' },
      { title: 'Stamping', desc: 'E-stamp procurement at appropriate value (varies by State and term).' },
      { title: 'Registration (if >12 months)', desc: 'Sub-registrar registration with both parties + 2 witnesses.' },
      { title: 'Possession Handover', desc: 'Inventory, key handover, deposit receipt, society intimation.' },
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882 — Sections 105-117', desc: 'Lease provisions.' },
      { name: 'Registration Act, 1908 — Section 17(1)(d)', desc: 'Mandatory registration for leases > 12 months.' },
      { name: 'Indian Stamp Act / State Schedules', desc: 'Stamp duty varies by lease term.' },
      { name: 'Income Tax Act — Section 194-I', desc: 'TDS @ 10% on rent above ₹2.4 lakh/year.' },
      { name: 'CGST Act, 2017', desc: 'GST 18% on commercial rent above threshold.' },
    ],
    pitfalls: [
      { title: 'Repeated 11-Month Renewals', desc: 'Continuous 11-month renewals to evade registration are recharacterized by courts as continuous tenancy.' },
      { title: 'No Termination Notice Period', desc: 'Without proper termination notice, vacating becomes contentious.' },
      { title: 'Vague Maintenance', desc: '"Reasonable maintenance" is subjective; specify each category.' },
      { title: 'Security Deposit Forfeiture', desc: 'Deposit is refundable; forfeiture clauses are routinely struck down by courts.' },
    ],
    faqs: [
      { q: 'Why are 11-month rent agreements common?', a: 'They fall outside Section 17(1)(d) compulsory registration and attract lower stamp duty. However, repeated renewals are noted by courts.' },
      { q: 'Do I need to register a 1-year+ lease?', a: 'Yes — under Section 17(1)(d), leases over 12 months OR reserving annual rent are compulsorily registrable.' },
      { q: 'Is GST applicable on residential rent?', a: 'Residential rent for residential use — exempt. Residential to registered person for business use — RCM @ 18%. Commercial / industrial — 18% GST.' },
      { q: 'Can security deposit be more than 6 months rent?', a: 'No statutory cap, but Model Tenancy Act (where adopted) caps at 2 months residential / 6 months commercial. Regulations vary by State.' },
      { q: 'Can I evict tenant before agreement ends?', a: 'Only as per agreement (default, breach) or under Rent Control Acts (in States that have them). Random eviction is not permitted.' },
    ],
    relatedServices: [
      { name: 'Lease Deed Registration', href: '/services/property/registration/lease-deed' },
      { name: 'Real Estate Agreement', href: '/services/documentation/legal/real-estate-agreement' },
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
    ],
  },

  'legal-contract': {
    title: 'Legal Contract',
    description:
      'Drafting, review and negotiation of contracts under Indian Contract Act, 1872 — service agreements, vendor contracts, consulting agreements, supply contracts.',
    keywords: [
      'contract drafting India',
      'legal contract review',
      'service agreement',
      'consulting contract',
      'vendor contract',
      'supply agreement',
      'commercial contract lawyer',
    ],
    overview:
      'Legal Contracts are the backbone of every commercial relationship — service agreements, consulting contracts, vendor agreements, supply contracts, license agreements, distribution arrangements and all manner of bilateral arrangements. Under the Indian Contract Act, 1872, valid contracts require offer, acceptance, lawful consideration, capacity, free consent and lawful object.\n\nA well-drafted contract precisely allocates risk, defines deliverables, sets timelines, structures payment, and provides for breach, termination and dispute resolution. Poorly drafted contracts (vague obligations, missing remedies, no jurisdiction clause, unclear IP ownership) create the disputes they were meant to prevent.\n\nWe draft, review and negotiate contracts across sectors — IT/SaaS, consulting, manufacturing, F&B, pharma, real estate services, fintech, edtech and traditional industries. We work with startups, MSMEs, mid-market, and large corporates on bilateral and multi-party contracts.',
    whyChooseUs: [
      { title: 'Sector-Aware Drafting', desc: 'IT/SaaS, fintech, edtech, pharma, manufacturing — sector-specific clauses where they matter.' },
      { title: 'Risk-Allocated', desc: 'Indemnity, limitation of liability, cap, IP ownership — drafted with explicit risk allocation.' },
      { title: 'Negotiation Support', desc: 'Live negotiation with counterparties; mark-up turns delivered same-day.' },
      { title: 'Template Library', desc: 'For high-volume clients — customized template library with periodic refresh.' },
    ],
    keyPoints: [
      'Service / Consulting Agreements',
      'Vendor / Supplier Agreements',
      'Distribution / Reseller Agreements',
      'License Agreements (software, IP, brand)',
      'SaaS / Subscription Agreements',
      'Master Service Agreement + SOW structure',
      'Indemnity, limitation of liability, cap',
      'IP ownership and license-back',
      'Confidentiality and data protection',
      'Force majeure and change-in-law',
      'Termination, transition and survival',
      'Dispute resolution (arbitration / jurisdiction)',
    ],
    process: [
      { title: 'Briefing', desc: 'Capture commercial terms, parties, deliverables and risk concerns.' },
      { title: 'Drafting', desc: 'Tailored agreement with allocations and protective clauses.' },
      { title: 'Negotiation', desc: 'Mark-up cycles with counterparty; we attend negotiation calls.' },
      { title: 'Execution', desc: 'Signing protocol; counter-signed copies and effective date.' },
      { title: 'Compliance Tracking', desc: 'Where ongoing — milestone tracking, renewal flags.' },
    ],
    statutoryRefs: [
      { name: 'Indian Contract Act, 1872', desc: 'Foundational law for contracts.' },
      { name: 'Specific Relief Act, 1963 (as amended 2018)', desc: 'Specific performance now primary remedy.' },
      { name: 'Sale of Goods Act, 1930', desc: 'Goods supply contracts.' },
      { name: 'Information Technology Act, 2000', desc: 'Electronic contracts and digital signatures.' },
      { name: 'Digital Personal Data Protection Act, 2023', desc: 'Data processing agreements within larger contracts.' },
    ],
    pitfalls: [
      { title: 'Generic Templates', desc: 'Generic templates miss sector-specific risks and create gaps.' },
      { title: 'No Cap on Liability', desc: 'Without a cap, exposure is unlimited — major financial risk.' },
      { title: 'Vague Deliverables', desc: '"Reasonable services" or "best efforts" without measurable criteria invites disputes.' },
      { title: 'Missing IP Clauses', desc: 'In service contracts producing IP, ownership / license terms are essential.' },
    ],
    faqs: [
      { q: 'Is a written contract necessary?', a: 'Verbal contracts are valid in India for most matters but evidentially weaker. Written, signed contracts are strongly recommended for any commercial arrangement.' },
      { q: 'Does the contract need to be on stamp paper?', a: 'Stamp duty varies by State and contract type. Many contracts (service agreements, NDAs) attract nominal duty. Some (licenses, lease, partnership) attract higher duty.' },
      { q: 'Are e-signed contracts valid in India?', a: 'Yes — under Information Technology Act, 2000 (Section 5 and 10A), electronic signatures and contracts are valid except for specific excluded categories (negotiable instruments, wills, trust deeds, immovable property transfer).' },
      { q: 'How do I enforce a contract?', a: 'Through (a) civil suit for damages / specific performance, (b) arbitration if clause exists, (c) mediation under Mediation Act, 2023. Choice of forum and governing law clauses determine the path.' },
      { q: 'How much does contract drafting cost?', a: 'Routine contracts: ₹3,000-25,000. Complex / negotiated contracts: ₹50,000-5 lakh. Hourly rates available for negotiation-heavy work.' },
    ],
    relatedServices: [
      { name: 'Business Agreement', href: '/services/documentation/legal/business-agreement' },
      { name: 'Non-Disclosure Agreement (NDA)', href: '/services/documentation/business-corporate/nda' },
      { name: 'MoU', href: '/services/documentation/business-corporate/mou' },
      { name: 'Legal Notice', href: '/services/documentation/legal/legal-notice' },
    ],
  },

  'business-agreement': {
    title: 'Business Agreement',
    description:
      'Comprehensive Business Agreement drafting — partnership, JV, founders, shareholders, distribution and complex commercial arrangements.',
    keywords: [
      'business agreement',
      'partnership agreement',
      'shareholders agreement',
      'founders agreement',
      'distribution agreement',
      'commercial agreement India',
    ],
    overview:
      'Business Agreements span the full range of inter-party commercial arrangements — Partnership Deeds (Indian Partnership Act, 1932), LLP Agreements (LLP Act, 2008), Shareholders Agreements (Companies Act, 2013), Founders Agreements, Distribution Agreements, Reseller Arrangements, Co-Marketing, Licensing and beyond.\n\nUnlike standardized contracts, Business Agreements often involve complex governance, equity, deadlock-resolution, exit and IP clauses. They establish the foundational rules of multi-party business relationships and frequently determine outcomes years later when disputes arise.\n\nWe draft and negotiate Business Agreements for partnerships, LLPs, joint ventures, group restructuring, founder formations, equity rounds, distribution networks and complex commercial arrangements. We integrate corporate, tax, IP and dispute-resolution considerations.',
    whyChooseUs: [
      { title: 'Multi-Discipline Integration', desc: 'Corporate + tax + IP + employment integrated into single agreement.' },
      { title: 'Founders & Investors Both Sides', desc: 'Acted on both sides of equity rounds and founder agreements.' },
      { title: 'Deadlock & Exit Drafting', desc: 'Tag-along, drag-along, ROFR, ROFO, deadlock resolution drafted to actually work.' },
      { title: 'Governance Frameworks', desc: 'Board composition, reserved matters, voting thresholds — structured for stability.' },
    ],
    keyPoints: [
      'Partnership Deed / LLP Agreement',
      'Shareholders Agreement (SHA)',
      'Founders Agreement',
      'Joint Venture Agreement',
      'Distribution / Channel Partner Agreement',
      'Co-Marketing / Co-Branding',
      'Reserved matters and board composition',
      'Tag-along, drag-along, ROFR, ROFO',
      'Vesting, leaver provisions, anti-dilution',
      'Deadlock and exit mechanisms',
      'Indemnity and warranties',
      'Confidentiality and IP ownership',
    ],
    process: [
      { title: 'Term Sheet', desc: 'Capture economics, governance, exit and IP allocation.' },
      { title: 'Diligence', desc: 'Where applicable — counterparty diligence and document inspection.' },
      { title: 'Drafting', desc: 'Comprehensive agreement with all clauses; cross-references with subsidiary documents.' },
      { title: 'Negotiation', desc: 'Mark-up cycles; in-person / video negotiation rounds.' },
      { title: 'Execution', desc: 'Signing protocol with witnesses, dates and effective date.' },
    ],
    statutoryRefs: [
      { name: 'Indian Partnership Act, 1932', desc: 'Partnership formation and operations.' },
      { name: 'LLP Act, 2008', desc: 'Limited Liability Partnership.' },
      { name: 'Companies Act, 2013', desc: 'Shareholders agreements (Section 6 — overrides AoA conflict).' },
      { name: 'Indian Contract Act, 1872', desc: 'General contract law foundation.' },
    ],
    pitfalls: [
      { title: 'No Vesting in Founders Agreement', desc: 'Founders splitting equity without vesting risk losing stability when one founder exits early.' },
      { title: 'Vague Reserved Matters', desc: 'Reserved matters drafted broadly create deadlock; precise list with super-majority thresholds works better.' },
      { title: 'No Exit Mechanism', desc: 'SHA without tag / drag / put-call options leaves minorities trapped or majorities unable to consolidate.' },
      { title: 'Conflict with AoA', desc: 'SHA clauses conflicting with Articles must be reflected in AoA — Section 6 overrides AoA only to limited extent.' },
    ],
    faqs: [
      { q: 'Is partnership deed registration mandatory?', a: 'Not strictly under Indian Partnership Act, but unregistered partnerships face limitations — cannot sue, cannot enforce contracts in court. Registration is highly recommended.' },
      { q: 'Are SHA terms binding on company?', a: 'Section 6 of Companies Act, 2013 makes SHA binding only to extent not contrary to AoA. Best practice: incorporate critical SHA clauses into AoA.' },
      { q: 'What is reserved matters list?', a: 'Decisions requiring super-majority / specific consent — typically capital actions, M&A, key hires, related-party transactions, business changes. Critical for minority protection.' },
      { q: 'How is founders agreement different from SHA?', a: 'Founders Agreement is between co-founders pre-funding (vesting, roles, IP). SHA is between company, founders and investors post-funding (governance, exit, anti-dilution).' },
      { q: 'Should agreement be governed by Indian law?', a: 'For Indian-incorporated entities, generally Indian law and Indian arbitration. Cross-border deals may use SIAC / ICC arbitration with English / Singapore law.' },
    ],
    relatedServices: [
      { name: 'Joint Venture Agreement', href: '/services/documentation/business-corporate/joint-venture-agreement' },
      { name: 'Non-Disclosure Agreement (NDA)', href: '/services/documentation/business-corporate/nda' },
      { name: 'Legal Contract', href: '/services/documentation/legal/legal-contract' },
      { name: 'Memorandum of Understanding (MoU)', href: '/services/documentation/business-corporate/mou' },
    ],
  },

  'real-estate-agreement': {
    title: 'Real Estate Agreement',
    description:
      'Specialized real-estate agreements — Builder Buyer, Joint Development, Sale Agreement, Lease, Construction Contracts, Allotment Letters and RERA-compliant instruments.',
    keywords: [
      'real estate agreement',
      'builder buyer agreement',
      'joint development agreement',
      'construction agreement',
      'real estate contract lawyer',
      'RERA agreement',
    ],
    overview:
      'Real Estate Agreements are sector-specific contracts requiring deep familiarity with RERA Act, 2016, State RERA Rules, Transfer of Property Act, GST and stamp duty. They include Builder Buyer Agreements, Joint Development Agreements, Sale Agreements, Lease Deeds, Construction Contracts, Allotment Letters, Permission Letters and Society Agreements.\n\nEach has distinct regulatory, tax and risk-allocation considerations. Generic templates routinely fail to capture sector requirements — RERA-mandated disclosures, escrow obligations, possession-default consequences and specific buyer protections under Section 18.\n\nWe draft and review the full range — including for buyers, sellers, developers, contractors, society / RWA, and infrastructure projects. We integrate RERA, GST, tax, FEMA and mortgage law into single coherent transaction architecture.',
    whyChooseUs: [
      { title: 'RERA-Native Drafting', desc: 'Every agreement RERA-mapped from inception; not retrofitted.' },
      { title: 'Tax-Optimized Structures', desc: 'Capital gains, GST and stamp duty considered upfront.' },
      { title: 'Multi-Party Coordination', desc: 'Multi-party agreements (developer + landowner + investor + lender).' },
      { title: 'Litigation-Ready', desc: 'Drafted to withstand RERA / court scrutiny.' },
    ],
    keyPoints: [
      'Builder Buyer Agreement (BBA) — RERA Section 13',
      'Joint Development Agreement (JDA)',
      'Sale Agreement / Agreement to Sale',
      'Lease Deed and Long-term Lease',
      'Construction Contract / EPC Agreement',
      'Allotment Letter / Possession Letter',
      'Society / Apartment Association documents',
      'Conveyance Deed',
      'Maintenance Agreement',
      'Project Management Agreement',
    ],
    process: [
      { title: 'Project Diagnostic', desc: 'Identify project type, parties, regulatory regime and applicable approvals.' },
      { title: 'Term Sheet', desc: 'Commercial terms — price, possession, payment, warranties.' },
      { title: 'Drafting', desc: 'Tailored agreement with RERA / GST / stamp considerations.' },
      { title: 'Stamping & Registration', desc: 'Per State law; RERA registration where applicable.' },
      { title: 'Closing & Compliance', desc: 'Possession, mutation, ongoing compliance.' },
    ],
    statutoryRefs: [
      { name: 'RERA Act, 2016', desc: 'Sections 11-19 governing project registration, agreements and possession.' },
      { name: 'Transfer of Property Act, 1882', desc: 'Sale, lease, mortgage frameworks.' },
      { name: 'Registration Act, 1908', desc: 'Compulsory registration provisions.' },
      { name: 'CGST Act / Schedule II', desc: 'Construction services as taxable supply.' },
      { name: 'Income Tax Act — Section 45(5A), 50C, 56(2)(x)', desc: 'Tax provisions specific to real estate transactions.' },
    ],
    pitfalls: [
      { title: 'Pre-RERA Templates', desc: 'Many builders still use pre-RERA templates which omit mandatory disclosures and protections.' },
      { title: 'Carpet vs Super Area', desc: 'Pre-RERA pricing on super area vs RERA-mandated carpet area — clarify.' },
      { title: 'Force Majeure Drafting', desc: 'Generic FM clauses excuse builders for years; narrow drafting needed.' },
      { title: 'Possession Default Inadequacy', desc: 'Buyer-side draftings should preserve Section 18 RERA refund + interest right.' },
    ],
    faqs: [
      { q: 'When does RERA apply to my agreement?', a: 'For real estate projects exceeding RERA registration thresholds (500 sqm or 8+ apartments). RERA applies even to ongoing projects. Section 13 mandates registered Agreement for Sale.' },
      { q: 'Is BBA same as Sale Deed?', a: 'No — BBA is Agreement for Sale (binding to convey in future). Sale Deed actually transfers title at completion. Both are used in real estate.' },
      { q: 'What about JDA tax?', a: 'JDAs trigger capital gains for landowner. Section 45(5A) defers tax to completion certificate, subject to conditions (registered JDA + completion-based transfer).' },
      { q: 'Can I cancel a BBA?', a: 'Yes — under Section 18 RERA on possession default, or per agreement-specific cancellation clauses. Refund + interest available on builder default.' },
    ],
    relatedServices: [
      { name: 'Builder Buyer Agreement', href: '/services/property/registration/builder-buyer-agreement' },
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'RERA Registration & Compliances', href: '/services/property/real-estate/rera-registration' },
      { name: 'Sell / Purchase / Development of Land', href: '/services/property/real-estate/sell-purchase-development' },
      { name: 'Real Estate Litigation (RERA)', href: '/services/property/real-estate/litigation' },
    ],
  },
};
