import type { ServiceContent } from '@/components/leaf-service-page';

export const certificationServices: Record<string, ServiceContent> = {
  'iso-certification': {
    title: 'ISO Certification',
    description:
      'ISO certification consultancy — ISO 9001 (quality), ISO 14001 (environment), ISO 27001 (information security), ISO 45001 (OH&S) and 20+ other standards across industries.',
    keywords: [
      'ISO certification India',
      'ISO 9001 certification',
      'ISO 14001 certification',
      'ISO 27001 certification',
      'ISO 45001 certification',
      'ISO accreditation body',
      'ISMS certification',
      'QMS certification',
    ],
    overview:
      'ISO (International Organization for Standardization) certifications validate that your organization\'s management systems meet internationally recognized standards. ISO 9001 (Quality Management), ISO 14001 (Environmental Management), ISO 27001 (Information Security), ISO 45001 (Occupational Health and Safety) and ISO 22000 (Food Safety) are among the most sought-after certifications. ISO certifications are issued by accredited certification bodies, not by ISO itself.\n\nWhile not legally mandatory in most cases, ISO certifications are increasingly required by enterprise customers, government tenders (especially defence and PSU), export markets and insurance providers. Implementation involves gap analysis, documentation (manual, procedures, work instructions), implementation, internal audit, management review and certification audit by an accredited body.\n\nWe provide end-to-end ISO certification consultancy — gap analysis, documentation, implementation training, internal audit, accredited body coordination and post-certification surveillance audit support across all major standards.',
    whyChooseUs: [
      { title: 'Multi-Standard Experience', desc: 'ISO 9001, 14001, 27001, 45001, 22000, 13485, 17025 — all major standards.' },
      { title: 'Accredited Body Network', desc: 'Coordination with NABCB / IAF-accredited certification bodies (TUV, BSI, Bureau Veritas, DNV, Intertek).' },
      { title: 'Documentation Templates', desc: 'Pre-built templates customized to your operations — saves 60-70% time.' },
      { title: 'Surveillance Support', desc: 'Annual surveillance audits supported; certificate maintained year-on-year.' },
    ],
    keyPoints: [
      'ISO 9001 — Quality Management System',
      'ISO 14001 — Environmental Management System',
      'ISO 27001 — Information Security Management',
      'ISO 45001 — Occupational Health & Safety',
      'ISO 22000 — Food Safety Management',
      'ISO 13485 — Medical Devices QMS',
      'ISO 17025 — Testing / Calibration Labs',
      'IATF 16949 — Automotive QMS',
      'NABCB-accredited certification body coordination',
      'Internal auditor training',
      'Surveillance and recertification audits',
      'IAF (International Accreditation Forum) recognition',
    ],
    process: [
      { title: 'Gap Analysis', desc: 'Current-state vs ISO standard requirements; gap report.' },
      { title: 'Documentation', desc: 'Manual, procedures, work instructions, forms, records — tailored to your operations.' },
      { title: 'Implementation & Training', desc: 'Roll-out across functions; awareness training for all employees.' },
      { title: 'Internal Audit', desc: 'Pre-certification internal audit; corrective actions on findings.' },
      { title: 'Certification Audit', desc: 'Stage 1 (documentation) and Stage 2 (implementation) audit by accredited body.' },
      { title: 'Certification & Surveillance', desc: 'Certificate issued (3-year validity); annual surveillance audits.' },
    ],
    statutoryRefs: [
      { name: 'ISO Standards (International)', desc: 'Specific ISO standard requirements (9001:2015, 14001:2015, 27001:2022, etc.).' },
      { name: 'NABCB Accreditation Criteria', desc: 'National Accreditation Board for Certification Bodies — accreditation framework.' },
      { name: 'IAF MLA', desc: 'International Accreditation Forum Multilateral Agreement — global recognition.' },
      { name: 'ISO 17021 / 17065', desc: 'Standards governing the certification bodies themselves.' },
    ],
    pitfalls: [
      { title: 'Non-Accredited Body', desc: 'Certificates from non-accredited bodies have limited international value. Insist on NABCB / IAF accreditation.' },
      { title: 'Documentation-Only Approach', desc: 'Just having documents doesn\'t pass surveillance — actual implementation is verified.' },
      { title: 'Single-Person Knowledge', desc: 'When ISO knowledge is concentrated in one person, exit risks loss of capability — train multiple stakeholders.' },
      { title: 'Surveillance Lapses', desc: 'Missing annual surveillance leads to suspension; full re-audit needed for re-certification.' },
    ],
    faqs: [
      { q: 'Is ISO certification mandatory?', a: 'Not legally mandatory in most contexts. But increasingly required by customers (especially exports, defence, healthcare, government tenders), regulators in some sectors and for B2B credibility.' },
      { q: 'How long does certification take?', a: 'Typically 3-6 months for first-time certification — gap analysis (2-4 weeks), documentation (4-8 weeks), implementation (4-8 weeks), audits (2-4 weeks).' },
      { q: 'How long is the certificate valid?', a: '3 years — with mandatory annual surveillance audits in years 1 and 2, full recertification in year 3.' },
      { q: 'How much does ISO certification cost?', a: 'Highly variable based on company size, scope, standard. Small (< 50 employees): ₹60,000-1.5 lakh + body fees. Medium: ₹1.5-5 lakh. Large multi-site: ₹5-25 lakh+.' },
      { q: 'Can ISO certificate be revoked?', a: 'Yes — if surveillance audits reveal major non-conformity or fraudulent practices. Suspended / revoked certificates affect customer relationships significantly.' },
      { q: 'Which ISO should I start with?', a: 'For most service / manufacturing companies — ISO 9001 is the foundation. Sector-specific (27001 for IT, 22000 for food, 13485 for medical devices) often added later.' },
    ],
    relatedServices: [
      { name: 'BIS Certification', href: '/services/compliances/certification/bis-certification' },
      { name: 'CA Audit & Report', href: '/services/compliances/closure-convert-others/ca-audit-report' },
      { name: 'GST Audit', href: '/services/business-registration/taxation/gst-audit' },
    ],
  },

  'bis-certification': {
    title: 'BIS Certification',
    description:
      'Bureau of Indian Standards (BIS) certification — ISI mark for products, FMCS for foreign manufacturers, CRS for electronics and Hallmarking for jewellery.',
    keywords: [
      'BIS certification',
      'ISI mark',
      'BIS standard mark',
      'FMCS certification',
      'CRS BIS',
      'BIS hallmarking',
      'BIS license',
      'BIS license process',
    ],
    overview:
      'Bureau of Indian Standards (BIS) under the BIS Act, 2016 administers product certification in India through the Standard Mark (commonly known as ISI mark) under various schemes — Standard Mark (Scheme-I), Foreign Manufacturers Certification Scheme (FMCS), Compulsory Registration Scheme (CRS) for electronics, Hallmarking Scheme for precious metals and Eco-mark for environmentally-friendly products.\n\nBIS certification is mandatory for over 380 products under various Quality Control Orders — cement, steel, electrical wires, electronic appliances, helmets, certain food and pharma products, gold jewellery (mandatory hallmarking), drinking water bottles and many others. Other products can voluntarily seek BIS certification for market credibility.\n\nWe handle BIS certification end-to-end — eligibility analysis, application drafting (BIS Form V / FM/V), factory inspection coordination, sample testing at BIS-recognized labs, license issuance and renewal. We work for Indian manufacturers under Scheme-I, foreign manufacturers under FMCS and importers under CRS for electronics.',
    whyChooseUs: [
      { title: 'All Schemes Coverage', desc: 'Scheme-I (Indian), FMCS (foreign), CRS (electronics), Hallmarking — single team across schemes.' },
      { title: 'Lab Coordination', desc: 'Network with BIS-recognized labs for product testing — minimizes test-cycle time.' },
      { title: 'Foreign Manufacturer Support', desc: 'Authorized Indian Representative (AIR) services for FMCS applicants.' },
      { title: 'Renewal Tracking', desc: 'Periodic renewals (typically 1-2 years) tracked; never lapse.' },
    ],
    keyPoints: [
      'Standard Mark Scheme-I (Indian manufacturers)',
      'FMCS — Foreign Manufacturers Certification Scheme',
      'CRS — Compulsory Registration Scheme (electronics, IT goods)',
      'Hallmarking Scheme (gold jewellery — now mandatory)',
      'Eco-mark Scheme',
      'Quality Control Orders (QCO) compliance',
      'BIS license fee structure',
      'Factory inspection by BIS officer',
      'Sample testing at BIS-recognized labs',
      'AIR (Authorized Indian Representative) for foreign applicants',
      'License renewal (typically 1-2 years)',
      'Surveillance audits',
    ],
    process: [
      { title: 'Standard Identification', desc: 'Confirm applicable IS standard for your product; QCO applicability.' },
      { title: 'Application & Documentation', desc: 'BIS Form V; manufacturing details; raw material list; quality manual.' },
      { title: 'Factory Inspection', desc: 'BIS officer visits factory; verifies infrastructure, production, quality systems.' },
      { title: 'Sample Testing', desc: 'Random samples drawn during inspection; tested at BIS-recognized labs.' },
      { title: 'License Grant', desc: 'On successful test report and inspection, BIS license issued with Standard Mark right.' },
      { title: 'Renewal & Surveillance', desc: 'Periodic renewal; surveillance inspection during validity.' },
    ],
    documents: [
      'Manufacturing license / factory registration',
      'Layout plan and machinery list',
      'Raw material specifications',
      'Quality manual and SOPs',
      'Testing equipment list',
      'Personnel qualifications',
      'GST and PAN of entity',
      'Foreign applicants: AIR appointment + apostilled documents',
    ],
    statutoryRefs: [
      { name: 'Bureau of Indian Standards Act, 2016', desc: 'BIS framework and certification powers.' },
      { name: 'BIS (Conformity Assessment) Regulations, 2018', desc: 'Procedural framework for certification schemes.' },
      { name: 'Quality Control Orders', desc: 'Sector-specific QCOs mandating BIS for various products.' },
      { name: 'Hallmarking Regulations, 2018 (as amended)', desc: 'Mandatory hallmarking framework.' },
    ],
    pitfalls: [
      { title: 'Wrong IS Standard', desc: 'Applying under wrong Indian Standard wastes 3-6 months. Verify applicable standard first.' },
      { title: 'Lab Test Failures', desc: 'Sample test failure delays license by 3-6 months and may require manufacturing process improvements.' },
      { title: 'QCO Timeline', desc: 'New QCOs often have specific commencement dates; missing the date means stopping marketing until certified.' },
      { title: 'AIR for Foreign Applicants', desc: 'FMCS requires Indian-resident AIR; without proper AIR, application is rejected.' },
    ],
    faqs: [
      { q: 'What is the difference between ISI mark and BIS certification?', a: 'BIS certification is the formal license; ISI mark (now called Standard Mark) is the visible mark you can apply on certified products. Same thing in essence — license entitles you to use Mark.' },
      { q: 'Is BIS mandatory for all products?', a: 'No — only for products covered by Quality Control Orders (QCOs). Currently 380+ products are mandatory; others are voluntary.' },
      { q: 'How long does BIS certification take?', a: 'Typically 4-9 months end-to-end — application (1 month), inspection (1-2 months), sample test (2-4 months), license issuance (1 month).' },
      { q: 'Is hallmarking mandatory?', a: 'Yes — hallmarking of gold jewellery is mandatory in 343 districts (as of 2024) and being expanded. Manufacturers, retailers and customers benefit.' },
      { q: 'Can foreign manufacturers get BIS?', a: 'Yes — under FMCS scheme, with mandatory Authorized Indian Representative (AIR) for legal accountability and complaint handling.' },
      { q: 'How much does BIS certification cost?', a: 'BIS application fee: ₹1,000-5,000. License fee: ₹3,000-10,000 per year. Inspection charges: ₹15,000-1 lakh. Lab testing: variable. Total typically ₹50,000-3 lakh+.' },
    ],
    relatedServices: [
      { name: 'ISO Certification', href: '/services/compliances/certification/iso-certification' },
      { name: 'FSSAI License', href: '/services/business-registration/license/fssai-license' },
      { name: 'AYUSH License', href: '/services/business-registration/license/ayush-license' },
      { name: 'Drug License', href: '/services/business-registration/license/drug-license' },
    ],
  },
};
