import type { ServiceContent } from '@/components/leaf-service-page';

export const propertyRealEstateServices: Record<string, ServiceContent> = {
  'rera-registration': {
    title: 'RERA Registration & Compliances',
    description:
      'End-to-end RERA registration, project disclosures, quarterly updates and ongoing compliance under the Real Estate (Regulation and Development) Act, 2016.',
    keywords: [
      'RERA registration',
      'RERA compliance',
      'real estate regulatory authority',
      'RERA Section 3 4',
      'RERA project registration',
      'RERA agent registration',
      'state RERA filing',
    ],
    overview:
      'The Real Estate (Regulation and Development) Act, 2016 (RERA) requires every promoter to register projects (where land area exceeds 500 sqm or there are more than 8 apartments) and every real-estate agent to register with the State RERA Authority before any sale, advertisement or marketing. RERA brings transparency, accountability and consumer protection to the previously unregulated real-estate sector.\n\nProjects must disclose layouts, plans, approvals, escrow account details, completion timelines, carpet area calculations, defect-liability terms and litigation status. Quarterly compliance updates are mandatory; non-compliance attracts up to 10% of project cost as penalty and personal liability of promoters.\n\nOur RERA-specialist team handles project registration across all major State RERA Authorities (Maharashtra MahaRERA, Karnataka K-RERA, UP-RERA, Haryana RERA, Tamil Nadu TNRERA), agent registration, ongoing compliance, complaint defence and Appellate Tribunal representation.',
    whyChooseUs: [
      { title: 'State-Authority Network', desc: 'Active filings across MahaRERA, K-RERA, UP-RERA, HRERA, TNRERA and others.' },
      { title: 'Promoter & Buyer Both Sides', desc: 'We act for promoters (registration / compliance) and for buyers (complaints / refund / interest).' },
      { title: 'Quarterly Compliance Programs', desc: 'Managed quarterly updates to avoid de-registration and penalty.' },
      { title: 'Tribunal Litigation', desc: 'Appellate Tribunal representation for adverse orders.' },
    ],
    keyPoints: [
      'Project registration under RERA Section 3-4',
      'Promoter, project, plans, approvals disclosure',
      'Carpet area calculation as per Section 2(k)',
      'Escrow account (70% rule) compliance',
      'Quarterly project updates (Section 11)',
      'Real-estate agent registration',
      'Promoter agreement compliance',
      'Force majeure / extension applications',
      'Buyer complaint defence',
      'Appellate Tribunal proceedings',
    ],
    process: [
      { title: 'Project Diagnostic', desc: 'Assess registrability, document readiness and disclosure gaps.' },
      { title: 'Registration', desc: 'File project registration with all approvals, plans, disclosures.' },
      { title: 'Authority Queries', desc: 'Respond to RERA queries; address deficiencies.' },
      { title: 'Registration Number', desc: 'Receive RERA registration number; mandatory in all marketing.' },
      { title: 'Ongoing Compliance', desc: 'Quarterly project updates, escrow audits, litigation reports.' },
      { title: 'Complaint Defence', desc: 'If complaints arise, defend before RERA / Tribunal.' },
    ],
    documents: [
      'Land title chain and ownership proof',
      'Approved building plan, layout, elevations',
      'Environmental and other regulatory approvals',
      'Escrow account opening documents',
      'Project schedule and completion certification',
      'Sample agreement for sale',
      'Promoter directors / partners KYC',
      'Past project track record disclosure',
      'CA-certified financial details',
    ],
    statutoryRefs: [
      { name: 'Real Estate (Regulation and Development) Act, 2016', desc: 'Central Act establishing RERA framework.' },
      { name: 'State RERA Rules', desc: 'Each State has its own Rules — Maharashtra Real Estate (Regulation and Development) Rules, Karnataka RERA Rules etc.' },
      { name: 'RERA Section 3', desc: 'Mandatory project registration for projects over thresholds.' },
      { name: 'RERA Section 18', desc: 'Refund with interest on possession default.' },
      { name: 'RERA Section 14', desc: 'Adherence to plans; structural defect liability for 5 years.' },
    ],
    pitfalls: [
      { title: 'Marketing Before Registration', desc: 'Section 3 prohibits any sale / advertisement before RERA registration. Common but costly violation.' },
      { title: 'Carpet Area Mis-Statements', desc: 'Pre-RERA practices of super-area pricing are now penalized; carpet area must match registered plan.' },
      { title: '70% Escrow Lapses', desc: '70% of buyer collections must go into project-specific escrow. Diversion is regulatory and criminal.' },
      { title: 'Missing Quarterly Updates', desc: 'Project status updates are mandatory. Repeated lapses lead to suspension of registration.' },
    ],
    faqs: [
      { q: 'When is RERA registration mandatory?', a: 'When project land area exceeds 500 sqm OR has more than 8 apartments. Below thresholds — voluntary registration. Re-development projects also have specific thresholds per State Rules.' },
      { q: 'What about ongoing projects?', a: 'Projects ongoing on the date of RERA enforcement (where OC / completion certificate not issued) had to be registered within 3 months. Most ongoing projects have been brought under RERA.' },
      { q: 'How long does RERA registration take?', a: 'Typically 30-60 days. Authority has 30 days to reject; otherwise registration is deemed approved.' },
      { q: 'What is escrow under RERA?', a: '70% of amounts realized from buyers must be deposited in project-specific escrow account; withdrawal only based on project progress and architect / engineer / CA certification.' },
      { q: 'Can I cancel and get refund under RERA?', a: 'Yes — under Section 18, on possession delay or defects, buyer can withdraw and demand full refund + interest. Or continue and claim monthly delay interest.' },
      { q: 'What is the penalty for non-registration?', a: 'Up to 10% of estimated project cost; in case of repeated non-compliance, imprisonment up to 3 years.' },
    ],
    relatedServices: [
      { name: 'Builder Buyer Agreement', href: '/services/property/registration/builder-buyer-agreement' },
      { name: 'Real Estate Litigation (RERA)', href: '/services/property/real-estate/litigation' },
      { name: 'Conveyance Deed Registration', href: '/services/property/registration/conveyance-deed' },
      { name: 'Title Clearance & Due Diligence', href: '/services/property/real-estate/title-clearance' },
    ],
  },

  'fdi': {
    title: 'FDI in Real Estate',
    description:
      'Foreign Direct Investment advisory in Indian real estate — FEMA, Press Note 3, sectoral caps, downstream investment and exit strategy.',
    keywords: [
      'FDI in real estate',
      'foreign investment Indian property',
      'FEMA real estate',
      'Press Note 3 FDI',
      'NRI investment property India',
      'FPI real estate',
    ],
    overview:
      'Foreign Direct Investment (FDI) in Indian real estate is permitted in construction-development projects under the FEMA Non-Debt Instruments Rules, 2019 — subject to specific conditions on minimum project size, capitalization, lock-in and exit. Direct investment in trading of land, farm-houses or completed real-estate is restricted; investment in REITs is now welcomed.\n\nKey conditions include minimum 20,000 sqm built-up area, minimum FDI of US $5 million, 3-year lock-in (subject to project completion), and pre-development investment restrictions. Press Note 3 of 2020 added screening for investments from countries sharing land borders with India (China, Pakistan, Bangladesh, etc.).\n\nWe advise foreign developers, sovereign wealth funds, REITs and pension funds on FDI structuring, FEMA compliance, downstream investment via Indian holding companies, repatriation, exit and dispute resolution. We also advise NRIs / OCIs on FEMA-compliant property investment.',
    whyChooseUs: [
      { title: 'FEMA-Compliant Structuring', desc: 'Investment structures designed for repatriation and regulatory comfort.' },
      { title: 'Press Note 3 Navigation', desc: 'Where investor jurisdiction triggers prior approval — DPIIT process managed end-to-end.' },
      { title: 'JV / SPV Structuring', desc: 'Joint venture and SPV structures for development partnerships.' },
      { title: 'Exit & Repatriation', desc: 'Compliance for project exit, dividend / capital repatriation.' },
    ],
    keyPoints: [
      'FDI eligibility under FEMA NDI Rules, 2019',
      'Construction-development conditionality',
      'Minimum project size (20,000 sqm) and capitalization (US $5M)',
      '3-year lock-in subject to project completion',
      'Press Note 3 — prior approval for land-border countries',
      'Joint venture and SPV structuring',
      'Downstream investment compliance',
      'REIT / InvIT investment route',
      'Repatriation and exit advisory',
      'NRI / OCI specific routes',
    ],
    process: [
      { title: 'Eligibility & Structure', desc: 'Map investor profile, target project, Press Note 3 applicability.' },
      { title: 'Approval (if required)', desc: 'DPIIT prior-approval filing for sensitive jurisdictions.' },
      { title: 'SPV / JV Setup', desc: 'Indian SPV incorporation, FDI infusion, ROC filings.' },
      { title: 'FEMA Compliance', desc: 'FC-GPR, FC-TRS, ARF and other RBI filings.' },
      { title: 'Project Execution', desc: 'Land acquisition / development; ongoing FEMA compliance.' },
      { title: 'Exit', desc: 'Sale of investment, repatriation, FEMA closure.' },
    ],
    statutoryRefs: [
      { name: 'FEMA, 1999 and Non-Debt Instruments Rules, 2019', desc: 'Govern foreign investment in India.' },
      { name: 'Press Note 3 of 2020', desc: 'Prior approval for investments from land-border countries.' },
      { name: 'Consolidated FDI Policy', desc: 'DPIIT-issued policy with sectoral caps and conditions.' },
      { name: 'RERA Act, 2016', desc: 'Project regulatory compliance applicable regardless of investor nationality.' },
    ],
    pitfalls: [
      { title: 'Pre-Development Restrictions', desc: 'FDI cannot be infused for trading of plots / completed assets — only for construction-development.' },
      { title: 'Lock-in Mis-Application', desc: '3-year lock-in is project-specific; transfer / exit before lock-in is restricted.' },
      { title: 'Press Note 3 Triggers', desc: 'Even indirect ownership from land-border countries triggers approval. Beneficial-ownership analysis essential.' },
      { title: 'FEMA Non-Filing', desc: 'FC-GPR / FC-TRS filings within 30 days are mandatory; missed filings invite compounding.' },
    ],
    faqs: [
      { q: 'Can foreigners directly buy land in India?', a: 'No — direct purchase of agricultural / plantation / farmhouse land by foreigners is prohibited. Investment in construction-development projects through corporate vehicles is permitted under FDI policy.' },
      { q: 'What is the minimum investment under FDI route?', a: 'US $5 million (effectively), with 20,000 sqm minimum project area. These minimums apply to construction-development; some sectors (REITs) have different thresholds.' },
      { q: 'How does Press Note 3 affect FDI?', a: 'Investments from land-border countries (China, Pakistan, Bangladesh, Nepal, Bhutan, Myanmar, Afghanistan) require prior DPIIT approval, regardless of sector. Beneficial-ownership analysis applies.' },
      { q: 'Can NRIs invest in real estate?', a: 'Yes — NRIs / OCIs can buy residential and commercial property (not agricultural / plantation / farmhouse) on a non-repatriable basis under FEMA. Repatriable investment has additional conditions.' },
      { q: 'What about REIT / InvIT investment?', a: 'FDI in registered REITs / InvITs is permitted under automatic route up to specified limits. Provides cleaner regulatory pathway than direct construction-development FDI.' },
    ],
    relatedServices: [
      { name: 'RERA Registration & Compliances', href: '/services/property/real-estate/rera-registration' },
      { name: 'Real Estate Project Finance', href: '/services/property/real-estate/project-finance' },
      { name: 'Sell / Purchase / Development of Land', href: '/services/property/real-estate/sell-purchase-development' },
      { name: 'Title Clearance & Due Diligence', href: '/services/property/real-estate/title-clearance' },
    ],
  },

  'sez': {
    title: 'Special Economic Zones (SEZ)',
    description:
      'SEZ developer notification, unit licensing, tax incentives, exit / de-notification — comprehensive advisory under the SEZ Act, 2005.',
    keywords: [
      'SEZ Act 2005',
      'SEZ developer license',
      'SEZ unit setup',
      'SEZ approval committee',
      'IT SEZ',
      'multi product SEZ',
      'SEZ rule 74',
    ],
    overview:
      'Special Economic Zones (SEZs) under the SEZ Act, 2005 are designated areas with relaxed business and customs regulations and significant tax incentives. They aim to promote exports, FDI and economic activity. Different categories — Multi-Product, Sector-Specific (IT, biotech, gems & jewellery), Free Trade & Warehousing — have distinct minimum land area and infrastructure norms.\n\nSEZ developers obtain notification through the Board of Approval (BoA); units within SEZ apply to the Approval Committee. SEZ tax holidays under Section 10AA were sunset for new units from April 2020 (with some pending grandfather), though existing SEZ units continue to enjoy benefits through their designated period.\n\nWe advise SEZ developers and units on notification / re-notification, unit setup, customs and tax compliance, employee secondment, compliance audits, de-notification, exit and Domestic Tariff Area (DTA) sale.',
    whyChooseUs: [
      { title: 'SEZ Lifecycle Coverage', desc: 'From greenfield notification to de-notification and exit.' },
      { title: 'Tax & Customs Integrated', desc: 'IT, indirect tax and customs counsel within single team.' },
      { title: 'BoA & Approval Committee Liaison', desc: 'Active filings with Board of Approval and zonal Development Commissioners.' },
      { title: 'DTA Transition Support', desc: 'For SEZs exiting / de-notifying, DTA conversion and tax / customs handling.' },
    ],
    keyPoints: [
      'SEZ developer notification under Section 3-4',
      'Co-developer arrangements',
      'Unit approval under Section 15',
      'Tax holidays under Section 10AA (existing units)',
      'Customs duty exemption on imports',
      'Service tax / GST exemption / refund',
      'Employee secondment and visa coordination',
      'Annual / quarterly compliance reports',
      'De-notification and exit (Rule 74)',
      'DTA sale and conversion',
    ],
    process: [
      { title: 'Eligibility', desc: 'Map sector, land area, infrastructure and business case for SEZ.' },
      { title: 'BoA Filing', desc: 'File notification application with detailed master plan, financial closure, environmental clearances.' },
      { title: 'Notification', desc: 'BoA approval; gazette notification; de-bonding from DTA.' },
      { title: 'Operations', desc: 'Customs procedure, tax compliance, periodic audits.' },
      { title: 'Exit / De-notification', desc: 'Where required, file Rule 74 application; address customs and tax dues.' },
    ],
    statutoryRefs: [
      { name: 'Special Economic Zones Act, 2005', desc: 'Statutory framework for SEZ creation and operation.' },
      { name: 'SEZ Rules, 2006', desc: 'Operational rules including notification, unit approval and de-notification.' },
      { name: 'Income Tax Act — Section 10AA', desc: 'Tax holiday for SEZ units (sunset for new units from April 1, 2020).' },
      { name: 'Customs Act / GST Acts', desc: 'Customs duty exemption and GST treatment for SEZ.' },
    ],
    pitfalls: [
      { title: 'Sunset of Section 10AA', desc: 'New units after April 1, 2020 cannot avail Section 10AA tax holiday — significantly reducing SEZ attractiveness.' },
      { title: 'Annual Compliance Lapses', desc: 'Missing annual returns or Net Foreign Exchange (NFE) reports invites de-notification.' },
      { title: 'DTA Sale Restrictions', desc: 'Sale of goods / services to DTA from SEZ has duty / IGST implications often misunderstood.' },
      { title: 'Employee Misclassification', desc: 'SEZ units often have HR confusion on employee jurisdiction; secondment arrangements need careful structuring.' },
    ],
    faqs: [
      { q: 'Are tax benefits still available for new SEZ units?', a: 'Section 10AA tax holiday is sunset for units commencing operations after April 1, 2020. Customs and GST exemptions for inputs continue. New SEZ developer benefits also significantly curtailed.' },
      { q: 'Can existing SEZs de-notify?', a: 'Yes — under Rule 74, SEZ developer / units can apply for de-notification. Process involves clearing customs / tax dues, returning concessions on lapse and gazette de-notification.' },
      { q: 'What are minimum sizes for different SEZs?', a: 'Multi-Product SEZ: 1000 hectares; Sector-specific SEZ: 100 hectares; IT/ITES/Biotech: 10 hectares with 1 lakh sqm built-up; FTWZ: 40 hectares.' },
      { q: 'Can I sell goods from SEZ to DTA?', a: 'Yes — but treated as imports into DTA, attracting customs duty + IGST. Specific procedures and rate calculations apply.' },
      { q: 'Are SEZ units eligible for export incentives?', a: 'SEZ units are eligible for various export-related incentives — duty drawback, refund of unutilized ITC, etc., subject to specific conditions.' },
    ],
    relatedServices: [
      { name: 'FDI in Real Estate', href: '/services/property/real-estate/fdi' },
      { name: 'Real Estate Project Finance', href: '/services/property/real-estate/project-finance' },
      { name: 'Land Acquisition', href: '/services/property/real-estate/land-acquisition' },
    ],
  },

  'sell-purchase-development': {
    title: 'Sell / Purchase / Development of Land',
    description:
      'End-to-end legal advisory and documentation for land sale, purchase, joint development, development management agreements and real-estate transactions.',
    keywords: [
      'land sale purchase',
      'joint development agreement',
      'JDA real estate',
      'development management agreement',
      'land transaction lawyer',
      'real estate transaction India',
    ],
    overview:
      'Land sale, purchase and development transactions span everything from individual residential plots to multi-acre integrated township acquisitions. Each transaction requires careful structuring — title due diligence, regulatory approvals, stamp duty optimization, escrow, financing, RERA registration and post-closing compliance.\n\nJoint Development Agreements (JDAs) — where landowners contribute land and developers contribute construction services in exchange for a share of built-up area or revenue — are particularly nuanced. They involve complex tax (capital gains on contribution), GST (on construction services), and structural choices (revenue share vs area share, transfer at start vs at completion).\n\nWe handle individual plot transactions, JDA structuring, Development Management Agreements (where developer is hired without land transfer), FSI / TDR transactions, redevelopment, slum-rehabilitation projects, and multi-party land acquisitions. We integrate tax, GST, RERA, FEMA and corporate law into a single transaction architecture.',
    whyChooseUs: [
      { title: 'JDA Specialists', desc: 'Tax-optimized JDA structures (Section 45(5A) eligible) with realistic developer-landowner risk allocation.' },
      { title: 'Multi-Party Coordination', desc: 'Multi-landowner aggregations, escrow and contingent closing.' },
      { title: 'GST / Stamp Duty Strategy', desc: 'Transactions structured for optimal indirect-tax and stamp-duty outcomes.' },
      { title: 'RERA Coordination', desc: 'Where development is a "real estate project", RERA registration integrated.' },
    ],
    keyPoints: [
      'Land sale / purchase Sale Deeds',
      'Agreement to Sale and conditions precedent',
      'Joint Development Agreement (JDA)',
      'Development Management Agreement (DMA)',
      'Revenue-share vs area-share JDA structuring',
      'Section 45(5A) capital gains advisory',
      'GST advisory on construction services',
      'TDR / FSI transactions',
      'Slum rehabilitation / redevelopment',
      'Multi-party land aggregation',
      'Escrow and contingent closing',
      'Post-closing RERA compliance',
    ],
    process: [
      { title: 'Term Sheet', desc: 'Map deal economics, structure, key risks and walk-away triggers.' },
      { title: 'Due Diligence', desc: 'Title, regulatory, tax, environmental, litigation diligence.' },
      { title: 'Structuring', desc: 'Choose between Sale, Conditional Sale, JDA, DMA, License — based on tax and risk fit.' },
      { title: 'Documentation', desc: 'Tailored agreements with risk-allocated clauses and dispute resolution.' },
      { title: 'Closing', desc: 'Conditions precedent, escrow release, registration, mutation.' },
      { title: 'Post-Closing', desc: 'RERA, GST, capital gains, mutation and ongoing compliance.' },
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882', desc: 'Sale, conveyance and assignment principles.' },
      { name: 'Income Tax Act, 1961 — Section 45(5A)', desc: 'Capital gains deferral for JDAs subject to conditions.' },
      { name: 'GST Acts', desc: 'Construction services taxability, RCM on land transfer to developer.' },
      { name: 'RERA Act, 2016', desc: 'Project registration where applicable.' },
    ],
    pitfalls: [
      { title: 'JDA Capital Gains Trigger', desc: 'JDA may trigger capital gains for landowner at execution itself unless Section 45(5A) conditions are met (registered JDA + completion certificate transfer).' },
      { title: 'GST on JDA Services', desc: 'Developer\'s construction services to landowner attract GST (now at 5%); structuring affects who pays.' },
      { title: 'Revenue-Share Disputes', desc: 'Vague revenue-share definitions ("net sale proceeds") are litigation magnets; precise definitions essential.' },
      { title: 'RERA Compliance Skipping', desc: 'JDA projects exceeding RERA thresholds need registration; both developer and landowner share liability.' },
    ],
    faqs: [
      { q: 'What is a JDA?', a: 'Joint Development Agreement — landowner contributes land; developer contributes construction services. In exchange, landowner gets share of constructed area (area share) or sale proceeds (revenue share). JDA can structure transfer at execution or completion.' },
      { q: 'When is capital gains triggered in JDA?', a: 'Without Section 45(5A) — at JDA execution (transfer for tax purposes). With Section 45(5A) — at completion certificate / part-completion. Conditions: JDA must be registered and structured per Section 45(5A).' },
      { q: 'Is GST applicable on JDA?', a: 'Yes — developer\'s construction services to landowner are taxable supply (currently 5% on residential). Structuring affects whether landowner or developer bears it.' },
      { q: 'What is Development Management Agreement?', a: 'DMA is where developer is hired as service provider for development without transfer of land or built-up area. Landowner retains ownership; developer earns fees / share of profits.' },
      { q: 'Can multiple landowners enter single JDA?', a: 'Yes — multi-landowner JDAs are common in larger projects. Requires careful aggregation, signing protocols, and escrow for diligence completion.' },
    ],
    relatedServices: [
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'RERA Registration & Compliances', href: '/services/property/real-estate/rera-registration' },
      { name: 'Land Acquisition', href: '/services/property/real-estate/land-acquisition' },
      { name: 'Real Estate Project Finance', href: '/services/property/real-estate/project-finance' },
      { name: 'Title Clearance & Due Diligence', href: '/services/property/real-estate/title-clearance' },
    ],
  },

  'ppp': {
    title: 'PPP (Public Private Partnership) Projects',
    description:
      'Legal advisory for Public Private Partnership projects in real estate and infrastructure — concession agreements, BOT, BOOT, viability gap funding and dispute resolution.',
    keywords: [
      'PPP projects India',
      'public private partnership',
      'BOT BOOT concession',
      'PPP concession agreement',
      'infrastructure PPP',
      'viability gap funding',
      'urban renewal PPP',
    ],
    overview:
      'Public Private Partnership (PPP) projects pool government and private resources to deliver infrastructure and real-estate outcomes — highways, ports, airports, urban renewal, low-income housing, hospitals and educational institutions. Common models include BOT (Build-Operate-Transfer), BOOT (Build-Own-Operate-Transfer), DBFOT (Design-Build-Finance-Operate-Transfer), HAM (Hybrid Annuity Model) and DBFOM.\n\nPPP transactions are highly complex — long-term concession agreements (20-30+ years), tariff regulation, force majeure, change-in-law, termination payments, escrow, dispute resolution and financing security. Both sides require specialist counsel.\n\nWe represent both Authorities (Central / State / ULBs) and Concessionaires (Indian and foreign). We draft RFQ / RFP / MCAs (Model Concession Agreements), advise on bid strategy, financial closure, termination and arbitration / Conciliation Settlement.',
    whyChooseUs: [
      { title: 'Both Sides Experience', desc: 'Acted for Authorities and Concessionaires; brings balanced perspective.' },
      { title: 'Sector Coverage', desc: 'Roads, ports, airports, urban infra, real-estate-led PPP, smart cities.' },
      { title: 'Financial Closure Coordination', desc: 'Bank-side documentation harmonized with concession agreement.' },
      { title: 'Dispute Resolution', desc: 'Active in Conciliation, Arbitration (SIAC, ICC, ICA) and writ proceedings.' },
    ],
    keyPoints: [
      'PPP model selection (BOT / BOOT / DBFOT / HAM / DBFOM)',
      'Concession agreement drafting',
      'Bid documentation (RFQ / RFP)',
      'Tariff and revenue-share structuring',
      'Force majeure and change-in-law',
      'Termination and termination payments',
      'Viability gap funding (VGF) and grant-funded PPPs',
      'Equity lock-in, change in shareholding',
      'Lender step-in and substitution',
      'Dispute resolution clauses',
    ],
    process: [
      { title: 'Project Structuring', desc: 'Choose appropriate PPP model based on project economics, risk allocation and authority capacity.' },
      { title: 'Documentation', desc: 'RFQ, RFP, Model Concession Agreement, escrow, security documents.' },
      { title: 'Bidding & Award', desc: 'Bidding process management, evaluation, letter of award.' },
      { title: 'Financial Closure', desc: 'Lender documentation, hedging, security creation.' },
      { title: 'Project Execution', desc: 'Construction, operations, change orders, dispute management.' },
      { title: 'Handover', desc: 'End-of-concession transfer, reconciliation, handover.' },
    ],
    statutoryRefs: [
      { name: 'Constitution of India — Article 245-294', desc: 'Power to enter into contracts and acquire property.' },
      { name: 'Indian Contract Act, 1872', desc: 'Foundational contract law.' },
      { name: 'Arbitration & Conciliation Act, 1996', desc: 'Dispute resolution framework.' },
      { name: 'Sector-Specific Acts', desc: 'NHAI Act, Major Port Trusts Act, Airports Authority Act, etc.' },
    ],
    pitfalls: [
      { title: 'Risk Allocation Imbalance', desc: 'One-sided risk allocation leads to bid failures or future disputes.' },
      { title: 'Termination Payment Inadequacy', desc: 'Termination payment formulas favoring authorities discourage private investment and complicate financing.' },
      { title: 'Force Majeure Drafting', desc: 'Generic FM clauses fail in projects with regulatory volatility.' },
      { title: 'Lender Step-in Restrictions', desc: 'Restrictive step-in undermines bankability.' },
    ],
    faqs: [
      { q: 'What is the difference between BOT and BOOT?', a: 'BOT (Build-Operate-Transfer): Concessionaire builds, operates for concession period, transfers to authority. BOOT (Build-Own-Operate-Transfer): Concessionaire owns the asset during operation; transfers at end.' },
      { q: 'What is HAM?', a: 'Hybrid Annuity Model — government pays 40% of project cost during construction, balance through annuity over operation period. Reduces concessionaire revenue risk.' },
      { q: 'Are PPP disputes arbitrable?', a: 'Generally yes — most concession agreements have arbitration clauses (domestic / international). Some matters (constitutional, public interest) may go to writ courts.' },
      { q: 'What is VGF?', a: 'Viability Gap Funding — government grant for projects that are economically justified but commercially unviable. Up to 20-40% of project cost can be VGF.' },
    ],
    relatedServices: [
      { name: 'Land Acquisition', href: '/services/property/real-estate/land-acquisition' },
      { name: 'Real Estate Project Finance', href: '/services/property/real-estate/project-finance' },
      { name: 'Property Dispute Resolution & Arbitration', href: '/services/property/real-estate/dispute-arbitration' },
    ],
  },

  'dispute-arbitration': {
    title: 'Property Dispute Resolution & Arbitration',
    description:
      'Strategic property dispute resolution — pre-litigation negotiation, mediation, arbitration and civil litigation across title, possession, tenancy and contractual disputes.',
    keywords: [
      'property dispute lawyer',
      'real estate arbitration',
      'property mediation India',
      'title dispute resolution',
      'partition suit',
      'specific performance suit',
      'real estate ADR',
    ],
    overview:
      'Property disputes constitute one of the largest categories of Indian civil litigation, contributing to 60-80% of pendency in some States. Categories include title disputes, partition / inheritance, possession (forcible / constructive), specific performance of agreements, builder-buyer disputes, society / RWA disputes, encroachment and tenancy.\n\nWhile civil litigation remains the default forum, Alternate Dispute Resolution (ADR) — particularly mediation under the Mediation Act, 2023 and arbitration under the Arbitration and Conciliation Act, 1996 — increasingly resolves property disputes faster and more cost-effectively. Arbitration of property disputes is permitted unless rights in rem (inheritance, partition decrees) are involved.\n\nWe handle every type of property dispute — pre-litigation cease-and-desist, structured negotiation, mediation, sole / 3-arbitrator arbitration, civil suits (partition, declaration, injunction, specific performance), revisions, second appeals and Supreme Court SLPs. We integrate strategy, procedure and execution.',
    whyChooseUs: [
      { title: 'ADR-First Approach', desc: 'Many disputes settled through structured negotiation and mediation — saving years of litigation.' },
      { title: 'Multi-Forum Capability', desc: 'Civil court, RERA, Consumer Forum, Cooperative Court — appropriate forum selected.' },
      { title: 'Senior Counsel Network', desc: 'Active engagement of Senior Advocates for High Court and Supreme Court matters.' },
      { title: 'Execution Specialists', desc: 'Decree is just half — our execution team ensures actual recovery / possession.' },
    ],
    keyPoints: [
      'Pre-litigation cease and desist',
      'Mediation under Mediation Act, 2023',
      'Sole and 3-arbitrator arbitration',
      'Civil suits — partition, declaration, injunction, specific performance',
      'Eviction / possession proceedings',
      'RERA complaints and Tribunal appeals',
      'Consumer Forum proceedings (flat purchasers)',
      'Society / Cooperative Court proceedings',
      'Cross-border property disputes',
      'Decree execution and possession recovery',
    ],
    process: [
      { title: 'Diagnostic', desc: 'Assess facts, applicable law, forum, prospects, and timeline.' },
      { title: 'Pre-litigation', desc: 'Legal notice, structured negotiation, mediation attempts.' },
      { title: 'Forum Filing', desc: 'Civil court / arbitration / RERA / Consumer Forum / Cooperative Court as appropriate.' },
      { title: 'Trial / Arbitration', desc: 'Pleadings, evidence, cross-examination, arguments.' },
      { title: 'Decree / Award', desc: 'Final decision; appeals as necessary.' },
      { title: 'Execution', desc: 'Decree execution, attachment, sale, possession recovery.' },
    ],
    statutoryRefs: [
      { name: 'Code of Civil Procedure, 1908', desc: 'Civil litigation procedure.' },
      { name: 'Specific Relief Act, 1963 (as amended 2018)', desc: 'Specific performance is now primary remedy.' },
      { name: 'Arbitration & Conciliation Act, 1996', desc: 'Arbitration framework.' },
      { name: 'Mediation Act, 2023', desc: 'Statutory mediation framework with enforceability.' },
      { name: 'Limitation Act, 1963', desc: '12-year limitation for property claims; adverse possession.' },
    ],
    pitfalls: [
      { title: 'Limitation Lapses', desc: 'Property claims have 3-12 year limitation periods — late filing often fatal.' },
      { title: 'Wrong Forum', desc: 'RERA matter filed in civil court or vice versa wastes years and fees.' },
      { title: 'Inadequate Pleadings', desc: 'Vague pleadings lead to amendment delays; precise specific-performance prayers essential.' },
      { title: 'Ignoring Execution', desc: 'Decree without execution is symbolic. Many cases lose 80% value at execution stage.' },
    ],
    faqs: [
      { q: 'How long does property litigation take in India?', a: 'Civil suits: 5-15 years through trial + appeals. RERA / Consumer Forum: 12-30 months at trial level. Arbitration: 12-24 months for completion (post-2015 amendments enforce timelines).' },
      { q: 'Are property disputes arbitrable?', a: 'Yes — most contractual property disputes (sale agreement, JDA, lease) are arbitrable. Rights in rem (partition affecting third parties, declarations of title against world) are not arbitrable per Supreme Court rulings.' },
      { q: 'What is the cost?', a: 'Court fee — ad valorem on relief value (typically 1-3%). Lawyer fees vary widely — ₹50,000 to ₹50 lakh+ depending on complexity, value and forum.' },
      { q: 'Can I claim damages for delayed possession?', a: 'Yes — under RERA Section 18 (refund + interest), Consumer Protection Act (compensation) or contract (specific damages clause). Multiple parallel remedies often available.' },
      { q: 'When should I prefer arbitration over court?', a: 'Arbitration: faster, confidential, party-appointed arbitrator. Court: appellate review, broader powers, free legal aid for indigent. Choose based on complexity, value, time-sensitivity and confidentiality needs.' },
    ],
    relatedServices: [
      { name: 'Real Estate Litigation (RERA)', href: '/services/property/real-estate/litigation' },
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Builder Buyer Agreement', href: '/services/property/registration/builder-buyer-agreement' },
      { name: 'Land Acquisition', href: '/services/property/real-estate/land-acquisition' },
    ],
  },

  'project-finance': {
    title: 'Real Estate Project Finance',
    description:
      'Structured finance and lending advisory for real-estate projects — construction finance, mezzanine, NCDs, REITs, AIF investments, and exit financing.',
    keywords: [
      'real estate project finance',
      'construction finance',
      'mezzanine finance real estate',
      'real estate NCD',
      'AIF real estate',
      'REIT investment finance',
    ],
    overview:
      'Real estate project finance encompasses the full spectrum of debt and equity financing for development projects — bank construction finance, mezzanine debt, NCDs (Non-Convertible Debentures), structured equity, AIF investments, REIT-led acquisitions and exit financing. Each instrument has distinct regulatory, tax and security implications.\n\nOur project finance team works for developers, lenders, AIFs, REITs and offshore investors. We structure transactions to optimize gearing, security creation (mortgage, hypothecation, escrow, share pledge, personal guarantees), drawdown mechanics, financial covenants, and exit / refinancing options.\n\nRegulatory considerations span SARFAESI, NBFC Regulations, AIF Regulations, REIT Regulations, FEMA (for cross-border financing), GST and stamp duty optimization. We integrate these with the developer\'s construction timeline, RERA compliance and downstream sale strategy.',
    whyChooseUs: [
      { title: 'Multi-Instrument Capability', desc: 'Bank loans, NCDs, mezzanine, structured equity, REITs — single team across instruments.' },
      { title: 'Lender & Borrower Experience', desc: 'Acted for both — gives realistic negotiation perspective.' },
      { title: 'Cross-Border Structuring', desc: 'FEMA-compliant inbound investment from foreign banks, AIFs, sovereign wealth funds.' },
      { title: 'Default & Restructuring', desc: 'Where projects face stress — restructuring, IBC, SARFAESI managed.' },
    ],
    keyPoints: [
      'Bank construction finance documentation',
      'NCD and structured-debt issuance',
      'Mezzanine and last-mile finance',
      'AIF investment structuring',
      'REIT-led acquisition and exit',
      'Inter-creditor arrangements (multiple lenders)',
      'Security creation — mortgage, hypothecation, escrow, share pledge',
      'CERSAI, ROC and sub-registrar filings',
      'Drawdown mechanics and financial covenants',
      'Default, restructuring and IBC pathways',
    ],
    process: [
      { title: 'Term Sheet', desc: 'Capture key commercial terms — quantum, tenor, pricing, security, milestones.' },
      { title: 'Diligence', desc: 'Lender-side title, project, RERA, environmental, regulatory diligence.' },
      { title: 'Documentation', desc: 'Loan agreement, security documents, escrow, inter-creditor (where multi-lender).' },
      { title: 'Security Creation', desc: 'Mortgage, hypothecation, share pledge, CERSAI / ROC filings.' },
      { title: 'Drawdown', desc: 'Construction-stage drawdowns linked to architect / engineer certifications.' },
      { title: 'Repayment / Exit', desc: 'Repayment from sales / refinance / take-out finance.' },
    ],
    statutoryRefs: [
      { name: 'SARFAESI Act, 2002', desc: 'Enforcement of secured interests.' },
      { name: 'Companies Act, 2013 — Sections 71, 77', desc: 'Debenture issuance and charge filings.' },
      { name: 'AIF Regulations, 2012', desc: 'Alternate Investment Funds for real estate.' },
      { name: 'REIT Regulations, 2014', desc: 'Listed REIT framework.' },
      { name: 'FEMA, 1999', desc: 'Cross-border financing compliance.' },
    ],
    pitfalls: [
      { title: 'Inadequate Security', desc: 'Equitable mortgage without CERSAI registration is enforceable but evidentially weaker; insist on registered or registered-equitable.' },
      { title: 'No Inter-Creditor', desc: 'Multi-lender deals without ICA invite priority disputes at default.' },
      { title: 'RERA / Construction Risk', desc: 'Lender exposure to RERA penalty / project delay must be mapped and ringfenced.' },
      { title: 'Personal Guarantee Issues', desc: 'Promoter PG, while common, has IBC / family-property implications post-default.' },
    ],
    faqs: [
      { q: 'What is mezzanine finance in real estate?', a: 'Subordinate debt typically priced higher than senior bank debt, often with equity-like features (warrants, profit share). Used for last-mile financing or filling gaps between senior debt and equity.' },
      { q: 'Can REITs invest in under-construction projects?', a: 'Listed REITs primarily invest in completed and rent-yielding assets (80% requirement). Up to 20% can be in under-construction projects, with conditions.' },
      { q: 'What is the typical security package?', a: 'Mortgage of project land + construction; hypothecation of receivables; escrow of buyer collections; pledge of promoter shares; personal guarantee of promoters; assignment of rights under contracts.' },
      { q: 'How does RERA affect project finance?', a: 'RERA mandates 70% of buyer collections in project escrow; lender finance interacts with RERA escrow rules. Documentation must accommodate RERA timelines and escrow.' },
    ],
    relatedServices: [
      { name: 'RERA Registration & Compliances', href: '/services/property/real-estate/rera-registration' },
      { name: 'Sell / Purchase / Development of Land', href: '/services/property/real-estate/sell-purchase-development' },
      { name: 'CERSAI Verification', href: '/services/property/verification/cersai-verification' },
      { name: 'FDI in Real Estate', href: '/services/property/real-estate/fdi' },
    ],
  },

  'land-acquisition': {
    title: 'Land Acquisition',
    description:
      'Land acquisition advisory under the Right to Fair Compensation and Transparency in Land Acquisition Act, 2013 — for landowners, developers and government bodies.',
    keywords: [
      'land acquisition act 2013',
      'fair compensation land',
      'LARR Act',
      'compulsory land acquisition',
      'private land acquisition',
      'Section 11 notification',
      'social impact assessment',
    ],
    overview:
      'Land acquisition in India operates under two primary frameworks: (a) the Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013 (LARR / RFCTLARR Act) for compulsory acquisition by Government for public purpose, and (b) private acquisition through purchase, JDA or aggregation under general property law.\n\nLARR Act mandates Social Impact Assessment, consent of 80% (private projects) / 70% (PPP projects) of affected families, fair compensation (2x rural / 1x urban), rehabilitation and resettlement, and transparent disposal. The 2013 framework substantially raises landowner protections compared to the colonial 1894 Act.\n\nWe represent landowners (compensation enhancement, R&R, displacement defence), acquiring authorities (notification drafting, SIA, consent), and developers (private land aggregation strategy, JDA structures). We litigate in High Courts and Supreme Court on acquisition disputes.',
    whyChooseUs: [
      { title: 'All Sides Experience', desc: 'Acted for landowners, authorities and developers — comprehensive perspective.' },
      { title: 'Compensation Enhancement', desc: 'Specialist in Section 64 / 73 LARR enhancement claims.' },
      { title: 'Aggregation Strategy', desc: 'Private land aggregation across hundreds of landowners with risk-allocated structures.' },
      { title: 'Constitutional Litigation', desc: 'Article 226 / 32 challenges to acquisition — High Court and Supreme Court.' },
    ],
    keyPoints: [
      'LARR Act, 2013 procedure (Sections 4, 11, 19, 23)',
      'Social Impact Assessment',
      'Consent of affected families (80% / 70%)',
      'Compensation calculation (multiplier-based)',
      'Rehabilitation and Resettlement (R&R)',
      'Section 64 enhancement before LAT',
      'Section 73 reference to civil court',
      'Urgency clause (Section 40) navigation',
      'Private land aggregation strategy',
      'Litigation in HC / SC against acquisition',
    ],
    process: [
      { title: 'Identification', desc: 'Identify acquisition trigger — government compulsory, voluntary purchase, JDA aggregation.' },
      { title: 'Stakeholder Map', desc: 'Affected families, gram panchayat, district authority.' },
      { title: 'Documentation / Reps', desc: 'Filing objections, R&R claims, compensation negotiations.' },
      { title: 'Quantum Litigation', desc: 'Where compensation is inadequate, file Section 64 enhancement before LAT.' },
      { title: 'Possession & Award', desc: 'Possession on award; payment received; civil court reference if objected.' },
    ],
    statutoryRefs: [
      { name: 'Right to Fair Compensation Act, 2013 (LARR / RFCTLARR)', desc: 'Primary statute for compulsory land acquisition.' },
      { name: 'State Amendments', desc: 'Several States have amended LARR Act for urgency / consent thresholds.' },
      { name: 'Constitution of India — Article 300A', desc: 'Right to property as constitutional right.' },
      { name: 'Land Acquisition Act, 1894 (now repealed)', desc: 'Old framework; older proceedings continue under transition provisions.' },
    ],
    pitfalls: [
      { title: 'Late Objections', desc: 'Objections must be filed within statutory time (30 days from Section 4 / 11 notification). Late objections are time-barred.' },
      { title: 'Inadequate Compensation Documentation', desc: 'Sale instances, valuation reports and exemplar evidence are critical for compensation enhancement.' },
      { title: 'Skipping R&R Claims', desc: 'Many landowners focus on compensation and miss R&R entitlements (employment, alternate land, training).' },
      { title: 'Voluntary Sale Confusion', desc: 'Voluntary sale to government / authority may not invoke LARR protections; understand the framework before signing.' },
    ],
    faqs: [
      { q: 'When does LARR Act apply?', a: 'For compulsory acquisition by Government / Government-controlled entities for public purpose. Voluntary sales and private aggregations are governed by general property law (TPA, Registration Act).' },
      { q: 'What compensation is payable under LARR?', a: 'Market value (based on circle rate or comparable instances, whichever higher) multiplied by factor (1x urban, 1-2x rural) plus 100% solatium plus interest and R&R entitlements.' },
      { q: 'Is consent of all landowners required?', a: '80% consent for private projects; 70% for PPP projects. Government public-purpose acquisition does not require consent (but SIA and other safeguards apply).' },
      { q: 'Can acquisition be challenged?', a: 'Yes — through Section 64 / 73 LARR for compensation; Article 226 writ for procedural defects; Article 32 SC for fundamental rights violation.' },
      { q: 'What about R&R for displaced families?', a: 'Comprehensive R&R entitlements — employment, residential plot / house, transportation allowance, livelihood training, basic amenities. Schedules under LARR Act prescribe quantums.' },
    ],
    relatedServices: [
      { name: 'Sell / Purchase / Development of Land', href: '/services/property/real-estate/sell-purchase-development' },
      { name: 'Land Scrutiny Report', href: '/services/property/verification/land-scrutiny-report' },
      { name: 'Property Dispute Resolution & Arbitration', href: '/services/property/real-estate/dispute-arbitration' },
      { name: 'PPP (Public Private Partnership)', href: '/services/property/real-estate/ppp' },
    ],
  },

  'litigation': {
    title: 'Real Estate Litigation (RERA)',
    description:
      'RERA Authority and Appellate Tribunal litigation — refund, possession, interest, structural defects, builder accountability and consumer-protection actions.',
    keywords: [
      'RERA litigation',
      'RERA Appellate Tribunal',
      'RERA complaint procedure',
      'flat possession delay',
      'RERA refund interest',
      'builder accountability',
      'apartment buyer rights',
    ],
    overview:
      'RERA Authority and the Real Estate Appellate Tribunal are the primary forums for real-estate disputes between flat buyers and developers. Common complaints include possession delay (Section 18), structural defects within 5-year liability (Section 14), unfair carpet area, hidden charges, change in plans without consent (Section 14) and refusal of refund.\n\nFlat buyers can file RERA complaints (Section 31), Consumer Forum complaints (concurrent jurisdiction) and writ petitions in some cases. Each forum has distinct procedure, timelines and reliefs. Strategic forum selection matters significantly — RERA is faster but limited; Consumer Forums are slower but offer broader compensation.\n\nWe represent both buyers (refund, possession, interest, compensation) and builders (defence, settlement negotiation, appeal). We handle RERA Authority proceedings, Appellate Tribunal appeals, High Court writ petitions and Supreme Court SLPs.',
    whyChooseUs: [
      { title: 'Forum Strategy', desc: 'RERA vs Consumer vs writ — choice based on facts, pace and relief.' },
      { title: 'Both-Side Experience', desc: 'Buyer and builder representation gives realistic outcome assessment.' },
      { title: 'Class / Group Complaints', desc: 'Coordinated multi-buyer complaints with shared evidence and counsel costs.' },
      { title: 'Settlement Negotiation', desc: 'Many cases settle pre-judgment — we negotiate from strength.' },
    ],
    keyPoints: [
      'RERA complaint under Section 31',
      'Possession delay claim under Section 18',
      'Structural defect claim under Section 14',
      'Carpet area / area change claims',
      'Consumer Forum complaints (concurrent jurisdiction)',
      'Appellate Tribunal appeals (Section 43)',
      'High Court / Supreme Court litigation',
      'Multi-buyer / class complaints',
      'Builder defence and settlement',
      'Decree execution and recovery',
    ],
    process: [
      { title: 'Diagnostic', desc: 'Map facts, identify violations, compute interest / damages, choose forum.' },
      { title: 'Notice', desc: 'Pre-complaint legal notice often resolves issues; mandatory in some cases.' },
      { title: 'Complaint Filing', desc: 'RERA / Consumer Forum complaint with detailed grounds and prayers.' },
      { title: 'Hearings', desc: 'Procedural and substantive hearings; evidence and arguments.' },
      { title: 'Order', desc: 'Order for refund, possession, interest, compensation as appropriate.' },
      { title: 'Appeal & Execution', desc: 'Appeal where adverse; execute favourable order through recovery proceedings.' },
    ],
    statutoryRefs: [
      { name: 'RERA Act, 2016 — Section 31', desc: 'Complaint procedure before Authority.' },
      { name: 'RERA Section 18', desc: 'Refund + interest on possession default.' },
      { name: 'RERA Section 14', desc: '5-year structural defect liability.' },
      { name: 'Consumer Protection Act, 2019', desc: 'Concurrent jurisdiction; flat purchasers are consumers (Bangalore Development Authority v. Vijaya Leasing).' },
      { name: 'Pioneer Urban v. Govindan (2019) SC', desc: 'Establishes flat-purchaser as financial creditor under IBC.' },
    ],
    pitfalls: [
      { title: 'Wrong Forum', desc: 'Filing in Consumer Forum where RERA jurisdiction is exclusive (or vice versa) wastes years.' },
      { title: 'Limitation Lapse', desc: 'RERA Section 18 has limitation; older claims may be time-barred. Act promptly.' },
      { title: 'Settlement at Sub-optimal Terms', desc: 'Builders often offer partial refund without interest; calculate full statutory entitlement before settling.' },
      { title: 'Execution Neglect', desc: 'RERA Authority orders need execution through District Magistrate; many decrees gather dust without execution drive.' },
    ],
    faqs: [
      { q: 'What can I claim if my flat is delayed?', a: 'Under Section 18 RERA: (a) Refund of all amounts paid + interest at SBI MCLR + 2% (typically 10-12% p.a.), or (b) Continue to await possession + monthly interest until possession.' },
      { q: 'Where do I file my complaint — RERA or Consumer Forum?', a: 'Either — Supreme Court has confirmed concurrent jurisdiction. RERA is faster; Consumer Forum can grant broader compensation. Our recommendation depends on specific facts and goals.' },
      { q: 'How long does RERA litigation take?', a: 'RERA Authority order: 60-180 days typically. Appellate Tribunal appeal: 90-180 days. High Court writ: 12-30 months. Supreme Court SLP: variable.' },
      { q: 'Can I withdraw if I miss the registered Builder Buyer Agreement?', a: 'RERA protections apply regardless of BBA registration. Section 18 allows withdrawal on possession default — registration not a precondition.' },
      { q: 'Are settlement amounts taxable?', a: 'Refund of principal — not taxable. Interest component — taxable as "Income from Other Sources". Plan tax accordingly.' },
    ],
    relatedServices: [
      { name: 'RERA Registration & Compliances', href: '/services/property/real-estate/rera-registration' },
      { name: 'Builder Buyer Agreement', href: '/services/property/registration/builder-buyer-agreement' },
      { name: 'Property Dispute Resolution & Arbitration', href: '/services/property/real-estate/dispute-arbitration' },
      { name: 'Conveyance Deed Registration', href: '/services/property/registration/conveyance-deed' },
    ],
  },

  'title-clearance': {
    title: 'Title Clearance & Due Diligence',
    description:
      'Bank-grade Title Clearance Reports and comprehensive Due Diligence for property purchases, mortgages, REITs, AIF investments and portfolio acquisitions.',
    keywords: [
      'title clearance report',
      'title clearance lawyer',
      'comprehensive property DD',
      'title certificate property',
      'lender legal opinion',
      'investment grade title report',
    ],
    overview:
      'Title Clearance & Due Diligence is the comprehensive verification a property must undergo before any major transaction — bank loan sanction, REIT acquisition, AIF investment, portfolio sale or large commercial purchase. It combines title search, encumbrance verification, regulatory compliance, litigation search, physical inspection and documentary review into a single Title Clearance Report.\n\nA bank-grade Title Clearance Report (TCR) is the gold standard — accepted by all PSU banks, private sector banks, NBFCs and large institutional buyers without re-verification. The TCR includes (a) chain of title for 30 years with each link analyzed, (b) encumbrance certificate analysis, (c) CERSAI search, (d) court / litigation search, (e) regulatory compliance audit (RERA, environmental, layout), (f) physical site inspection, (g) categorical opinion on marketability.\n\nOur senior real-estate counsel issue TCRs that are accepted by leading lenders without queries. We work with developers (for project-level TCRs), buyers (transaction-specific TCRs), banks (loan due diligence) and institutional investors (portfolio TCRs).',
    whyChooseUs: [
      { title: 'Bank-Empanelment', desc: 'Empanelled with leading PSU and private banks for legal opinions.' },
      { title: 'Senior Counsel Sign-Off', desc: 'TCRs signed by senior partner / counsel — carrying weight with institutional buyers.' },
      { title: 'Multi-Disciplinary', desc: 'Lawyers + surveyors + environmental + tax integrated under one project lead.' },
      { title: 'Portfolio Capability', desc: 'Capable of TCRs for 50-200 property portfolios under tight timelines.' },
    ],
    keyPoints: [
      '30-year title chain analysis',
      'Encumbrance Certificate verification',
      'CERSAI charge search',
      'Civil court / High Court litigation search',
      'RERA registration and compliance audit',
      'Approved plan, OC and layout verification',
      'Environmental clearance review (where applicable)',
      'Physical site inspection and boundary verification',
      'Statutory dues clearance (property tax, electricity, water)',
      'Society / RWA / association records',
      'Tax incentives and stamp duty optimization',
      'Categorical marketability opinion',
    ],
    process: [
      { title: 'Engagement', desc: 'Define scope — single property / portfolio, transaction type, lender / buyer requirements.' },
      { title: 'Document Compilation', desc: 'Comprehensive document request list; multi-source cross-verification.' },
      { title: 'Diligence Streams', desc: 'Title, regulatory, litigation, physical, tax — parallel workstreams.' },
      { title: 'Site Visit', desc: 'Physical inspection by surveyor / counsel; boundary verification; structural check.' },
      { title: 'Report', desc: 'Bank-grade TCR with executive summary, findings, risk matrix, marketability opinion.' },
      { title: 'Cure / Closing', desc: 'Where defects exist — coordinate cure (NOC, mutation, settlement) before closing.' },
    ],
    documents: [
      'All title chain documents (30 years)',
      'Encumbrance certificate (15-30 years)',
      'CERSAI search output',
      'Mutation extracts (Khata / 7-12 / Patta)',
      'Property tax receipts',
      'Approved plan, OC, layout',
      'RERA project disclosures',
      'Environmental and statutory clearances',
      'Society / RWA records',
      'Court litigation search outputs',
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882; Registration Act, 1908', desc: 'Title and registration framework.' },
      { name: 'RERA Act, 2016', desc: 'Real-estate project disclosures.' },
      { name: 'SARFAESI Act, 2002', desc: 'Lender enforcement framework — TCR is foundational.' },
      { name: 'Bank / RBI Guidelines', desc: 'PSU and private bank guidelines on legal opinions.' },
    ],
    pitfalls: [
      { title: 'Sample-Based Diligence', desc: 'For portfolios, sample-based diligence misses defective properties; full coverage essential for institutional buyers.' },
      { title: 'Skipping Site Visit', desc: 'Documentary review without physical inspection misses encroachments, neighbour disputes and structural issues.' },
      { title: 'Generic Opinion', desc: '"Title appears marketable subject to..." is not a useful opinion — categorical marketability with specified conditions / cure is what lenders / buyers need.' },
      { title: 'Outdated Searches', desc: 'EC and CERSAI older than 3 months may miss recent transactions; refresh just before closing.' },
    ],
    faqs: [
      { q: 'What is a Title Clearance Report?', a: 'Comprehensive report combining title search, encumbrance verification, regulatory compliance, litigation search, physical inspection and a categorical marketability opinion — typically required by lenders and institutional buyers.' },
      { q: 'How is TCR different from Title Search?', a: 'Title Search is the underlying chain-of-ownership verification. TCR includes Title Search + encumbrance + regulatory + physical inspection + opinion. TCR is comprehensive due diligence; Title Search is one component.' },
      { q: 'How long does TCR take?', a: '2-6 weeks for single property depending on complexity. Portfolios (50-200 properties) take 6-12 weeks with parallel teams.' },
      { q: 'Are TCRs accepted by all banks?', a: 'TCRs by empanelled lawyers are accepted by their empanelling banks. We are empanelled with most major PSU and private sector banks and NBFCs.' },
      { q: 'What if TCR finds defects?', a: 'Three options: (a) cure before closing, (b) negotiate price reduction or seller indemnity, (c) walk away. Defects may be curable (mutation lapse, missing NOC) or non-curable (defective chain, ongoing high-stakes litigation).' },
      { q: 'How much does TCR cost?', a: 'Single property: ₹50,000–₹3 lakh based on type and complexity. Portfolio: typically discounted per-property rate. Bank-empanelled rates often follow bank schedules.' },
    ],
    relatedServices: [
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Due Diligence Report', href: '/services/property/verification/due-diligence-report' },
      { name: 'Encumbrances Check', href: '/services/property/verification/encumbrances-check' },
      { name: 'CERSAI Verification', href: '/services/property/verification/cersai-verification' },
      { name: 'Land Scrutiny Report', href: '/services/property/verification/land-scrutiny-report' },
    ],
  },
};
