import type { ServiceContent } from '@/components/leaf-service-page';

export const propertyRegistrationServices: Record<string, ServiceContent> = {
  'sale-deed': {
    title: 'Sale Deed Registration',
    description:
      'Lawyer-drafted Sale Deed registration with title verification, stamp duty optimization and sub-registrar coordination across India.',
    keywords: [
      'sale deed registration',
      'property sale deed',
      'sale deed lawyer',
      'sale deed drafting',
      'stamp duty sale deed',
      'sub registrar property',
      'sale deed format India',
      'property transfer deed',
    ],
    overview:
      'A Sale Deed is the principal instrument of transfer for absolute ownership of immovable property in India. Governed by the Transfer of Property Act, 1882 and registered under the Registration Act, 1908, it is the only document that legally vests title from seller to buyer. A poorly drafted or improperly registered Sale Deed creates a defective title that surfaces years later — often in the next sale, mortgage or succession.\n\nOur property lawyers handle every aspect — preliminary title search, drafting, stamp duty computation under the relevant State Stamp Act, e-stamping, sub-registrar appointment booking, biometric verification and post-registration mutation. We close common loopholes — incorrect schedule of property, unnoticed encumbrances, missing witness signatures, mismatched aadhaar names — that derail registration or expose the buyer to litigation.\n\nWe represent both buyers and sellers across residential, commercial, industrial and agricultural properties, and act for NRIs through Power of Attorney.',
    whyChooseUs: [
      { title: 'Title-Verified Drafting', desc: 'Every Sale Deed we draft is preceded by a 30-year title search and encumbrance check.' },
      { title: 'Stamp Duty Optimization', desc: 'We apply circle rate vs market value reasoning and available concessions (women, first-time buyer, family transfer).' },
      { title: 'Sub-Registrar Coordination', desc: 'Slot booking, document verification and biometric appearance are coordinated end-to-end.' },
      { title: 'PAN-India Coverage', desc: 'Active in all major Indian States and Union Territories with on-ground associates.' },
    ],
    keyPoints: [
      'Drafting under Transfer of Property Act, 1882 with Section 54 compliance',
      '30-year title search and encumbrance verification',
      'Circle rate / collector rate vs market value optimization',
      'E-stamp paper procurement (SHCIL / authorized vendors)',
      'Sub-registrar slot booking and biometric coordination',
      'Witness arrangement and Aadhaar / ID verification',
      'Post-registration mutation in revenue / municipal records',
      'Capital gains tax advisory for seller (Section 54 / 54F / 54EC)',
      'TDS Section 194-IA compliance for sales above ₹50 lakh',
      'NRI Sale Deed via Power of Attorney',
    ],
    process: [
      { title: 'Title Search & Diligence', desc: 'Verify chain of title for last 30 years from sub-registrar, encumbrance certificate, mutation records, property tax receipts and pending litigation.' },
      { title: 'Sale Deed Drafting', desc: 'Comprehensive deed with detailed schedule of property, recitals, consideration, indemnity, possession clause and dispute resolution.' },
      { title: 'Stamp Duty & E-Stamping', desc: 'Compute stamp duty on higher of consideration or circle rate; pay via e-stamp / SHCIL; collect e-stamp paper.' },
      { title: 'Sub-Registrar Appointment', desc: 'Book slot online; ensure both parties + 2 witnesses present with Aadhaar / PAN; biometric capture.' },
      { title: 'Registration', desc: 'Sub-Registrar reads deed, captures photographs, biometrics; charges registration fee (typically 1%); deed receives unique registration number.' },
      { title: 'Mutation & Tax Updates', desc: 'Within 30-90 days, file mutation application with municipal / revenue authorities; transfer property tax records.' },
    ],
    documents: [
      'Title chain — past Sale Deeds for last 30 years',
      'Encumbrance certificate (15-30 years)',
      'Mother deed / parent document',
      'Latest property tax receipts',
      'Mutation extract (Khata / Patta)',
      'Approved building plan and Occupation Certificate',
      'NOC from society / RWA / lender if applicable',
      'PAN, Aadhaar of both parties + 2 witnesses',
      'Photos of property (recent)',
      'Power of Attorney (if executed by attorney holder)',
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882', desc: 'Section 54 defines "sale" and Section 55 sets out rights/liabilities of buyer & seller.' },
      { name: 'Registration Act, 1908', desc: 'Section 17 makes Sale Deeds compulsorily registrable; Section 49 makes unregistered deeds inadmissible.' },
      { name: 'Indian Stamp Act, 1899 / State Acts', desc: 'Stamp duty under State schedules; rates vary by State, gender, property type.' },
      { name: 'Income Tax Act, 1961', desc: 'Section 194-IA (TDS at 1% above ₹50 lakh); Sections 54/54F/54EC capital gains exemptions.' },
    ],
    pitfalls: [
      { title: 'Skipping Title Search', desc: 'Buyers who skip 30-year title search inherit hidden encumbrances, partition claims and litigation risk.' },
      { title: 'Under-Stating Consideration', desc: 'Paying stamp duty on circle rate while showing lower consideration triggers Section 50C / 56(2)(x) tax additions.' },
      { title: 'Missing Mutation', desc: 'Failure to mutate after registration means property tax, electricity, water remain in seller\'s name — risky for the buyer.' },
      { title: 'Verbal Possession Promises', desc: 'Possession clauses must be written in the Sale Deed; verbal promises are unenforceable.' },
    ],
    faqs: [
      { q: 'Is Sale Deed registration mandatory?', a: 'Yes — under Section 17 of the Registration Act, 1908, every Sale Deed of immovable property worth ₹100 or more must be compulsorily registered. An unregistered Sale Deed is inadmissible as evidence of title under Section 49.' },
      { q: 'How is stamp duty calculated for Sale Deed?', a: 'Stamp duty is calculated on the higher of (a) actual consideration or (b) circle rate / collector rate. Rates vary by State (typically 4–8%) and may include concessions for women buyers, first-time buyers and family transfers.' },
      { q: 'Can I register a Sale Deed online?', a: 'Most States allow online slot booking and document upload, but physical appearance of both parties + 2 witnesses at the Sub-Registrar office for biometric verification is mandatory. Some States allow video-based registration in limited cases.' },
      { q: 'What is the timeline for Sale Deed registration?', a: 'From document readiness, sub-registrar appointment is typically within 7-15 days. Registration itself takes 1-2 hours on the appointment date. Mutation post-registration takes 30-90 days.' },
      { q: 'Can NRIs execute Sale Deed remotely?', a: 'Yes — NRIs can execute via a notarized / apostilled Power of Attorney empowering an attorney holder in India to register the Sale Deed on their behalf. The PoA itself must be registered in India.' },
      { q: 'What is the difference between Sale Deed and Sale Agreement?', a: 'A Sale Agreement is a contract to sell in the future; it does not transfer title. A Sale Deed is the actual conveyance instrument that transfers title. Both are commonly used together — agreement first, deed at closing.' },
      { q: 'What if circle rate is higher than my actual price?', a: 'You must pay stamp duty on the higher circle rate. Tax officials may also treat the difference as deemed income under Section 56(2)(x) for buyer and Section 50C for seller. Proper documentation of why market rate is lower (distress sale, family circumstances) helps mitigate this.' },
    ],
    relatedServices: [
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Encumbrances Check', href: '/services/property/verification/encumbrances-check' },
      { name: 'Mutation', href: '/services/property/registration/mutation' },
      { name: 'Due Diligence Report', href: '/services/property/verification/due-diligence-report' },
      { name: 'Agreement to Sale', href: '/services/property/registration/agreement-to-sale' },
      { name: 'Builder Buyer Agreement', href: '/services/property/registration/builder-buyer-agreement' },
    ],
  },

  'gift-deed': {
    title: 'Gift Deed Registration',
    description:
      'Legally compliant Gift Deed drafting and registration for transferring property without consideration — among family members, charitable purposes or friends.',
    keywords: [
      'gift deed registration',
      'gift deed property India',
      'gift deed lawyer',
      'gift deed stamp duty',
      'family gift deed',
      'donor donee gift deed',
      'gift deed format',
    ],
    overview:
      'A Gift Deed is the legal instrument under Section 122 of the Transfer of Property Act, 1882 to voluntarily transfer immovable property without consideration. It is widely used for transfers within families — between parents and children, husband and wife, siblings — and for charitable / religious endowments.\n\nUnlike a Sale Deed, a Gift Deed records a transfer "without consideration" but with acceptance by the donee during the donor\'s lifetime. It must be registered to be valid (Section 123 TPA r/w Section 17 Registration Act). Most States offer concessional stamp duty for gifts to specified relatives — typically 1–3% versus 5–8% for sale.\n\nOur lawyers handle every nuance — verifying capacity to gift (donor must own clearly), drafting acceptance, navigating concessional duty, ensuring proper attestation by 2 witnesses and managing post-registration mutation. We also advise on income-tax implications under Section 56(2)(x) for non-relative gifts.',
    whyChooseUs: [
      { title: 'Family-Sensitive Drafting', desc: 'Gift deeds within families need careful drafting around revocation, conditional gifts and survivorship.' },
      { title: 'Concessional Duty Capture', desc: 'We ensure correct relative-status proof to claim State concessional stamp duty.' },
      { title: 'Tax-Compliant Structuring', desc: 'Section 56(2)(x) implications mapped for both donor and donee.' },
      { title: 'Clean Mutation', desc: 'Post-registration mutation handled to update revenue and tax records.' },
    ],
    keyPoints: [
      'Drafting under TPA Section 122 with conditional / unconditional clauses',
      'Donor capacity verification (sound mind, ownership, not under coercion)',
      'Donee acceptance during donor\'s lifetime (Section 122 TPA)',
      'Concessional stamp duty for specified relatives',
      'Two-witness attestation as statutorily required',
      'Sub-registrar registration under Section 17 Registration Act',
      'Mutation in revenue / municipal records',
      'Income-tax Section 56(2)(x) advisory for donee',
      'Revocation strategy where reservation of life interest desired',
      'NRI gift deeds via PoA',
    ],
    process: [
      { title: 'Capacity & Title Check', desc: 'Verify donor is the absolute owner with clean title and full mental capacity.' },
      { title: 'Gift Deed Drafting', desc: 'Detailed deed including donor-donee relationship, schedule, recitals, acceptance, conditions (if any) and indemnity.' },
      { title: 'Stamp Duty & E-Stamping', desc: 'Pay concessional duty (where applicable) on circle rate; obtain e-stamp paper.' },
      { title: 'Registration', desc: 'Sub-registrar registration with both parties + 2 witnesses; biometric capture.' },
      { title: 'Mutation', desc: 'File mutation with municipal / revenue authorities to transfer records.' },
    ],
    documents: [
      'Donor\'s ID and address proof (Aadhaar / PAN)',
      'Donee\'s ID and address proof',
      'Property title chain (Sale Deed, partition deed etc.)',
      'Encumbrance certificate (15+ years)',
      'Property tax receipts and mutation extract',
      'Approved building plan / OC',
      'Relationship proof (for concessional duty)',
      'Two witnesses with ID',
      'NOC from society / RWA if applicable',
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882 — Sections 122–129', desc: 'Defines gift, conditions, acceptance, revocation and onerous gifts.' },
      { name: 'Registration Act, 1908 — Section 17', desc: 'Mandatory registration for gift of immovable property.' },
      { name: 'Indian Stamp Act / State Acts', desc: 'Concessional stamp duty for gift to relatives — Schedule 1A entry "Gift".' },
      { name: 'Income Tax Act, 1961 — Section 56(2)(x)', desc: 'Gifts above ₹50,000 from non-relatives are taxable in donee\'s hands.' },
    ],
    pitfalls: [
      { title: 'Acceptance Not on Record', desc: 'Acceptance must be evidenced in the deed itself or by acts during donor\'s lifetime — silence is not acceptance.' },
      { title: 'Conditional Gifts Drafted Vaguely', desc: 'Conditions like "donee shall maintain donor for life" need precise drafting and revocation triggers.' },
      { title: 'Wrong Relative Category', desc: 'Some States limit "relative" concession to specified categories (spouse, lineal ascendant/descendant). Wrong claim invites duty + penalty.' },
      { title: 'Skipping Registration', desc: 'An unregistered Gift Deed is void for immovable property — many family disputes arise from this oversight.' },
    ],
    faqs: [
      { q: 'Is stamp duty payable on Gift Deed?', a: 'Yes — but most States offer concessional duty (1-3%) for gifts to specified relatives (spouse, parents, children, siblings). Non-relative gifts attract regular sale rates.' },
      { q: 'Can a Gift Deed be revoked?', a: 'A Gift Deed once executed and registered is generally irrevocable, except (a) by mutual agreement, (b) on conditions specified in the deed itself, or (c) where consent was obtained by fraud or coercion (Section 126 TPA).' },
      { q: 'Are there income-tax implications?', a: 'Gifts from "relatives" (as defined in Section 56) are tax-exempt for the donee. Non-relative gifts above ₹50,000 in aggregate per year are taxable as income in the donee\'s hands.' },
      { q: 'Can I gift property to a minor?', a: 'Yes — through their natural guardian. The guardian accepts on behalf of the minor. The minor takes possession on attaining majority.' },
      { q: 'Can NRIs receive Gift Deeds?', a: 'Yes — NRIs can receive immovable property as gift from a person resident in India under FEMA (subject to property type — agricultural / plantation / farmhouse have restrictions).' },
      { q: 'What is the difference between Gift Deed and Will?', a: 'A Gift Deed transfers ownership immediately on registration. A Will operates only on the testator\'s death and is revocable any time before. Both serve estate-planning purposes differently.' },
    ],
    relatedServices: [
      { name: 'Will Registration', href: '/services/property/registration/will-registration' },
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Mutation', href: '/services/property/registration/mutation' },
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
    ],
  },

  'lease-deed': {
    title: 'Lease Deed Registration',
    description:
      'Drafting and registration of long-term Lease Deeds and rental agreements with stamp duty optimization, tenant verification and dispute-proof clauses.',
    keywords: [
      'lease deed registration',
      'long term lease deed',
      'rental agreement lawyer',
      'lease agreement India',
      'stamp duty lease',
      'commercial lease deed',
      'landlord tenant agreement',
    ],
    overview:
      'A Lease Deed is the legal contract under Section 105 of the Transfer of Property Act, 1882 by which a lessor (owner) transfers a right to enjoy immovable property to a lessee for a specified period in exchange for rent or premium. Leases for any term over one year, or reserving an annual rent, are compulsorily registrable under Section 17(1)(d) of the Registration Act, 1908.\n\nOur property lawyers draft and register residential, commercial, industrial and long-term land leases — incorporating clauses that often determine the outcome of disputes years later. We optimize stamp duty (which varies dramatically by lease term and State), incorporate proper renewal and termination triggers, security-deposit treatment, GST implications, lock-in periods and arbitration clauses.\n\nWe also advise on rental agreements under 11 months that are not compulsorily registrable but should still be properly stamped and notarized to be admissible in court.',
    whyChooseUs: [
      { title: 'Term-Tuned Stamp Duty', desc: 'We compute the right duty bracket — leases up to 1, 3, 5, 10, 30 years carry materially different rates.' },
      { title: 'Dispute-Resilient Clauses', desc: 'Renewal, termination, lock-in, security deposit — drafted to survive litigation.' },
      { title: 'GST & TDS Mapping', desc: 'Rent above ₹2.4L/year attracts TDS; commercial rent may attract GST — we structure cleanly.' },
      { title: 'Society / RWA NOC Handling', desc: 'Where the property is in a society, we coordinate the NOC alongside drafting.' },
    ],
    keyPoints: [
      'Lease drafting under TPA Section 105 with all material terms',
      'Term selection (11 months, 1, 3, 5, 10, 30, 99 years) and stamp duty optimization',
      'Section 17(1)(d) compulsory registration for leases > 1 year',
      'Security deposit terms and forfeiture triggers',
      'Renewal options and rent escalation (CPI / fixed %)',
      'Lock-in period and exit clauses',
      'Permitted use, alterations and sub-lease restrictions',
      'GST applicability for commercial leases',
      'TDS Section 194-I compliance',
      'Arbitration / dispute resolution clause',
    ],
    process: [
      { title: 'Term Sheet', desc: 'Capture commercials — rent, deposit, lock-in, term, renewal, escalation, deposit refund.' },
      { title: 'Drafting', desc: 'Detailed lease deed with schedule of property, fitting-out terms, repair obligations, indemnity and arbitration.' },
      { title: 'Stamp Duty', desc: 'Compute on annual rent + premium based on State schedule for the chosen term.' },
      { title: 'Registration', desc: 'Sub-registrar registration with both parties + 2 witnesses (mandatory for leases > 1 year).' },
      { title: 'Tenancy Onboarding', desc: 'Possession handover with inventory, key handover, deposit receipt and society / RWA intimation.' },
    ],
    documents: [
      'Lessor and lessee ID / Aadhaar / PAN',
      'Property title document (Sale Deed)',
      'Latest property tax receipts',
      'Society / RWA NOC',
      'Rent receipts (if existing tenancy)',
      'Two witnesses with ID',
      'Existing lease (if renewal)',
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882 — Sections 105–117', desc: 'Definition, rights, duties, determination and forfeiture of leases.' },
      { name: 'Registration Act, 1908 — Section 17(1)(d)', desc: 'Mandatory registration for leases over 1 year or reserving yearly rent.' },
      { name: 'Indian Stamp Act / State Schedules', desc: 'Stamp duty varies by lease term — typically 0.5%–8% of average annual rent.' },
      { name: 'Income Tax Act, 1961 — Section 194-I', desc: 'TDS @ 10% on rent above ₹2.4 lakh/year by the tenant.' },
    ],
    pitfalls: [
      { title: 'Treating 11-Month Lease as a Loophole', desc: 'Repeated 11-month renewals to evade registration are noted — courts treat them as continuous tenancies, with risks.' },
      { title: 'Missing Lock-in Symmetry', desc: 'Lock-in must protect both parties; one-sided lock-in is often struck down.' },
      { title: 'Vague Maintenance Allocation', desc: 'Painting, plumbing, AC service — explicitly allocate or face disputes at exit.' },
      { title: 'No Arbitration Clause', desc: 'Litigation in rent matters drags 3-7 years; arbitration with a sole arbitrator is faster.' },
    ],
    faqs: [
      { q: 'When is registration mandatory for a lease?', a: 'Under Section 17(1)(d) of the Registration Act, every lease for a term exceeding 12 months OR reserving a yearly rent is compulsorily registrable. Shorter leases may be optionally registered.' },
      { q: 'Why are 11-month leases popular?', a: 'They avoid mandatory registration and often attract lower stamp duty. However, they cannot be used to evade rent control or Section 17(1)(d) — courts look at substance over form.' },
      { q: 'Is GST applicable on rent?', a: 'GST @ 18% applies on commercial / industrial rent if the landlord crosses the GST threshold. Residential rent for residential use is exempt; residential rent to a registered person for non-residential use attracts reverse charge GST.' },
      { q: 'Can security deposit be forfeited?', a: 'Only as per the deed. Indian courts view security deposit as a refundable deposit, not advance rent — forfeiture beyond agreed deductions is reversed.' },
      { q: 'What about Rent Control Acts?', a: 'Several States have Rent Control Acts that override certain lease terms (eviction grounds, rent increase). Whether a property falls under rent control depends on the State, age of premises and rent threshold.' },
      { q: 'Can a tenant sub-let?', a: 'Only if the lease deed expressly permits sub-letting. Most leases prohibit sub-letting without written consent — unauthorized sub-letting is a ground for eviction.' },
    ],
    relatedServices: [
      { name: 'Rent / Lease Agreement', href: '/services/documentation/legal/rent-lease-agreement' },
      { name: 'Conveyance Deed Registration', href: '/services/property/registration/conveyance-deed' },
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
    ],
  },

  'conveyance-deed': {
    title: 'Conveyance Deed Registration',
    description:
      'Conveyance Deed drafting and registration for transfer of common areas in housing societies, builder-to-society conveyance and absolute property transfers.',
    keywords: [
      'conveyance deed',
      'society conveyance deed',
      'deemed conveyance',
      'builder society conveyance',
      'conveyance deed registration',
      'conveyance lawyer Maharashtra',
    ],
    overview:
      'A Conveyance Deed is the instrument by which legal title in immovable property — including land, common areas and structures — is transferred. In housing societies (especially in Maharashtra under MOFA, 1963 / RERA, 2016), Conveyance Deed transfers ownership of land and common amenities from the builder to the cooperative housing society or apartment association.\n\nWhere the builder fails to execute conveyance within the statutory period, societies can apply for Deemed Conveyance under Section 11 of MOFA. Our lawyers handle both regular Conveyance Deeds and Deemed Conveyance applications — coordinating with sub-registrars, builders, society committees and District Deputy Registrar.\n\nWe also draft Conveyance Deeds for outright property transfers (similar to Sale Deeds) where the term "conveyance" is used in property practice.',
    whyChooseUs: [
      { title: 'Society Conveyance Specialists', desc: 'We handle dozens of society conveyances annually — including Deemed Conveyance under MOFA / RERA.' },
      { title: 'Builder-Side Coordination', desc: 'We negotiate with builders to execute conveyance and exit holdouts.' },
      { title: 'Regulatory Filings', desc: 'RERA filings, AGM resolutions and DDR applications managed end-to-end.' },
      { title: 'Property Tax & Mutation', desc: 'Post-conveyance updates with municipal records included.' },
    ],
    keyPoints: [
      'Conveyance Deed drafting under TPA',
      'Society / Apartment Conveyance under MOFA, 1963',
      'Deemed Conveyance application before DDR',
      'RERA Section 17 conveyance compliance for new projects',
      'Schedule of land, common areas and amenities',
      'Stamp duty optimization (concessional for society conveyance in some States)',
      'Sub-registrar coordination and biometric appearance',
      'Mutation of land in society / association name',
      'AGM resolution and committee authorization',
      'Indemnity from builder for hidden defects / unpaid dues',
    ],
    process: [
      { title: 'Project Diagnosis', desc: 'Verify builder\'s title chain, AGREEMENTS, RERA registration and conveyance status.' },
      { title: 'Negotiation / Demand', desc: 'Issue legal notice; negotiate where builder is willing.' },
      { title: 'Deemed Conveyance Application', desc: 'If builder unresponsive, file before District Deputy Registrar with society resolutions and project documents.' },
      { title: 'Deed Drafting', desc: 'Detailed deed with schedule, recitals and indemnities.' },
      { title: 'Registration', desc: 'Sub-registrar registration; payment of stamp duty (often concessional).' },
      { title: 'Mutation', desc: 'Update property cards, tax records and society records.' },
    ],
    documents: [
      'Builder agreements (Sale Deed, Allotment Letter)',
      'Approved layout, building plan, OC',
      'Society registration certificate',
      'Members\' list and shareholding',
      'AGM resolution authorizing conveyance',
      'RERA registration and disclosures',
      'Property tax receipts and 7/12 / Khata',
      'NOC from builder / lender (if any)',
    ],
    statutoryRefs: [
      { name: 'Maharashtra Ownership Flats Act, 1963 — Section 11', desc: 'Mandates conveyance to society within 4 months of formation; Deemed Conveyance remedy.' },
      { name: 'RERA Act, 2016 — Section 17', desc: 'Promoter must execute conveyance to allottees / association of allottees.' },
      { name: 'Transfer of Property Act, 1882', desc: 'General provisions governing transfer of immovable property.' },
      { name: 'Registration Act, 1908', desc: 'Mandatory registration for conveyance of immovable property.' },
    ],
    pitfalls: [
      { title: 'Accepting Conveyance Without Land', desc: 'Some builders convey only flats / structures, retaining land — a major risk to society.' },
      { title: 'Missing RERA Compliance Verification', desc: 'Verify builder\'s RERA registration, audit reports and project completion before accepting conveyance.' },
      { title: 'No Indemnity from Builder', desc: 'Conveyance should include builder indemnity for past liabilities, taxes, statutory dues.' },
      { title: 'Society Resolutions Vague', desc: 'AGM resolution authorizing conveyance must be detailed, with specific members and authorization to sign.' },
    ],
    faqs: [
      { q: 'What is the difference between Sale Deed and Conveyance Deed?', a: 'In practice the terms overlap. Strictly, "Sale Deed" refers to outright transfer for consideration; "Conveyance Deed" is broader — including transfer of common areas, conveyance to societies and other instruments of transfer. Society Conveyance specifically refers to MOFA / RERA society conveyance.' },
      { q: 'What is Deemed Conveyance?', a: 'When a builder fails to execute society conveyance within statutory time (4 months under MOFA Maharashtra), the society can apply to the District Deputy Registrar for Deemed Conveyance under Section 11 of MOFA — a unilateral conveyance order.' },
      { q: 'How long does Deemed Conveyance take?', a: 'Typically 6-18 months — comprising society resolution, application drafting, hearing, builder objections (if any), DDR order and registration with sub-registrar.' },
      { q: 'Is stamp duty concessional for society conveyance?', a: 'Several States offer concessional duty for society conveyance — Maharashtra typically has nominal stamp duty for Deemed Conveyance. Verify based on State and project type.' },
      { q: 'Who pays stamp duty for society conveyance?', a: 'Stamp duty is typically paid by the society from members\' contributions, but the deed may allocate liability differently. Original sale agreements may have stamp-duty payment clauses.' },
    ],
    relatedServices: [
      { name: 'Builder Buyer Agreement', href: '/services/property/registration/builder-buyer-agreement' },
      { name: 'RERA Registration & Compliances', href: '/services/property/real-estate/rera-registration' },
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Real Estate Litigation (RERA)', href: '/services/property/real-estate/litigation' },
    ],
  },

  'agreement-to-sale': {
    title: 'Agreement to Sale',
    description:
      'Drafting and registration of Agreement to Sale (Sale Agreement) — preserving buyer rights, structuring earnest money, conditions precedent and dispute clauses.',
    keywords: [
      'agreement to sale',
      'sale agreement property',
      'sale agreement registration',
      'earnest money agreement',
      'agreement to sell India',
      'banakhat',
      'sale agreement lawyer',
    ],
    overview:
      'An Agreement to Sale (also called Sale Agreement, Sale-Cum-Sale Agreement or "Banakhat" in some regions) is the contract under Section 54 of the Transfer of Property Act, 1882 by which the seller agrees to transfer property to the buyer at a future date upon fulfilment of conditions. Unlike a Sale Deed, it does not transfer title — it creates a binding right to claim conveyance.\n\nA well-drafted Agreement to Sale captures earnest money, balance payment schedule, conditions precedent (clear title, vacant possession, NOCs, loan disbursement), default clauses, specific performance rights and force-majeure terms. In some States, the Agreement to Sale must be stamped and registered to be admissible — Maharashtra mandates stamping of agreements for sale of flats under MOFA.\n\nOur lawyers draft buyer-protective and seller-protective agreements depending on which side we represent, capturing the realistic transaction architecture and protecting the deposit / earnest money.',
    whyChooseUs: [
      { title: 'Position-Aware Drafting', desc: 'Buyer-side drafting protects earnest money; seller-side protects against frivolous specific-performance claims.' },
      { title: 'Conditions Precedent Clarity', desc: 'NOCs, loan, vacant possession, society approval — explicitly mapped with timelines and consequences.' },
      { title: 'Specific Performance Mapping', desc: 'We structure agreements to preserve / limit specific-performance remedy under SRA, 1963.' },
      { title: 'Stamp Duty Strategy', desc: 'Where Agreement to Sale is registered, stamp duty paid is adjusted against final Sale Deed duty.' },
    ],
    keyPoints: [
      'Drafting under TPA Section 54',
      'Earnest money and forfeiture / refund terms',
      'Balance payment schedule and instalments',
      'Conditions precedent — title, NOCs, possession, loan',
      'Indemnity for encumbrances and litigation',
      'Default clauses and time as essence',
      'Specific performance vs damages liquidation',
      'Force majeure and project delay handling',
      'GST and TDS allocation',
      'Arbitration / mediation dispute resolution',
    ],
    process: [
      { title: 'Term Sheet Capture', desc: 'Earnest money, total consideration, payment schedule, conditions precedent, exit triggers.' },
      { title: 'Title Diligence', desc: 'Verify seller\'s title before agreement; insert specific representations and warranties.' },
      { title: 'Drafting', desc: 'Comprehensive agreement with schedule of property and timeline matrix.' },
      { title: 'Stamping & Registration', desc: 'Stamp per State law; register where mandatory (e.g., Maharashtra under MOFA).' },
      { title: 'CP Tracking', desc: 'Monitor satisfaction of conditions; coordinate Sale Deed execution at closing.' },
    ],
    documents: [
      'Seller\'s title chain and parent documents',
      'Encumbrance certificate',
      'Approved building plan, OC, completion certificate',
      'NOC from society / lender / authority',
      'Buyer and seller IDs',
      'Earnest money payment proof',
      'Existing loan sanction (if buyer financed)',
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882 — Section 54', desc: 'Defines "agreement to sell" as not creating any interest in property until conveyance.' },
      { name: 'Specific Relief Act, 1963 (as amended)', desc: 'Right to specific performance of contract; revised post-2018 amendment to make specific performance the rule.' },
      { name: 'Indian Contract Act, 1872', desc: 'Validity, formation, performance and breach of contracts.' },
      { name: 'Maharashtra Ownership Flats Act, 1963', desc: 'Mandates stamping / registration of agreements to sell flats in Maharashtra.' },
    ],
    pitfalls: [
      { title: 'Vague Conditions Precedent', desc: 'CPs drafted vaguely ("all approvals to be obtained") create disputes about who is in default.' },
      { title: 'Missing Time-as-Essence Clause', desc: 'Without explicit "time is the essence", courts often grant extended periods, hurting the non-defaulting party.' },
      { title: 'Excessive Earnest Money Forfeiture', desc: 'Forfeiture clauses must be reasonable; courts strike down penalty clauses.' },
      { title: 'No Specific-Performance Strategy', desc: 'Especially after 2018 Specific Relief Act amendment, careful drafting determines whether specific performance is realistically obtainable.' },
    ],
    faqs: [
      { q: 'Does an Agreement to Sale transfer property?', a: 'No — under Section 54 of TPA, an Agreement to Sale "does not, of itself, create any interest in or charge on such property." Only a registered Sale Deed transfers title.' },
      { q: 'Is registration of Agreement to Sale mandatory?', a: 'Generally no, but specific State laws (e.g., MOFA in Maharashtra) require registration for flats. Even where not mandatory, registration provides stronger protection.' },
      { q: 'Can I claim specific performance if seller defaults?', a: 'Yes — under the Specific Relief Act, 1963 (as amended in 2018), specific performance is now a primary remedy (rather than discretionary) for contracts of sale of immovable property.' },
      { q: 'How much earnest money is reasonable?', a: 'Typically 10-25% of consideration. Excessive earnest money risks being treated as penalty (and refundable on default) rather than genuine pre-estimate of damages.' },
      { q: 'Can the agreement be cancelled?', a: 'Yes — by mutual agreement, or unilaterally if conditions precedent fail. Forfeiture / refund of earnest money depends on the clauses and which party is in default.' },
      { q: 'What happens if seller dies before Sale Deed?', a: 'The agreement binds the seller\'s legal heirs (Section 40 TPA). Buyer can enforce specific performance against the heirs / estate.' },
    ],
    relatedServices: [
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Builder Buyer Agreement', href: '/services/property/registration/builder-buyer-agreement' },
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Property Dispute Resolution & Arbitration', href: '/services/property/real-estate/dispute-arbitration' },
    ],
  },

  'mutation': {
    title: 'Mutation of Property',
    description:
      'End-to-end mutation services — updating property tax, revenue and municipal records after sale, gift, succession or partition transfer.',
    keywords: [
      'property mutation',
      'mutation of property records',
      'khata transfer',
      'patta transfer',
      'dakhal kharij',
      'mutation lawyer',
      'property tax mutation',
    ],
    overview:
      'Mutation (also called "Dakhal Kharij" in North India, "Khata Transfer" in Karnataka, "Patta" in Tamil Nadu) is the process of updating revenue / municipal records to reflect change in ownership of property. While not a title document by itself, mutation is critical for paying property tax, applying for utilities, claiming subsidies and proving possession.\n\nMutation is generally required after Sale, Gift, Will / Inheritance, Partition, Court Decree or Settlement. Each State has its own procedure — some require online filing, others physical applications. Failure to mutate after registration leaves property tax bills, utility connections and revenue records in the previous owner\'s name — creating problems for the new owner.\n\nOur property lawyers handle all categories of mutation — coordinating with municipal corporations, Tehsildar offices, Patwari, Village Accountants, BBMP / MCD / NMMC and other revenue authorities — including urgent expediting for time-sensitive transactions.',
    whyChooseUs: [
      { title: 'Multi-State Coverage', desc: 'BBMP Khata, Maharashtra Property Card, Delhi MCD, Tamil Nadu Patta, UP Dakhil-Kharij — we know each system.' },
      { title: 'Speedy Processing', desc: 'Standard mutations completed in 30-60 days; urgent track via objection follow-up.' },
      { title: 'Inheritance Mutation Specialist', desc: 'Succession-based mutation with legal heir certificates handled end-to-end.' },
      { title: 'Objection Handling', desc: 'Where third parties object, we represent in revenue court hearings.' },
    ],
    keyPoints: [
      'Mutation after Sale Deed registration',
      'Inheritance / succession mutation',
      'Partition / family settlement mutation',
      'Court decree mutation',
      'Khata Transfer / A-Khata / B-Khata (Karnataka)',
      'Property Card update (Maharashtra)',
      'MCD mutation in Delhi',
      'Patta / chitta in Tamil Nadu',
      'Tehsildar / Patwari coordination in rural areas',
      'Property tax record update',
    ],
    process: [
      { title: 'Document Compilation', desc: 'Gather Sale Deed / decree / will, IDs, photos, encumbrance certificate.' },
      { title: 'Application Filing', desc: 'File mutation application (online / offline) with prescribed fee.' },
      { title: 'Verification & Notice', desc: 'Authority publishes notice (often in newspaper); period for objections (15-30 days).' },
      { title: 'Inspection / Hearing', desc: 'Site inspection or hearing where required; address objections.' },
      { title: 'Order & Record Update', desc: 'Mutation order issued; records updated; certificate / extract obtained.' },
    ],
    documents: [
      'Sale Deed / Gift Deed / Will / Decree (registered)',
      'Old Khata / Patta / Property Card extract',
      'Latest property tax receipts',
      'Encumbrance certificate',
      'Aadhaar / PAN of applicant',
      'Photographs of property',
      'Death certificate (for inheritance)',
      'Legal heir / succession certificate (where applicable)',
      'NOC from co-heirs (for partial mutation)',
    ],
    statutoryRefs: [
      { name: 'State Revenue Codes / Land Records Acts', desc: 'Each State has its own statute — Karnataka Land Revenue Act, Maharashtra Land Revenue Code, Delhi Land Reforms Act, etc.' },
      { name: 'Municipal Corporation Acts', desc: 'For urban properties — BBMP Act, MMC Act, DMC Act etc. govern Khata / property tax mutation.' },
      { name: 'Hindu Succession Act, 1956 / Indian Succession Act, 1925', desc: 'Govern inheritance-based mutation.' },
    ],
    pitfalls: [
      { title: 'Skipping Mutation After Purchase', desc: 'Buyers often defer mutation — leading to property tax notices in seller\'s name and complications at next sale.' },
      { title: 'A-Khata vs B-Khata Confusion (Karnataka)', desc: 'B-Khata properties have constraints — buyers must understand Khata category before purchase.' },
      { title: 'Missing Co-Heir Consent', desc: 'For inheritance mutation, missing NOC from one co-heir invites objection and reversal.' },
      { title: 'Wrong Tehsil / Authority', desc: 'Filing in wrong jurisdiction wastes 2-3 months; jurisdictional verification at the start saves time.' },
    ],
    faqs: [
      { q: 'Is mutation mandatory after buying property?', a: 'Strictly, mutation is not the document of title — Sale Deed is. But mutation is essential for property tax, utility connections, loans and proving possession. Skipping it causes practical problems even though title remains valid.' },
      { q: 'How long does mutation take?', a: 'Typically 30-90 days from filing, depending on State, urban / rural and complexity. Urban mutations (Khata transfer, MCD mutation) are faster than rural Tehsildar mutations.' },
      { q: 'What is the difference between A-Khata and B-Khata?', a: 'In Karnataka, A-Khata is for properties that comply with all building bylaws and are eligible for loans / building permission. B-Khata is for non-compliant properties (no plan sanction, layout violations) — they pay tax but cannot get full sanction.' },
      { q: 'Can I get loan on B-Khata property?', a: 'Most banks decline loans on B-Khata; some NBFCs lend at higher rates. B-Khata to A-Khata conversion is possible through regularization (Akrama-Sakrama or similar State schemes).' },
      { q: 'Can mutation be challenged?', a: 'Yes — mutation orders can be challenged before higher revenue authorities (Tahsildar > AC > DC > Divisional Commissioner) and ultimately civil courts. But mutation does not by itself decide title — title disputes are decided by civil courts.' },
    ],
    relatedServices: [
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Legal Heir Certificate', href: '/services/property/verification/legal-heir-certificate' },
      { name: 'Succession Certificate', href: '/services/property/verification/succession-certificate' },
      { name: 'Will Registration', href: '/services/property/registration/will-registration' },
    ],
  },

  'transfer-of-memorandum': {
    title: 'Transfer of Memorandum (TM)',
    description:
      'Drafting and registration of Transfer of Memorandum for transfer of leasehold rights, allotments and assignments of immovable property interests.',
    keywords: [
      'transfer of memorandum',
      'TM property',
      'leasehold transfer memorandum',
      'allotment transfer',
      'memorandum of transfer',
    ],
    overview:
      'A Transfer of Memorandum (TM) is the instrument by which leasehold rights, allotment letters (in DDA, GDA, NOIDA, HUDA, MHADA, CIDCO etc.) or other assignable property interests are transferred from one holder to another. Unlike Sale Deeds (which transfer ownership), a TM transfers a leasehold or contractual interest — but is no less critical and commonly required when buying / selling lease-hold flats and allotted plots.\n\nThe TM must be executed on appropriate stamp paper, accompanied by a No-Objection Certificate (NOC) from the lessor / authority, and registered where the underlying interest exceeds 12-month tenor. Authority approvals (e.g., DDA / DDA conversion, MHADA NOC) often run in parallel.\n\nOur lawyers handle TM drafting, NOC procurement, authority approvals, sub-registrar registration and post-transfer mutation in authority records — for both buyer and seller side transactions.',
    whyChooseUs: [
      { title: 'Authority-Specific Expertise', desc: 'DDA, MHADA, CIDCO, HUDA, NOIDA — each has distinct TM procedures and we navigate each.' },
      { title: 'NOC Coordination', desc: 'NOC procurement from authority / lessor handled alongside drafting.' },
      { title: 'Conversion Advisory', desc: 'For leasehold-to-freehold conversions (DDA), we run parallel applications.' },
      { title: 'Mutation Closure', desc: 'Records updated in authority allotment register — not just sub-registrar.' },
    ],
    keyPoints: [
      'TM drafting for leasehold / allotment transfer',
      'Authority NOC and approval procurement',
      'DDA / MHADA / CIDCO / HUDA / NOIDA / GDA TM procedures',
      'Stamp duty assessment (varies by authority and tenor)',
      'Sub-registrar registration where mandatory',
      'Authority-side mutation in allotment register',
      'Conversion to freehold (DDA leasehold to freehold)',
      'Indemnity for unpaid lease rent / dues',
      'Possession transfer protocol',
      'Power of Attorney support for NRIs',
    ],
    process: [
      { title: 'Authority Verification', desc: 'Confirm allotment status, lease term, paid-up status, restrictions.' },
      { title: 'NOC Procurement', desc: 'Apply to authority for transfer NOC; respond to queries; obtain approval.' },
      { title: 'TM Drafting', desc: 'Tailored memorandum with schedule, indemnities and authority terms.' },
      { title: 'Stamping & Registration', desc: 'Stamp per State law; register at sub-registrar.' },
      { title: 'Authority Mutation', desc: 'Update allotment records with authority; collect new allotment letter / lease deed.' },
    ],
    documents: [
      'Original allotment letter / lease deed',
      'Possession letter / handing-over certificate',
      'Lease rent / maintenance dues clearance',
      'Authority NOC for transfer',
      'IDs of transferor and transferee',
      'Stamp duty payment proof',
      'Power of Attorney (if applicable)',
      'Bank consent (if mortgaged)',
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882', desc: 'General principles of assignment of leasehold interests.' },
      { name: 'Authority-Specific Regulations', desc: 'DDA Lease & Conveyance Rules, MHADA Regulations, CIDCO Disposal Regulations etc.' },
      { name: 'Registration Act, 1908', desc: 'Compulsory registration where transfer exceeds 12 months.' },
    ],
    pitfalls: [
      { title: 'Skipping Authority NOC', desc: 'Many private TMs are executed without authority NOC — these are void against the lessor and unenforceable.' },
      { title: 'Unpaid Lease Rent', desc: 'Authority will refuse mutation if lease rent / maintenance is unpaid; verify before purchase.' },
      { title: 'Restrictive Use Clauses', desc: 'Allotments often restrict use (residential only, no commercial) — TM does not change these.' },
      { title: 'Conversion Status Confusion', desc: 'Some allotted properties have been converted to freehold; verify the actual status, not assumptions.' },
    ],
    faqs: [
      { q: 'When is a TM used instead of Sale Deed?', a: 'When the property is held on leasehold or under an allotment from a development authority (DDA, MHADA, etc.), the holder cannot execute a Sale Deed of ownership — only a Transfer of Memorandum / assignment of leasehold interest.' },
      { q: 'Is authority NOC mandatory?', a: 'Yes — for DDA, MHADA, CIDCO, NOIDA, GDA and similar authority allotments, transfer without authority NOC is void against the authority and unenforceable.' },
      { q: 'Can DDA leasehold be converted to freehold?', a: 'Yes — DDA conversion scheme allows leasehold flats to be converted to freehold by paying conversion charges. Many TMs are executed alongside conversion applications.' },
      { q: 'Is stamp duty same as Sale Deed?', a: 'No — stamp duty varies by State and authority; some States offer concessional duty for authority transfers. Verify with the specific authority and State.' },
      { q: 'Can NRIs purchase via TM?', a: 'Yes — NRIs can acquire leasehold property via TM, subject to FEMA restrictions and authority-specific eligibility.' },
    ],
    relatedServices: [
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Conveyance Deed Registration', href: '/services/property/registration/conveyance-deed' },
      { name: 'Mutation', href: '/services/property/registration/mutation' },
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
    ],
  },

  'will-registration': {
    title: 'Will Registration',
    description:
      'Professional Will drafting and registration under the Indian Succession Act — testamentary planning, executor appointment and probate readiness.',
    keywords: [
      'will registration India',
      'will drafting lawyer',
      'testamentary planning',
      'probate ready will',
      'will registration sub registrar',
      'NRI will India',
      'unprivileged will',
    ],
    overview:
      'A Will is a legal declaration by a testator regarding the distribution of their property after death, governed by the Indian Succession Act, 1925. While registration of a Will is optional under Section 18 of the Registration Act, 1908, registration significantly strengthens the Will\'s presumption of validity and reduces challenges from disgruntled heirs.\n\nA properly drafted Will covers self-acquired and ancestral interests, appointment of executor, alternate beneficiaries, contingencies (heir predeceasing testator), specific bequests, residuary clauses, debt and tax instructions, charitable bequests and burial / funeral instructions. NRIs can execute Indian Wills for their Indian properties — typically separate from their overseas Wills.\n\nOur estate-planning lawyers draft and register Wills for individuals, joint Wills for spouses, mutual Wills, conditional Wills and testamentary trusts. We coordinate registration at sub-registrar offices and store originals securely. We also advise on probate strategy and challenges to validity.',
    whyChooseUs: [
      { title: 'Holistic Estate Planning', desc: 'Will drafting integrated with HUF, trusts, nominations, joint accounts and PoA strategy.' },
      { title: 'Probate-Ready Drafting', desc: 'Wills drafted to anticipate challenge — capacity proof, witness coordination, originality safeguards.' },
      { title: 'NRI Coordination', desc: 'Indian Wills for Indian assets, alongside foreign Will harmonization.' },
      { title: 'Secure Storage', desc: 'Original Wills stored under attorney-client privilege; copies provided to executor.' },
    ],
    keyPoints: [
      'Will drafting under Indian Succession Act, 1925',
      'Testator capacity verification (sound mind, free will)',
      'Two-witness attestation as statutorily required',
      'Optional sub-registrar registration under Section 18 RA',
      'Joint and mutual Wills for spouses',
      'Executor and alternate executor appointment',
      'Specific and residuary bequests',
      'Conditional bequests and contingent beneficiaries',
      'Probate strategy advisory',
      'NRI Wills for Indian assets',
    ],
    process: [
      { title: 'Estate Mapping', desc: 'Inventory all assets — property, securities, bank accounts, businesses, IP, foreign assets.' },
      { title: 'Beneficiary Strategy', desc: 'Map beneficiaries, alternates, contingencies and rationale.' },
      { title: 'Drafting', desc: 'Comprehensive Will with executor, witnesses, contingencies, debt and tax instructions.' },
      { title: 'Execution', desc: 'Testator signs in presence of 2 witnesses who also sign in presence of testator and each other.' },
      { title: 'Registration (Optional)', desc: 'Register at sub-registrar; nominal fee. Original deposited at sub-registrar safe custody (in some States).' },
      { title: 'Storage & Updates', desc: 'Original safely stored; periodic review every 3-5 years and on life events.' },
    ],
    documents: [
      'Testator ID and address proof',
      'Two witnesses with ID',
      'Asset inventory and ownership documents',
      'Beneficiary IDs',
      'Existing Wills (for revocation reference)',
      'Medical / capacity certificate (for elderly testator)',
      'Death certificate of pre-deceased spouse (for joint Will)',
    ],
    statutoryRefs: [
      { name: 'Indian Succession Act, 1925 — Sections 57–63', desc: 'Governs creation, execution, attestation and revocation of Wills.' },
      { name: 'Registration Act, 1908 — Section 18', desc: 'Wills are optionally registrable; not compulsory.' },
      { name: 'Hindu Succession Act, 1956', desc: 'Governs intestate succession when no Will exists; relevant for understanding default rules.' },
      { name: 'Probate jurisdiction (CPC Schedule)', desc: 'Probate compulsory in Bombay, Calcutta and Madras presidency areas; optional elsewhere.' },
    ],
    pitfalls: [
      { title: 'Unsigned / Unwitnessed Will', desc: 'A Will without two attesting witnesses (in proper form) is invalid — this is the most common reason Wills fail.' },
      { title: 'Bequeathing Ancestral Property Beyond Share', desc: 'In coparcenary HUF property, testator can bequeath only their undivided share — not the whole property.' },
      { title: 'No Capacity Proof for Elderly', desc: 'Wills by elderly are routinely challenged on capacity. Medical certificate, video evidence and detailed recitals help.' },
      { title: 'Vague Bequests', desc: '"My house" or "my account" without identification creates ambiguity. Always specify with detail.' },
    ],
    faqs: [
      { q: 'Is registration of a Will mandatory?', a: 'No — Will registration is optional under Section 18 of the Registration Act, 1908. However, registration creates strong presumption of validity and execution, reducing challenges.' },
      { q: 'Can a Will be revoked?', a: 'Yes — a Will can be revoked at any time during the testator\'s lifetime by (a) executing a new Will, (b) writing of revocation, or (c) destruction by the testator with intent to revoke.' },
      { q: 'What is probate and is it mandatory?', a: 'Probate is the court certificate of the executor\'s authority to administer the Will. It is mandatory in former presidency towns (Bombay, Calcutta, Madras). Elsewhere, probate is optional but useful for clear title transfer.' },
      { q: 'Can NRIs make an Indian Will?', a: 'Yes — NRIs commonly execute separate Indian Wills for Indian assets (since foreign Wills face probate complexities for Indian property).' },
      { q: 'How many witnesses are needed?', a: 'Two witnesses, both of whom must (a) see the testator sign, and (b) sign in the testator\'s presence. Beneficiaries should not be witnesses (their bequest may be void).' },
      { q: 'Can I disinherit a child?', a: 'Yes — under Hindu and Indian Succession laws, a testator has full freedom to bequeath self-acquired property as desired. Children can be excluded but courts examine such Wills carefully for capacity and free will.' },
      { q: 'What about Muslim Wills?', a: 'Muslim Wills are governed by Muslim Personal Law, not the Indian Succession Act. A Muslim can will only 1/3rd of their property; bequests beyond require consent of heirs.' },
    ],
    relatedServices: [
      { name: 'Succession Certificate', href: '/services/property/verification/succession-certificate' },
      { name: 'Legal Heir Certificate', href: '/services/property/verification/legal-heir-certificate' },
      { name: 'General Power of Attorney', href: '/services/property/registration/general-power-of-attorney' },
      { name: 'Gift Deed Registration', href: '/services/property/registration/gift-deed' },
    ],
  },

  'general-power-of-attorney': {
    title: 'General Power of Attorney (GPA)',
    description:
      'GPA drafting, registration and authentication for property management, transactions and legal representation — including special PoA and NRI PoA.',
    keywords: [
      'general power of attorney',
      'GPA registration',
      'special power of attorney',
      'NRI power of attorney',
      'PoA property India',
      'authenticated power of attorney',
    ],
    overview:
      'A Power of Attorney (PoA) is a legal instrument under the Powers of Attorney Act, 1882 by which a principal (donor) authorizes an attorney (donee) to act on their behalf. A General Power of Attorney (GPA) authorizes broad acts; a Special Power of Attorney (SPA) authorizes specific acts.\n\nFor property transactions in India, the Supreme Court in Suraj Lamp & Industries (2011) held that GPA-based sales (called "GPA sales") do not transfer title — only a registered Sale Deed does. However, GPAs remain critical for executing Sale Deeds, managing property, attending court, signing on behalf of NRIs and incapacitated persons.\n\nFor a GPA to be valid for property transactions, it must be (a) executed on appropriate stamp paper, (b) notarized / registered, and (c) for NRIs, attested at the Indian Embassy or apostilled. We draft, register, authenticate and revoke PoAs for individuals, NRIs and corporates.',
    whyChooseUs: [
      { title: 'Scope-Tailored Drafting', desc: 'GPA, SPA, durable PoA, springing PoA — drafted to your specific transaction.' },
      { title: 'NRI PoA Coordination', desc: 'Embassy attestation / apostille and Indian registration handled in parallel.' },
      { title: 'Revocation & Cancellation', desc: 'Where existing PoAs need cancellation, we file revocation and public notice.' },
      { title: 'Anti-Misuse Safeguards', desc: 'PoA drafted with limitations, time-bounds and reporting requirements to prevent misuse.' },
    ],
    keyPoints: [
      'PoA drafting under Powers of Attorney Act, 1882',
      'GPA, SPA and durable PoA tailoring',
      'Stamp duty per State schedule (typically nominal)',
      'Notarization / registration for property transactions',
      'NRI PoA — Embassy attestation / apostille',
      'PoA revocation and public notice',
      'Limitations and time-bound clauses',
      'Authority for sale, lease, mortgage, court representation',
      'Anti-misuse clauses (reporting, accounting)',
      'Power of substitution and delegation',
    ],
    process: [
      { title: 'Scope Definition', desc: 'Identify exact powers — sell specific property, manage rental, attend court, operate bank account.' },
      { title: 'Drafting', desc: 'Comprehensive PoA with schedule of property, scope, limitations and revocation triggers.' },
      { title: 'Stamping', desc: 'Pay stamp duty per State (often nominal — ₹100-500).' },
      { title: 'Authentication', desc: 'Notarize within India, or attest at Embassy / apostille for overseas execution.' },
      { title: 'Registration', desc: 'Mandatory registration at sub-registrar for property-transaction PoAs (Sale, Mortgage).' },
    ],
    documents: [
      'Principal\'s ID and address proof',
      'Attorney\'s ID',
      'Schedule of property (where PoA is for property)',
      'Photographs of principal and attorney',
      'Stamp duty payment proof',
      'Embassy / consulate attestation (for NRIs)',
      'Notary endorsement',
    ],
    statutoryRefs: [
      { name: 'Powers of Attorney Act, 1882', desc: 'Governs creation, scope and effect of powers of attorney.' },
      { name: 'Indian Stamp Act / State Schedules', desc: 'Stamp duty on PoA — varies by State and scope (general / special / for-consideration).' },
      { name: 'Registration Act, 1908', desc: 'Section 17 — PoAs creating interest in immovable property compulsorily registrable.' },
      { name: 'Suraj Lamp & Industries v. State of Haryana (2011)', desc: 'Supreme Court — GPA sales do not transfer title; SaleDeed registration mandatory.' },
    ],
    pitfalls: [
      { title: 'Treating GPA as Sale Substitute', desc: 'Post-Suraj Lamp, GPA sales of immovable property are unenforceable — only registered Sale Deeds transfer title.' },
      { title: 'No Time-Bound Clause', desc: 'Open-ended PoAs that survive years risk misuse — always include time limits and reporting.' },
      { title: 'Missing Embassy Attestation for NRIs', desc: 'NRI PoAs must be attested at Indian Embassy / apostilled — purely notarized PoAs from abroad are often rejected.' },
      { title: 'Continuing After Revocation', desc: 'Failing to publish revocation in newspaper allows misuse by previous attorney.' },
    ],
    faqs: [
      { q: 'Can I sell property using GPA only?', a: 'No — the Supreme Court in Suraj Lamp & Industries (2011) held that GPA does not transfer title. The GPA holder can only execute a Sale Deed on behalf of the principal; the Sale Deed itself transfers title.' },
      { q: 'Is a GPA required to be registered?', a: 'GPAs creating any interest in immovable property (e.g., authorizing sale, mortgage, lease > 1 year) must be registered at sub-registrar. Other PoAs (operating accounts, court representation) typically only need notarization.' },
      { q: 'How does an NRI execute PoA?', a: 'Two routes: (a) execute in India during a visit (most reliable), (b) execute abroad and attest at the Indian Embassy / Consulate. Apostille works for Hague-Convention countries; non-Hague countries need Embassy attestation.' },
      { q: 'Can a PoA be revoked?', a: 'Yes — by (a) written revocation, (b) executing a new contradictory PoA, (c) death of principal, (d) bankruptcy, (e) completion of purpose. Revocation should be publicly notified to prevent third-party reliance on the old PoA.' },
      { q: 'What is a durable PoA?', a: 'A durable PoA continues to be valid even when the principal becomes mentally incapacitated. India recognizes such PoAs through specific drafting; useful for elderly / illness scenarios.' },
      { q: 'How long is a PoA valid?', a: 'Until revoked, expired (if time-bound) or principal dies. Best practice: include explicit expiry of 1-3 years with renewal option.' },
    ],
    relatedServices: [
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Will Registration', href: '/services/property/registration/will-registration' },
      { name: 'Notary, Stamp & Attestation', href: '/services/documentation/legal/notary-stamp-attestation' },
      { name: 'Apostille (MEA/HRD)', href: '/services/documentation/legal/apostille' },
    ],
  },

  'builder-buyer-agreement': {
    title: 'Builder Buyer Agreement (BBA)',
    description:
      'Drafting and review of Builder Buyer Agreements (BBAs) under RERA — protecting buyer rights, possession timelines, payment schedules and exit terms.',
    keywords: [
      'builder buyer agreement',
      'BBA RERA',
      'builder agreement review',
      'RERA Section 13',
      'flat allotment agreement',
      'apartment buyer agreement',
      'BBA lawyer',
    ],
    overview:
      'The Builder Buyer Agreement (BBA), also known as the Apartment Buyer Agreement or Sale Agreement (in real estate parlance), is the contract between a property developer and a flat purchaser. Post-RERA Act, 2016, BBAs are heavily regulated — they must be in the prescribed model form (where the State has prescribed one), include RERA disclosures, mandate timely possession and provide for compensation on delay.\n\nMost ready-made builder agreements are aggressively builder-favourable — extending possession indefinitely under "force majeure", forfeiting buyer payments on minor defaults, levying excessive escalation, restricting buyer assignment, and burying interest-on-delay clauses. Without legal review, buyers often sign agreements that surrender critical RERA protections.\n\nOur RERA-specialist lawyers review BBAs before signing, negotiate amendments with developers, draft buyer-side contracts and represent buyers in RERA Authority and AAR (Appellate Tribunal) proceedings for delays, defects and refunds.',
    whyChooseUs: [
      { title: 'RERA-First Approach', desc: 'Every BBA reviewed against the State RERA Rules and model agreement.' },
      { title: 'Negotiation with Builders', desc: 'We negotiate amendments with developers — many builders accept reasonable demands when legally articulated.' },
      { title: 'Possession Timeline Lock-In', desc: 'Force majeure narrowly drafted; possession date with delay-compensation safeguards.' },
      { title: 'RERA Litigation Ready', desc: 'BBAs we review are designed to enable RERA complaints if disputes arise.' },
    ],
    keyPoints: [
      'BBA review against RERA Act, 2016 and State Rules',
      'Possession timeline with grace period and delay compensation',
      'Force majeure narrowing',
      'Payment schedule and demand-letter procedure',
      'Carpet area vs super area definitions (RERA-mandated)',
      'Specifications, common area schedule and amenities',
      'Default and forfeiture clauses (reasonable, mutual)',
      'Buyer assignment / transfer rights',
      'GST and stamp duty allocation',
      'Possession and conveyance clauses',
      'Maintenance and society formation timeline',
      'Arbitration / RERA jurisdiction clause',
    ],
    process: [
      { title: 'BBA Review', desc: 'Page-by-page review with marked changes against RERA framework.' },
      { title: 'Mark-up Negotiation', desc: 'Submit changes to builder; negotiate critical clauses.' },
      { title: 'Stamp Duty', desc: 'Pay stamp duty per State (typically 5-7% of consideration).' },
      { title: 'Registration', desc: 'Sub-registrar registration where State mandates (e.g., Maharashtra).' },
      { title: 'Compliance Tracking', desc: 'Monitor RERA registration, project progress, demand letters and possession.' },
      { title: 'Closing', desc: 'Possession, mutation and society conveyance.' },
    ],
    documents: [
      'Builder allotment letter',
      'RERA registration of project',
      'Approved plans and OC',
      'Brochure and amenities specification',
      'Booking application and payment receipts',
      'Buyer ID / Aadhaar / PAN',
      'Loan sanction letter (if financed)',
      'Power of Attorney (for NRI / co-applicant)',
    ],
    statutoryRefs: [
      { name: 'Real Estate (Regulation and Development) Act, 2016 — Section 13', desc: 'Promoters cannot accept more than 10% as advance without entering registered Agreement for Sale.' },
      { name: 'RERA — Section 18', desc: 'Refund with interest on possession default.' },
      { name: 'State RERA Rules', desc: 'Each State has its own Rules and often a model agreement (Maharashtra, Karnataka, UP, Haryana).' },
      { name: 'Consumer Protection Act, 2019', desc: 'Alternate forum for builder defaults — flat purchasers are consumers.' },
    ],
    pitfalls: [
      { title: 'Open-Ended Force Majeure', desc: 'Builders use "force majeure" expansively — reduce to specific events with time limits.' },
      { title: 'One-Sided Default Clauses', desc: 'Buyer default forfeits 10-25%; builder default offers token interest. Negotiate symmetry.' },
      { title: 'Super Area vs Carpet Area Confusion', desc: 'Pre-RERA agreements used "super area"; post-RERA mandates carpet area. Verify definitions.' },
      { title: 'Possession Timeline Buffers', desc: '"Possession by 2025-12-31, with 6-month grace, plus extensions" — clarify outer limit and consequences.' },
    ],
    faqs: [
      { q: 'Is BBA required to be registered?', a: 'Under RERA, the agreement is mandatorily registrable for projects covered by RERA. Some States (e.g., Maharashtra, Karnataka) mandate registration of BBAs separately. Always register — registered BBAs are stronger evidence.' },
      { q: 'What is RERA-mandated carpet area?', a: 'RERA Section 2(k) defines carpet area as the net usable floor area excluding external walls, common areas, balconies. Builder must declare and price based on carpet area, not super built-up.' },
      { q: 'What if builder delays possession?', a: 'Under RERA Section 18, buyer can (a) withdraw and demand refund with interest at SBI MCLR + 2% (typically 10-12%), or (b) continue and claim monthly interest until possession.' },
      { q: 'Can BBA be assigned to another person?', a: 'Most BBAs allow assignment with builder consent and transfer fee. Unilateral restriction is often struck down by RERA.' },
      { q: 'Should I sign BBA without review?', a: 'No — many BBA clauses are heavily builder-favourable. Independent legal review before signing protects you against years of dispute.' },
      { q: 'What is the jurisdiction for BBA disputes?', a: 'Primary forum — RERA Authority (project-State); appeals to RERA Appellate Tribunal. Alternate forum — Consumer Forums (district / state / national). Arbitration clauses in BBAs do not oust RERA jurisdiction.' },
    ],
    relatedServices: [
      { name: 'RERA Registration & Compliances', href: '/services/property/real-estate/rera-registration' },
      { name: 'Real Estate Litigation (RERA)', href: '/services/property/real-estate/litigation' },
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Conveyance Deed Registration', href: '/services/property/registration/conveyance-deed' },
      { name: 'Agreement to Sale', href: '/services/property/registration/agreement-to-sale' },
    ],
  },
};
