import type { ServiceContent } from '@/components/leaf-service-page';

export const propertyVerificationServices: Record<string, ServiceContent> = {
  'title-search': {
    title: 'Title Search Verification',
    description:
      'Comprehensive 30-year title search and verification report — chain of ownership, encumbrances, litigation and statutory clearances before property purchase.',
    keywords: [
      'title search property',
      'title verification report',
      'property title search lawyer',
      '30 year title search',
      'chain of title verification',
      'property title certificate',
      'title due diligence India',
    ],
    overview:
      'Title Search Verification is the foundational due diligence before any property purchase, mortgage or major transaction. It traces the chain of ownership backwards through public records — Sale Deeds, Gift Deeds, Wills, partition deeds, mutation orders, court decrees — typically for 30 years (or longer for litigation-prone properties).\n\nA proper title search reveals defects that aren\'t visible on the seller\'s document: prior ownership disputes, missing inheritance shares, unregistered partitions, charges on the property, ongoing litigation, encroachments and statutory irregularities. Skipping or shortcutting the title search is the single biggest cause of property litigation in India.\n\nOur lawyers conduct certified title searches at sub-registrar offices, revenue offices, civil courts, and online portals — issuing a Title Verification Report with a clear opinion on marketability, defects and remedies. We work for individual buyers, banks (for loan due diligence) and corporates (for portfolio acquisitions).',
    whyChooseUs: [
      { title: 'Bank-Grade Reports', desc: 'Our reports meet PSU bank standards — accepted for home loans without re-verification.' },
      { title: 'Litigation Trace', desc: 'We check civil courts, High Court and Supreme Court for pending litigation in seller\'s name.' },
      { title: 'Multi-Source Cross-Verification', desc: 'Sub-registrar, Tehsildar, CERSAI, MCD/BBMP, RERA, court records — comprehensive coverage.' },
      { title: 'Clear Opinion', desc: 'No fence-sitting — we state "Marketable", "Marketable with Conditions" or "Not Marketable" with reasons.' },
    ],
    keyPoints: [
      'Chain of title verification for 30 years',
      'Sub-registrar record search (registered deeds)',
      'Mutation chain at municipal / Tehsildar offices',
      'Encumbrance certificate retrieval (15-30 years)',
      'Litigation search in civil / family / High Courts',
      'CERSAI charge verification',
      'Approved layout / building plan check',
      'Statutory clearances (urban land ceiling, RERA)',
      'Stamp duty deficiency and registration anomalies',
      'Title Verification Report with marketability opinion',
    ],
    process: [
      { title: 'Document Collection', desc: 'Collect parent documents, Sale Deeds, mutation extracts and encumbrance certificates from seller.' },
      { title: 'Sub-Registrar Search', desc: 'Verify each registered deed in sub-registrar records; retrieve certified copies where needed.' },
      { title: 'Court / Litigation Search', desc: 'Search court records for litigation in seller\'s name and against the property.' },
      { title: 'Statutory & Authority Search', desc: 'Verify approvals, OC, layout sanctions, urban-land ceiling clearance.' },
      { title: 'Report Drafting', desc: 'Comprehensive Title Verification Report with chain analysis, defects and marketability opinion.' },
    ],
    documents: [
      'All past title documents (Sale Deeds, Gift Deeds, Wills, partition deeds)',
      'Encumbrance certificate (15-30 years)',
      'Mutation extracts (Khata / Patta / 7-12)',
      'Property tax receipts',
      'Approved building plan and OC',
      'Death certificates (where succession involved)',
      'Court orders / decrees affecting the property',
      'Society / RWA records (for flats)',
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882', desc: 'Section 55 — seller\'s duty to disclose material defects in title.' },
      { name: 'Registration Act, 1908 — Sections 17–18', desc: 'Compulsorily and optionally registrable documents — basis for chain verification.' },
      { name: 'Limitation Act, 1963', desc: 'Adverse possession (12 years private, 30 years State) and limitation periods.' },
      { name: 'RBI / Bank Loan Guidelines', desc: 'Banks mandate independent title search reports for loan against property.' },
    ],
    pitfalls: [
      { title: 'Relying Only on Encumbrance Certificate', desc: 'EC shows registered encumbrances only — does not catch unregistered claims, litigation or possession disputes.' },
      { title: 'Skipping Court Search', desc: 'Pending litigation in seller\'s name is a major risk. Civil / family / High Court searches catch this.' },
      { title: 'Short Title Search Period', desc: '15-year searches miss early-chain defects that surface in litigation. 30 years is the minimum.' },
      { title: 'Trusting Builder Approvals', desc: 'Builder may show approval letters but actual layout / building deviations exist. Physical verification + sanctioned plan match is essential.' },
    ],
    faqs: [
      { q: 'How long does title search take?', a: 'Typically 7-15 working days for a comprehensive 30-year search. Urgent searches (loan-deadline driven) can be done in 3-5 days at higher cost.' },
      { q: 'What is the cost of title search?', a: 'Varies by property type, location and complexity — typically ₹15,000–₹75,000 for residential and ₹50,000–₹3 lakh for commercial / industrial. Premium for complex chains.' },
      { q: 'Why 30 years?', a: 'Indian limitation law (Limitation Act, 1963) provides 12-30 year limitation for property claims. A 30-year search ensures most claims are time-barred and the title is "perfect" by adverse possession or limitation.' },
      { q: 'Can title search guarantee perfect title?', a: 'No — title search reveals defects in public records but cannot guarantee against fraudulent documents, unregistered claims or future challenges. Title insurance (limited availability in India) provides additional protection.' },
      { q: 'Do I need a fresh title search if my bank already did one?', a: 'Bank\'s title search is for the bank\'s loan security — it may not address all buyer concerns. An independent buyer-side search is recommended for major transactions.' },
      { q: 'What if title search reveals defects?', a: 'Options: (a) negotiate price reduction, (b) demand seller to cure defect (e.g., obtain partition / NOC), (c) walk away, (d) take indemnity from seller for known defects.' },
    ],
    relatedServices: [
      { name: 'Encumbrances Check', href: '/services/property/verification/encumbrances-check' },
      { name: 'Due Diligence Report', href: '/services/property/verification/due-diligence-report' },
      { name: 'Sale Deed Registration', href: '/services/property/registration/sale-deed' },
      { name: 'Title Clearance & Due Diligence', href: '/services/property/real-estate/title-clearance' },
    ],
  },

  'encumbrances-check': {
    title: 'Encumbrances Check',
    description:
      'Encumbrance Certificate retrieval and analysis — verifying charges, mortgages, lis pendens and other registered encumbrances on the property.',
    keywords: [
      'encumbrance certificate',
      'EC property',
      'encumbrance check property',
      'EC sub registrar',
      'mortgage charge property',
      'encumbrance verification India',
    ],
    overview:
      'An Encumbrance Certificate (EC) is a statutory document issued by the sub-registrar listing all registered encumbrances on a property — mortgages, charges, lien, lis pendens (pending litigation notices) and other claims that affect free transferability. The EC is one of the most critical documents in any property transaction.\n\nMany States have moved EC retrieval online (Karnataka Kaveri, Tamil Nadu STAR, Telangana IGRS, etc.). Different States use different naming — "Form 15", "Form 16", "Nil EC" vs "Encumbrance EC" — but the substance is similar: a sub-registrar certificate listing registered transactions affecting the property.\n\nWe retrieve, decode and analyze ECs as part of due diligence. We also assist in obtaining historical ECs spanning 15-30 years and resolving anomalies where the property identification doesn\'t match across deeds.',
    whyChooseUs: [
      { title: 'Multi-State Online & Offline', desc: 'We retrieve ECs across all States — online where available, manual sub-registrar visits where not.' },
      { title: 'Historical EC Reconstruction', desc: 'Where 30-year EC isn\'t directly available, we piece it from multiple sub-registrar visits.' },
      { title: 'Anomaly Resolution', desc: 'Property identification mismatches resolved through cross-referencing.' },
      { title: 'Charge Discharge Coordination', desc: 'For paid-off mortgages still showing on EC, we coordinate discharge filings.' },
    ],
    keyPoints: [
      'EC retrieval from sub-registrar (online / offline)',
      '15-year and 30-year historical ECs',
      'Form 15 / Form 16 / Form 22 (State-specific) handling',
      'Mortgage and charge analysis',
      'Lis pendens (pending litigation) detection',
      'Lease and easement registration check',
      'Court attachment verification',
      'Power of Attorney registration check',
      'Discharge / release deed verification for paid-off charges',
      'EC interpretation and translation report',
    ],
    process: [
      { title: 'Property Details', desc: 'Compile detailed schedule — survey number, plot number, owner names, North-South-East-West boundaries.' },
      { title: 'EC Application', desc: 'File online or at sub-registrar; pay fee and capture token.' },
      { title: 'Retrieval', desc: 'Receive EC; standard turnaround 1-7 days online, 7-15 days offline.' },
      { title: 'Analysis', desc: 'Decode each entry; identify discharged vs subsisting charges; correlate with other documents.' },
      { title: 'Report', desc: 'Plain-English summary with recommendations.' },
    ],
    documents: [
      'Property identification — Sale Deed, schedule, survey numbers',
      'Owner ID',
      'Past Sale Deed reference numbers',
      'Khata / Patta',
      'Property tax receipts',
    ],
    statutoryRefs: [
      { name: 'Registration Act, 1908 — Sections 57–59', desc: 'Public access to sub-registrar records and basis for EC issuance.' },
      { name: 'State Registration Rules', desc: 'Form formats, fee schedules and turnaround times vary by State.' },
      { name: 'Transfer of Property Act, 1882', desc: 'Encumbrance definitions — mortgage, charge, lien, easement.' },
    ],
    pitfalls: [
      { title: 'EC Property Mismatch', desc: 'EC issued on slightly different schedule may miss real encumbrances. Verify exact survey / plot match.' },
      { title: 'Discharged Mortgage Still Showing', desc: 'Older ECs often show paid-off mortgages because release deeds weren\'t filed. This isn\'t a defect but needs documentation.' },
      { title: 'Short-Period EC', desc: '5-10 year EC misses earlier defects. Insist on 15+ year, ideally 30 year EC.' },
      { title: 'No Court Search Beyond EC', desc: 'EC catches lis pendens only if registered. Independent court search is essential.' },
    ],
    faqs: [
      { q: 'How is EC different from title search?', a: 'EC is a single document listing registered encumbrances from sub-registrar. Title search is a comprehensive verification across multiple sources — EC is one input to title search, not a substitute.' },
      { q: 'Is "Nil Encumbrance" EC enough?', a: 'A "Nil EC" means no registered encumbrances during the EC period. It is necessary but not sufficient — combine with court search, mutation verification and physical inspection.' },
      { q: 'Can EC be obtained online?', a: 'Most major States offer online EC — Karnataka (Kaveri), Tamil Nadu (STAR), Telangana / AP (IGRS), Kerala. Some States still require sub-registrar visit.' },
      { q: 'How much does EC cost?', a: 'Government fee is nominal (₹100-500) but online portals charge handling fee. Through a service, total cost is typically ₹500-2,000 depending on State and period.' },
      { q: 'What if my property isn\'t on online portal?', a: 'For older / rural / non-digitized properties, manual sub-registrar visits are required. We coordinate physical retrieval.' },
    ],
    relatedServices: [
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Due Diligence Report', href: '/services/property/verification/due-diligence-report' },
      { name: 'CERSAI Verification', href: '/services/property/verification/cersai-verification' },
    ],
  },

  'due-diligence-report': {
    title: 'Due Diligence Report',
    description:
      'Comprehensive Property Due Diligence Reports for buyers, lenders and investors — title, regulatory, litigation, zoning, environmental and tax verification.',
    keywords: [
      'property due diligence',
      'real estate due diligence',
      'property DD report',
      'commercial property DD',
      'lender due diligence',
      'investment property report',
    ],
    overview:
      'Property Due Diligence is the comprehensive multi-disciplinary verification that goes beyond title search to cover regulatory, zoning, environmental, tax, encumbrance, litigation and physical aspects of a property. It is mandatory for institutional buyers, lenders and serious investors before any major property transaction.\n\nA proper due diligence report integrates work by lawyers, surveyors, structural engineers and tax advisors. It identifies title defects, layout violations, pending dues (property tax, electricity, water), litigation risk, RERA compliance, environmental clearances (where applicable), pending demolition orders and statutory non-compliance.\n\nOur multi-disciplinary team produces lender-grade due diligence reports for residential, commercial, industrial, hospitality and mixed-use properties — including for portfolio acquisitions, REIT inputs, mortgage sanctions and acquisition finance.',
    whyChooseUs: [
      { title: 'Multi-Disciplinary Team', desc: 'Lawyers + surveyors + tax + environmental advisors integrated under single project lead.' },
      { title: 'Lender-Grade Output', desc: 'Reports accepted by leading PSU and private sector banks for loan sanctions.' },
      { title: 'Red-Amber-Green Risk Matrix', desc: 'Each finding rated for severity with mitigation recommendations.' },
      { title: 'Portfolio-Scale Capability', desc: 'Capable of running 50-200 property due diligences in parallel for large transactions.' },
    ],
    keyPoints: [
      'Title and chain verification',
      'RERA registration and compliance',
      'Approved plan and OC verification',
      'Zoning and land-use compliance',
      'Encumbrance and CERSAI charge check',
      'Litigation and writ search',
      'Property tax and statutory dues clearance',
      'Society / RWA / association records',
      'Environmental clearances (where applicable)',
      'Demolition / regularization status',
      'Tax incentives and stamp duty optimization',
      'Risk-rated findings and mitigation matrix',
    ],
    process: [
      { title: 'Scoping', desc: 'Define property type, transaction value, buyer / lender requirements and scope of work.' },
      { title: 'Document Collection', desc: 'Comprehensive request list to seller / borrower; multi-source cross-verification.' },
      { title: 'Site Visit & Survey', desc: 'Physical inspection, boundary verification, structural assessment.' },
      { title: 'Diligence', desc: 'Legal title, regulatory, zoning, environmental, tax, litigation streams in parallel.' },
      { title: 'Report Drafting', desc: 'Comprehensive report with executive summary, findings, risk matrix and recommendations.' },
    ],
    statutoryRefs: [
      { name: 'Transfer of Property Act, 1882; Registration Act, 1908', desc: 'Title and registration framework.' },
      { name: 'RERA Act, 2016', desc: 'Project registration and disclosures for real estate.' },
      { name: 'Master / Development Plans', desc: 'State-specific zoning and land-use regulations.' },
      { name: 'Environment Protection Act, 1986', desc: 'Environmental clearances for large / industrial properties.' },
    ],
    pitfalls: [
      { title: 'Relying on Builder/Seller Reps', desc: 'Builder representations are not a substitute for independent verification.' },
      { title: 'Missing OC Discrepancies', desc: 'Approved plan vs constructed building often differ; this affects regularization and saleability.' },
      { title: 'Outdated Encumbrance Certificates', desc: 'EC older than 3 months may miss recent transactions.' },
      { title: 'No Site Visit', desc: 'Physical inspection catches encroachments, neighbour disputes and structural issues that paperwork doesn\'t reveal.' },
    ],
    faqs: [
      { q: 'When is full due diligence required vs title search?', a: 'For high-value (₹2 crore+), commercial, industrial, hospitality, portfolio transactions and lender financing — full due diligence. For straightforward residential resale at lower values, title search may suffice.' },
      { q: 'How long does due diligence take?', a: 'Typically 2-6 weeks depending on property complexity and document availability. Portfolio due diligence (multiple properties) may run 6-12 weeks.' },
      { q: 'What is the cost?', a: 'Highly variable — typically ₹50,000–₹5 lakh for single property based on type and complexity. Portfolio rates negotiable.' },
      { q: 'Are physical site visits mandatory?', a: 'Yes — for any meaningful due diligence. Document review must be paired with physical inspection of boundaries, construction quality, neighborhood and access.' },
      { q: 'Can findings be remedied?', a: 'Often yes — many findings (missing NOCs, mutation lapses, minor regulatory defects) can be cured through curative actions before closing.' },
    ],
    relatedServices: [
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Encumbrances Check', href: '/services/property/verification/encumbrances-check' },
      { name: 'CERSAI Verification', href: '/services/property/verification/cersai-verification' },
      { name: 'Title Clearance & Due Diligence', href: '/services/property/real-estate/title-clearance' },
    ],
  },

  'land-scrutiny-report': {
    title: 'Land Scrutiny Report',
    description:
      'In-depth Land Scrutiny Report for agricultural, industrial and large land parcels — revenue records, Khasra, Khatauni, conversion status and land-ceiling compliance.',
    keywords: [
      'land scrutiny report',
      'land verification report',
      'agricultural land scrutiny',
      'land conversion CLU',
      'urban land ceiling',
      'industrial land due diligence',
      'land 7/12 verification',
    ],
    overview:
      'Land Scrutiny is the specialized due diligence required for agricultural land, large parcels, industrial land and rural / semi-urban acquisitions. It goes deeper than urban property due diligence — verifying revenue records (7/12, Khasra, Khatauni, RoR), boundary surveys, land-use classification, conversion (CLU) status, urban-land-ceiling compliance and tribal-land restrictions.\n\nLand transactions in India are complicated by State-specific tenancy laws, agricultural-buyer restrictions, ceiling laws, land conversion requirements (NA / CLU), tribal-land protections and RoR mismatches. A single overlooked entry in the 7/12 extract can derail a multi-crore land deal at the registration stage.\n\nOur land-specialist lawyers conduct end-to-end scrutiny — visiting Tehsildar / Patwari offices, retrieving 7/12 / Khasra extracts, mutation chains, parcellary maps, conducting boundary surveys with licensed surveyors, and verifying conversion / CLU status with concerned authorities.',
    whyChooseUs: [
      { title: 'Rural / Tehsildar Network', desc: 'Active relationships with Tehsildar / Patwari offices for record retrieval.' },
      { title: 'Boundary Survey Coordination', desc: 'Licensed surveyors and demarcation services bundled with legal scrutiny.' },
      { title: 'Conversion (NA/CLU) Specialists', desc: 'We handle land-use conversion alongside scrutiny.' },
      { title: 'Tenancy & Tribal-Land Expertise', desc: 'State-specific tenancy laws (Maharashtra, Karnataka, Goa) and tribal-land restrictions navigated.' },
    ],
    keyPoints: [
      '7/12 (Saatbara) / Khasra / Khatauni / RoR retrieval',
      'Mutation chain verification at revenue authorities',
      'Land use classification (agricultural / non-agricultural / NA)',
      'Conversion / CLU status verification',
      'Boundary survey and demarcation',
      'Urban Land Ceiling Act compliance (where applicable)',
      'Agricultural-buyer eligibility (State tenancy laws)',
      'Tribal-land restriction analysis',
      'Forest / wetland / coastal regulation overlay',
      'Land acquisition / notification check',
    ],
    process: [
      { title: 'Initial Survey', desc: 'Property identification with survey number, hissa number, gram panchayat.' },
      { title: 'Revenue Records', desc: '7/12 / Khasra / Khatauni / RoR retrieval; mutation chain.' },
      { title: 'Conversion Status', desc: 'Verify NA / CLU status; check pending applications.' },
      { title: 'Boundary Survey', desc: 'Physical demarcation with licensed surveyor and tape match with revenue records.' },
      { title: 'Restriction Mapping', desc: 'Tenancy, tribal-land, forest, coastal, ceiling overlays.' },
      { title: 'Report', desc: 'Comprehensive report with marketability opinion and curative recommendations.' },
    ],
    documents: [
      'Past Sale / Gift / Partition deeds',
      '7/12 extract / Khasra / Khatauni / RoR',
      'Mutation register copy',
      'Conversion (NA/CLU) order if any',
      'Approved layout / building plan',
      'Survey settlement records',
      'Property tax receipts',
      'Tribal-land NOC (where applicable)',
    ],
    statutoryRefs: [
      { name: 'State Land Revenue Codes', desc: 'Maharashtra Land Revenue Code, Karnataka Land Revenue Act, etc. — basis for revenue records.' },
      { name: 'Tenancy & Agricultural Lands Acts', desc: 'Restrict purchase by non-agriculturists; e.g., Maharashtra Tenancy Act, Karnataka Land Reforms Act.' },
      { name: 'Urban Land Ceiling Act (where in force)', desc: 'Ceiling on urban land holdings; State variations.' },
      { name: 'Indian Forest Act / Forest Conservation Act, 1980', desc: 'Forest land restrictions; non-forest use requires central clearance.' },
    ],
    pitfalls: [
      { title: 'Skipping 7/12 vs Sale Deed Mismatch', desc: 'Revenue records and Sale Deed schedule may differ; reconcile both.' },
      { title: 'Buying Tribal Land', desc: 'In tribal areas, sale to non-tribals is restricted. Even with consent, transactions can be void.' },
      { title: 'Missing NA Conversion', desc: 'Building on agricultural land without NA conversion attracts demolition and penalty.' },
      { title: 'Boundary Disputes Hidden', desc: 'Revenue records may not show neighbour encroachments; physical survey essential.' },
    ],
    faqs: [
      { q: 'Can a non-agriculturist buy agricultural land?', a: 'Many States restrict — Maharashtra, Karnataka, Gujarat, Himachal Pradesh require buyer to be an agriculturist. Some States have abolished this; check State law.' },
      { q: 'What is NA conversion?', a: 'Non-Agricultural conversion is the process of changing land use from agricultural to non-agricultural (residential / commercial / industrial). Granted by Collector / DC; requires payment of conversion charges.' },
      { q: 'How is 7/12 different from Sale Deed?', a: '7/12 is a revenue record showing current possession and rights — not a title document. Sale Deed is the registered transfer instrument. Both should match for clean title.' },
      { q: 'What if 7/12 shows multiple holders?', a: 'Indicates joint ownership or unresolved partition. Each holder must consent to sale, or partition must be executed.' },
      { q: 'How long does land scrutiny take?', a: 'Typically 4-8 weeks for rural land due to manual record retrieval. Urban / semi-urban land 2-4 weeks.' },
    ],
    relatedServices: [
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Due Diligence Report', href: '/services/property/verification/due-diligence-report' },
      { name: 'Land Acquisition', href: '/services/property/real-estate/land-acquisition' },
      { name: 'Title Clearance & Due Diligence', href: '/services/property/real-estate/title-clearance' },
    ],
  },

  'cersai-verification': {
    title: 'CERSAI Verification',
    description:
      'CERSAI charge verification on immovable property — tracing registered security interests of banks / financial institutions before purchase or fresh mortgage.',
    keywords: [
      'CERSAI verification',
      'CERSAI search property',
      'CERSAI charge check',
      'CERSAI registered security interest',
      'bank charge verification',
      'mortgage charge CERSAI',
    ],
    overview:
      'CERSAI (Central Registry of Securitisation Asset Reconstruction and Security Interest of India) is the central registry under Section 20 of the SARFAESI Act, 2002 that records security interests created in favour of banks and financial institutions over immovable / movable property. Since 2016, registration of mortgages with CERSAI within 30 days of creation has been mandatory.\n\nCERSAI verification reveals if a property is mortgaged to any lender — even if the encumbrance certificate at the sub-registrar is silent (e.g., for equitable mortgages by deposit of title deeds, which are not registered with sub-registrar). It is the only systematic source for detecting equitable mortgages in India.\n\nWe conduct CERSAI searches at https://www.cersai.org.in/ for every meaningful property due diligence — and assist in obtaining no-due certificates / mortgage discharge filings where charges are paid off but not formally satisfied on CERSAI.',
    whyChooseUs: [
      { title: 'Standard Due-Diligence Step', desc: 'Every Title Search / DD report we issue includes CERSAI search.' },
      { title: 'Discharge Coordination', desc: 'For paid-off mortgages, we coordinate with lenders to file Form II discharge.' },
      { title: 'Equitable Mortgage Specialists', desc: 'CERSAI catches equitable mortgages that sub-registrar EC misses entirely.' },
      { title: 'Same-Day Reports', desc: 'Online CERSAI searches typically completed same business day.' },
    ],
    keyPoints: [
      'CERSAI online search for registered security interests',
      'Detection of equitable mortgages',
      'Form I (creation), Form II (satisfaction), Form III (modification) interpretation',
      'Multi-property portfolio search',
      'Lender / borrower-side search',
      'Discharge filing coordination (Form II)',
      'Asset Reconstruction Company (ARC) charge tracing',
      'Cross-verification with sub-registrar EC',
      'Aadhaar / PAN / CIN-based search',
    ],
    process: [
      { title: 'Property Identification', desc: 'Compile property schedule, owner Aadhaar / PAN, prior owner names.' },
      { title: 'CERSAI Search', desc: 'Online search at cersai.org.in by property / borrower; retrieve Form I/II/III filings.' },
      { title: 'Analysis', desc: 'Decode each filing — lender, principal, status; map against EC and other records.' },
      { title: 'Discharge Coordination', desc: 'Where charges are paid but still active on CERSAI, coordinate Form II filing with lender.' },
      { title: 'Report', desc: 'Plain-English summary of all CERSAI charges with status.' },
    ],
    statutoryRefs: [
      { name: 'SARFAESI Act, 2002 — Section 20', desc: 'Establishes CERSAI as central registry for security interests.' },
      { name: 'Security Interest (Enforcement) Rules, 2002', desc: 'Form I / II / III filing procedure.' },
      { name: 'CERSAI Regulations, 2011', desc: 'Operational framework for registration, search and fees.' },
      { name: 'SARFAESI 2016 Amendment', desc: 'Made registration mandatory within 30 days for all secured creditors.' },
    ],
    pitfalls: [
      { title: 'Skipping CERSAI for "Clean" EC Properties', desc: 'EC may show "Nil" but CERSAI may show equitable mortgage — always check both.' },
      { title: 'Old Charges Not Discharged', desc: 'Even paid-off loans show as active until lender files Form II — buyer must demand discharge before closing.' },
      { title: 'Multiple Charges Confusion', desc: 'A property may have charges in multiple owner names. Search by owner Aadhaar and prior owners.' },
      { title: 'No Lender NOC', desc: 'For mortgaged property sale, lender NOC + simultaneous loan closure is essential — not just CERSAI clearance.' },
    ],
    faqs: [
      { q: 'What is the difference between EC and CERSAI?', a: 'EC (Encumbrance Certificate) shows registered transactions at sub-registrar — including registered mortgages. CERSAI shows all security interests (including equitable / unregistered mortgages) created with banks / FIs. Both are needed for complete picture.' },
      { q: 'Is CERSAI search mandatory?', a: 'For lenders, registering charges within 30 days is mandatory under SARFAESI. For buyers, CERSAI search is highly recommended (effectively standard practice) for property due diligence.' },
      { q: 'How do I do a CERSAI search?', a: 'Online at cersai.org.in — search by Aadhaar, PAN, property identification or filing reference. Fee is nominal (₹50-100 per search).' },
      { q: 'How are paid-off mortgages cleared?', a: 'The lender files Form II (Satisfaction) within 30 days of full repayment. Borrowers should follow up with the lender to ensure timely Form II filing — many lenders are slow.' },
      { q: 'What if Form II isn\'t filed despite payment?', a: 'Borrower can issue a legal notice to lender demanding Form II filing. CERSAI also has grievance redressal mechanism. Independently obtained NoDue certificate from lender can substantiate full satisfaction.' },
    ],
    relatedServices: [
      { name: 'Encumbrances Check', href: '/services/property/verification/encumbrances-check' },
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Permission to Mortgage (PTM)', href: '/services/property/verification/permission-to-mortgage' },
      { name: 'Due Diligence Report', href: '/services/property/verification/due-diligence-report' },
    ],
  },

  'certified-copy': {
    title: 'Certified Copy of Documents',
    description:
      'Certified copies of registered Sale Deeds, Gift Deeds, Wills, agreements and other public documents — sub-registrar attested for legal proceedings.',
    keywords: [
      'certified copy sub registrar',
      'certified copy sale deed',
      'CTC property documents',
      'true copy sub registrar',
      'duplicate sale deed',
    ],
    overview:
      'A Certified True Copy (CTC) is a sub-registrar-attested copy of a registered document, admissible as evidence under Section 65 of the Evidence Act, 1872 when the original is lost, destroyed, in adversary\'s possession or otherwise unavailable. CTCs are routinely required for litigation, loan applications, mutation, RERA filings and replacement of lost originals.\n\nCertified copies can be obtained for any registered document — Sale Deeds, Gift Deeds, partition deeds, Wills, mortgage deeds, lease deeds, court orders. Each State has its own application process and fee schedule. Online portals exist in some States but many still require physical sub-registrar visits.\n\nWe procure certified copies across India, manage urgent timelines (often required for litigation deadlines), and coordinate retrieval from older sub-registrar offices where digitization is incomplete.',
    whyChooseUs: [
      { title: 'PAN-India Coverage', desc: 'Certified copy retrieval from any sub-registrar office in India.' },
      { title: 'Urgent Track', desc: 'Same-week retrieval for litigation deadlines, where possible.' },
      { title: 'Older Records Retrieval', desc: 'Pre-digitization records sourced through manual processes.' },
      { title: 'Multiple Copy Coordination', desc: 'Bulk requests for portfolio / chain title searches.' },
    ],
    keyPoints: [
      'Certified copy of registered Sale / Gift / Lease / Partition deeds',
      'Certified copy of registered Wills (post-death)',
      'Certified copy of mortgage / charge documents',
      'Court orders and decrees (from court registry)',
      'Authority orders (RERA, regulator filings)',
      'Multi-copy applications for portfolio diligence',
      'Old / pre-digitization document retrieval',
      'Translation and notarization where required',
      'Delivery to lender / court / authority',
    ],
    process: [
      { title: 'Document Identification', desc: 'Capture exact document details — date, registration number, sub-registrar office, parties.' },
      { title: 'Application', desc: 'File application (online / offline) with prescribed fee.' },
      { title: 'Sub-Registrar Processing', desc: 'Sub-registrar verifies record and prepares certified copy with seal.' },
      { title: 'Delivery', desc: 'Collect from sub-registrar; courier to client.' },
    ],
    statutoryRefs: [
      { name: 'Indian Evidence Act, 1872 — Section 65', desc: 'Conditions under which secondary evidence (certified copies) is admissible.' },
      { name: 'Registration Act, 1908 — Section 57', desc: 'Inspection and copy of registered documents from sub-registrar.' },
      { name: 'State Registration Rules', desc: 'Application form, fee and turnaround vary by State.' },
    ],
    pitfalls: [
      { title: 'Wrong Sub-Registrar Application', desc: 'Document registered at one office cannot be retrieved from another — verify exact office before filing.' },
      { title: 'Vague Document Reference', desc: 'Without registration number / date, retrieval becomes a fishing expedition. Compile exact details first.' },
      { title: 'Pre-Digitization Delays', desc: 'Older records (pre-2000) may take 4-8 weeks. Plan for litigation deadlines accordingly.' },
    ],
    faqs: [
      { q: 'Is a certified copy admissible in court?', a: 'Yes — as secondary evidence under Section 65 of the Evidence Act when the original is lost, destroyed, in adversary\'s possession or otherwise unavailable.' },
      { q: 'How long does it take?', a: 'Typically 7-21 days for digitized records. Older records (pre-2000) may take 4-8 weeks.' },
      { q: 'How much does a certified copy cost?', a: 'Government fee is page-based (typically ₹10-100 per page). Total cost depends on document size; service fees additional.' },
      { q: 'Can I get certified copy of someone else\'s document?', a: 'Yes — registered documents are public records under Section 57 of the Registration Act. Anyone can apply for a certified copy.' },
      { q: 'Will replacement of lost Sale Deed give me title?', a: 'A certified copy is evidence of the transaction; it doesn\'t reissue title. If original is needed for sale / mortgage, certified copy + indemnity bond + lost-original affidavit + newspaper notification is the standard cure.' },
    ],
    relatedServices: [
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
      { name: 'Legal Publish in Newspaper', href: '/services/property/verification/legal-newspaper-publication' },
      { name: 'Encumbrances Check', href: '/services/property/verification/encumbrances-check' },
    ],
  },

  'permission-to-mortgage': {
    title: 'Permission to Mortgage (PTM)',
    description:
      'Permission to Mortgage (PTM) procurement from authorities (DDA, MHADA, CIDCO, NOIDA) for leasehold and allotted properties before bank financing.',
    keywords: [
      'permission to mortgage',
      'PTM property',
      'DDA PTM',
      'MHADA permission to mortgage',
      'leasehold property mortgage',
      'authority NOC mortgage',
    ],
    overview:
      'Permission to Mortgage (PTM) is the formal authorization from the lessor / authority required before a leasehold or allotted property can be mortgaged with a bank or financial institution. Authorities including DDA, MHADA, CIDCO, NOIDA, GNIDA, GDA and State Housing Boards mandate PTM before any equitable or registered mortgage can be created.\n\nWithout PTM, a mortgage on leasehold property is void against the lessor — the bank cannot enforce its security through SARFAESI proceedings. This is a common defect in older home-loan portfolios. PTM is a curable defect but requires authority application, fees and waiting periods (typically 30-90 days).\n\nWe handle PTM applications, NOC procurement, response to authority queries, mortgage registration coordination with banks and post-discharge "no-due" certificates from authorities. We work both buyer-side (acquiring leasehold property with loan) and lender-side (legal due diligence for portfolio mortgage).',
    whyChooseUs: [
      { title: 'Authority-Specific Process Knowledge', desc: 'DDA, MHADA, CIDCO each have distinct PTM procedures we navigate.' },
      { title: 'Bank Coordination', desc: 'Bank legal team integrated with PTM timeline.' },
      { title: 'Conversion Bundle', desc: 'For DDA leasehold, we bundle PTM with leasehold-to-freehold conversion where eligible.' },
      { title: 'Lender Audit Cure', desc: 'For existing portfolios with missing PTM, we run cure programs.' },
    ],
    keyPoints: [
      'PTM application drafting and filing',
      'Authority NOC procurement',
      'Authority-specific procedures (DDA / MHADA / CIDCO / NOIDA / GDA)',
      'Bank / lender coordination',
      'Conversion (leasehold to freehold) bundling',
      'Mortgage registration after PTM',
      'Post-discharge no-due certificate',
      'Existing portfolio PTM cure programs',
      'Multi-authority single-property PTMs',
    ],
    process: [
      { title: 'Eligibility Verification', desc: 'Confirm property type, allotment status, lease term and PTM eligibility.' },
      { title: 'PTM Application', desc: 'File with authority — application form, prescribed fee, NOC from existing lessor / society.' },
      { title: 'Authority Processing', desc: 'Authority verifies records, checks dues, issues PTM (typically 30-90 days).' },
      { title: 'Mortgage Creation', desc: 'Bank registers mortgage post-PTM; loan disbursed.' },
      { title: 'Discharge', desc: 'Post-loan repayment, obtain no-due from bank and discharge filing with authority.' },
    ],
    documents: [
      'Allotment letter / lease deed',
      'Possession certificate',
      'Property tax / lease rent clearance',
      'No-Due from authority',
      'Bank loan sanction letter',
      'Borrower KYC',
      'Society NOC (where applicable)',
      'Existing mortgage discharge (if refinance)',
    ],
    statutoryRefs: [
      { name: 'Authority Lease Deed Terms', desc: 'PTM is contractual — based on lease deed terms with the authority.' },
      { name: 'DDA Lease & Conveyance Rules; MHADA Regulations', desc: 'Authority-specific PTM procedures and fees.' },
      { name: 'Transfer of Property Act, 1882', desc: 'Section 108 — lessor consent required for assignment / mortgage of leasehold.' },
      { name: 'SARFAESI Act, 2002', desc: 'Enforcement of secured interest — requires valid mortgage; PTM is foundational.' },
    ],
    pitfalls: [
      { title: 'Skipping PTM for "Speed"', desc: 'Some borrowers / lenders skip PTM to expedite — creating void mortgages discovered at default / sale.' },
      { title: 'Wrong Authority', desc: 'Property may be under multiple authorities (e.g., MHADA + Municipal Corporation). PTM needed from each.' },
      { title: 'Outdated Lease Status', desc: 'Lease may have expired or been forfeited; PTM cannot validate a void lease.' },
      { title: 'No Discharge Filing', desc: 'After loan repayment, missing discharge filing leaves the property nominally mortgaged — affects future transactions.' },
    ],
    faqs: [
      { q: 'Is PTM mandatory for all leasehold properties?', a: 'For properties under DDA, MHADA, CIDCO, NOIDA, GNIDA and similar authorities — yes, before any mortgage. For private leases, it depends on the lease deed terms.' },
      { q: 'How long does PTM take?', a: 'Typically 30-90 days depending on authority. DDA PTM has been streamlined and often completes in 30-45 days. MHADA / CIDCO can take longer.' },
      { q: 'What is the cost?', a: 'Authority fee varies — DDA PTM is in low thousands; some authorities charge based on property value. Service fees additional.' },
      { q: 'Can I sell a property mortgaged without PTM?', a: 'Technically yes — but the void mortgage exposes the buyer to bank claims. Best practice is to cure before sale: obtain PTM retrospectively or pay off the loan with valid discharge.' },
      { q: 'Is PTM required for freehold property?', a: 'No — freehold properties don\'t need authority permission to mortgage. PTM is specific to leasehold / authority-allotted properties.' },
    ],
    relatedServices: [
      { name: 'CERSAI Verification', href: '/services/property/verification/cersai-verification' },
      { name: 'Encumbrances Check', href: '/services/property/verification/encumbrances-check' },
      { name: 'Transfer of Memorandum (TM)', href: '/services/property/registration/transfer-of-memorandum' },
      { name: 'Title Search Verification', href: '/services/property/verification/title-search' },
    ],
  },

  'legal-newspaper-publication': {
    title: 'Legal Publish in Newspaper',
    description:
      'Legal newspaper publications and public notices — for lost documents, change of name, partition, will probate, statutory notices and property acquisitions.',
    keywords: [
      'legal newspaper publication',
      'public notice newspaper',
      'lost document public notice',
      'name change publication',
      'partition public notice',
      'probate notice newspaper',
    ],
    overview:
      'Legal newspaper publications are statutory or precautionary public notices published in newspapers for various legal purposes — lost / damaged property documents, change of name, public objection invitations, succession / probate notices, partition notices and statutory acquisition notices.\n\nMany Indian laws require notice in two newspapers — typically one English daily and one regional language daily — with circulation in the relevant area. The notice must be precise about subject, parties, schedule of property and time-period for objections. Improper or vague notices fail their legal purpose and are routinely set aside.\n\nWe draft legal notices, coordinate publication in appropriate newspapers (with circulation proof), maintain newspaper clippings as evidence, and file these as part of court / authority proceedings. We work for individuals, families and institutions across India.',
    whyChooseUs: [
      { title: 'Statutory-Compliant Drafting', desc: 'Notices drafted to satisfy specific statute / court / authority requirements.' },
      { title: 'Newspaper Network', desc: 'Direct empanelment with leading English and regional dailies — discounted rates.' },
      { title: 'Circulation Affidavit', desc: 'Newspaper-issued affidavit of circulation in the relevant area for evidence.' },
      { title: 'Multi-Language', desc: 'English + regional language coverage including Hindi, Marathi, Tamil, Telugu, Kannada, Bengali.' },
    ],
    keyPoints: [
      'Lost / damaged document public notice',
      'Name change advertisement',
      'Partition / family settlement public notice',
      'Will / succession / probate notice',
      'Society / RWA related notices',
      'Statutory acquisition / RERA notices',
      'Lender / arbitration / SARFAESI notices',
      'Cease and desist / cease use notices',
      'Property auction notices (for liquidators / banks)',
      'Multi-newspaper, multi-language publication',
    ],
    process: [
      { title: 'Notice Drafting', desc: 'Tailored notice with precise particulars, schedule, parties and objection window.' },
      { title: 'Newspaper Selection', desc: 'Identify appropriate English + regional dailies with circulation in concerned area.' },
      { title: 'Publication Coordination', desc: 'Submit notice for publication; pay charges; verify proof.' },
      { title: 'Evidence Compilation', desc: 'Original newspaper page, circulation affidavit, dated clippings preserved for court / authority.' },
    ],
    documents: [
      'Underlying transaction / event documents (lost original, gazette notice, etc.)',
      'Schedule of property',
      'Applicant ID',
      'Statutory citation requiring publication',
      'Court / authority order if mandated',
    ],
    statutoryRefs: [
      { name: 'Indian Succession Act, 1925', desc: 'Probate / succession proceedings often require newspaper notice.' },
      { name: 'SARFAESI Act, 2002', desc: 'Section 13(4) — possession notice; Section 13(2) — demand notice; auction notices.' },
      { name: 'Various State Statutes', desc: 'Land acquisition, partition, name change — many statutes require newspaper publication.' },
      { name: 'Court Practice Rules', desc: 'Civil and criminal courts often require notice publication for ex-parte proceedings.' },
    ],
    pitfalls: [
      { title: 'Vague Notice Drafting', desc: 'Notice without specific parties, property details and objection deadline is legally ineffective.' },
      { title: 'Wrong Newspaper Choice', desc: 'Publication in newspapers without circulation in the relevant area fails the "wide circulation" test.' },
      { title: 'Missing Regional Language Notice', desc: 'Many statutes require publication in regional language paper. English-only is often insufficient.' },
      { title: 'No Evidence Preservation', desc: 'Original newspaper, clippings and circulation affidavit must be preserved — a "we published" statement isn\'t enough.' },
    ],
    faqs: [
      { q: 'When is newspaper publication required?', a: 'For lost / damaged document indemnity, name change, partition, probate, public objections, SARFAESI proceedings, regulatory notices and many statutory contexts. Each statute / context has specific requirements.' },
      { q: 'How many newspapers should I publish in?', a: 'Standard is two — one English + one regional language. For specific contexts (e.g., SARFAESI, RERA), check the specific Act for prescribed newspapers.' },
      { q: 'How much does it cost?', a: 'Highly variable — typically ₹3,000–₹15,000 per newspaper depending on size, day and edition. Multi-edition / national papers cost more.' },
      { q: 'Is the notice legally effective immediately?', a: 'No — most notices include an objection / response window (typically 15-30 days). The legal effect crystallizes after the objection period closes without challenge.' },
      { q: 'What is "wide circulation"?', a: 'A newspaper with significant readership in the geographical area where the matter is relevant. Courts and authorities reject publications in obscure papers without local circulation.' },
    ],
    relatedServices: [
      { name: 'Certified Copy of Documents', href: '/services/property/verification/certified-copy' },
      { name: 'Legal Heir Certificate', href: '/services/property/verification/legal-heir-certificate' },
      { name: 'Succession Certificate', href: '/services/property/verification/succession-certificate' },
      { name: 'Will Registration', href: '/services/property/registration/will-registration' },
    ],
  },

  'legal-heir-certificate': {
    title: 'Legal Heir Certificate',
    description:
      'Legal Heir Certificate procurement from Tehsildar / Revenue Authority for inheritance, pension, insurance claims and property mutation after death.',
    keywords: [
      'legal heir certificate',
      'heir certificate India',
      'tehsildar legal heir',
      'inheritance certificate',
      'family member certificate',
      'survivor certificate',
    ],
    overview:
      'A Legal Heir Certificate (also called Surviving Family Member Certificate or Family Member Certificate in some States) is a document issued by the Tehsildar / Revenue Authority listing the surviving family members of a deceased person. It is required for routine inheritance matters — pension, gratuity, PF, insurance claims, bank account closure, electricity / water connection transfer and property mutation.\n\nUnlike a Succession Certificate (which is judicially issued for movable property / debts), a Legal Heir Certificate is administratively issued and faster — typically 30-60 days. It is sufficient for non-disputed inheritance and routine government / banking / utility matters. For disputed inheritance or movable property in court, a Succession Certificate is required.\n\nWe handle Legal Heir Certificate applications across India — Tamil Nadu, Karnataka, Andhra, Telangana, Kerala, Maharashtra, Delhi, UP and other States. Each State has distinct procedures, forms and authorities; we navigate State-specific requirements.',
    whyChooseUs: [
      { title: 'Multi-State Coverage', desc: 'Familiar with distinct procedures across Tamil Nadu, Karnataka, Maharashtra, etc.' },
      { title: 'Document Coordination', desc: 'Death certificate, family relationship proofs, ration card — compiled and submitted as a complete file.' },
      { title: 'Objection Handling', desc: 'Where Tehsildar issues notice for objections, we manage hearings and replies.' },
      { title: 'Mutation Bundle', desc: 'Heir certificate + property mutation handled in single workstream.' },
    ],
    keyPoints: [
      'Tehsildar / Revenue Authority application',
      'State-specific forms and procedures',
      'Family relationship proof compilation',
      'Public notice / objection window navigation',
      'Multi-heir applications',
      'Coordination with bank / insurance / pension authorities',
      'Property mutation post-issuance',
      'Heir certificate vs Succession Certificate strategy',
      'Surviving spouse / child / parent / sibling certifications',
    ],
    process: [
      { title: 'Eligibility Check', desc: 'Verify Legal Heir Certificate is sufficient (vs Succession Certificate / Probate).' },
      { title: 'Application', desc: 'File at concerned Tehsildar / Revenue office with prescribed form and documents.' },
      { title: 'Verification', desc: 'Authority verifies through revenue records, neighborhood enquiry, sometimes newspaper notice.' },
      { title: 'Issuance', desc: 'Legal Heir Certificate issued listing family members.' },
      { title: 'Application to Authorities', desc: 'Use certificate for pension, insurance, bank, mutation etc.' },
    ],
    documents: [
      'Death certificate of deceased',
      'Aadhaar / ID of deceased and applicant',
      'Self-declaration / affidavit of family members',
      'Family ration card',
      'Address proof',
      'Marriage certificate (for spouse claim)',
      'Birth certificates of children',
      'Photographs of family members',
    ],
    statutoryRefs: [
      { name: 'State Revenue Codes', desc: 'Each State\'s revenue code or rules govern Legal Heir Certificate issuance.' },
      { name: 'Hindu Succession Act, 1956 / Indian Succession Act, 1925', desc: 'Determine who qualifies as legal heir.' },
      { name: 'Muslim Personal Law (Shariat) Application Act, 1937', desc: 'For Muslim inheritance.' },
    ],
    pitfalls: [
      { title: 'Confusing with Succession Certificate', desc: 'Legal Heir Certificate is for routine matters; Succession Certificate (court-issued) is for movable property / debts in dispute.' },
      { title: 'Missing One Heir', desc: 'If even one heir is omitted, certificate may be challenged or void. List all surviving heirs.' },
      { title: 'Wrong Tehsildar Office', desc: 'Application must be at deceased\'s last residence Tehsildar — not applicant\'s.' },
      { title: 'Bank-Specific Variations', desc: 'Some banks demand Succession Certificate even where Legal Heir Certificate would suffice — anticipate and budget time.' },
    ],
    faqs: [
      { q: 'What\'s the difference between Legal Heir Certificate and Succession Certificate?', a: 'Legal Heir Certificate is administrative (Tehsildar), faster (30-60 days), used for routine pension / mutation / utility matters. Succession Certificate is judicial (civil court), for movable property / debts where amount in dispute, takes 6-12 months.' },
      { q: 'Is Legal Heir Certificate sufficient for property transfer?', a: 'For mutation in revenue / municipal records — yes. For sale of inherited property to outsiders — typically yes if all heirs sign. Some buyers demand Succession Certificate for added comfort.' },
      { q: 'How long does it take?', a: '30-60 days typically, longer in some States or where verifications get complex.' },
      { q: 'What is the cost?', a: 'Government fee is nominal (₹50-500). Total cost via service is typically ₹3,000-15,000 depending on complexity.' },
      { q: 'Can I apply if living abroad?', a: 'Yes — apply through Power of Attorney executed in India or attested by Indian Embassy abroad.' },
    ],
    relatedServices: [
      { name: 'Succession Certificate', href: '/services/property/verification/succession-certificate' },
      { name: 'Will Registration', href: '/services/property/registration/will-registration' },
      { name: 'Mutation', href: '/services/property/registration/mutation' },
      { name: 'Legal Publish in Newspaper', href: '/services/property/verification/legal-newspaper-publication' },
    ],
  },

  'succession-certificate': {
    title: 'Succession Certificate',
    description:
      'Succession Certificate procurement from civil court under Part X of the Indian Succession Act — for movable property, debts, securities and inheritance disputes.',
    keywords: [
      'succession certificate',
      'succession certificate court',
      'Indian Succession Act Part X',
      'inheritance court certificate',
      'shares debts succession',
      'movable property inheritance',
    ],
    overview:
      'A Succession Certificate is a civil-court-issued certificate under Part X (Sections 370-390) of the Indian Succession Act, 1925, granting the holder authority to receive debts, securities and movable property of a deceased person where there is no Will (intestate succession). It is essentially mandatory for transferring shares, mutual funds, FDs, insurance maturity proceeds and other movable assets of deceased account holders.\n\nApplication is made to the District Judge / Civil Judge (Senior Division) having jurisdiction. The court advertises in newspapers, hears objections, conducts inquiry and issues the certificate after typically 6-12 months. Succession Certificate is not a determination of inheritance rights — it is authority to collect; ultimate distribution is per personal succession law.\n\nWe represent applicants in Succession Certificate proceedings — drafting petition, paying court fee (ad valorem on value of assets, can be substantial), publishing notices, attending hearings and securing the certificate. We also advise on bond requirements and limitations on the certificate.',
    whyChooseUs: [
      { title: 'Court-Specialist Representation', desc: 'Active in District / Civil Courts across India for succession petitions.' },
      { title: 'Court Fee Structuring', desc: 'Strategic asset valuation to minimize ad-valorem court fees.' },
      { title: 'Faster Track Strategy', desc: 'Publication, objection-window navigation and hearing scheduling optimized.' },
      { title: 'Multi-Asset Petitions', desc: 'Single petition covering shares, mutual funds, FDs, EPF, insurance — avoiding repeat petitions.' },
    ],
    keyPoints: [
      'Petition under Indian Succession Act Section 372',
      'Jurisdiction at deceased\'s last residence',
      'Court fee — ad valorem on asset value',
      'Newspaper publication for objections',
      'Affidavit of relationship and asset list',
      'Hearing and inquiry by court',
      'Bond / surety requirement post-grant',
      'Distribution authority for shares, MF, FD, EPF, insurance',
      'Multi-State asset coordination',
      'NRI / OCI applications',
    ],
    process: [
      { title: 'Asset Inventory', desc: 'Comprehensive list of movable assets — shares, MF, FD, EPF, insurance, vehicles.' },
      { title: 'Petition Drafting', desc: 'Petition under Section 372 with affidavit and supporting documents.' },
      { title: 'Court Fee', desc: 'Pay ad-valorem court fee per State Court Fee Act.' },
      { title: 'Publication', desc: 'Court orders newspaper publication; 30-day objection window.' },
      { title: 'Hearing', desc: 'Inquiry; objections (if any) heard; petition decided on merits.' },
      { title: 'Grant', desc: 'Certificate issued, often with bond / surety requirement.' },
      { title: 'Asset Realization', desc: 'Submit certificate to share registrars, banks, insurance companies for transfer.' },
    ],
    documents: [
      'Death certificate of deceased',
      'Family member relationship proof',
      'Comprehensive asset list with values',
      'Latest holding statements (DEMAT, MF, FD)',
      'Insurance policy documents',
      'Bank passbook / statements',
      'Aadhaar / ID of applicant',
      'Affidavit per court format',
    ],
    statutoryRefs: [
      { name: 'Indian Succession Act, 1925 — Part X (Sections 370-390)', desc: 'Statutory framework for Succession Certificates.' },
      { name: 'Court Fees Act / State Court Fee Acts', desc: 'Ad-valorem court fee on certificate value.' },
      { name: 'Hindu Succession Act, 1956', desc: 'Distribution rules for Hindu intestate succession.' },
      { name: 'Indian Stamp Act / State Stamp Acts', desc: 'Stamp duty on Succession Certificate.' },
    ],
    pitfalls: [
      { title: 'Underestimating Court Fee', desc: 'Court fee is ad valorem (often 2-3% of asset value); for high-value certificates, fee can run into lakhs.' },
      { title: 'Missing Heirs Not Cited', desc: 'All legal heirs must be cited as parties or notified; missed heirs can challenge later.' },
      { title: 'Confusing with Probate', desc: 'Succession Certificate is for intestate (no Will) cases. With a Will, Probate / Letters of Administration is the right remedy.' },
      { title: 'Insurance Claim Time-Limits', desc: 'Insurance policies have claim time-limits; succession certificate process can outrun these — consider interim relief.' },
    ],
    faqs: [
      { q: 'When is Succession Certificate required?', a: 'For transferring movable assets of a deceased intestate person — shares, mutual funds, FDs, debts, EPF, insurance maturity. It is not required where there is a registered Will (Probate is the right route).' },
      { q: 'How long does it take?', a: '6-12 months typically — comprising petition filing, publication, objection window, hearings and grant. Disputed petitions can take 2-3 years.' },
      { q: 'How much court fee?', a: 'Ad valorem per State Court Fee Act — typically 2-3% of asset value, capped at certain ceiling. Verify based on State.' },
      { q: 'Is Succession Certificate enough for property transfer?', a: 'No — Succession Certificate is for movable property only. For immovable property inheritance, Legal Heir Certificate + mutation, or Probate / Letters of Administration (where Will exists), is required.' },
      { q: 'Can I get Succession Certificate for property abroad?', a: 'Indian Succession Certificates apply to assets in India. For foreign assets, separate succession proceedings may be needed in the asset jurisdiction.' },
      { q: 'Can it be challenged?', a: 'Yes — by any person claiming as heir or having interest. Common challenges: unaccounted heir, disputed authenticity, fraud. Court adjudicates contested petitions.' },
    ],
    relatedServices: [
      { name: 'Legal Heir Certificate', href: '/services/property/verification/legal-heir-certificate' },
      { name: 'Will Registration', href: '/services/property/registration/will-registration' },
      { name: 'Mutation', href: '/services/property/registration/mutation' },
      { name: 'Legal Publish in Newspaper', href: '/services/property/verification/legal-newspaper-publication' },
    ],
  },
};
